### ISSUE TITLE
Unable to start Minikube on Debian 10.7 using GCP VM 

### ISSUE THREAD

**Issue by Akshay123455667** [kubernetes/minikube#10006]
**Steps to reproduce the issue:** 
I installed Minikube on GCP Debian VM using  below command 

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
sudo dpkg -i minikube_latest_amd64.deb

and installed Kubectl and Docker too , but when starting the minikube getting below error

$ minikube start
😄  minikube v1.16.0 on Debian 10.7
👎  Unable to pick a default driver. Here is what was considered, in preference order:
    ▪ podman: Not installed: exec: "podman": executable file not found in $PATH
    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH
    ▪ vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in $PATH
    ▪ docker: Not healthy: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/version: dial unix /var/run/docker.sock: connect: permission denied
    ▪ kvm2: Not installed: exec: "virsh": executable file not found in $PATH
    ▪ none: Not installed: exec: "iptables": executable file not found in $PATH

❌  Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/

Any suggestion on how to resolve this

**Comment by afbjorklund** [comment]
Please look at https://docs.docker.com/engine/install/debian/
and https://docs.docker.com/engine/install/linux-postinstall/

Need to make sure that `docker version` works properly...
This is something of a fallout from missing docs: #7963

**Comment by afbjorklund** [comment]
There is some kind of censorship going on here, with the error messages...

The first log entry is:

`global.go:110] docker priority: 8, state: {Installed:true Healthy:false Running:true NeedsImprovement:false Error:"docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: dial unix /var/run/docker.sock: connect: permission denied Fix:Add your user to the 'docker' group: 'sudo usermod -aG docker $USER && newgrp docker' Doc:https://docs.docker.com/engine/install/linux-postinstall/}`

Note the helpful "fix" there, which has the suggested command and a doc url.

Then the second log entry is:

`driver.go:240] not recommending "docker" due to health: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: dial unix /var/run/docker.sock: connect: permission denied`

**Comment by Akshay123455667** [comment]
by following post install steps it worked , but now when I start minikube 
getting below output

minikube start
😄  minikube v1.16.0 on Debian 10.7
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
E1219 21:07:34.359636   71006 start.go:271] kubectl info: exec: fork/exec /usr/local/bin/kubectl: exec format error


I have installed updated kubectl , but still getting "E1219 21:07:34.359636   71006 start.go:271] kubectl info: exec: fork/exec /usr/local/bin/kubectl: exec format error"

**Comment by afbjorklund** [comment]
Seems like you installed `kubectl` for the wrong platform or something ? You can use `minikube kubectl --` instead

**Comment by sharifelgamal** [comment]
yeah `exec format error` usually happens when you install a binary for the wrong platform, like installing a darwin binary on linux for example. as @afbjorklund mentioned, minikube always provides its own kubectl internally for ease of use.

**Comment by spowelljr** [comment]
Hi @Akshay123455667, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
