### ISSUE TITLE
* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

### ISSUE THREAD

**Issue by scpxin** [kubernetes/minikube#10010]
** minikube start --driver=hyperv**：

*** Microsoft Windows 10 Pro 10.0.19042 Build 19042 上的 minikube v1.15.1
* 根据用户配置使用 hyperv 驱动程序
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/
* Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by priyawadhwa** [comment]
Hey @scpxin thank you for opening this issue. Based on the error, it looks like this is failing because no External vswitch or 
Default Switch was found. Were you able to consult https://docs.docker.com/machine/drivers/hyper-v/ to try and set one up?

嘿 @scpxin 感谢您打开此问题。根据错误，这似乎是失败的，因为没有外部vswitch或
找到默认开关。您是否可以查阅 https://docs.docker.com/machine/drivers/hyper-v/ 尝试进行设置？

**Comment by medyagh** [comment]
Hi @scpxin , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

**Comment by medyagh** [comment]
Hi @scpxin I haven', I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
