### ISSUE TITLE
Unable to resize minikube virtual machine disk size

### ISSUE THREAD

**Issue by jpswade** [kubernetes/minikube#1002]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug
**Minikube version** (use `minikube version`): minikube version: v0.15.0
**Environment**:
- **OS** (e.g. from /etc/os-release): Mac OS X
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **Docker version** (e.g. `docker -v`): Docker version 1.10.2, build c3959b1
- **Install tools**: brew
**What happened**: I stopped the minikube cluster, then stated it again with a 30g disk size flag
**What you expected to happen**: I expected the disk to resize to 30g
**How to reproduce it** (as minimally and precisely as possible): `minikube stop && minikube start --disk-size 30g`

This stems from the main issue which is that the minikube virtual machine has run out of disk space. I would expect minikube to be able to programatically resize the disk size based on the flag that is passed in on start, by passing this to the driver, alas that doesn't seem to be the case.

**Comment by r2d4** [comment]
The drivers we support can't dynamically resize the disk image it creates without a full delete/start.  

I'm not sure if its easy to do so, and if it were, the drivers (xhyve, virtualbox, hyper-v) would actually be the ones performing it.  The different drivers also sometimes use different disk formats (qcow2, sparse, raw, etc.) so it might be tough. 

We should at least not ignore the flag silently in this case

**Comment by jpswade** [comment]
There's no mention in the documentation that this is the initial disk size only either.

**Comment by aaron-prindle** [comment]
Thanks for reporting this.  Feel free to send a PR with updated documentation regarding this.  We auto generate the VM settings and defaults here: https://github.com/kubernetes/minikube/blob/master/docs/minikube_start.md

**Comment by Ademord** [comment]
This markdown no longer exists?

**Comment by r2d4** [comment]
@Ademord, the markdown was just the output of `minikube start --help`.  We no longer autogenerate it.

**Comment by JessMTermini** [comment]
I also am finding all of these as major issues or at least barriers to testing and entry as i am developing locally on a small chromebook and to not be able to change the initial disk size on start (regardless of how it has to be done) is preventing me completely from being able to use it because I simply don't have access to a dedicated 20gb disk on this particular chromebook I am needing to use it on to do some very basic initial testing...(aside from having to power up and configure an entire remote/cloud machine - which I feel shouldn't be necessary at this stage of the game. Maybe perhaps after winning me over, dipping my toes in the water, but I just can't justify it RIGHT YET. IDK, maybe this will become so important to me I inevitably decide to bite the bullet and do it) But at least have SOMETHING in the documentation about this, as a noob, I felt stupid to even google it thinking it was probably just me (which it probably might still be!! lol, but spent too much time LOOKING and scouring the provided minikube docs and links to find this only to finally goole it and see that it's  been a long time problem that apparently looking at the date of this post no one has even cared to update since 2017??) No shade, I just find this strange being that it's supposedly so widely used and a requirement for both kubernetes and docker...so yea, that's it, go figure.. 

Anyways, if anyone can point me to a current fix on this that I may have missed, it would be greatly appreciated (!!), as I was really trying to finish this tutorial setup from bitnami to setup a minimal wordpress site for testing to see if this could be a viable solution for my future sites moving forward eventually in production and I would really hate to pass this up on account of this being really simple to fix and setup as a very basic and simple initial testing space!! 

Thank you in advance if anyone responds!!

**Comment by gsdcadmin** [comment]
We resize minikube kvm raw disk image on CentOS 9 Stream.

Step summarize:
  - backup raw image
  - use `qemu-img resize -f raw`
  - create loop device from raw image
  - modify partition with loop device
  - resize fs with loop device mapper
  - clean up loop device

Commands:
```bash
# stop minikube
cp -a ~/.minikube/machines/{$PROFILE}/${NAME}.rawdisk  /backup
qemu-img resize -f raw ~/.minikube/machines/{$PROFILE}/${NAME}.rawdisk +60G
chown ${USER}:${USER} ~/.minikube/machines/{$PROFILE}/${NAME}.rawdisk
file -s ~/.minikube/machines/{$PROFILE}/${NAME}.rawdisk
sudo losetup -f ~/.minikube/machines/{$PROFILE}/${NAME}.rawdisk
sudo losetup -a
# check result for loop device name
sudo fdisk /dev/loop0
      # check partion number
      p
      # delete last partion
      d 1
      # create new partion 
      n
      # accepting Partition number, First sector and Last sector the defaults
      <Enter>
      <Enter>
      <Enter>
      # do not remove old signature
      no
      # write the changes
      w
sudo fdisk -l /dev/loop0
sudo kpartx -a /dev/loop0
sudo e2fsck -f /dev/mapper/loop0p1
sudo resize2fs /dev/mapper/loop0p1
sudo mount /dev/mapper/loop0p1 /mnt
df -h /mnt/
sudo umount /mnt
sudo kpartx -d /dev/loop0
sudo losetup -d /dev/loop0
sed 's/"DiskSize": .*,/"DiskSize": 80000,/' -i ~/.minikube/machines/{$PROFILE}/config.json
# start minikube
```
