### ISSUE TITLE
implement operation auditing for minkube (--user) flag

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10041]
there should be a way to know what user did what operition on a minikube cluster

(to be used by multiple tools that use minikube at the same time
skaffold, cloud code, cloud run, cloud shel ....)

```
----------------------------------------
command, option, user , start_time , end_time
----------------------------------------
start, --driver=docker , driver, cloud-code, 223232,2 23232
start, --driver=hyperkit , driver, code-shell, 223232,2 23232
stop, steven, 223232,2 23232

```

if no user was provided, it should default to the OS user name

**Comment by priyawadhwa** [comment]
Commands we will track: start, stop, pause, unpause, delete
Command we won't track because they may clutter the log: status, version

Options for deleting the audit file:
1. consistently append to a single file and assume that it will be deleted whenever a user runs `--purge`
2. put a TTL on the audit file (if it hasn't been modified in a week, delete it and start a new one)


Whenever we append to the file, we can also log what we are appending to STDERR which will satisfy https://github.com/kubernetes/minikube/issues/9520
