### ISSUE TITLE
Make addon yaml templates image name configurable

### ISSUE THREAD

**Issue by lingsamuel** [kubernetes/minikube#10063]
Some registry may have different image name rule, for example:
aliyun ingress image name: `registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2`, but in the template:

https://github.com/kubernetes/minikube/blob/92511decd0ece326701c385f1c642d11af092d16/deploy/addons/ingress/ingress-dp.yaml.tmpl#L52

Notice the image name `ingress-nginx/controller` and `nginx-ingress-controller`.

We may need more configurable YAML templates.

**Comment by springcomefromprogrammingtheworld** [comment]
I used the command: minicube cache add registry.cn - hangzhou.aliyuncs.com/google_ containers/nginx-ingress-c ontroller:v0.40.2

Then run the command: minicube cache list
result: [spring@bogon .minikube]$ minikube cache list
registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2


Try the command again: minicube addresses enable address

result:[spring@bogon .minikube]$ minikube addons enable ingress
🔎  Verifying ingress addon...

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by lingsamuel** [comment]
@springcomefromprogrammingtheworld It's a bug currently I think... you may need to tag the image as `us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2` or `registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2` if you are using aliyun as image repository.
Then run `minikube cache add us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2`.

**Comment by springcomefromprogrammingtheworld** [comment]
> @springcomefromprogrammingtheworld It's a bug currently I think... you may need to tag the image as `us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2` or `registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2` if you are using aliyun as image repository.
> Then run `minikube cache add us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2`.
> 
> You could check the image name by run `kubectl -n kube-system describe deploy ingress-nginx-controller | grep Image`

[spring@bogon .minikube]$ kubectl -n kube-system describe deploy ingress-nginx-controller | grep Image
    Image:       registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2
.......I feel like I've missed some steps

**Comment by lingsamuel** [comment]
@springcomefromprogrammingtheworld Currently the template is wrong, it renders `registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2`, notice the last part `controller:v0.40.2`, the image pulled from aliyun is `nginx-ingress-controller:v0.40.2`

**Comment by springcomefromprogrammingtheworld** [comment]
> @springcomefromprogrammingtheworld Currently the template is wrong, it renders `registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2`, notice the last part `controller:v0.40.2`, the image pulled from aliyun is `nginx-ingress-controller:v0.40.2`

[spring@bogon .minikube]$ minikube cache list
.
registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2

Is that right? A little confused. Are you Chinese?

**Comment by springcomefromprogrammingtheworld** [comment]
@lingsamuel

**Comment by lingsamuel** [comment]
run:
```bash
docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2 registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2
minikube cache add registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2
```

**Comment by springcomefromprogrammingtheworld** [comment]
> run:
> 
> ```shell
> docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2 registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2
> minikube cache add registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2
> ```

@lingsamuel 

oh my god

**Comment by springcomefromprogrammingtheworld** [comment]
[spring@bogon google_containers]$ docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2 registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2
[spring@bogon google_containers]$ docker images
REPOSITORY                                                                     TAG                 IMAGE ID            CREATED             SIZE
registry.cn-hangzhou.aliyuncs.com/google_containers/dashboard                  v2.1.0              9a07b5b4bfac        2 weeks ago         226MB
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy                 v1.20.0             10cc881966cf        3 weeks ago         118MB
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager    v1.20.0             b9fa1895dcaa        3 weeks ago         116MB
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver             v1.20.0             ca9843d3b545        3 weeks ago         122MB
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler             v1.20.0             3138b6e3d471        3 weeks ago         46.4MB
registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner        v4                  85069258b98a        4 weeks ago         29.7MB
registry.cn-hangzhou.aliyuncs.com/google_containers/controller                 v0.40.2             4b26fa2d90ae        2 months ago        286MB
registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller   v0.40.2             4b26fa2d90ae        2 months ago        286MB
registry.cn-hangzhou.aliyuncs.com/google_containers/etcd                       3.4.13-0            0369cf4303ff        4 months ago        253MB
registry.cn-hangzhou.aliyuncs.com/google_containers/coredns                    1.7.0               bfe3a36ebd25        6 months ago        45.2MB
registry.cn-hangzhou.aliyuncs.com/google_containers/metrics-scraper            v1.0.4              86262685d9ab        9 months ago        36.9MB
registry.cn-hangzhou.aliyuncs.com/google_containers/pause                      3.2                 80d28bedfe5d        10 months ago       683kB
[spring@bogon google_containers]$ minikube cache add registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2
E1230 17:51:31.991799  125788 cache.go:63] save image to file "registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2" -> "/home/spring/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/controller_v0.40.2" failed: nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2: GET https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/controller/manifests/v0.40.2: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:google_containers/controller Type:repository]]

❌  Exiting due to MK_CACHE_LOAD: save to dir: caching images: caching image "/home/spring/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/controller_v0.40.2": nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2: GET https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/controller/manifests/v0.40.2: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:google_containers/controller Type:repository]]

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
Can we find a better title for this issue? It's not clear to me what isn't configurable. It's a Go template that can apply nearly any logic you can think of.

PR's welcome to adjust the name of the image appropriately.

**Comment by springcomefromprogrammingtheworld** [comment]
The problem has been solved。。。

1.docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2

2.docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2  us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2

3.minikube cache add us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2

4.minikube addons enable ingress --alsologtostderr

Thank you for your proposal @lingsamuel

**Comment by lingsamuel** [comment]
Can't find a simple command line way to config addons image names cuz some addons contains many images...
To make all image names configurable, we may need some configs at cluster config/somewhere else.

e.g.
```bash
$ minikube addons images ingress
Addon "ingress" images:
|-------------------|----------------------------------|-----------------------------------|
| IMAGE CONFIG NAME |            IMAGE NAME            |          IMAGE REPOSITORY         |
|-------------------|----------------------------------|-----------------------------------|
| ingress-container | ingress-nginx/controller:v0.40.2 |                                   |
| ingress-container | nginx-ingress-controller:v0.40.2 | registry.cn-hangzhou.aliyuncs.com |
|-------------------|----------------------------------|-----------------------------------|
```

This should be stored system-wide instead of profile and should be related to which image repository being used.
```bash
$ minikube addons configure-image ingress
Config format is "registry/image-name", divided by comma
-- Enter custom images for "ingress-container": registry.cn-hangzhou.aliyuncs.com/nginx-ingress-controller:v0.40.2
```
