### ISSUE TITLE
GUEST_PROFILE_DELETION: CreateFile C:\boot2docker.iso: Access is denied.

### ISSUE THREAD

**Issue by KimSeongHo-cloud** [kubernetes/minikube#10086]
**Steps to reproduce the issue:** 

1.λ minikube delete
🔥  Removing C:\Users\user\.minikube\machines\minikube ...

❌  Exiting due to GUEST_PROFILE_DELETION: CreateFile C:\Users\user\.minikube\machines\minikube\boot2docker.iso: Access is denied.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
``` minikube version ```

- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8

the initial log I see shows that Your windows does not have access to the iso file. is there a user permission problem on ur windows?

/triage needs-information
/kind support

**Comment by priyawadhwa** [comment]
Hey @KimSeongHo-cloud are you still seeing this issue?

**Comment by medyagh** [comment]
Hi @KimSeongHo-cloud , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
