### ISSUE TITLE
ES-issue

### ISSUE THREAD

**Issue by amigowifi1** [kubernetes/minikube#10166]
**Los comandos necesarios para reproducir la incidencia**:

**El resultado completo del comando que ha fallado**: <details>

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:

**Comment by priyawadhwa** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`
* The full output of `kubectl get po -A`

Thank you for sharing your experience!

---

Todavía no tengo una forma clara de replicar este problema. ¿Le importaría agregar algunos detalles adicionales? Aquí hay información adicional que sería útil:

* La línea de comando exacta `minikube start` utilizada
* La salida completa del comando `minikube start`, preferiblemente con` --alsologtostderr -v = 4` para un registro adicional.
 * La salida completa de los `registros de minikube`
* La salida completa de `kubectl get po -A`


¡Gracias por compartir su experiencia!

**Comment by medyagh** [comment]
Hi @amigowifi1 , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
