### ISSUE TITLE
After restart the windows 10 machine unable to start the Minikube

### ISSUE THREAD

**Issue by thirdpartyusage** [kubernetes/minikube#10278]
minikube start
😄  minikube v1.17.0 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...

🤦  StartHost failed, but will try again: provision: Temporary Error: NewSession: new client: new client: dial tcp 127.0.0.1:49156: connect: connection refused
🏃  Updating the running docker "minikube" container ...
😿  Failed to start docker container. Running "minikube delete" may fix it: provision: Temporary Error: NewSession: new client: new client: dial tcp 127.0.0.1:49156: connect: connection refused

❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: NewSession: new client: new client: dial tcp 127.0.0.1:49156: connect: connection refused

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by spowelljr** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The full output of the command you are using by adding --alsologtostderr -v=8 for example

```
$ minikube start --alsologtostderr -v=8
```
- Also the full the output of the
```
$ minikube logs
```
This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by Tejolaxmi** [comment]
I am also facing the same issue.
After the restarting windows 10 machine i am unable to start minikube and i am getting below error 
! StartHost failed, but will try again: provision: Temporary Error: NewSession: new client: new client: dial tcp 127.0.0.1:49156: connectex: No connection could be made because the target machine actively refused it.

Reinstalled minikube  and tries starting it did not work.

Kindly let me know on how to proceed with this issue

**Comment by medyagh** [comment]
@Tejolaxmi I am curious if deleting minikube would fix this problem ?
this might be an issue that is caused by Docker Desktop restarting would not Start back minikube or the port change.

does this fix the problem 
```
minikube delete
minikube start
``` 
btw our latest version is 1.18.1

**Comment by spowelljr** [comment]
Hi @thirdpartyusage, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by rsalinas** [comment]
I'm having the same problem.  Deleting and starting again "fixes" the problem.
