### ISSUE TITLE
 minikube addons enable ingress

### ISSUE THREAD

**Issue by zhangb191** [kubernetes/minikube#10287]
🔎  Verifying ingress addon...

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by sharifelgamal** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* Your operating system

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

---

我还没有明确的方法来复制此问题。您介意添加一些其他详细信息吗？以下是其他有用的信息：

*您的操作系统

*使用的确切minikube启动命令行

* minikube start命令的完整输出，最好使用--alsologtostderr -v = 4来进行额外的日志记录。

* minikube日志的完整输出

* kubectl的完整输出得到po -A

感谢您分享经验！

**Comment by spowelljr** [comment]
Hi @zhangb191, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

嗨@ zhangb191，我们还没有收到您的回音，您还有这个问题吗？
此问题中没有足够的信息以使其无法操作，并且持续了足够长的时间，因此此问题很可能难以复制。

我将暂时关闭此问题，但是当您准备提供更多信息时，可以随时重新打开。
