### ISSUE TITLE
Minikube hangs on start if the hyper-v manager doesn't have a proper virtual switch. 

### ISSUE THREAD

**Issue by Yinten** [kubernetes/minikube#10299]
**Steps to reproduce the issue:** 

1.   Give virtual switch no internet
2.   run minikube start --drive=hyperv   
3.  Hangs

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by ilya-zuyev** [comment]
@Yinten thanks! Could you provide logs of `minikube start` and details about operating system you're using?

**Comment by spowelljr** [comment]
Hi @Yinten, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
