### ISSUE TITLE
Look into improving `minikube start` time with containerd by 10%

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#10438]
This would be about a 4 second improvement.

**Comment by priyawadhwa** [comment]
My main idea around improving start time is to start including preloaded tarballs in the kic base image.

Instead of downloading preload images as a separate tarball, we could include the tarball as the final layer in the kic image. 

Pros:
- Download should be the same for users, since we’re just downloading as an image layer instead of a separate tarball
- If we make sure to have the preload tarball as the last layer, then when a user wants to switch k8s version, they only have to download the additional layer for the new version, since the underlying base image has already been downloaded

Cons:
- Instead of having one kic base image, we would have one per kubernetes runtime (~50 images??)
- It would be really important to have robust automation around building and releasing all of these images
- We could continue to only build the default k8s versions for testing on individual PRs

**Comment by afbjorklund** [comment]
As you probably know, this is what kind is doing (with the "node" image, that is layered on top of the "base" image)

**Comment by afbjorklund** [comment]
In order to do this, one would probably first want to do different installation for different runtimes: #9989

Otherwise the kicnode image would be _enormous_, if it included both the packages and the images:

```
492M	~/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar.lz4
561M	~/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v10-v1.20.2-cri-o-overlay-amd64.tar.lz4
912M	~/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v10-v1.20.2-containerd-overlay2-amd64.tar.lz4
```

So in the "worst" case, you could end up with four different layers of images (some of them squashed?).

* base operating system (ubuntu)
* hacks to make it work under systemd (entrypoint)
* adding the container runtime
* adding the container binaries and images

But the final step should not be more complicated than trying to recreate what the code is currently doing.

```Dockerfile
FROM gcr.io/k8s-minikube/kicbase:v0.0.20
ADD preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar.lz4 /var
```

**Comment by afbjorklund** [comment]
Turns out that docker doesn't support lz4 compression for ADD, only gz and xz.

```Dockerfile
ADD preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar.gz /var
```

```
1146	preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar
492	preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar.lz4
348	preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar.gz
246	preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar.xz
```
