### ISSUE TITLE
SSH driver: please provide an IP address 

### ISSUE THREAD

**Issue by shafiurrahmanA** [kubernetes/minikube#10498]
Failed to start ssh bare metal machine. Running "minikube delete" may fix it: config: please provide an IP address  X Exiting due to GUEST_PROVISION: Failed to start host: config: please provide an IP address * * If the above advice does not help, please let us know:   - https://github.com/kubernetes/minikube/issues/new/choose

**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @shafiurrahmanA thanks for opening this issue. Could you please provide the following info so that we can help resolve it?

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`
* The full output of `kubectl get po -A`


Thank you for sharing your experience!

**Comment by medyagh** [comment]
@shafiurrahmanA SSH driver is our newest driver, it seems like u are trying to use SSH driver but u have not provided an IP address, I know on the early version there was a bug, have u tried with latest verison of minikube ?

and do u mind please share the full command that u call minikube with ? and also add --alsologtostderr for verbose logs ?

**Comment by medyagh** [comment]
we fixed this on master to not auto select ssh driver
