### ISSUE TITLE
minikube startup issue

### ISSUE THREAD

**Issue by limkakk** [kubernetes/minikube#10587]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by spowelljr** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr, for example:

```
$ minikube start --alsologtostderr
```
- Also the full the output of the
```
$ minikube logs
```
This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @limkakk, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
