### ISSUE TITLE
open() file failed (13: Permission denied) in nginx & docker

### ISSUE THREAD

**Issue by melekes** [kubernetes/minikube#1067]
**Minikube version** (use `minikube version`): v0.15.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
```
NAME=Buildroot
VERSION=2016.08
ID=buildroot
VERSION_ID=2016.08
PRETTY_NAME="Buildroot 2016.08"
```
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **Docker version** (e.g. `docker -v`): Docker version 1.11.1, build 5604cbe
- **Install tools**: was installed as a binary
- **Others**:
VBoxManage -version: 5.1.14r112924

**What happened**:
https://stackoverflow.com/questions/41987887/open-file-failed-13-permission-denied-in-nginx-docker-minikube

**What you expected to happen**:
Data directory will be mounted with correct permissions.

Compare output of minikube docker:

```
$ docker run -it --rm -v "$(PWD):/etc/nginx/conf.d":ro -v "$(PWD)/data:/data" -p 8085:80 nginx bash -c 'ls -la /data/ && nginx -g "daemon off;"'
total 8
drwxrwx--- 1 root 1013  102 Feb  1 13:08 .
drwxr-xr-x 1 root root 4096 Feb  1 20:47 ..
-rwxrwx--- 1 root 1013   11 Feb  1 13:08 pub_key.json
```

with host docker (Docker version 1.13.1-rc1, build 2527cfc):

```
$ docker run -it --rm -v "$(PWD):/etc/nginx/conf.d":ro -v "$(PWD)/data:/data" -p 8085:80 nginx bash -c 'ls -la /data/ && nginx -g "daemon off;"'
total 8
drwxrwxrwx  3 root root  102 Feb  1 13:08 .
drwxr-xr-x 34 root  root  4096 Feb  1 20:50 ..
-rwxrwxrwx  1 root root   11 Feb  1 13:08 pub_key.json
```

**Comment by r2d4** [comment]
These are actually different data folders.  One is the /data folder inside the minikube VM, the other is the /data folder on your host (or inside the docker for mac or windows VM).  

Can you give the output of 
`cat ~/.minikube/machines/minikube/config.json | grep ISO`

You may need to recreate minikube VM with `minikube delete` then 

```
minikube start --iso-url=https://storage.googleapis.com/minikube/iso/minikube-v1.0.5.iso
```

The permissions were fixed with https://github.com/kubernetes/minikube/pull/994, but we haven't done a release yet with that as the default image

**Comment by melekes** [comment]
`https://storage.googleapis.com/minikube/iso/minikube-v1.0.2.iso`

Yes, upgrading the iso fixed the problem. Thank you!
