### ISSUE TITLE
Using Bridge to K8s to debug minikube on VMWare

### ISSUE THREAD

**Issue by SillyCode** [kubernetes/minikube#10785]
Hi all,

I have a `Win10` host system on which I'm running a `VMware Workstation` `Debian` VM.
This VM has `Docker` and `Minikube` (started with driver=none) running and all works quite well.

My question is. Is it possible to debug an application running on the `Minikube` cluster (on the VM)
from the `Visual Studio` on `win10` using the "Bridge to Kubernetes"?

Thank you

**Comment by afbjorklund** [comment]
I think the none driver still binds to all interfaces, rather than localhost, so you can (ab)use that...
Instead of the regular 127.0.0.1, you use the VM IP. Eventually that **bug** will be fixed though: #4313

https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/

Otherwise when accessing a kubernetes cluster on a remote host, one normally uses SSH tunnels.
So you tunnel to the machine using minikube, either forwarding the 8443 port or use `kubectl proxy`

https://kubernetes.io/docs/tasks/extend-kubernetes/http-proxy-access-api/

----

In the future, using the `ssh` drivers will make it easier to use remote clusters such as this one.

Since it will set up your _local_ kubernetes config, instead of doing it on the control plane.

See https://github.com/kubernetes/minikube/issues/4733#issuecomment-510556159 for the reasoning behind the new driver, and how it completes "none".

The obvious alternative would otherwise be to run your IDE on the Debian VM with minikube.

**Comment by SillyCode** [comment]
As far as I understand VS unable to access the VM even if I copy the K8S config file over the host.
And using the VM IP address, still does not seem to get me to where I want to be. See image below:
![image](https://user-images.githubusercontent.com/5475378/111072026-7d528480-84e1-11eb-9dfc-9f75f151c879.png)

Also, not sure how do I make use of `kubectl proxy` for my benefit.

Resorted to using the VS Code IDE with Bridge to Kubernetes and remote debugging for now with .Net. 
Not the greatest solution but at least it works

**Comment by afbjorklund** [comment]
I think this could be a good topic for a tutorial, how to connect to a remote computer running minikube...

**Comment by SillyCode** [comment]
Actually, connecting to the VM is not a problem. It has NAT and bridged net cards defined.
So we do have explicit and direct access to it over SSH and over port 80/443.
So you are able to access K8S services on your web browser without any tunneling.
But having the VS IDE connecting to the VM cluster is a different issue.

**Comment by afbjorklund** [comment]
minikube is only supposed to be available to the local learning environment, i.e. localhost

**Comment by awhileback** [comment]
The whole point is to simulate an environment, which cannot be done if it refuses to talk to a network outside of the host it's running on.
