### ISSUE TITLE
Ingress nginx for TCP and UDP services

### ISSUE THREAD

**Issue by nikoladsp** [kubernetes/minikube#10978]
Is **ingress-nginx** the right namespace? I used **kube-system** in order to work.

**Comment by govargo** [comment]
/kind support
/area addons

Thank you for opening this.

I guess that you mentioned about [Ingress nginx for TCP and UDP services](https://minikube.sigs.k8s.io/docs/tutorials/nginx_tcp_udp_ingress/).

Until minikube v1.8.1(current latest), `kube-system` is namespace for ingress addon as you mentioned.
This will change at next release(maybe v1.9.0-beta and v1.9.0).
The PR is https://github.com/kubernetes/minikube/pull/10879.

`ingress-nginx` is the next namespace for ingress addon. This namespace is used by upstream([kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx)).

But unfortunatly, the document was merged in advance before next release by https://github.com/kubernetes/minikube/pull/10879.
This is because there is no version management on our docs.
So, you have to change the reading of the namespace.

**Comment by govargo** [comment]
v1.19.0 was released and I think this issue can be closed.

https://github.com/kubernetes/minikube/releases/tag/v1.19.0
