### ISSUE TITLE
minikube v0.16.0 artifacts missing from google cloud storage 

### ISSUE THREAD

**Issue by dims** [kubernetes/minikube#1112]
short story : Can someone please upload localkube binaries somewhere public please?

The Makefile[1] indicates that some artifacts are uploaded to google storage. The https://storage.googleapis.com/minikube/k8s_releases.json does contain v1.6.0-alpha.0 but is missing an entry for v1.6.0. 
More importantly `wget https://storage.googleapis.com/minikube/k8sReleases/v1.6.0-alpha.0/localkube-linux-amd64` works fine while `wget https://storage.googleapis.com/minikube/k8sReleases/v1.6.0/localkube-linux-amd64` fails. 

[1] https://github.com/kubernetes/minikube/blob/d9355d89e7f486ceb1157005f813e9a12a521599/Makefile#L178

**Comment by dlorenc** [comment]
Hey,

We don't have any v1.6.0 releases yet because it's not out :) We published the alpha.0 release, which you found.

We're currently working on getting a v1.6.0-alpha.1 release out soon, but we won't have v1.6.0 until it's officially released by k8s.

What build exactly are you trying to grab?

**Comment by dims** [comment]
@dlorenc very weird - i do not see any instances of "alpha" on this page https://github.com/kubernetes/minikube/releases/tag/v0.16.0

**Comment by dims** [comment]
but thanks for confirming :)

**Comment by dlorenc** [comment]
Ah, I see. Yeah I think that page should get changed, it's misleading. It looks like a bug in our release bot.

**Comment by r2d4** [comment]
@dims this isn't a bug

0.16 happens to be the current minikube version.  This is separate and unrelated to the _localkube_ version, which is tracked by the version of k8s that it vendors in.  For instance, the previous 0.15 version of minikube can run any version of k8s that we publish, including v1.6.0-alpha.0.

Localkube is a binary that is shipped inside minikube that runs the k8s components.  Minikube is a binary that provisions and manages a VM in order to run localkube.

**Comment by dims** [comment]
@r2d4 gotcha. thanks for the explanation. closing this bug.
