### ISSUE TITLE
X Exiting due to HOST_CONFIG_LOAD: unmarshal: unexpected end of JSON input

### ISSUE THREAD

**Issue by xsonghppy** [kubernetes/minikube#11123]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by spowelljr** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr, for example:

```
$ minikube start --alsologtostderr
```
- Also the full the output of the
```
$ minikube logs
```
This will help us isolate the problem further. Thank you!

-----

感谢您分享您的经验！如果您不介意，请提供以下信息：

-minikube版本。
-您使用的驱动程序。 （docker，virtualbox，hyperv ...）
-您使用的操作系统（Windows，Mac或Linux及其版本）
-通过添加--alsologtostderr，您正在使用的命令的完整输出，例如：

```
$ minikube start --alsologtostderr
```
- 也是完整的输出
```
$ minikube logs
```
这将帮助我们进一步隔离问题。谢谢！

/triage needs-information
/kind support

**Comment by ilya-zuyev** [comment]
@xsonghppy any update on this issue? thanks

**Comment by spowelljr** [comment]
Hi @xsonghppy, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

-----

嗨@xsonghppy，我们还没有收到您的回音，您还有这个问题吗？
此问题中没有足够的信息以使其无法操作，并且持续了足够长的时间，因此此问题很可能难以复制。

我将暂时关闭此问题，但是当您准备提供更多信息时，可以随时重新打开。
