### ISSUE TITLE
mac m1 minikube start error

### ISSUE THREAD

**Issue by onkeyi** [kubernetes/minikube#11246]
**Steps to reproduce the issue:** 

1. brew install minikube
2. minikube start 
3. 

**Full output of `minikube logs` command:**
<details>
Exiting due to GUEST_PROVISION: Failed to start host: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.20@sha256:0250dab3644403384bd54f566921c6b57138eecffbb861f9392feef9b2ec44f6 -d /var/lib: exit status 125
stdout:

</details>

**Full output of failed command:**
<details>
docker: Error: error contacting notary server: unknown: Project 'project:gcr.io:k8s-minikube' not found or deleted.
See 'docker run --help'.

</details>

**Comment by afbjorklund** [comment]
Hmm, that is the same problem setting up the minikube volume as we have seen on other operating systems.

Troubleshooting:
```
docker volume create test
docker run --rm --entrypoint /usr/bin/test -v test:/var gcr.io/k8s-minikube/kicbase:v0.0.20 -d /var/lib
docker volume inspect test
```

**Comment by spowelljr** [comment]
Hi @onkeyi, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
