### ISSUE TITLE
minikube service xxxx 命令访问不了pod的映射端口。

### ISSUE THREAD

**Issue by RtlduinoMan** [kubernetes/minikube#11252]
**重现问题所需的命令**： minikube service xxxx

**失败的命令的完整输出**：<details>
请看截图，我使用另外的一台电脑可以使用，这台会报错，192.168.49.2，在我的电脑上面是访问不了，不知道为什么minikube怎么会把作为node ip地址。

</details>

**`minikube logs`命令的输出**： <details>

</details>
在windows7 上面安装使用k8s出现的问题，这个问题已经困扰我 一周时间，希望可以尽快解决 ，谢谢。

**使用的操作系统版本**：
![minikube_error](https://user-images.githubusercontent.com/22052645/116809907-342ec080-ab73-11eb-98b7-f7692773305b.png)

**Comment by medyagh** [comment]
@RtlduinoMan  mind pasting the "minikube version" ?
and attach the file  `minikube logs -f logs.txt` to this issue ?

(ensure u are using the latest minikube)

**Comment by medyagh** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

The exact minikube start command line used: preferably with --alsologtostderr -v=8 added.
The full output of the command
The full output of "minikube logs"
Please feel free to do so at any point. Thank you for sharing your experience!
