### ISSUE TITLE
hack/release_notes.sh should print a link to the full changelog.

### ISSUE THREAD

**Issue by andriyDev** [kubernetes/minikube#11278]
Currently, hack/release_notes.sh prints release notes relative to the last release version regardless of if it is a beta release. For full releases though, this should be printed relative to the last full release.

This can be done by adding an optional argument to hack/release_notes.sh to specify the tag to print relative to.

**Comment by medyagh** [comment]
I think we should continue doing as we have been doing, maybe instead of repeating the changelog we could attach a link to the previous Beta Release 


For example in https://github.com/kubernetes/minikube/releases/tag/v1.19.0
There should be a link for https://github.com/kubernetes/minikube/releases/tag/v1.19.0-beta.0

**Comment by andriyDev** [comment]
As we've discussed, the better solution is to print a link to the full changelog, that way all changes can be seen in sequence!
