### ISSUE TITLE
`minikube cp` should support copying from minkube to user's host

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11296]
currently minikube cp does NOT support doing this.

```
minikube cp minikube:/var/lib/minikube/certs/etcd/peer.crt /tmp
```

current workaround by @tstromberg 
```
minikube ssh "cat /var/lib/minikube/certs/etcd/peer.crt" > /tmp/peer.cert
```

**Comment by afbjorklund** [comment]
This needs support in the Asset API, which currently only has `Copy`.

**Comment by vishjain** [comment]
@daehyeok Are you working on this?

**Comment by daehyeok** [comment]
@vishjain yes. i will make PR after little clean up code

**Comment by TairanLee** [comment]
Hi, now that minikube has `minikube cp`, but it seems it's underlying mechanism is still `cat >`?  
I'm asking this because I found a strange `cat` process, and the `minikube cp` running at low efficiency.  
If it can be done through scp or rsync, I think it would greatly improve the speed of copying.  
Thanks!
