### ISSUE TITLE
[kicbase] Proposal: install containerd (and docker) from binary tgz, not from deb

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/minikube#11327]
https://github.com/kubernetes/minikube/blob/c31bd57f93d45726e4bd30607374f8c720e70e95/deploy/kicbase/Dockerfile#L110-L114

Currently, kicbase uses `containerd.io` deb maintained by Docker, Inc.
This makes impossible to update kicbase to use containerd 1.5.0, as contained 1.5.0 is not available in the apt repo: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/

So I suggest installing containerd (and also docker) from binary tgz, not from deb.

The binary tgz of containerd can be fetched from https://github.com/containerd/containerd/releases .
The binary tgz of docker is available at https://download.docker.com/linux/static/stable/x86_64/ .

**Comment by afbjorklund** [comment]
Why is containerd and buildkitd not available as regular packages ?

**Comment by AkihiroSuda** [comment]
> Why is containerd and buildkitd not available as regular (apt/deb) packages ?

Mostly, it is simply because we do not know how to provide apt repo, without maintaining a web server, nor subscribing a paid service 😓 .
It would be great if GitHub or CNCF can provide free apt service.

**Comment by afbjorklund** [comment]
Actually containerd _is_ available as a system package:

https://packages.ubuntu.com/focal-updates/containerd

Not that it actually helps going to containerd 1.5.0

**Comment by medyagh** [comment]
Two things, we could either install containerd with binary on a the current kic base and measure the performance and the test failures and see how it performs

and if it performs better, we maybe could do a prototype of including the containerd Binary in the Preload Tar

**Comment by BenTheElder** [comment]
KIND (origin of kic base) is installing these from binary because of how incredibly old the packaged versions are. There are extremely useful improvements in more recent versions.


> if we install containerd from binaries, do we need to install systemd files ourselfes and do configruations ? 

Yes.

> is there an example of doing it correclty ?

There's a systemd unit in the containerd repo. https://github.com/containerd/containerd/blob/master/containerd.service

You can see also https://github.com/kubernetes-sigs/kind/tree/main/images/base which is still doing this of course.


> But trying to get Kubernetes or Google to host the apt and yum repositories...

Kubernetes will not be relying on the Google cloud's APT / YUM hosting long term, the Google package hosting can only be maintained by Googlers (Google is not going to give external users access to sign and upload packages to this infrastructure) and is not available as a product. Source: I lead the team currently ensuring the Kubernetes packages are built and uploaded (amongst other things), also this is tracked in https://github.com/kubernetes/release/issues/281

We're definitely not adding more projects to this.

**Comment by afbjorklund** [comment]
@medyagh : we would have to add our own configuration and our own systemd units. See "kind" for example

images/base/files/etc/
├── containerd
│   └── config.toml
├── crictl.yaml
└── systemd
    └── system
        ├── containerd.service

https://github.com/kubernetes-sigs/kind/tree/main/images/base/files/etc

Same thing for buildkitd

**Comment by afbjorklund** [comment]
This also needs to be synched with the installation in the VM, which currently has a mix of binary and source

https://github.com/kubernetes/minikube/tree/master/deploy/iso/minikube-iso/package/containerd-bin

https://github.com/kubernetes/minikube/tree/master/deploy/iso/minikube-iso/package/buildkit-bin

**Comment by medyagh** [comment]
I would like to see more feature parity between our ISO and KIC image so I would +1 for installing containerd using binary as opposed to deb package

**Comment by AkihiroSuda** [comment]
We have containerd 1.6 dpkgs now, so no need to use tgz atm

**Comment by afbjorklund** [comment]
Couldn't find any deb from containerd.io, only the docker ones ?

**Comment by AkihiroSuda** [comment]
> Couldn't find any deb from containerd.io, only the docker ones ?

Docker, Inc. provides RPM/DPKG packages named `containerd.io`, but the containerd project (https://containerd.io) does not provide such packages (mostly because of lack of APT/DNF repo infra)
