### ISSUE TITLE
Use containerd runtime by default

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#11406]
It looks like in the next years Kubernetes development will be based on containerd as CRI implementation. Let's follow it and switch default container runtime from docker to containerd.

**Comment by afbjorklund** [comment]
This is duplicating the "MEP" process: #9639

The problem is not so much changing the default container runtime, the main issue are the implications like `docker-env` disappearing and BuildKit installation still having some usability issues.

Also it seems like kind and kubeadm have very different strategies on _which_ containerd to choose. Where kind uses latest/greatest from upstream, but kubeadm uses the one from docker ?

**Comment by medyagh** [comment]
we should decide based on users needs, minikube's main users are local developers. current bechmarks for image build https://minikube.sigs.k8s.io/docs/benchmarks/imagebuild/ shows docker runtime has better image build
