### ISSUE TITLE
minikube failed to start on macos

### ISSUE THREAD

**Issue by timekarma** [kubernetes/minikube#11468]
**Steps to reproduce the issue:** 

1.curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
2. sudo install minikube-darwin-amd64 /usr/local/bin/minikube
3.minikube start

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>
[lastStart.txt](https://github.com/kubernetes/minikube/files/6512550/lastStart.txt)

**Comment by dinever** [comment]
Hi @timekarma,

Thanks for reporting the issue!

```
curl -sS -m 2 https://k8s.gcr.io/: Process exited with status 28
```

It appears that your hyperkit VM doesn't have network access as the above `curl` timed out.

Do you have any VPN (e.g. Cisco Anyconnect) running or any special Docker desktop configuration enabled?

Thanks!

**Comment by spowelljr** [comment]
Hi @timekarma, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
