### ISSUE TITLE
minikube start not working

### ISSUE THREAD

**Issue by gthri2k** [kubernetes/minikube#11488]
Hi,
I'm having trouble installing minikube.
I have a windows 10 machine. Have installed ubuntu in Oracle VM Virtual box manager
When I give minikube start , it throws me this error

    
 minikube v1.20.0 on Ubuntu 20.04
✨  Automatically selected the virtualbox driver

🧯  The requested memory allocation of 1939MiB does not leave room for system overhead (total system memory: 1939MiB). You may face stability issues.
💡  Suggestion: Start minikube with less memory allocated: 'minikube start --memory=1939mb'

👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=1939MB, Disk=20000MB) ...
🔥  Deleting "minikube" in virtualbox ...
🤦  StartHost failed, but will try again: creating host: create host timed out in 360.000000 seconds
🔥  Creating virtualbox VM (CPUs=2, Memory=1939MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create host timed out in 360.000000 seconds
❗  Startup with virtualbox driver failed, trying with alternate driver ssh: Failed to start host: creating host: create host timed out in 360.000000 seconds
🔥  Deleting "minikube" in virtualbox ...
💀  Removed all traces of the "minikube" cluster.

❌  Exiting due to MK_USAGE: No IP address provided. Try specifying --ssh-ip-address, or see https://minikube.sigs.k8s.io/docs/drivers/ssh/

Thanks

**Comment by afbjorklund** [comment]
Please disregard the errors from "ssh" at the end, they have been fixed: #11371

! Startup with virtualbox driver failed, trying with alternate driver ssh: Failed to start host: creating host: create host timed out in 360.000000 seconds

x Exiting due to MK_USAGE: No IP address provided. Try specifying --ssh-ip-address, or see https://minikube.sigs.k8s.io/docs/drivers/ssh/

The real error is the timeout, probably from trying to run VirtualBox in Virtualbox

Would it not be easier to run minikube from Windows, and skip the Ubuntu VM ?

**Comment by gthri2k** [comment]
Oh yes! This works from windows! Thanks!
