### ISSUE TITLE
kvm2 driver unable to set up network connecting two minikube instances

### ISSUE THREAD

**Issue by jmazzitelli** [kubernetes/minikube#11499]
I want two minikube instances (using `kvm2` driver) each running on the same host be able to talk to each other. However, it doesn't work.

**Steps to reproduce the issue:** 

1. I have a simple/default kvm installation from rpm on RHEL 8.3 - I did no customizations.

2. Installed two minikube instances (east and west):
```
$ minikube --driver=kvm2 --profile=east start
😄  [east] minikube v1.19.0 on Redhat 8.3
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node east in cluster east
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.4 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "east" cluster and "default" namespace by default

$ minikube --driver=kvm2 --profile=west start
😄  [west] minikube v1.19.0 on Redhat 8.3
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node west in cluster west
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🔥  Deleting "west" in kvm2 ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine west didn't return IP after 1 minute
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.4 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "west" cluster and "default" namespace by default
```

3. Both have valid IPs
```
$ minikube --profile=east ip
192.168.39.176

$ minikube --profile=west ip
192.168.50.5
```

4. My laptop host can see west k8s master API
```
$ curl -kI "https://192.168.50.5:8443/api/v1/namespaces" && echo ">>> can see west!"
HTTP/2 403 
cache-control: no-cache, private
content-type: application/json
x-content-type-options: nosniff
x-kubernetes-pf-flowschema-uid: 6455027e-e40e-4b29-a8ba-40894522a5e6
x-kubernetes-pf-prioritylevel-uid: 104ce126-7517-48cb-b5d6-8a333a91ee43
content-length: 320
date: Mon, 24 May 2021 16:33:05 GMT

>>> can see west!
```

5.  But why can't I see west k8s master API from inside of east???

```
$ minikube -p east ssh -- curl -kI "https://192.168.50.5:8443/api/v1/namespaces" && echo ">>> can see west!"
curl: (7) Failed to connect to 192.168.50.5 port 8443: Connection refused
ssh: Process exited with status 7
```

FWIW: I never had this kind of problem using driver `virtualbox` - but I switched laptops so I tried `kvm2` driver and found it didn't work as explained above.

**Comment by jmazzitelli** [comment]
And to show you how I expect it to work - I just installed virtualbox, and then installed 2 minikube instances (again called "east" and "west") but this time I used `virtualbox` for the `--driver` option. This is now what I see (notice I can see west's k8s master API from within east minikube):

```
$ minikube -p east ip
192.168.99.101
$ minikube -p west ip
192.168.99.102
```

From the host:

```
$ curl -kI "https://192.168.99.102:8443/api/v1/namespaces" && echo ">>> can see west"
HTTP/2 403 
cache-control: no-cache, private
content-type: application/json
x-content-type-options: nosniff
x-kubernetes-pf-flowschema-uid: 9b66073b-5a7a-4902-a83b-f758ca69938b
x-kubernetes-pf-prioritylevel-uid: bf8f0cc9-094c-4342-9440-d812bc080154
content-length: 320
date: Mon, 24 May 2021 19:48:31 GMT

>>> can see west
```

From east minikube:
```
$ minikube -p east ssh -- curl -kI "https://192.168.99.102:8443/api/v1/namespaces" && echo ">>> can see west"
HTTP/1.1 403 Forbidden
Cache-Control: no-cache, private
Content-Type: application/json
X-Content-Type-Options: nosniff
X-Kubernetes-Pf-Flowschema-Uid: 9b66073b-5a7a-4902-a83b-f758ca69938b
X-Kubernetes-Pf-Prioritylevel-Uid: bf8f0cc9-094c-4342-9440-d812bc080154
Date: Mon, 24 May 2021 19:48:59 GMT
Content-Length: 320

>>> can see west
```

**Comment by jmazzitelli** [comment]
For the record, I did try to start both minikube instances with the same `--network` value, but I couldn't even start one of them up:

```
$ minikube --driver=kvm2 --network mc --profile east start
😄  [east] minikube v1.19.0 on Redhat 8.3
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node east in cluster east
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🔥  Deleting "east" in kvm2 ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine east didn't return IP after 1 minute
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
😿  Failed to start kvm2 VM. Running "minikube delete -p east" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine east didn't return IP after 1 minute

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine east didn't return IP after 1 minute

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

So for some reason `--network` isn't helpful here.

**Comment by jmazzitelli** [comment]
I was on v1.19.0 of minikube -- just tried the latest v1.20.0 and still didn't work. I'm attaching the logs here.
[minikube_--driver_97150c08fdbaf81b51845722203d6cf71ab29d74_0.log](https://github.com/kubernetes/minikube/files/6535512/minikube_--driver_97150c08fdbaf81b51845722203d6cf71ab29d74_0.log)

**Comment by sharifelgamal** [comment]
@prezha any guidance here?

**Comment by prezha** [comment]
sure, @sharifelgamal !

@jmazzitelli this is "by design" (ie, expected behaviour): kvm2 driver uses private subnet to connect guest - minikube cluster node(s) to the host while being isolated from other guests - minikube cluster node(s) that are deliberately placed on different/separate private subnets

if you compare your kvm2 and virtualbox examples from the above, you can notice that kvm2 minikube clusters are created on different subnets (192.168.39.0/24 and 192.168.50.0/24), while virtualbox keeps them all on the same one (192.168.99.0/24), which is why they are able to communicate directly in the later case.

***but***, there's a way to enable comm between kvm2 minikube clusters - you can try the following steps:
1. stop both east and west kvm2 minikube clusters (`minikube stop --profile east` and `minikube stop --profile west`)
2. `sudo virsh net-edit mk-east` (should open your default editor) and insert `  <forward mode='route'/>` line eg, below the line with `<uuid>`, so it looks something like:
```
<network>
  <name>mk-east</name>
  <uuid>9cfebe30-6319-4de2-8a6d-8381a33059f5</uuid>
  <forward mode='route'/>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac address='52:54:00:fc:fc:d5'/>
  <dns enable='no'/>
  <ip address='192.168.39.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.39.2' end='192.168.39.254'/>
      <host mac='52:54:00:cd:2e:19' name='east' ip='192.168.39.34'/>
    </dhcp>
  </ip>
</network>
```
save and execute: `virsh net-destroy mk-east` then `virsh net-start mk-east`
3. repeat the previous step (2.) for 'west'
4. start both east and west kvm2 minikube clusters (`minikube start --profile east` and `minikube start --profile west`)
5. please test again and report the results here :)

i do remember "implementing" this "feature" last time i worked on kvm2 driver and don't remember i had any issues (eg, side effects) back then, but there were other significant changes i made then there, so i decided not to mix it in at that time, while the change is quite simple - ie, inserting the `<forward mode='route'/>` line eg after the line with `<name>` in the network interface template:
https://github.com/kubernetes/minikube/blob/b49acefb2acf72d11ca0869349f6a0432a5748fb/pkg/drivers/kvm/network.go#L37-L49

**Comment by medyagh** [comment]
@jmazzitelli does the answer by @prezha help ?

**Comment by jmazzitelli** [comment]
I haven't tried it yet. I'll assume it works :) Thanks for the info.
