### ISSUE TITLE
vmware: No arranco 

### ISSUE THREAD

**Issue by aymg01** [kubernetes/minikube#11605]
Hola,

SO: Win 10-20H2
VMware® Workstation 16 Pro: 16.1.2 build-17966106

Utilicé Chocolatey "choco install minikube" para instalar, luego de no arrojar errores, intentó iniciar pero sacaba el error que no se encontraba vmrun. Agregue el path de Windows toda la carpeta de los ejecutables de vmware: "C:\Program Files (x86)\VMware\VMware Workstation" con lo que el error no salió, pero nunca pudo arrancar la maquina. Adjunto archivo de log y espero sea de ayuda.

Saludos y gracias!

[lastStart.txt](https://github.com/kubernetes/minikube/files/6613353/lastStart.txt)

**Comment by sharifelgamal** [comment]
Hi @aymg01, it looks like the error came from VMWare itself: 

```
I0607 22:35:16.975610    5112 main.go:128] libmachine: (minikube) DBG | executing: C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe start C:\Users\aymg0\.minikube\machines\minikube\minikube.vmx nogui
I0607 22:35:17.834814    5112 main.go:128] libmachine: (minikube) DBG | Error: The operation was canceled
```

I would suggest running `minikube delete` then `minikube start` again to see if that helps.

---


Hola @ aymg01, parece que el error provino del propio VMWare:

```
I0607 22:35:16.975610    5112 main.go:128] libmachine: (minikube) DBG | executing: C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe start C:\Users\aymg0\.minikube\machines\minikube\minikube.vmx nogui
I0607 22:35:17.834814    5112 main.go:128] libmachine: (minikube) DBG | Error: The operation was canceled
```

Sugeriría ejecutar `minikube delete` y luego` minikube start` nuevamente para ver si eso ayuda.

**Comment by spowelljr** [comment]
Hi @aymg01, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

-----

Hola @ aymg01, no hemos tenido noticias tuyas, ¿todavía tienes este problema?
No hay suficiente información en este problema para que sea procesable, y ha pasado una duración lo suficientemente larga, por lo que es probable que este problema sea difícil de replicar.


Cerraré este problema por ahora, pero no dude en volver a abrirlo cuando se sienta listo para proporcionar más información.
