### ISSUE TITLE
│    - /tmp/minikube_stop_f872f27c991140edb3970cd203c691f8ea8e5445_0.log    │

### ISSUE THREAD

**Issue by zettaRepo** [kubernetes/minikube#11776]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by RA489** [comment]
@zettaRepo Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by spowelljr** [comment]
Hi @zettaRepo, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by zettaRepo** [comment]
Hello sir the problem is fixed. But I Don't know how it is happened and
what I did to fix it .

Le mer. 21 juil. 2021 à 19:06, Steven Powell ***@***.***> a
écrit :
