### ISSUE TITLE
discourge users of using virtualbox driver when other options are available

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11913]
virtualbox is cause of most of the minikube support issues and un-happy users.

some users have been using virtualbox  because of previous config, we should Advice and encourage users to use other drivers if they are available

for example KVM on linux
hyperv on Windows
and hyperkit on Mac

**Comment by de-sh** [comment]
Hi, I am very new to the minikube repo and golang in general, but I do have some experience learning the basics of k8s with it's help, so I felt like giving this issue a look and I have a very naive idea for a solution which brings the following questions to mind, sorry if this isn't going anywhere:

Would the solution classify as the addition of [a new Exit Code and an issue to the Issue list](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/reason/known_issues.go#L537) that would print out a suggestion to use any of the other drivers from [`SupportedDrivers()`](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/driver/driver.go#L74)?

Some of the commands I see triggering this might include:
- `minikube start --vm-driver virtualbox`
- `minikube config set vm-drive virtualbox`

We should be allowing people to also force the use of virtualbox if they chose to do so, how do you think we should go about doing that?

**Comment by spowelljr** [comment]
Hi @de-sh, thank you for being willing to contribute to minikube!

First off, if you'd like to work on this issue, comment `/assign` and this issue will be assigned to you.

-----

> Would the solution classify as the addition of [a new Exit Code and an issue to the Issue list](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/reason/known_issues.go#L537) that would print out a suggestion to use any of the other drivers from [`SupportedDrivers()`](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/driver/driver.go#L74)?

No, this would not be an addition of a new exit code. We already have an example of this with the `none` driver. If you start minikube with the `none` driver the following is output:
```
❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/
```
For reference: https://github.com/kubernetes/minikube/blob/master/pkg/minikube/node/start.go#L667

These are just basic messages output to the screen.

-----

> We should be allowing people to also force the use of virtualbox if they chose to do so, how do you think we should go about doing that?

So the output above is shown to the user, but that is the extent of the work. We don't exit or force the user to not use the `none` driver, we just inform them and let them decide how they want to go from there, the same would be the case for this issue.

-----

In order to get the list of possible drivers you can use https://github.com/kubernetes/minikube/blob/master/pkg/minikube/driver/driver.go#L246, this returns them in order of preference.

-----

Hopefully this helps you get started, if you have anymore questions feel free to ask.

**Comment by de-sh** [comment]
Thanks for the detailed update @spowelljr, have started writing some code, will point you to it for review soon 😄

**Comment by de-sh** [comment]
How does the following message look?
```
❗  The 'virtualbox' driver could be troublesome to work with, do not use if you aren't familiar with it
💡  You could instead use one of the drivers listed below:
- kvm2
- ssh
- vmware

📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/
```
