### ISSUE TITLE
no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run

### ISSUE THREAD

**Issue by Abdulrhman-max** [kubernetes/minikube#12001]
* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/
*

**Comment by spowelljr** [comment]
Hi @Abdulrhman-max, thanks for reporting you issue with minikube!

It looks like you don't have a switch setup, is that correct?

https://docs.docker.com/machine/drivers/hyper-v/#example
This is an example of how to setup a switch, let me know if that help.

**Comment by spowelljr** [comment]
Hi @Abdulrhman-max, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
