### ISSUE TITLE
Show which versions of Kubernetes are available to use

### ISSUE THREAD

**Issue by mcandre** [kubernetes/minikube#1201]
**FEATURE REQUEST**

Please offer a `minikube start` subcommand for showing the list of available Kubernetes versions, so that users don't have to guess in the dark which version strings will result in a valid download URL.

**Comment by aaron-prindle** [comment]
This is already possible via the `minikube get-kubernetes-versions` command

**Comment by feluxe** [comment]
`minikube get-k8s-versions` doesn't work with `0.30.0`.

**Comment by raiviskrumins** [comment]
@feluxe please read this https://github.com/kubernetes/website/pull/10423
this command ir removed, now you can use k8s version in free form:
`minikube start --kubernetes-version 1.12`

**Comment by feluxe** [comment]
@raiviskrumins Thanks for your reply.

I know about `--kubernetes-version` but it doesn't really help in the sense, that you need to know the exact version of kubernetes that you want to run.

If I run `minikube start --kubernetes-version '1.10'` I get this error:

```
Starting local Kubernetes 1.10 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E1116 15:34:45.763458   18280 start.go:254] Error updating cluster:  generating kubeadm cfg: parsing kubernetes version: parsing kubernetes version: No Major.Minor.Patch elements found
```

I don't know the latest `Patch` version and it's somewhat hard to find it online. 

I think it would be nice if `minikube` either:

* automatically selecting the latest `Patch` version in case you omit it.
* offer a command such as `get-k8s-versions` to get a list of all available versions.

**Comment by Typraeurion** [comment]
I’m having this same issue.  [constants.go](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/constants/constants.go) doesn’t help because that only shows the oldest and newest supported versions.  [Version Skew Policy](https://kubernetes.io/releases/version-skew-policy/) doesn’t help because that only lists minor versions, not patch versions.  In my case I need to run the latest patch version of 1.21, but specifying `--kubernetes-version=1.21` results in the error:
> Exiting due to MK_USAGE: Unable to parse "1.21": No Major.Minor.Patch elements found

and specifying any random guess like `--kubernetes-version=1.21.314159265358` results in:
> Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubeadm: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.21.314159265358/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.21.314159265358/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.21.314159265358/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.21.314159265358/bin/linux/amd64/kubeadm.sha256 Dst:/Users/trevinbeattie/.minikube/cache/linux/amd64/v1.21.314159265358/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x7334c78 0x7334c78 0x7334c78 0x7334c78 0x7334c78 0x7334c78 0x7334c78] Decompressors:map[bz2:0x7334c78 gz:0x7334c78 tar:0x7334c78 tar.bz2:0x7334c78 tar.gz:0x7334c78 tar.xz:0x7334c78 tar.zst:0x7334c78 tbz2:0x7334c78 tgz:0x7334c78 txz:0x7334c78 tzst:0x7334c78 xz:0x7334c78 zip:0x7334c78 zst:0x7334c78] Getters:map[file:0xc0015d0850 http:0xc001591460 https:0xc001591480] Dir:false ProgressListener:0x72f3e50 Insecure:false Options:[0x5541880]}: invalid checksum: Error downloading checksum file: bad response code: 404

I found an official list of Kubernetes releases at https://kubernetes.io/releases/ and tried `--kubernetes-version=1.21.13` which is the latest 1.21 listed, there, but that resulted in _another_ error which appears to be a consequence of the previous failed start:
> Exiting due to K8S_DOWNGRADE_UNSUPPORTED: Unable to safely downgrade existing Kubernetes v1.21.314159265358 cluster to v1.21.13

So I had to run `minikube delete` to delete the cluster (which as far as I can remember was last running 1.16) and then start it again on the newer version.
