### ISSUE TITLE
Cannot reconfigure metallb addon

### ISSUE THREAD

**Issue by victor-sudakov** [kubernetes/minikube#12051]
After configuring the metallb addon for the first time, I later decided to change the IP address range but have no idea how to "unconfigure" or "reconfigure" the addon without recreating the cluster from scratch:
```
$ minikube version
minikube version: v1.20.0
commit: c61663e942ec43b20e8e70839dcca52e44cd85ae
$ minikube addons configure metallb 
  - Using image metallb/speaker:v0.8.2
  - Using image metallb/controller:v0.8.2
* metallb was successfully configured
```
and that's it. How do I recall the interactive dialog about the IP range?

**Comment by spowelljr** [comment]
Hi @victor-sudakovm thanks for reporting you issue with minikube!

The way the addon is currently configured it doesn't re-ask for the values if they're already set, as you've discovered. However, since the point of `minikube config` is specifically asking to configure the value, I think this should be changed to always ask for the values.

As a work around for now you can open `~/.minikube/profiles/minikube/config.json` and edit `LoadBalancerStartIP` and `LoadBalancerEndIP` manually and then run `minikube addons enable metallb` to generate the template manifest files.

**Comment by spowelljr** [comment]
My change fixing this is merged in, this will be fixed with the next release of minikube.
