### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: dial unix /var/run/docker.sock: connect: permission denied

### ISSUE THREAD

**Issue by mdbhamanii** [kubernetes/minikube#12094]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @mdbhamanii, thanks for reporting your issue with minikube!

The first thing to check is to make sure that Docker is in fact running.

If that's not your issue, could you please provide:

- The version of minikube.
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr, for example:

```
$ minikube start --alsologtostderr
```
- Also the full the output of the
```
$ minikube logs
```
This will help us isolate the problem further. Thank you!

**Comment by medyagh** [comment]
Hi @mdbhamanii , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
