### ISSUE TITLE
Problem in Starting minikube on window10

### ISSUE THREAD

**Issue by QaSajjad** [kubernetes/minikube#12123]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>
[lastStart.txt](https://github.com/kubernetes/minikube/files/6934621/lastStart.txt)

**Comment by spowelljr** [comment]
Hi @QaSajjad, thanks for reporting your issue with minikube!

Unfortunately, it looks like your log file didn't finish uploading, can you please try uploading it again, thanks!

**Comment by QaSajjad** [comment]
Hi @spowelljr 
I have uploaded it again, please check and reply.
[lastStart.txt](https://github.com/kubernetes/minikube/files/6963925/lastStart.txt)

**Comment by spowelljr** [comment]
Hi @QaSajjad, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
