### ISSUE TITLE
Error while running minikube with Hyper-V

### ISSUE THREAD

**Issue by soleimaniamir** [kubernetes/minikube#12454]
I'm trying to run minikube with Hyper-V vm-driver:

```
PS>minikube start --vm-driver=hyperv --force                                                                                                                             * minikube v1.23.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
! minikube skips various validations when --force is supplied; this may lead to unexpected behavior
* Using the hyperv driver based on user configuration

* Exiting due to PROVIDER_HYPERV_NOT_FOUND: The 'hyperv' provider was not found: exec: "powershell": executable file not found in %PATH%
```
Before running start command I tried this:

```
PS>Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All                                                                                             

Path          :
Online        : True
RestartNeeded : False
```
and:

```
PS>Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online                                                                                                 

FeatureName      : Microsoft-Hyper-V-All
DisplayName      : Hyper-V
Description      : Provides services and management tools for creating and running virtual machines and their resources.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
```
my minikube version is:

```
minikube version: v1.23.0
commit: 5931455374810b1bbeb222a9713ae2c756daee10
```
what should I do?

**Comment by AmiteshDTU** [comment]
I am getting this same error. How you have solved this error ?

**Comment by milinches** [comment]
A

**Comment by milinches** [comment]
Any solution to this issue? Because, I'm facing the same issue here. 🥲

**Comment by soleimaniamir** [comment]
@AmiteshDTU , @milinches 
Add "C:\Windows\System32\WindowsPowerShell\v1.0" to user Environment Variable and check again.

**Comment by wendeee** [comment]
I tried the above suggestions but kept having this error:

Exiting due to PROVIDER_HYPERV_NOT_FOUND: The 'hyperv' provider was not found: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-CimInstance Win32_ComputerSystem).HypervisorPresent failed:

C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent failed:

* Suggestion: Start PowerShell as an Administrator
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

After many attempts, this is what worked for me:

C:\Windows\system32>bcdedit /set hypervisorlaunchtype auto

C:\Windows\system32>powershell -version 5

C:\Windows\system32>minikube start --vm-driver=hyperv
