### ISSUE TITLE
Failed to start host

### ISSUE THREAD

**Issue by elisvaldoazevedo** [kubernetes/minikube#12484]
**Full output of failed command if not `minikube start`:**
<details>
[minikube_logs_a261d1e655d78e232bea12734f898ae89eb06229_0.log](https://github.com/kubernetes/minikube/files/7174542/minikube_logs_a261d1e655d78e232bea12734f898ae89eb06229_0.log)

[lastStart.txt](https://github.com/kubernetes/minikube/files/7174691/lastStart.txt)

</details>

**Comment by spowelljr** [comment]
Hi @elisvaldoazevedo, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
