### ISSUE TITLE
unable to enable the registry

### ISSUE THREAD

**Issue by bcui2020** [kubernetes/minikube#12622]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube addons enable registry

After waiting for almost 10 mins, it shows: 
`Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for kubernetes.io/minikube-addons=registry pods: timed out waiting for the condition]`

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**
[logs.txt](https://github.com/kubernetes/minikube/files/7248456/logs.txt)

**Full output of failed command if not `minikube start`:**

<details>
[minikube_addons_0044a390071a97f671fa7d10060fff54c4582349_0.log](https://github.com/kubernetes/minikube/files/7248462/minikube_addons_0044a390071a97f671fa7d10060fff54c4582349_0.log)
</details>

**Comment by spowelljr** [comment]
Hi @bcui2020, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
