### ISSUE TITLE
SSH driver: --ssh-key option not taken into account

### ISSUE THREAD

**Issue by vrubiolo** [kubernetes/minikube#12634]
**Steps to reproduce the issue:** 
`minikube -p vm-cloud-k8s start --driver=ssh --native-ssh=false --ssh-user=vrubiolo --ssh-ip-address=vm-cloud --ssh-key=~/.ssh/id_rsa-vm_cloud --alsologtostderr -v=4 2>&1 | tee minikube-root-user.log`

Provisioning goes on until it eventually fails. The output is riddled w/ messages like `Error configuring auth during provisioning Temporary Error: NewSession: new client: new client: Error creating new native config from ssh using: root, &{[] [/home/vrubiolo/.ssh/id_rsa]}: ssh: this private key is passphrase protected`

The SSH key to use should be `~/.ssh/id_rsa-vm_cloud` (the one I specified via `--ssh-key`), not `/home/vrubiolo/.ssh/id_rsa` (my default key)

[minikube-root-user.log](https://github.com/kubernetes/minikube/files/7260272/minikube-root-user.log)
[logs-root-user.txt](https://github.com/kubernetes/minikube/files/7260274/logs-root-user.txt)

**Comment by spowelljr** [comment]
Hi @vrubiolo, thanks for reporting you issue with minikube!

I was debugging your issue and found what I believe is the root of the problem (https://github.com/kubernetes/minikube/issues/12659).

In your log file `SSHKeyPath` is empty, which I'm assuming is related the config storing the path to your key as a relative path:
```
new ssh client: &{IP:vm-cloud Port:22 SSHKeyPath: Username:root}
```
Since it's empty it's defaulting to `id_rsa` which is why you're seeing related messages.

Can you try starting your instance again either with a space between the key and value, or using the absolute path to the file and let me know if that solves your problem?
