### ISSUE TITLE
Cannot access Windows host services from pod

### ISSUE THREAD

**Issue by sousarmb** [kubernetes/minikube#12654]
minikube start --cpus=2 --memory=4g --network-plugin=cni --cni=calico --disk-size=5g --driver=hyperv --container-runtime=docker

Running minikube - v1.23.2, commit: 0a0ad764652082477c00d51d2475284b5d39ceed - on Windows 10 Professional, with the following scenario:

I'm trying to access SSH tunnel to use a DB server in another host. The tunnel is set up in the Windows host with Bitwise and listening on 0.0.0.0:1435 .

If i use Docker for Desktop - using host.docker.internal - i can access the DB on the other host without any issues. When i switch to minikube - using host.minikube.internal - i always get a timeout.

I know the Docker for Desktop setup works because i can see connections happenning in the Bitwise log.

**Comment by davclark** [comment]
I'm likewise trying to figure this one out. The docs for the minikube drivers say that the target of `host.minikube.internal` varies by driver, but doesn't provide details.

The below is from the perspective of Minikube run from WSL2 w/ docker driver on Docker Desktop.

From inside the minikube host container (i.e., the one you access via `minikube ssh`, 192.168.49.2 for me), both host.minikube.internal and host.docker.internal resolve to IP addresses, and I can ping both. The docker hostname resolves to my host AND I can netcat to a "host" process (including Windows processes and WSL2 processes) like `nc -vz host.docker.internal`. The minikube hostname is live according to `ping`, but I can't access host processes (nor do I know where that IP address resolves to, 192.168.49.1 for me).

There are a couple ways to address this:
1. The ideal would be to always have `host.minikube.internal` route through to the actual host. I know there is a route because Docker Desktop is setting this up. 
2. Another alternative that I'm using now is to configure your host process using the `host.docker.internal` hostname when using the minikube docker driver. This appears to be a potential solution for OP as well?
  - Ideally I would be able to query a running minikube for this info, is this possible?
  - Alternatively, I can write the driver to a file from a script when I start minikube, and read that value later when configuring k8s (in my case, configuring a CRD - which makes this a bit of a pain).
