### ISSUE TITLE
The VM session was closed before any attempt to power it on.

### ISSUE THREAD

**Issue by ramuyesupogu** [kubernetes/minikube#12747]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<Details: 00:05:42.484195 VBoxHeadless: stopping windows message loop
* Restarting existing virtualbox VM for "minikube" ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: driver start: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: The VM session was closed before any attempt to power it on
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface ISession>

<Details: 00:05:42.484195 VBoxHeadless: stopping windows message loop
>
[lastStart.txt](https://github.com/kubernetes/minikube/files/7378786/lastStart.txt)

**Comment by spowelljr** [comment]
Hi @ramuyesupogu, thanks for reporting your issue with minikube!

What version of VirtualBox are you using?

Also, please update to the latest version of minikube (v1.24.0) and see if this is resolved, thanks!

**Comment by spowelljr** [comment]
Hi @ramuyesupogu, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
