### ISSUE TITLE
Failed to start host: creating host: create host timed out in 360.000000 seconds 💡  Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software

### ISSUE THREAD

**Issue by Mohaloou** [kubernetes/minikube#12760]
**Hello,
I installed a hypervisor where I installed ubuntu, and I followed all the steps to install minikube, but I can't launch it:**

Kubectl version : 
clientVersion:
  buildDate: "2021-09-15T21:38:50Z"
  compiler: gc
  gitCommit: 8b5a19147530eaac9476b0ab82980b4088bbc1b2
  gitTreeState: clean
  gitVersion: v1.22.2
  goVersion: go1.16.8
  major: "1"
  minor: "22"
  platform: linux/amd64

The connection to the server localhost:8080 was refused - did you specify the right host or port?
------------------------------------------------------------------------------------------------------------------
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 ----------------------------------------------------------------------------------------------------------------------------------

😄  minikube v1.23.2 on Ubuntu 20.04
✨  Automatically selected the virtualbox driver. Other choices: none, ssh
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🔥  Deleting "minikube" in virtualbox ...
🤦  StartHost failed, but will try again: creating host: create host timed out in 360.000000 seconds
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create host timed out in 360.000000 seconds

❌  Exiting due to DRV_CREATE_TIMEOUT: Failed to start host: creating host: create host timed out in 360.000000 seconds
💡  Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software
🍿  Related issue: https://github.com/kubernetes/minikube/issues/7072

---------------------------------------------------------------------------------------------

**I also uninstalled the VPN and disabled firewall :**

 openvpn.service
     Loaded: masked (Reason: Unit openvpn.service is masked.)
     Active: inactive (dead)

oct. 22 01:22:31 mohamed-VirtualBox systemd[1]: Starting OpenVPN service...
oct. 22 01:22:31 mohamed-VirtualBox systemd[1]: Finished OpenVPN service.
oct. 22 01:25:00 mohamed-VirtualBox systemd[1]: openvpn.service: Succeeded.
oct. 22 01:25:00 mohamed-VirtualBox systemd[1]: Stopped OpenVPN service.

ufw disable
firewall stopped and disabled on system startup

---------------------------------------------------------------------------------------------------------------------------
**I I also activated VT-X for the virtual machine (Virtualbox)

😄  minikube v1.23.2 on Ubuntu 20.04
✨  Automatically selected the virtualbox driver. Other choices: none, ssh
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🔥  Deleting "minikube" in virtualbox ...
🤦  StartHost failed, but will try again: creating host: create host timed out in 360.000000 seconds
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create host timed out in 360.000000 seconds

❌  Exiting due to DRV_CREATE_TIMEOUT: Failed to start host: creating host: create host timed out in 360.000000 seconds
💡  Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software
🍿  Related issue: https://github.com/kubernetes/minikube/issues/7072

But I still can't start minikube .. can you help please ?

Thank you in advance.**

**Comment by 3ch01c** [comment]
It sounds like you are creating a Virtualbox VM inside a Virtualbox VM, which seems unnecessarily complicated. You might have better luck installing Minikube directly from the host using a package manager. On Windows, I prefer to [install Minikube via Chocolatey](https://v1-18.docs.kubernetes.io/docs/tasks/tools/install-minikube/#tab-with-md-2). On Linux & Mac, I prefer to [install Minikube with Homebrew](https://v1-18.docs.kubernetes.io/docs/tasks/tools/install-minikube/#tab-with-md-1). Hope that helps.

**Comment by spowelljr** [comment]
Hi @Mohaloou, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by imjerri** [comment]
> Hi @Mohaloou, we haven't heard back from you, do you still have this issue? There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.
> 
> I will close this issue for now but feel free to reopen when you feel ready to provide more information.

hey man...i stuck with the same problem in minikube installation

**Comment by imjerri** [comment]
jerrii@exilir:~$ minikube logs

==> Audit <==
|---------|-----------------------|----------|--------|---------|---------------------|---------------------|
| Command |         Args          | Profile  |  User  | Version |     Start Time      |      End Time       |
|---------|-----------------------|----------|--------|---------|---------------------|---------------------|
| start   |                       | minikube | jerrii | v1.27.1 | 11 Oct 22 16:07 IST |                     |
| start   | --driver=virtualbox   | minikube | jerrii | v1.27.1 | 11 Oct 22 16:07 IST |                     |
| config  | set driver virtualbox | minikube | jerrii | v1.27.1 | 11 Oct 22 16:09 IST | 11 Oct 22 16:09 IST |
| delete  |                       | minikube | jerrii | v1.27.1 | 11 Oct 22 16:10 IST | 11 Oct 22 16:10 IST |
| start   | --driver=virtualbox   | minikube | jerrii | v1.27.1 | 11 Oct 22 16:10 IST |                     |
| start   | --driver=virtualbox   | minikube | jerrii | v1.27.1 | 11 Oct 22 21:46 IST |                     |
| start   | --driver=virtualbox   | minikube | jerrii | v1.27.1 | 11 Oct 22 21:53 IST |                     |
| start   | --driver=virtualbox   | minikube | jerrii | v1.27.1 | 11 Oct 22 21:54 IST |                     |
| start   |                       | minikube | jerrii | v1.27.1 | 11 Oct 22 22:07 IST |                     |
| start   |                       | minikube | jerrii | v1.27.1 | 11 Oct 22 22:09 IST |                     |
| start   |                       | minikube | jerrii | v1.27.1 | 12 Oct 22 07:30 IST |                     |
| start   | --driver=virtualbox   | minikube | jerrii | v1.27.1 | 12 Oct 22 07:47 IST |                     |
| start   | --driver=virtualbox   | minikube | jerrii | v1.27.1 | 12 Oct 22 07:57 IST |                     |
| delete  |                       | minikube | jerrii | v1.27.1 | 12 Oct 22 08:15 IST |                     |
| start   |                       | minikube | jerrii | v1.27.1 | 12 Oct 22 08:18 IST |                     |
| stop    |                       | minikube | jerrii | v1.27.1 | 12 Oct 22 08:21 IST |                     |
|---------|-----------------------|----------|--------|---------|---------------------|---------------------|


==> Last Start <==
Log file created at: 2022/10/12 08:18:11
Running on machine: exilir
Binary: Built with gc go1.19.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1012 08:18:11.789538    7082 out.go:296] Setting OutFile to fd 1 ...
I1012 08:18:11.789651    7082 out.go:348] isatty.IsTerminal(1) = true
I1012 08:18:11.789653    7082 out.go:309] Setting ErrFile to fd 2...
I1012 08:18:11.789657    7082 out.go:348] isatty.IsTerminal(2) = true
I1012 08:18:11.789733    7082 root.go:333] Updating PATH: /home/jerrii/.minikube/bin
I1012 08:18:11.794410    7082 out.go:303] Setting JSON to false
I1012 08:18:11.852278    7082 start.go:116] hostinfo: {"hostname":"exilir","uptime":1595,"bootTime":1665541297,"procs":332,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.15.0-50-generic","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"be8f17da-ae4d-4a74-b2e1-8c1d216c8de5"}
I1012 08:18:11.852333    7082 start.go:126] virtualization: kvm host
I1012 08:18:12.122282    7082 out.go:177] 😄  minikube v1.27.1 on Ubuntu 22.04
I1012 08:18:12.364498    7082 notify.go:220] Checking for updates...
I1012 08:18:12.364967    7082 config.go:180] Loaded profile config "minikube": Driver=virtualbox, ContainerRuntime=docker, KubernetesVersion=v1.25.2
I1012 08:18:12.365460    7082 driver.go:362] Setting default libvirt URI to qemu:///system
I1012 08:18:12.530718    7082 virtualbox.go:136] virtual box version: 7.0.0r153978
I1012 08:18:12.606273    7082 out.go:177] ✨  Using the virtualbox driver based on existing profile
I1012 08:18:12.640176    7082 start.go:282] selected driver: virtualbox
I1012 08:18:12.640183    7082 start.go:808] validating driver "virtualbox" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.27.0-amd64.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.25.2 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/home/jerrii:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I1012 08:18:12.640292    7082 start.go:819] status for virtualbox: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:7.0.0r153978
}
I1012 08:18:12.658398    7082 cni.go:95] Creating CNI manager for ""
I1012 08:18:12.658409    7082 cni.go:169] CNI unnecessary in this configuration, recommending no CNI
I1012 08:18:12.658417    7082 start_flags.go:317] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.27.0-amd64.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.25.2 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/home/jerrii:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I1012 08:18:12.658529    7082 iso.go:124] acquiring lock: {Name:mk4874e0525aff3ca2cd69d12400067d0fe0a70c Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1012 08:18:12.715421    7082 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I1012 08:18:12.740492    7082 preload.go:132] Checking if preload exists for k8s version v1.25.2 and runtime docker
I1012 08:18:12.740524    7082 preload.go:148] Found local preload: /home/jerrii/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.25.2-docker-overlay2-amd64.tar.lz4
I1012 08:18:12.740530    7082 cache.go:57] Caching tarball of preloaded images
I1012 08:18:12.740616    7082 preload.go:174] Found /home/jerrii/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.25.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I1012 08:18:12.740631    7082 cache.go:60] Finished verifying existence of preloaded tar for  v1.25.2 on docker
I1012 08:18:12.740730    7082 profile.go:148] Saving config to /home/jerrii/.minikube/profiles/minikube/config.json ...
I1012 08:18:12.749844    7082 cache.go:208] Successfully downloaded all kic artifacts
I1012 08:18:12.749861    7082 start.go:364] acquiring machines lock for minikube: {Name:mkc1bb794d3060344f53257f5bcb49301ae3403a Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I1012 08:18:12.749909    7082 start.go:368] acquired machines lock for "minikube" in 38.572µs
I1012 08:18:12.749924    7082 start.go:96] Skipping create...Using existing machine configuration
I1012 08:18:12.749928    7082 fix.go:55] fixHost starting: 
I1012 08:18:12.750166    7082 main.go:134] libmachine: COMMAND: /usr/bin/VBoxManage showvminfo minikube --machinereadable



❌  Exiting due to DRV_CP_ENDPOINT: failed to lookup ip for ""
💡  Suggestion: 

    Recreate the cluster by running:
    minikube delete
    minikube start

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_logs_b02a65d5c08130f4b1fcbe2e78be568497bf5440_0.log                    │
│                                                                                           │

**Comment by imjerri** [comment]
> 

this is log anybudy please help me out of this

**Comment by Sule26** [comment]
Duplicate of https://github.com/kubernetes/minikube/issues/13950

**Comment by bdresdner** [comment]
I am having the exact same issue.  I installed minikube using chocolatey.
[logs.txt](https://github.com/kubernetes/minikube/files/13183709/logs.txt)
