### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by mhoja** [kubernetes/minikube#12766]
**Steps to reproduce the issue:** 

1.minukube start
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @mhoja, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
