### ISSUE TITLE
minikube start fails when using `virtualbox` driver on MacOS (and Ubuntu for VBox 6.1.28)

### ISSUE THREAD

**Issue by massenz** [kubernetes/minikube#12782]
**Steps to reproduce the issue:** 

1. removed Docker Desktop (MacOS)
2. run `minikube start` on a clean install of Minikube
3. fails with an error message related to VBox host-only
4. re-install Docker Desktop
5. run `minikube start` works just fine

(note that I'm running Virtualbox 6.1, so the "well-know" bug is history)
This is the error log:

`$  minikube start`
😄  minikube v1.23.2 on Darwin 11.6
✨  Automatically selected the virtualbox driver
💿  Downloading VM boot image ...
    > minikube-v1.23.1.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.23.1.iso: 225.22 MiB / 225.22 MiB [ 100.00% 3.51 MiB p/s 1m4s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.22.2 preload ...
    > preloaded-images-k8s-v13-v1...: 511.69 MiB / 511.69 MiB  100.00% 3.16 MiB
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in virtualbox ...
🤦  StartHost failed, but will try again: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

❌  Exiting due to IF_VBOX_NOT_VISIBLE: Failed to start host: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
💡  Suggestion: Reboot to complete VirtualBox installation, verify that VirtualBox is not blocked by your system, and/or use another hypervisor
📘  Documentation: https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3614
    ▪ https://github.com/kubernetes/minikube/issues/4222
    ▪ https://github.com/kubernetes/minikube/issues/5817

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by nbusseneau** [comment]
Hi, this is actually #12765 in disguise. The reason for the different error mesage (`The host-only adapter we just created is not visible` instead of simply `Access denied` is when the adapter was already existing before the upgrade to 6.1.28 and the new restrictions, hence the issue being not the creation but the usage of the adapter.

You can confirm this very easily while sticking with 6.1.28: manually delete the adapter from VirtualBox interface, then you will encounter the `Access denied` issue.

I would suggest you use the workaround provided in this comment https://github.com/kubernetes/minikube/issues/12765#issuecomment-953931265 instead of editing `/etc/vbox/networks.conf` when possible, as this ensures all potential other users of your scripts etc. will not have to do the same.

**Comment by spowelljr** [comment]
This is fixed by https://github.com/kubernetes/minikube/issues/12765 which will be included in the v1.24.0 release coming today or tomorrow, I'm going to close this issue.
