### ISSUE TITLE
Minikube addon registry-creds automation friendly

### ISSUE THREAD

**Issue by secat** [kubernetes/minikube#1285]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Minikube version** (use `minikube version`): v0.17.1

It would be very interesting for the minikube's addon named `registry-creds` to be automation script friendly. Currently, the command `minikube addons enable registry-creds` is asking multiple user inputs.

**Comment by r2d4** [comment]
We should add a `-q` flag to `addons enable` which doesn't ask for any user input.

**Comment by aaron-prindle** [comment]
This is a good point. We can enable a mode for running

**Comment by arthurlm44** [comment]
This is causing an issue for my workstation automation.
Is it possible to specify my AWS creds as args to the `minikube addons enable registry-creds` command as an alternative?

**Comment by diclophis** [comment]
Or possible use `/usr/bin/expect` to automate the text entry?

**Comment by aaron-prindle** [comment]
Adding a `-q` flag to this does not seem feasible the way that `enable` in implemented on top of `config set`.  For now I am going to make a PR to split all prompting into a `minikube addons configure ADDON` command and then make `minikube addons enable ADDON` simply turn on the addon so that it is always scriptable.

**Comment by r2d4** [comment]
ref https://github.com/kubernetes/minikube/pull/1322
