### ISSUE TITLE
HOST_CONFIG_LOAD

### ISSUE THREAD

**Issue by kennyblaze67** [kubernetes/minikube#12937]
- /var/folders/rs/rdyh1vfs7d92x750lhvys12w0000gp/T/minikube_logs_06e9b46abdddf33eb23fea2518473f15081f2cdd_0.log

**Steps to reproduce the issue:** 

1.
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @kennyblaze67, thanks for reporting your issue with minikube!

Unfortunately you haven't uploaded any information or log file for me to go off of, could you please run `minikube logs --file=logs.txt` and add the `logs.txt` file to this issue, thanks!

**Comment by medyagh** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

The exact minikube start command line used: preferably with --alsologtostderr -v=8 added.
The full output of the command
The full output of "minikube logs"
Please feel free to do so at any point. Thank you for sharing your experience!

**Comment by kennyblaze67** [comment]
I can’t remember I made my complaints a couple of week ago I just deleted minikube and downloaded a new one 
Regards 


Sent from Yahoo Mail for iPhone


On Wednesday, December 1, 2021, 2:17 PM, Medya Ghazizadeh ***@***.***> wrote:




Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

The exact minikube start command line used: preferably with --alsologtostderr -v=8 added.
The full output of the command
The full output of "minikube logs"
Please feel free to do so at any point. Thank you for sharing your experience!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
