### ISSUE TITLE
minikube start --driver=docker

### ISSUE THREAD

**Issue by Imtiazwaraich** [kubernetes/minikube#12936]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @Imtiazwaraich, thanks for reporting your issue with minikube!

Unfortunately you haven't uploaded any information or log file for me to go off of, could you please run `minikube logs --file=logs.txt` and add the `logs.txt` file to this issue, thanks!

**Comment by spowelljr** [comment]
Hi @Imtiazwaraich, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
