### ISSUE TITLE
 I want to map ports 80 and 443 of the minikube container to ports 80 and 433 of the host. What should be the correct command? Thanks

### ISSUE THREAD

**Issue by zhengxianlin** [kubernetes/minikube#13095]
The command I executed
：minikube start --mount --mount-string="/opt/rainbond:/opt/rainbond" --driver=docker  --ports=443 --ports=80 --apiserver-port=6443

Error：X Exiting due to MK_USAGE: Sorry, you cannot use privileged ports on the host (below 1024) [443 80]

Hope you send the correct order, thank you very much

**Comment by spowelljr** [comment]
Hi @zhengxianlin, thanks for reporting your issue with minikube!

The error message you're seeing was only meant to be when using WSL, but it was accidentally added to everything instead. We have since fixed it and will be included in the next release (v1.25.0).

If you let me know what OS you use I can provide you a link to our latest build and you can see if that resolves your issue, thanks!

**Comment by spowelljr** [comment]
This has been resolved and will be included in the next release.
