### ISSUE TITLE
Audit log defer not always being called

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#13186]
When any minikube command is run we have a [defer statement](https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/root.go#L81) that logs the command to the audit log. However, on `minikube start` sometimes we terminate the execution in a way that the defer is not run and then the start command is not added to the audit log.

I have a proposed way to remedy this, the only reason we defer it is so we can add then end time to the audit log, but to prevent the defer issue we can log everything but the end time to the audit log, and then if the command completes we can add the end time to the audit entry.

The one case we have to watch out for is if the user starts two `minikube start` commands at the same time, we simply can't modify the last entry in the log, so we'll need to make sure to track the index of the entry in the audit log.

Example:
```
# 1st minikube start
$ minikube start -p p1

# Audit log
minikube start -p p1 started at 1:00

# 2nd minikube start
$ minikube start -p p2

# Audit log
minikube start -p p1 started at 1:00
minikube start -p p2 started at 1:01

# 1st minikube start finishs

# Need to make sure we update the second last entry
minikube start -p p1 started at 1:00 ended at 1:03
minikube start -p p2 started at 1:01
```

**Comment by shadowshot-x** [comment]
Hi @spowelljr. Seems like an interesting issue. I would like to work on this.

**Comment by spowelljr** [comment]
Hi @shadowshot-x, comment `/assign` to assign the issue to yourself.

**Comment by NikhilSharmaWe** [comment]
@shadowshot-x Could you please inform that, are you still working on this issue ?

**Comment by shadowshot-x** [comment]
Go ahead @NikhilSharmaWe. Was a bit out due to New Year.

**Comment by NikhilSharmaWe** [comment]
@spowelljr I am able to understand

**Comment by NikhilSharmaWe** [comment]
@spowelljr I have understood the issue here

> I have a proposed way to remedy this, the only reason we defer it is so we can add then end time to the audit log, but to prevent the defer issue we can log everything but the end time to the audit log, and then if the command completes we can add the end time to the audit entry.

But not able to understand the solution you have suggested to remedy this. Could you please elaborate about the solution and also guide on how to proceed in this purpose.

**Comment by shadowshot-x** [comment]
Maybe, I can help a bit with that. In `root.go`, we are using `defer` statement. The whole statement(Eg:- "minikube start -p p1 started at 1:00 ended at 1:03") is added after the command has ended which is the main issue as sometimes this defer is skipped. What he means is to get rid of `defer`. First, add "minikube start -p p1 started at 1:00" when the command is run immediately. Then, when the command ends, append "ended at 1:03".

**Comment by NikhilSharmaWe** [comment]
@shadowshot-x Do we need to remove defer in func [`Execute()`](https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/root.go#L80) .Because func `Execute()` is not executed only for `start` command, if we will remove the `defer` then all commands logs will be effected.

**Comment by shadowshot-x** [comment]
Right, `Execute` is run for all the commands. So, all command logs will be affected. However, the end result will be the same (We want the audit log to be consistent). It might be possible where `defer` is skipped for some other command other than start.

**Comment by NikhilSharmaWe** [comment]
@shadowshot-x So do we need to add `audit.Log(time.Now())` at the start and at the end of the `Execute()` function without `defer`. 
If correct, I have two question - 
- How `audit.Log(time.Now())` will log the data like `minikube start -p p1 started at 1:00` because it will only IMO will log the time. And when we are able to log the preferred statement how we will connect the start and end times in one statement.
- How can we handle this case ? 
> The one case we have to watch out for is if the user starts two minikube start commands at the same time, we simply can't modify the last entry in the log, so we'll need to make sure to track the index of the entry in the audit log.

Apologies for asking so many questions.

**Comment by shadowshot-x** [comment]
No issues @NikhilSharmaWe. These are the 2 cents that I discovered while understanding the issue. Of course, @spowelljr might guide better to a solution. 

1. The `minikube start -p p1 started at 1:00` is a representational example I think. The logs are stored in JSON file I think( not exactly sure, but[ you can read about it](https://minikube.sigs.k8s.io/docs/tutorials/audit-policy/).) You have to modify the log file. To know more about how `audit.Log` is storing the logs, you can [check the audit package](https://github.com/kubernetes/minikube/blob/1b25cac7f5735be22f88a159b35b1996abba3c73/pkg/minikube/audit/audit.go#L54).
2. I think the work needed will be in audit package too as you will have to play around with some functions. I can propose keeping a counter of bytes in a variable you have written to the file. You can then append at this counter at the end of `Execute` command.

**Comment by NikhilSharmaWe** [comment]
@spowelljr and @shadowshot-x  I am thinking that we can add two parameter `start` and `end` of type `time.Time` to func [`Log()`](https://github.com/kubernetes/minikube/blob/1b25cac7f5735be22f88a159b35b1996abba3c73/pkg/minikube/audit/audit.go#L54) instead of only `startTime` and replace `time.Now()` with `end` in [here](https://github.com/kubernetes/minikube/blob/1b25cac7f5735be22f88a159b35b1996abba3c73/pkg/minikube/audit/audit.go#L58). We will assign values to `start` in the start of `Execute` function and to `end` at the end of the `Execute` function. And then we will run function `audit.Log(start, end)`. 

With this we will not need to use `defer` and we will get both start and end time values in the logs.

Please give your thoughts.

**Comment by NikhilSharmaWe** [comment]
@shadowshot-x Could you please give your thoughts on the above [comment](https://github.com/kubernetes/minikube/issues/13186#issuecomment-1003685760).

**Comment by shadowshot-x** [comment]
I think you are going in the right direction @NikhilSharmaWe. I am just a bit curious about the implementation you have proposed. 

- The first point is absolutely valid. `Log()` is not used anyplace else. So, you do something like this.
- As per the second point, from what I understand, you will call `audit.Log(start, end)` at the end of the `Execute` function. However, this does not solve the issue. As in some cases `defer` was not being executed which would mean that the code was being skipped. What about the case when the execution is interrupted before the end of `Execute` function is reached? There would be a loss of logs as we won't even know if the command was run or not.

Do correct me if I am wrong.

**Comment by NikhilSharmaWe** [comment]
@shadowshot-x First of all thanks for thoughts. Yes, I also thought about that. So, I think according to @spowelljr solution 
```
I have a proposed way to remedy this, the only reason we defer it is so we can add then end time to the audit log, but to prevent the defer issue we can log everything but the end time to the audit log, and then if the command completes we can add the end time to the audit entry.

The one case we have to watch out for is if the user starts two minikube start commands at the same time, we simply can't modify the last entry in the log, so we'll need to make sure to track the index of the entry in the audit log.
```
He says `We should run audit.Log(time.Now()) in the beginning of the Execution function and if the commands completes we can add the endTime to the audit entry.` How we can get to know that - when the command completes ? because at that moment we will add `time.Now()` to the `newRow()` func's last argument. And I am also confused about how we will track the index of the entry in the audit log.    

I think I have to read about the logs in the repo before making a solution in a PR. If you could provide some useful resources please inform. If you have more inputs you are welcome.

**Comment by shadowshot-x** [comment]
Earlier we knew when the command ended by using `defer` statement. Audit.Log was called when the Execute function reached the end. The concept remains the same. When all the subcommands of `Execute` have been executed, you can call Audit.Log.  This can be at the end of the function(I think). 

As for the tracking of the index in the entry, I did propose a solution above in Point 2. Feel free to discover your own approach:- 

> 2. I think the work needed will be in the audit package too as you will have to play around with some functions. I can propose keeping a counter of bytes in a variable you have written to the file. You can then append at this counter at the end of `Execute` command.

As per my knowledge, you don't need any more resources other than the code in the Audit package and the `Execute` function. You can check out the audit functionality maybe.

https://minikube.sigs.k8s.io/docs/tutorials/audit-policy/

**Comment by spowelljr** [comment]
Thanks for responding @shadowshot-x while I was gone!

I'll provide some clarifications and my proposal for the solution.

https://minikube.sigs.k8s.io/docs/tutorials/audit-policy/ is different than the auditing we're talking about, that link is related to Kubernetes auditing while we're talking about minikube command auditing. The audit we're talking about is very simple, it's just a json file containing all the commands we run with details such as flags passed and what version of minikube was used (`~/.minikube/logs/audit.json`).

I'll outline my proposal for the solution.

We rename the `Log()` function to something like `LogCommandStart()` and remove passing in the time arg since we can simply get the current time within the function. Also within `LogCommandStart()` we generate a unique ID (entry index?) and add it to the audit entry and we return it. Then we make a new func `LogCommandEnd(uniqueID)` and then we look through the audit entries in reverse order until we find the entry that has the matching unique ID and then add the end time to the entry.

Example:
```
auditID, err := LogCommandStart()
defer LogCommandEnd(auditID)
```

```
func LogCommandEnd(auditID string) error {
  // get JSON audit
  // loop through in reverse order until currEntry.ID == auditID
  // update entry with current end time
}
```

This is just my proposal, if you have a better idea feel free to go though it that way. If you have any further questions let me know!

**Comment by NikhilSharmaWe** [comment]
@spowelljr and @shadowshot-x 
- In `LogCommandStart()` we will only give value to `startTime` in `newRow()` function. We are not going to add `endTime` in this function but since `newRow()` function need argument for `endTime` it will show an error. How can we deal with that ?

- After that we will generate a random string and write it in place of one of the arguments in the `newRow()` function {not sure} because last argument's type is string and will return this random string it with `err`. Am I understanding correct here ? 

- Could you please provide me some examples where we do work with JSON audit, like how can we get it and more.

Apologies for asking so many questions, I am trying my best in understanding how can I make a reasonable implementation.

**Comment by spowelljr** [comment]
1. Only `Log` calls `newRow` so feel free to modify `newRow` as much as you'd like. You can simply remove the func param for `endTime` from `newRow`.
2. So first update the `row` struct to add an `ID` field, then in `newRow` create the unique ID. You can use the `"github.com/google/uuid"` package and do `uuid.New().String()` and assign the ID to the row. That row struct then gets returned and we now have it in the `Log` func, so all we have to do at the end of the func is `return row.ID`.
3. In `pkg/minikube/audit/row.go` there's a func `logsToRows` that converts the raw JSON logs into structs.

Hopefully that help!

**Comment by NikhilSharmaWe** [comment]
I have one question, that where are these logs. We have to put these logs as an argument in `LogCommandEnd()` function. Do this `~/.minikube/logs/audit.json` have to be added as logs.

**Comment by spowelljr** [comment]
In [logFile.go](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/audit/logFile.go) we have a variable `currentLogFile` that's either `nil` or points to the `audit.json` file. If it's `nil` just run `setLogFile()` like we do here [report.go](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/audit/report.go#L35).
