### ISSUE TITLE
minikube start results in 'panic: runtime error: index out of range [2] with length 2'

### ISSUE THREAD

**Issue by tomsucho** [kubernetes/minikube#13202]
### What Happened?

I was using minikube inside of a LXC Debian10 container and it suddenly stopped working i.e. panic when trying to startup. I launched a brand new LXC container with Ubuntu:18.04 and enabled priviliged & nesting mode, and when I try to start minikube fails the same way. 

lxc launch images:ubuntu/18.04 ubuntu-container
lxc config set ubuntu-container security.privileged true
lxc config set ubuntu-container security.nesting true
lxc exec ubuntu-container -- su --login ubuntu
install docker
install minikube
try minikube start

The LXC/LXD I run in Ubuntu 20.4 VirtualBox VM, under Windows. Please note that inside the Ubuntu 20.04 VM minikube continues to work just fine as it was before, so it is only inside the LXC/LXD that it now panics. Of course something had to change in my stack that it doesn't work anylonger but not sure what. If anyone has any pointers where to start, I would appreciate much.
Many thanks!

### Attach the log file

ubuntu@ubuntu-container:~$ minikube start
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/shirou/gopsutil/v3/cpu.parseStatLine({0xc000adf2a0, 0xc000ba77c0})
	/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.10/cpu/cpu_linux.go:255 +0x50f
github.com/shirou/gopsutil/v3/cpu.TimesWithContext({0x33b3680, 0x1c48a60}, 0x0)
	/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.10/cpu/cpu_linux.go:52 +0x1b2
github.com/shirou/gopsutil/v3/cpu.Times(...)
	/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.10/cpu/cpu_linux.go:28
github.com/shirou/gopsutil/v3/cpu.init.0()
	/go/pkg/mod/github.com/shirou/gopsutil/v3@v3.21.10/cpu/cpu.go:59 +0x54

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @tomsucho, thanks for reporting your issue with minikube!

So your issue seems to be with the https://github.com/shirou/gopsutil package itself.
We use the package to get the number of CPUs, but the package is failing on init.

The exact thing that's happening is it's trying to read a file and there doesn't seem to be the same amount of contents it's expecting.

If `HOST_PROC` env is set it tries reading that file, if that's empty it reads `/proc/stat`. There's a line in the file that's starting with `cpu` and there doesn't seem to be enough on that line. Could you try checking the contents of that file.

**Comment by tomsucho** [comment]
Hi @spowelljr 
thanks a milion for your feedback! I think I hit this issue:
https://github.com/lxc/lxd/issues/9725
I guess I'll track the other ticket then and wait for fixes, or is there a workaround possible to still be able to use minikube with this /proc/stat issues?

**Comment by spowelljr** [comment]
Since you're using the Docker driver that package isn't really used, so if you could simply overcome the init() failure you should be fine. Not sure if it would work but I'd suggest appending extra lines to `cpu` line in `/proc/stat` similar to what is listed in the issue you linked.

Right now you have something like
`cpu  2568500776029407000000`
Append the required number of fields so it's something like
`cpu  2568500776029407000000 11417161 48184671 2988896076 1918192 0 3631468 0 0 0`
It just needs to pass the range index, I'm not sure how changing that will affect anything else, but I think it might work.

**Comment by tomsucho** [comment]
Thanks for the hint but it doesn't let me edit the file as root, maybe it's due to the fact it's a pseudo-filesystem file representing some kernel read-only data, and not allowing any modification from user space. I'll close this ticket and wait for the fixes in Lxd/Ubuntu. Thanks for all the help!
