### ISSUE TITLE
Tunneling not working: Windows 11; Docker on Windows; kubernetes / minikube

### ISSUE THREAD

**Issue by dsosale** [kubernetes/minikube#13296]
Tunneling not working for the following configuration.  
Please advise if there is a fix:

Windows:  Windows 11 Pro
Windows for docker: Docker Desktop 4.3.2 (72729)
Kubernetes:  v1.23.0
Minikube: minikube version: v1.24.0

Command sequence:

minikube start --driver=docker

minikube mount C:/kubepgms/pods/resource/test/:/data/configs

minikube ssh
ls -la /data/configs/
(shows test1.yaml)

docker pull nginx:mainline-alpine

docker run -i -t --name nginx-mainline -p 80:80 nginx:mainline-alpine

If you navigate to http://localhost you will get a welcome page.

kubectl create deployment hello-node --image=nginx:mainline-alpine
kubectl get deployments
kubectl get pods
kubectl get events
kubectl expose deployment hello-node --type=LoadBalancer --port=8080

minikube service hello-node

Gives error:  ! Because you are using a Docker driver on windows, the terminal needs to be open to run it.

(does not work even if I paste the http address directly into chrome).

C:/kubepgms/pods/resource/test/test1.yaml:
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

**Comment by spowelljr** [comment]
Hi @dsosale, thanks for reporting your issue with minikube. I tried to replicate what you were experience and I believe it's related to the image you're using itself. Could you try using the commands below and let me know if that works for you.
```
kubectl create deployment balanced --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment balanced --type=LoadBalancer --port=8080
minikube tunnel

Then in your browser open http://127.0.0.1:8080/
```

That works for me, but when I try using the image `nginx:mainline-alpine` instead of `k8s.gcr.io/echoserver:1.4` it doesn't work for me, so I think it's related to the image itself.
