### ISSUE TITLE
Unable to load cached images

### ISSUE THREAD

**Issue by maulikusdad** [kubernetes/minikube#13290]
### What Happened?

Unable to load cached images

### Attach the log file

i am not able to install the minikube

### Operating System

Windows

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Hi @maulikusdad, thanks for reporting your issue with minikube!

Can you please describe in more detail what's going wrong, please include reproduction steps and logs.

**Comment by spowelljr** [comment]
Hi @maulikusdad, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
