### ISSUE TITLE
minikube service flask-service opens a browser but isn't connecting

### ISSUE THREAD

**Issue by effyyvv** [kubernetes/minikube#13291]
### What Happened?

Hello, 
by using minikube service flask-service,
I get the following
![Screenshot 2022-01-04 150254](https://user-images.githubusercontent.com/97101152/148063205-0885ff52-67d9-43db-b951-1624c1f6a19d.png)

while the url opens in my browser, it won't connect.
Can you help me?

### Attach the log file

-

### Operating System

Windows

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @effyyvv, thanks for reporting your issue with minikube!

Could you run the command again and include the `--alsologtostdderr` flag and then upload the output.

Also, what version of minikube are you using?

**Comment by spowelljr** [comment]
Hi @effyyvv, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
