### ISSUE TITLE
minikube starts failing with Virtualbox driver on Windows having AMD-v enabled

### ISSUE THREAD

**Issue by inductor** [kubernetes/minikube#13298]
**問題を再現するための手順:** 

```
 PS C:\Users\user> minikube start --driver=virtualbox --network-plugin=cni --cni=false
😄  Microsoft Windows 11 Pro 10.0.22000 Build 22000 上の minikube v1.24.0
✨  プロフィールを元に、 virtualbox ドライバを使用します
👍  コントロールプレーンのノード minikube を minikube 上で起動しています
🔥  virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) を作成しています...
🤦  StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
🔥  virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) を作成しています...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

❌  Exiting due to HOST_VIRT_UNAVAILABLE: Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
💡  提案: このコンピューターでは仮想化サポートが無効です。VM 内で minikube を実行する場合、'--driver=docker' を試してみてく
ださい。そうでなければ、仮想化を有効化する方法を BIOS の説明書を調べてください。
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3900
    ▪ https://github.com/kubernetes/minikube/issues/4730
```

I tested my Virtualbox and confirmed that it works just fine which implies the CPU virtualization is on.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/20236173/148151277-0138c2f1-5a24-4586-a2e7-9454bad80b15.png">

Any advices?

**Comment by spowelljr** [comment]
Hi @inductor, thanks for reporting your issue with minikube!

Could you run `systeminfo` and report back the output, thanks!

**Comment by thyhum** [comment]
Do you have hyper-v or Virtual Machine Platform feature enabled?

Check with this command on an elevated PowerShell: `dism /online /Get-FeatureInfo /FeatureName:VirtualMachinePlatform | findstr State` or go to Windows Features and look for Virtual Machine Platform

**Comment by klaases** [comment]
Hi @[inductor](https://github.com/inductor) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by ecormaksin** [comment]
I run into the same problem.

I think that when we start minikube with virtualbox driver, virtualizaion of `minikube` virtual machine (vm) on VirtualBox is needed to be enabled.

That is because, when we create a vm on VirtualBox,
virtualization of the vm is disabled by default.

To enable virtualization of the vm, we need to execute `VBoxManage modifyvm <vm name> --nested-hw-virt on`.

However, when we start minikube, `minikube` vm is locked by starting process.

So, I think that minikube need to enable virtualization of the vm on start up.

Or, can we enable virtualization of vms by default on VirtualBox?

![minikube-virtualbox-settings](https://user-images.githubusercontent.com/16113266/171768118-fada6f50-884b-4335-9655-9d2251942c4c.png)
