### ISSUE TITLE
Minikube start command does not response on time

### ISSUE THREAD

**Issue by rohitkesarvani55** [kubernetes/minikube#13335]
### What Happened?

I am trying to bring the minikube up to run my one node kubernetes cluster but it is not responding

Below are the logs attached. 

### Attach the log file

minikube start
* minikube v1.23.2 on Microsoft Windows 10 Home Single Language 10.0.19042 Build 19042
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 19.0117401s
* Restarting the docker service may improve performance.
* docker "minikube" container is missing, will recreate.

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by spowelljr** [comment]
Hi @rohitkesarvani55, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
