### ISSUE TITLE
minikube unable to start

### ISSUE THREAD

**Issue by Allan-xd** [kubernetes/minikube#13371]
### What Happened?

Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

😿  Sorry that minikube crashed. If this was unexpected

### Attach the log file

Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

😿  Sorry that minikube crashed. If this was unexpected

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by spowelljr** [comment]
Hi @Allan-xd, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
