### ISSUE TITLE
minikube start  失败

### ISSUE THREAD

**Issue by mondayEast** [kubernetes/minikube#13494]
**重现问题所需的命令**：
minikube start --vm-driver=none --registry-mirror=https://registry.docker-cn.com

**失败的命令的完整输出**：<details>
* minikube 1.24.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.24.0
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

! minikube v1.4.0 on Centos 8.1.1911
* Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
* Running on localhost (CPUs=2, Memory=3757MB, Disk=51175MB) ...
* OS release is CentOS Linux 8 (Core)
* Preparing Kubernetes v1.16.0 on Docker 18.06.3-ce ...
* Downloading kubeadm v1.16.0
* Downloading kubelet v1.16.0
*
X Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.16.0: failed to download: failed to download to temp file: download failed: 1 error(s) occurred:

**使用的操作系统版本**：
Centos 8.1.1911

**Comment by spowelljr** [comment]
Hi @mondayEast, thanks for reporting your issue with minikube!

You're currently using minikube `v1.4.0` which is an extremely old version, the current version of minikube is `v1.25.2`. Please try updating to the newest version of minikube, and run `minikube delete --all --purge` before trying to start minikube with the updated version.

**Comment by spowelljr** [comment]
Hi @mondayEast, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

-----

嗨@mondayEast，我们还没有收到你的回复，你还有这个问题吗？
此问题中没有足够的信息使其可操作，并且已经过去了足够长的时间，因此此问题可能难以复制。

我将暂时关闭此问题，但当您准备好提供更多信息时，请随时重新打开。

**Comment by mondayEast** [comment]
谢谢， 问题已经解决。感谢你们的帮助。



在 2022-03-17 02:09:17，"Steven Powell" ***@***.***> 写道：

Closed #13494.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
