### ISSUE TITLE
minikube start gets timed out

### ISSUE THREAD

**Issue by Kailash-Ramco** [kubernetes/minikube#13560]
### What Happened?

Hi Team,

I have installed minikube, using the below url

https://www.virtualizationhowto.com/2021/03/install-minikube-on-windows-server-2019-hyper-v/

But on minikube start, it failed with a timeout exception.

Additional Info:
![image](https://user-images.githubusercontent.com/97166966/152476274-62412365-a5fc-423c-aa02-33ca69497bad.png)

### Attach the log file

[minikube_logs_37a00e9b7ec6c234764ce28466b659079dec00f1_0.log](https://github.com/kubernetes/minikube/files/8000284/minikube_logs_37a00e9b7ec6c234764ce28466b659079dec00f1_0.log)

### Operating System

Windows

**Comment by spowelljr** [comment]
Hi @Kailash-Ramco, are you using a VPN or firewall?

**Comment by spowelljr** [comment]
Hi @Kailash-Ramco, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
