### ISSUE TITLE
Cannot build inside pod since mode flag disappeared

### ISSUE THREAD

**Issue by huguesBouvier** [kubernetes/minikube#13623]
### What Happened?

I am developing a rust application. To limit the development loop, I mount my code from the host into a minikube pod.
From there, I build using cargo build.

I used to mount with the following command:
minikube mount --gid root --pid root --mode 0777 /mycode:/mycode

However, now the option has disappeared and it is not possible to build from inside the pod:
 failed to write /host/xxxxx/target/debug/deps/libunicode_xid-8bb8457dab823b6f.rmeta: Invalid cross-device link (os error 18)

Is there an alternative than rolling back to previous version now that the option has disappeared?

### Attach the log file

Empty result

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Related to:
* https://github.com/kubernetes/minikube/pull/13162

**Comment by spowelljr** [comment]
Hi @huguesBouvier, thanks for reporting your issue with minikube!

The reason we removed the `--mode` flag is because if you had folder `mycode` on your host machine and it was `0755` if you set `--mode 0777` is would also change the folder permission in the pod but also on your host machine.

`chmod 0777 /mycode` should do that same thing the `--mode` flag was doing.

If you do the above does that resolve the issue?

**Comment by huguesBouvier** [comment]
It does. I understand the rational for the change. Thanks a lot!
