### ISSUE TITLE
Minikube won't start macOS Big Sur Intel Chip

### ISSUE THREAD

**Issue by almssp** [kubernetes/minikube#13648]
### What Happened?

Minikube won't start

this is a new install on a macOS.

current running Docket Desktop version 4.5.0

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8111251/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @almssp, thanks for reporting your issue with minikube!

I took a look at your logs and saw `Unable to get host status for minikube, assuming it has already been deleted`

It looks like the minikube container may have got deleted in Docker somehow.

Try running `minikube delete --all` and then try start minikube again and see if that resolves your issue.

**Comment by spowelljr** [comment]
Hi @almssp, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
