### ISSUE TITLE
Docs for minikube_delete and minikube_stop are missing

### ISSUE THREAD

**Issue by jseldess** [kubernetes/minikube#1369]
This is a bug report.

The [CockroachDB docs](https://www.cockroachlabs.com/docs/orchestrate-cockroachdb-with-kubernetes.html) link to the docs for `minikube_delete` and `minikube_start`, but our auto-link checker is showing that the pages for `minikube_delete` and `minikube_stop` are broken. 

Here are the URLs we're using:

https://github.com/kubernetes/minikube/blob/master/docs/minikube_delete.md
https://github.com/kubernetes/minikube/blob/master/docs/minikube_stop.md

If those pages have been moved, can you set up redirects?

**Comment by warmchang** [comment]
FYI:
https://github.com/kubernetes/minikube/pull/1356
https://github.com/kubernetes/minikube/issues/1338

**Comment by r2d4** [comment]
We stopped checking in autogenerated code, which is why this broke.  We could still check in documentation for each release.  We could also consider setting up a github pages site for others to link to documentation.

I don't think we can redirect since this is a link to our master branch, but could you point your links to 

https://github.com/kubernetes/minikube/blob/v0.18.0/docs/minikube_delete.md

or point us to it so we can send a PR to the right place.

@jseldess

**Comment by jseldess** [comment]
Thanks, @r2d4. For now, I've just removed the links from our Kubernetes tutorial. Users can get help via the cli as well. Feel free to close this issue.
