### ISSUE TITLE
不能访问通过NodePort暴露的Nginx服务

### ISSUE THREAD

**Issue by Remering** [kubernetes/minikube#13747]
**重现问题所需的命令**：
``` bash
~
❯ minikube start
😄  Microsoft Windows 10 Pro 10.0.19043 Build 19043 上的 minikube v1.25.2
✨  根据现有的配置文件使用 docker 驱动程序
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
❗  This container is having trouble accessing https://registry.cn-hangzhou.aliyuncs.com/google_containers
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  正在 Docker 20.10.12 中准备 Kubernetes v1.23.3…
    ▪ kubelet.housekeeping-interval=5m
🔎  Verifying Kubernetes components...
    ▪ Using image registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
~
❯ kubectl run web --image=nginx
pod/web created
~
❯ kubectl get pod/web
NAME   READY   STATUS    RESTARTS   AGE
web    1/1     Running   0          16s
~
❯ kubectl expose pod web --port 80 --type NodePort
service/web exposed
~
❯ kubectl get svc/web
NAME   TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
web    NodePort   10.102.114.207   <none>        80:30212/TCP   7s
~
❯ minikube service web --url
http://192.168.49.2:30212
🏃  Starting tunnel for service web.
❗  Because you are using a Docker driver on windows, the terminal needs to be open to run it.
```

**失败的命令的完整输出**：<details>
```bash
~
❯ curl http://192.168.49.2:30212
curl : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ curl http://192.168.49.2:30212
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebE
    xception
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

~
❯ netstat -ano | findstr 30212
```

</details>

**`minikube logs`命令的输出**： <details>
[minikube.log](https://github.com/Remering/pastebins/blob/main/minikube.log)

</details>

**使用的操作系统版本**：
Microsoft Windows 10 Pro 10.0.19043 Build 19043

**备注**
我使用同一台电脑WSL版本的minikube没有遇到对应的问题

**Comment by zhan9san** [comment]
Hi @Remering 

Both the following way may work for you.

Method 1. Access service exposed by tunnel

    ```bash
    $ curl http://127.0.0.1:30212
    ```

Method 2. Access service from minikube VM

    ```bash
    $ minikube ssh
    $ curl http://192.168.49.2:80
    ```

**Comment by Yjq14114** [comment]
你好，我也是同样的问题
grey@DESKTOP-DGIJU5L:/mnt/c/Users/jack20/kubernetesYaml$ kubectl get service
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
hello-minikube1   LoadBalancer   10.109.94.61   <pending>     8080:32046/TCP   9m16s
kubernetes        ClusterIP      10.96.0.1      <none>        443/TCP          27m
grey@DESKTOP-DGIJU5L:/mnt/c/Users/jack20/kubernetesYaml$ minikube service hello-minikube1 --url
http://192.168.49.2:32046
🏃  Starting tunnel for service hello-minikube1.
❗  Because you are using a Docker driver on linux, the terminal needs to be open to run it.


http://192.168.49.2:32046 这个地址浏览器打不开
而且ip还ping不通
PS C:\Users\jack20> ping 192.168.49.2

正在 Ping 192.168.49.2 具有 32 字节的数据:
请求超时。

**Comment by zhan9san** [comment]
Hi @Yjq14114 

你用最新版的minikube,然后对照这个文档，#13806

你发的这个URL, http://192.168.49.2:32046/在windows上是不可以直接访问的，需要使用`127.0.0.1`这样的地址，具体端口在上面文档里可以查到

试试可以解决吗？
