### ISSUE TITLE
Can't get ingress-dns running on Ubuntu 20.04

### ISSUE THREAD

**Issue by jkempf42** [kubernetes/minikube#13740]
### What Happened?

I can't seem to get ingress-dns running on Ubuntu 20.04. I tried the installation and configuration suggestions in the installation instructions [here](https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/) and the instructions in the issue list for this repo  [here](https://github.com/kubernetes/minikube/issues/10517) but I could not get the basic `hello-john.test` and `hello-jane.test `example working. I tried both enabling `dnsmasq `and configuring `systemd-resolved`  as described in the two links above. 

The last thing I tried was to disable name resolution through` NetworkManager.service` by putting` dns=none` in `/etc/NetworkManager/NetworkManager.conf` and restarting `NetworkManager`, then focusing on systemd-resolved. I added a config file `01-minikube.config` to` /usr/lib/systemd/resolved.conf.d/ `as follows;
```
          [Resolve]
          DNS=192.168.0.1 192.168.49.2
```
which should have added the` minikube` ip as a name server along with my existing name server, restarted `systemd-resolved `through `systemctl` but that didn't work either. 

Any suggestions?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8166636/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by r0ushann** [comment]
hey! I'm interested in this issue.

**Comment by tonyrizzotto** [comment]
@jak42 I think we're having the same issue. Just curious, are you able to access your app on a NodePort service? I believe this issue is related to the Minikube Ingress not installing on Linux. To confirm, I'd suggest deleting your minikube cluster with `minikube delete --purge --all` and run `minikube start --addons=ingress --alsologtostderr` and see in the ingress installation hangs. You'll notice something like: 
```
I0313 14:39:53.031414  177055 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0313 14:39:53.502730  177055 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0313 14:39:54.006302  177055 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
```
At which point it'll time out and say the addon was installed properly. However when you do a `kubectl get pod -n kube-system`

**Comment by jurca** [comment]
The documented Ingress DNS setup does not seem to work well with systems using systemd-resolve with Network Manager, unfortunately.

You can get it working *teporarily* by configuring the Minikube's bridge network device using `nmcli` (this does not require `sudo` unlike using `systemd-resolve --interface $BRIDGE_INTERFACE --set-dns $(minikube ip) --set-domain test`):

```sh
nmcli device modify "$BRIDGE_INTERFACE" ipv4.dns $(minikube ip)
nmcli device modify "$BRIDGE_INTERFACE" ipv4.dns-search test
```

(If you do not know which network interface to configure, use `minikube ip` to first find you Minikube cluster IP address, and then run `ip -family inet -brief address show type bridge` to see all bridge network interfaces and their IP address ranges on your system. You need to find the one which's network IP range will match your Minikube cluster IP).

Unfortunately, this is only temporary and needs to be re-applied after a reboot. Based on what I have pieced together so far, it seems that Minikube's bridge network interface is created after the OS starts a user session, which likely prevents us from using a NetworkManager config file evaluated at boot to make this automatic.

As a work-around I put the commands above into a custom script along with `minikube start` and use the custom script to start minikube instead. At least it's less typing.

It would be nice, though, if this configuration would be applied by minikube (e.g. for the .local-minikube or a configurable TLD), since the network interface is created by Minikube.

**Comment by Nieto2018** [comment]
Hi guys,

I posted my solution at the following link: https://github.com/kubernetes/minikube/issues/10517#issuecomment-1184340154.

Hope that helps!

**Comment by rodriguezc** [comment]
I had the same issue with NetworkManager on Ubuntu 22.04  (Virtualbox) and I finally solved it by following the official ingress dns doc BUT I had to delete the resolv.conf file before restarting the network service:
```
sudo mv /etc/resolv.conf /etc/resolv.conf.old
systemctl restart NetworkManager.service
```

**Comment by klaases** [comment]
Hi @jkempf42 – were you able to find a resolution to this issue based on @rodriguezc's comment above?

Feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by jkempf42** [comment]
I haven't checked since I stopped using minikube in spring. I needed more
control over the installation so I started using kubeadm. Sorry.

         jak

**Comment by abasu0713** [comment]
> I had the same issue with NetworkManager on Ubuntu 22.04 (Virtualbox) and I finally solved it by following the official ingress dns doc BUT I had to delete the resolv.conf file before restarting the network service:
> 
> ```
> sudo mv /etc/resolv.conf /etc/resolv.conf.old
> systemctl restart NetworkManager.service
> ```

This is a correct solution for the problem that I too faced. Working on actual bare-metal Ubuntu 22.04. Saw the same problem. I would also like to kindly request if we could  have the clarification on the [main documentation](https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/) where it only categorizes the type of Linux. It would be great to have each Linux distro/flavor specific tests.
