### ISSUE TITLE
[Bug] failure on starting minikube, error msg:  "Unable to add host alias: hosts update"

### ISSUE THREAD

**Issue by crimson-gao** [kubernetes/minikube#13796]
### What Happened?

Run cmd `minikube start` 
error occured:
```bash
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...- E0316 12:56:18.472814   29306 start.go:118] Unable to add host alias: hosts update: /bin/bash -c "{ grep -v $'\thost.minikube.internal$' "/etc/hosts"; echo "192.168.49.1      host.minikube.internal"; } > /tmp/h.$$; sudo cp /tmp/h.$$ "/etc/hosts"": Process exited with status 1
stdout:

stderr:
/bin/bash: /tmp/h.837: Permission denied
cp: cannot stat '/tmp/h.837': No such file or directory


❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: host alias: hosts update: /bin/bash -c "{ grep -v $'\tcontrol-plane.minikube.internal$' "/etc/hosts"; echo "192.168.49.2   control-plane.minikube.internal"; } > /tmp/h.$$; sudo cp /tmp/h.$$ "/etc/hosts"": Process exited with status 1
stdout:

stderr:
/bin/bash: /tmp/h.923: Permission denied
cp: cannot stat '/tmp/h.923': No such file or directory
```

I tried to figure out what happened, and found some code here which throws this error msg.
It seems that the command `/bin/bash -c "{ grep -v $'\tcontrol-plane.minikube.internal$' "/etc/hosts";  echo "192.168.49.2   control-plane.minikube.internal"; } > /tmp/h.$$; sudo cp /tmp/h.$$ "/etc/hosts"" `  ,  has too many double quotes.  
```go
func addHostAliasCommand(name string, record string, sudo bool, path string) *exec.Cmd {
	sudoCmd := "sudo"
	if !sudo { // for testing
		sudoCmd = ""
	}

	script := fmt.Sprintf(
		`{ grep -v $'\t%s$' "%s"; echo "%s"; } > /tmp/h.$$; %s cp /tmp/h.$$ "%s"`,
		name,
		path,
		record,
		sudoCmd,
		path)
	return exec.Command("/bin/bash", "-c", script)
}
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8259156/log.txt)

**Comment by spowelljr** [comment]
Hi @crimson-gao, thanks for reporting your issue with minikube!

I've looked at this, it's a common misconception that the quoting is incorrect (other issues mention the same thing), but it's more of just the way it's getting printed out in the logging. This can be backed up by the fact the errors lineup with what the command is actually trying to attempt. The command failed to create the `/tmp/h.837` file due to `Permission denied`, and then the `cp` command failed due to the lack of the file being created from the previous step.

So the question is why did you get `/tmp/h.837: Permission denied`, is it possible the user you started minikube with doesn't have access to `/tmp`? You could try doing `touch `/tmp/test.txt` or something similar to see if you have permission to write to the folder as that user.

**Comment by spowelljr** [comment]
Hi @crimson-gao, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by waxmoth** [comment]
I got this issue too, it can be fixed by:
```shell
minikube ssh
chmod 777 -R /tmp
```

**Comment by hmdshariati** [comment]
after resolving I faced some other problem. I decided to use https://kind.sigs.k8s.io/
