### ISSUE TITLE
Sorry that minikube crashed.

### ISSUE THREAD

**Issue by obasoro** [kubernetes/minikube#13827]
### What Happened?

Ran this command below:

`./kf-install.sh`

"The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?
⚠️  minikube 1.25.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.25.2

💣  Error getting IP: Could not find matching IP for MAC address 080027f672d3

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?"

### Attach the log file

 command runner
❌  Error: [SSH_AUTH_FAILURE] getting ssh client for bootstrapper: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
💡  Suggestion: Your host is failing to route packets to the minikube VM. If you have VPN software, try turning it off or configuring it so that it does not re-route traffic to the VM IP. If not, check your VM environment routing options.

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @obasoro, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by ntatpj** [comment]
Me too facing similar issue:
PS C:\WINDOWS\system32> minikube start
* minikube v1.30.1 on Microsoft Windows 10 Enterprise 10.0.19045.2965 Build 19045.2965
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* docker "minikube" container is missing, will recreate.
* Creating docker container (CPUs=2, Memory=4000MB) ...
! StartHost failed, but will try again: recreate: creating host: create host timed out in 360.000000 seconds
* Updating the running docker "minikube" container ...
* Failed to start docker container. Running "minikube delete" may fix it: provision: Temporary Error: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

X Exiting due to IF_SSH_AUTH: Failed to start host: provision: Temporary Error: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* Suggestion: Your host is failing to route packets to the minikube VM. If you have VPN software, try turning it off or configuring it so that it does not re-route traffic to the VM IP. If not, check your VM environment routing options.
* Documentation: https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/
* Related issue: https://github.com/kubernetes/minikube/issues/3930

PS C:\WINDOWS\system32> minikube status
E0710 17:00:08.152753   17976 status.go:376] failed to get storage capacity of /var: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
E0710 17:00:08.152771   17976 status.go:260] status error: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
minikube
type: Control Plane
host: Error
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Configured

**Comment by spowelljr** [comment]
Hi @ntatpj, I see that you're restarting an existing cluster. If you try running `minikube delete` and then try starting minikube again do you get a different result?
