### ISSUE TITLE
Kubernetes 1.24.0 breaks enabling CNI

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#13945]
### What Happened?

```
kubelet[5105]: Error: failed to parse kubelet flag: unknown flag: --network-plugin
```

```
kubelet[4728]: Error: failed to parse kubelet flag: unknown flag: --cni-conf-dir
```

### Solution
we need to pass the cni config directly to the Containerd or CRIO and cri-dockerd

We need to check if k8s version is greater than 1.24.0-alpha.2

### Attach the log file

Example	
	https://storage.googleapis.com/minikube-builds/logs/13904/23444/Docker_Linux_containerd.html#fail_TestStartStop%2fgroup%2fnewest-cni%2fserial%2fFirstStart

https://storage.googleapis.com/minikube-builds/logs/13904/23444/Docker_Linux.html#fail_TestStartStop%2fgroup%2fnewest-cni%2fserial%2fFirstStart

**Comment by afbjorklund** [comment]
The actual --cni-conf-dir code is in pkg/minikube/cni/cni.go, the above was for --network-plugin

They are both removed with the dockershim, and handled by container runtime configuration instead...

Note: both containerd and cri-o default to using CNI, so they don't need any `--network-plugin=cni` set.

We should also try to remove --runtime-request-timeout=15m, it has been deprecated since k8s 1.10 !

**Comment by travisn** [comment]
When will this fix be released? It doesn't seem to be included in v1.26.0-beta.0. This is blocking our CI from running K8s 1.24. Thanks!

**Comment by afbjorklund** [comment]
Seems like PR #13600 got stuck in review, will try to untangle

**Comment by sfxworks** [comment]
For anyone stuck here via kubeadm, there's a flag in `nano /etc/kubernetes/kubelet.env` that has this set. Removing this allows everything to complete.

**Comment by goshlanguage** [comment]
@afbjorklund Has this been resolved?

**Comment by afbjorklund** [comment]
Only in the PR, it was not in the release afaik
