### ISSUE TITLE
Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

### ISSUE THREAD

**Issue by soni-H** [kubernetes/minikube#13992]
### What Happened?

The following error appears on executing the command - minikube start
Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

I have tried the following solution but does not seem to work-
rm ~/.docker/config.json
minikube delete
minikube start

But even after doing so, the error persists

### Attach the log file

Could not get the log file as per the tip mentioned;

harshita@hs:~$ minikube logs --file=log.txt

❌  Exiting due to DRV_CP_ENDPOINT: failed to lookup ip for ""
💡  Suggestion: 

    Recreate the cluster by running:
    minikube delete
    minikube start

**Comment by spowelljr** [comment]
Hi @soni-H, thanks for reporting your issue with minikube.

Could you try running the following:
```
$ chmod 777 ~/.docker
$ chmod 66 ~/.docker/config.json
```

https://github.com/kubernetes/minikube/issues/8409#issuecomment-907269490

**Comment by spowelljr** [comment]
Hi @soni-H, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
