### ISSUE TITLE
Minikube starts fine, but can´t read minikube certificate on Windows.

### ISSUE THREAD

**Issue by jleandrocr** [kubernetes/minikube#14135]
### What Happened?

Minikube starts fine, but can´t read minikube certificate on Windows.

Please help, I´ve tried many things and can´t fix it.
How do I change or provide new permissions or how do I solve it?

### Attach the log file

![minikube certs error](https://user-images.githubusercontent.com/93690195/167704484-2b23b7b4-3e59-4ec3-aba6-68a0f94d5321.PNG)

### Operating System

Windows

### Driver

Docker

**Comment by klaases** [comment]
Hi @jleandrocr, is it possible that this could be a permissions issue?

I am not able to confirm this, and I could be wrong, but your username `jonathan.leandro` may be treated as a file with the extension `.leandro` rather than a path. If you have another user without a `.` would you be willing to give it a try?

**Comment by klaases** [comment]
Hi @jleandrocr – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
