### ISSUE TITLE
[Question] Why does minikube cluster work properly even though node's cpu usage exceeds my pc capacity?

### ISSUE THREAD

**Issue by hiroaki2020** [kubernetes/minikube#14170]
### What Happened?

My PC is macbook air which has 2 cpu cores (= 4 logical cpu cores).
I heard I need to allocate at least 2 cpu cores (I assume this is logical ones) to each node in minikube.
With docker driver, I spin up 2 minikube node containers which need 4 cpu cores while using other apps such as chrome and terminal.
Total cpu usage exceeds my pc capacity but minikube still works properly. Why?

### Attach the log file

I will add one if necessary.

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
It is over-allocated, twice (or more).

The first time is when you start the Docker VM, then it uses a number of vCPU. Say that you start it with 4, then on your host you have 2 physical cores that are multi-threading into 4 execution threads. Normally one says that this will give a 130% increase at best (possibly up to 150%), not 200% that you could expect - like when adding more physical resources. These 4 are then given the task to run an additional 4 vCPU for the virtual machine, which they do - without traditional emulation. So now you have 8 queues, for your 2 cores.

Then you start minikube, and when you use the container drivers it will actually not reserve any limits but just say that it wants to schedule work for 4 vCPU which is not more than what the virtual machine is willing to accept. It doesn't actually allocate 2 vCPU to each fake "node", but they both get to share on what their actual machine is. Whether it is physical (like on bare metal) or virtual (like in this case). The `kubeadm` requirement of 2 "CPUs" is somewhat arbitrary in the first place, but that's another story (#10808). Then you can start containers, inside these nodes. They both see the full capabity of the node, since it is not hidden like when running for instance LXC.

So, in the end it is all smoke and mirrors.

If you schedule more work than the machine has capacity for, then they will end up waiting in a queue. This is reflected in the "load average" of Linux, where you can see the number of jobs waiting. Normally you want this number (from `uptime`) to be the same as the number of online processors (`nproc`), if it is higher it means that there is a queue. For the special case of multithreading, we schedule two jobs but expect to see them running at 150% rather than 200% efficiency.

If you want to learn more about this topic, which is rather interesting all by itself, there are some good resources available online. Otherwise you can just use minikube without caring about it, and the multiple layers will be hidden for you. In this particular case, there are three layers of virtualization or containerization nested on top of each other. If it sounds complex, compared to "just" running regular processes on a non-hyperthreaded linux machine (hard enough), that is because it is.

**Comment by afbjorklund** [comment]
Last KubeCon EU we held a presentation about it: (this year, it will be more about ARM and GUI)

https://kccnceu2021.sched.com/event/iE7w/minikube-and-three-different-local-kubernetes-learning-environments-anders-bjorklund-predrag-rogic

![minikube-environments](https://user-images.githubusercontent.com/10364051/168415404-ce1522ae-9321-4424-90b2-25d571c21177.png)

We normally pretend that "docker" is just **one** environment, so that is why it is "three environments" (rather than four)

**Comment by hiroaki2020** [comment]
@afbjorklund Thank you for explaining in detail. This helps me a lot.

**Comment by afbjorklund** [comment]
It probably should be described in the (advanced section of) documentation.

**Comment by hiroaki2020** [comment]
> It probably should be described in the (advanced section of) documentation ?

That would be great.

> The actual system requirements are also somewhat different if you run two different clusters, with one control plane / database each, or if it is one multi-node cluster with one worker - since the worker nodes don't need as many k8s components running

> However, currently the minimum requirements (2 vCPU + 2 GiB) are the same.

Thank you for sharing additional info.
