### ISSUE TITLE
Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.

### ISSUE THREAD

**Issue by robsonazevdo** [kubernetes/minikube#14205]
**Os comandos necessários para reproduzir o problema**:
 
**A saída completa do comando que apresentou falha**: <details>

</details>

**A saída do comando `minikube logs`**:<details>

</details>

**A versão do sistema operacional usado**:

**Comment by klaases** [comment]
Hi @robsonazevdo  – it looks like this issue was created in error. If not, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed.

To create and attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
