### ISSUE TITLE
Error while launching minikube

### ISSUE THREAD

**Issue by haykeminyan** [kubernetes/minikube#14220]
### What Happened?

After executing command "minikube start" I got such message:

Failed to start docker container. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

OS: Arch Linux

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8758336/logs.txt)

### Operating System

Other

**Comment by guresonur** [comment]
@haykeminyan, 
just wondering how your docker config.json file looks like , can you share your ~/.docker/config.json file?

also can you share output of following comand, might worth to check how minikube container looks like? ;
`docker inspect $(docker ps -a | grep minikube | awk '{print $1}')`

to restore your issue, did you try to ;
1. delete your minikube cluster
2. remove all minikube containers (even exited ones, to trigger a scratch container creation)
3. recreate a minikube cluster

**Comment by spowelljr** [comment]
Hi @haykeminyan, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
