### ISSUE TITLE
Establishing Connectivity between two locally created minikube clusters on two laptops

### ISSUE THREAD

**Issue by mudit000** [kubernetes/minikube#14278]
### What Happened?

1)I have two laptops L1 & L2
2)I am creating minikube cluster on each laptop. ML1 & ML2
3)Both laptop can ping each other. L1 <---->L2
4)From one laptop i cann't ping the minikube VM ip on other laptop

L1 --X--> ML2
L2 --X--> ML1

I need to setup connectivity between ML1 and ML2

I am using virtualbox driver on mac.

### Attach the log file

dd
[log.txt](https://github.com/kubernetes/minikube/files/8840612/log.txt)

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by afbjorklund** [comment]
While you can* change the virtualbox driver to use another network solution, this sounds more like cluster-to-cluster networking ?

\* https://www.virtualbox.org/manual/ch06.html

Using ssh tunnels would be the simplest workaround.

**Comment by zhan9san** [comment]
It's bridge network.
So the question becomes how to make minikube runn in a VM with bridge network.

**Comment by klaases** [comment]
Hi @mudit000, are you still working on this issue? After a quick search I found an article that talks about setting up the bridge between two computers.

https://dpb587.me/post/2020/04/11/minikube-and-bridged-networking/

Specifically, rather than using `minikube tunnel`, which only works on the local machine which is running kubernetes, you may instead want to use `route` to open up a range of IPs that are accessible outside of L1.

```
# local routing
# sudo route add -net 10.96.0.0/12 $( get_bridged_ip )
```

https://github.com/dpb587/dpb587.me/blob/master/appendix/2020-04-11-minikube-and-bridged-networking/minikube.sh#L4

**Comment by klaases** [comment]
Hi @mudit000  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
