### ISSUE TITLE
Can't create mount on arch with docker driver

### ISSUE THREAD

**Issue by AdamJSoftware** [kubernetes/minikube#14325]
### What Happened?

When trying to mount my home directory (or any directory to minikube) I get the following error

```
📁  Mounting host path /home/adam into VM as /new_host ...
    ▪ Mount type:
    ▪ User ID:      docker
    ▪ Group ID:     docker
    ▪ Version:      9p2000.L
    ▪ Message Size: 262144
    ▪ Options:      map[]
    ▪ Bind Address: 192.168.49.1:36955
🚀  Userspace file server: ufs starting

❌  Exiting due to GUEST_MOUNT: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=36955,trans=tcp,version=9p2000.L 192.168.49.1 /new_host" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=36955,trans=tcp,version=9p2000.L 192.168.49.1 /new_host": Process exited with status 32
stdout:

stderr:
mount: /new_host: mount(2) system call failed: Bad address.
```

I am using arch linux for this. I have previously installed the regular kubernetes on my system. Is that causing a conflict potentially?

Also, I am actually able to create a mount, however only when the minikube cluster starts.

```
minikube start --mount-string="$HOME:/host" --mount
```

### Attach the log file

I would love to provide my logs, however I think I found another issue where minikube is not logging. Running minikube logs --file=logs.txt outputs absolutely nothing. However I was able to retrieve the mount log from /tmp
[minikube_mount_5b648b798ac9a35c8e08174f949f0727845a2f27_0.log](https://github.com/kubernetes/minikube/files/8886994/minikube_mount_5b648b798ac9a35c8e08174f949f0727845a2f27_0.log)

### Operating System

Other

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @AdamJSoftware, thanks for reporting your issue with minikube..

The reason the mount works when passed into the start is because it uses a different mounting method.

If you include mount args on start and you're using the Docker driver it used Docker to do the mounting.

For all other cases, including `minikube mount` it uses 9P for the mounting, hence whey there is a discrepancy between the two cases.

> I have previously installed the regular kubernetes on my system. Is that causing a conflict potentially?

It shouldn't as the mount command failing is being run inside the Docker container, so anything regarding your system should be irrelevant.

> I would love to provide my logs, however I think I found another issue where minikube is not logging.

You're likely seeing:
```
🤷  The control plane node must be running for this command
👉  To start a cluster, run: "minikube start"
```
It's a confusing error, it's failing to get pod specific logs, but it still generates the last start logs. If you look in your filesystem you should see that a `logs.txt` file was indeed generated. I have since removed the above error (https://github.com/kubernetes/minikube/pull/13873) and the fix will be included in our next release.

As to the exact reason why your mounting is failing, I'm not sure, I'll take a better look at the logs tomorrow. But we don't have tests that check for mounting and they pass consistently, so might be related to running on Arch.

**Comment by gudn** [comment]
/reopen

Hello, I'd met with the same issue. Cluster was started with `minikube start` with default docker daemon.

Logs:
[minikube_mount.log](https://github.com/kubernetes/minikube/files/9226139/minikube_mount.log)
[logs.txt](https://github.com/kubernetes/minikube/files/9226140/logs.txt)

Docker version output:
```
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.18.3
 Git commit:        100c70180f
 Built:             Sat Jun 11 23:27:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.3
  Git commit:       a89b84221c
  Built:            Sat Jun 11 23:27:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1.m
 runc:
  Version:          1.1.3
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Minikube version:
```
minikube version: v1.26.0
commit: f4b412861bb746be73053c9f6d2895f12cf78565-dirty
```

Kernel version is 5.15.57-2-MANJARO
