### ISSUE TITLE
Minikube start error

### ISSUE THREAD

**Issue by shashi8280** [kubernetes/minikube#14397]
### What Happened?

Unable to start Minikube 

### Attach the log file

root@ip-172-31-25-89:~# minikube start --vm-driver=none
* minikube v1.26.0 on Ubuntu 18.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 18.04.6 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

**Comment by spowelljr** [comment]
Hi @shashi8280, thanks for reporting your issue with minikube.

Kubernetes v1.24 dropped support for Dockershim, so if you want to use the combination of the none driver, Kubernetes v1.24+, and the Docker container runtime you'll need to install cri-dockerd on your system, as listed in our [requirements page](https://minikube.sigs.k8s.io/docs/drivers/none/#requirements).

Other options include using a [different driver](https://minikube.sigs.k8s.io/docs/drivers/), using an older version of Kubernetes `--kubernetes-version`, or using a different container runtime `--container-runtime`.

Please try one of those solution and let me know if it resolves your issue, thanks

**Comment by bagariarakesh** [comment]
I am using below commands and it was working fine day before yesterday , i do not have any Clue what is wrong now. 
Now install docker

sudo apt update && apt -y install docker.io
install Kubectl

curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl
install Minikube
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
supporting third party software 
apt install conntrack
minikube start --vm-driver=none


I am getting same error with all options 👍 
minikube start --kubernetes-version=''
* minikube v1.26.0 on Ubuntu 18.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 18.04.6 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

root@ip-172-31-47-155:/home/ubuntu# minikube start --container-runtime=''
* minikube v1.26.0 on Ubuntu 18.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 18.04.6 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

**Comment by getangar** [comment]
I have the same problem on Windows 11 Enterprise 10.0.22000 Build 22000

**Comment by spowelljr** [comment]
@bagariarakesh 
> I am using below commands and it was working fine day before yesterday , i do not have any Clue what is wrong now.

minikube v1.26.0 came out two days ago, and based on your logs you updated to it which is what is causing a difference. v1.26.0 now defaults the Kubernetes version to the current Kubernetes version which is v1.24.1. You were likely on minikube v1.25.2 before which the default Kubernetes version was v1.23.X. Kubernetes dropped Dockershim support with Kubernetes v1.24, which now makes cri-dockerd a requirement if you want to use the Docker container-runtime.

minikube v1.25.2 -> Defaults k8s v1.23.X -> cri-docker not required
minikube v1.26.0 -> Defaults k8s v1.24.1 -> cri-docker is required

You can use the options I listed in my previous comment

> You can install cri-dockerd on your system, as listed in our [requirements page](https://minikube.sigs.k8s.io/docs/drivers/none/#requirements).

> Other options include using a [different driver](https://minikube.sigs.k8s.io/docs/drivers/), using an older version of Kubernetes `--kubernetes-version`, or using a different container runtime `--container-runtime`.

**Comment by spowelljr** [comment]
@getangar 
> I have the same problem on Windows 11 Enterprise 10.0.22000 Build 22000

Are you using the `none` driver on Windows? WSL? If you're not using the `none` driver something very different is happening and you should open your own issue. But if you're using the `none` driver the advice above should resolve your issue.

**Comment by bagariarakesh** [comment]
> @bagariarakesh
> 
> > I am using below commands and it was working fine day before yesterday , i do not have any Clue what is wrong now.
> 
> minikube v1.26.0 came out two days ago, and based on your logs you updated to it which is what is causing a difference. v1.26.0 now defaults the Kubernetes version to the current Kubernetes version which is v1.24.1. You were likely on minikube v1.25.2 before which the default Kubernetes version was v1.23.X. Kubernetes dropped Dockershim support with Kubernetes v1.24, which now makes cri-dockerd a requirement if you want to use the Docker container-runtime.
> 
> minikube v1.25.2 -> Defaults k8s v1.23.X -> cri-docker not required minikube v1.26.0 -> Defaults k8s v1.24.1 -> cri-docker is required
> 
> You can use the options I listed in my previous comment
> 
> > You can install cri-dockerd on your system, as listed in our [requirements page](https://minikube.sigs.k8s.io/docs/drivers/none/#requirements).
> 
> > Other options include using a [different driver](https://minikube.sigs.k8s.io/docs/drivers/), using an older version of Kubernetes `--kubernetes-version`, or using a different container runtime `--container-runtime`.

I am getting below issue while trying to install cri-dockerd

root@ip-172-31-47-155:/home/ubuntu/cri-dockerd/bin# go install && go build -o bin/cri-dockerd
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
root@ip-172-31-47-155:/home/ubuntu/cri-dockerd/bin#

**Comment by spowelljr** [comment]
Are you following the instructions in: https://github.com/Mirantis/cri-dockerd#build-and-install

I don't see `go install` listed anywhere in the instructions, if you have a problem installing cri-docker you should reach out to the cri-docker team

**Comment by spowelljr** [comment]
Going to close this issue to centralize these duplicated `cri-docker` issues in https://github.com/kubernetes/minikube/issues/14410. If you have any further questions or comments please leave them in https://github.com/kubernetes/minikube/issues/14410, thank you.
