### ISSUE TITLE
 API server cannot be started.

### ISSUE THREAD

**Issue by tamasbudai** [kubernetes/minikube#14446]
### What Happened?

Hi all,
after the execution of  "minikube start --driver docker" command the API server cannot be started.

Error Message:
W0627 18:27:28.748694   45422 out.go:239] ❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition
❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition
W0627 18:27:28.748756   45422 out.go:239] 

minikube status:
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Stopped
kubeconfig: Configured

If you have any idea what could be the issue please let me know.

Best Regards,
Samu

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8994028/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by tamasbudai** [comment]
I suspect that the problem should be connection with permissions.

**Comment by klaases** [comment]
Hi @tamasbudai, did you happen to use `sudo` when installing minikube?

**Comment by klaases** [comment]
Hi @tamasbudai – I would suggest re-installing minikube without `sudo`, in order to ensure the default permissions are applied.

Otherwise, is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
