### ISSUE TITLE
Building ISO fails

### ISSUE THREAD

**Issue by psschwei** [kubernetes/minikube#14459]
### What Happened?

Trying to build the Minikube ISO [as per the docs](https://github.com/kubernetes/minikube/blob/474b52c02fc9f6b3e44dfd1c34fec8f065ab2d44/site/content/en/docs/contrib/building/iso.md?plain=1#L40) yields an error:

```
$ make out/minikube.iso
make: *** No rule to make target 'out/minikube.iso'.  Stop.
```

Looks like the rule was updated in https://github.com/kubernetes/minikube/commit/d92f42a6e459313fe22ca935bc5869cee05146e9 , so seems like the docs just need to be updated.

### Attach the log file

n/a

### Operating System

Redhat/Fedora

### Driver

N/A

**Comment by spowelljr** [comment]
Hi @psschwei, thanks for reporting your issue with minikube.

Thanks for the heads up, that stemmed from us originally only having one ISO (amd64), but since we added arm64 support the target got updated to specify the arch.

I'm open to a PR from anyone that updates the documentation that indicates the two possible commands.

**Comment by psschwei** [comment]
I'll fix it
/assign
