### ISSUE TITLE
 Exiting due to PROVIDER_VMWARE_NOT_FOUND

### ISSUE THREAD

**Issue by zarak-shahjee** [kubernetes/minikube#14513]
user1@master-node:~$ minikube start --vm-driver=vmware
😄  minikube v1.25.2 on Ubuntu 18.04
✨  Using the vmware driver based on user configuration

🤷  Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "docker-machine-driver-vmware": executable file not found in $PATH
💡  Suggestion: Install docker-machine-driver-vmware
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

**Comment by klaases** [comment]
Hi @zarak-shahjee, were you able to install `docker-machine-driver-vmware` as suggested?

**Comment by hariharPai** [comment]
I am facing the same issue 

Before this I did brew install docker-machine-driver-vmware

minikube start --driver=vmware
😄  minikube v1.26.1 on Darwin 12.5
✨  Using the vmware driver based on user configuration

🤷  Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "vmrun": executable file not found in $PATH
💡  Suggestion: Install vmrun
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

**Comment by spowelljr** [comment]
@hariharPai  This is a different error, the original issue was for `"docker-machine-driver-vmware": executable file not found in $PATH`, but you're experiencing `"vmrun": executable file not found in $PATH`. You'll need to find where `vmrun` is and add it to your path.

**Comment by klaases** [comment]
Hi @hariharPai, were you able apply the above suggestion to help solve the different error?

**Comment by hariharPai** [comment]
I could not use minikube. I used dockerdesktop to solve the problem.

Thanks and regards,
Harihar Pai

**Comment by klaases** [comment]
Hi @hariharPai  – sure, I see. If needed, please feel free to re-open the issue by commenting with `/reopen`.

Thank you for sharing your experience!

**Comment by rajakumarlearning** [comment]
check and add the environment variable for Vmware

**Comment by Zarak-Shah-ji** [comment]
> re you able apply the above suggestion to help solve the different err

Yes.
