### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by jaydeep123s** [kubernetes/minikube#14515]
### What Happened?

minikube start --vm-driver=none
this command is not run

### Attach the log file

my minikube not install on ubuntu18

### Operating System

Ubuntu

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by spowelljr** [comment]
Hi @jaydeep123s, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
