### ISSUE TITLE
Use fully qualified name in addon files

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#14520]
The files [deploy/addons/aliyun_mirror.json](https://github.com/kubernetes/minikube/blob/master/deploy/addons/aliyun_mirror.json) and [pkg/minikube/assets/addons.go](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/assets/addons.go) should be updated to use the fully qualified image names `docker.io/org/image` instead of just `org/image`.

This should be done after https://github.com/kubernetes/minikube/pull/14518 is merged to prevent merge conflicts.

**Comment by SiddhantKhisty** [comment]
I'd like to work on this issue 😄

**Comment by spowelljr** [comment]
Hi @SiddhantKhisty, comment `/assign` to assign the issue to yourself

**Comment by klaases** [comment]
Hi @siddhant-khisty, how are things going, have you been able to work on the issue?

**Comment by siddhant-khisty** [comment]
hey @klaases , I am working on this issue. Looks like the PR didn't get attached to the issue for some reason.

**Comment by klaases** [comment]
Hi @siddhant-khisty, I see that the issue has been added to your PR, thanks.

**Comment by DanielViniciusAlves** [comment]
Hey, I'm new to the Kubernetes environment and still trying to figure out what is minikube, and would be of great help if some one could explain to me what the issue was and how it was fixed.

**Comment by siddhant-khisty** [comment]
Hey, @DanielViniciusAlves. Minikube in the most simple sense is a compressed control plane for Kubernetes. Usually, in order to just run a bare metal Kubernetes cluster with no applications on it, you would need a minimum of 3 nodes. However, using minikube you can do it using only one node so it is great when you have low system resources.

This PR was for changing the registry names to better determine where to look for the image. So for example, earlier it was only `xyz-org/app-image` type of format. We didn't really know which container registry to find the image in. Hence we made this PR to add the registry as well which would make the previous entry as `docker.io/xyz-org/app-image`. Hope that helps :smile:
