### ISSUE TITLE
minikube logs --file=log.txt

### ISSUE THREAD

**Issue by jigyasumishra321** [kubernetes/minikube#14530]
### What Happened?

kube-proxy showing stop stat

### Attach the log file

minikube logs --file=log.txt

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Hi @jigyasumishra321, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
