### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by preetsohivirk** [kubernetes/minikube#14604]
### What Happened?

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

### Attach the log file

stderr:
sudo: crictl: command not found

### Operating System

Windows

### Driver

Docker

**Comment by RA489** [comment]
@preetsohivirk I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by preetsohivirk** [comment]
actually I am new to this. I am gonna attach the screenshot of issue been struggling to fix it
![Screenshot (1)](https://user-images.githubusercontent.com/91236048/179807204-772619a9-8858-4c41-8c56-2bf2de77626b.png)
.

**Comment by vivek625** [comment]
same problem 
how to solve this problem .......................????????????

**Comment by spowelljr** [comment]
Hi @preetsohivirk , we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by preetsohivirk** [comment]
no not able to do this
