### ISSUE TITLE
Minikube isn't starting.

### ISSUE THREAD

**Issue by enn-dee** [kubernetes/minikube#14649]
### What Happened?

I have kubectl already installed/enabled when I run minikube start cmd it's showing me error. Can anyone help me to resolve this problem ?.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9196020/logs.txt)

### Operating System

Windows

### Driver

Docker

**Comment by Rajat0002** [comment]
Check if your docker desktop is running in background if yes, try by using minikube delete cmd and then use minikube start

**Comment by enn-dee** [comment]
> Check if your docker desktop is running in background if yes, try by using minikube delete cmd and then use minikube start

I already tried this thing nothing happened still showing me same error.

**Comment by spowelljr** [comment]
Hi @enn-dee, it looks like you're getting a cert issue:
`error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "minikubeCA")`

Could you try running `minikube delete --all --purge` to clear out the existing certs and then try starting minikube again and seeing if that resolves your issue.

**Comment by klaases** [comment]
Hi @enn-dee, did you have a chance to review the above comments?

Are you still experiencing this issue?

/triage needs-information

**Comment by enn-dee** [comment]
Yes, it aided me in resolving the problem.

**Comment by klaases** [comment]
Hi @enn-dee, thanks for the update!

Have a great weekend!
