### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by dhana7766** [kubernetes/minikube#14701]
### What Happened?

error while creating the k8s
 

### Attach the log file

* Failed to start none bare metal machine. Running "minikube delete" may fix it: creating host: create: precreate: exec: "docker": executable file not found in $PATH

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: precreate: exec: "docker": executable file not found in $PATH
*

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
You need to install both docker and cri-dockerd, and some other requirements like conntrack and crictl.

See https://minikube.sigs.k8s.io/docs/drivers/none/

**Comment by spowelljr** [comment]
Hi @dhana7766, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
