### ISSUE TITLE
Not enough memory in the system to start the virtual machine minikube

### ISSUE THREAD

**Issue by Chethiya2001** [kubernetes/minikube#14744]
### What Happened?

'minikube' failed to start. (Virtual machine ID D6B797B5-C7D3-480F-99C7-F419F48DE404)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine
ID D6B797B5-C7D3-480F-99C7-F419F48DE404)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation.
(0x8007000E). (Virtual machine ID D6B797B5-C7D3-480F-99C7-F419F48DE404)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: creating: exit status 1

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: exit status 1
*

### Attach the log file

'minikube' failed to start. (Virtual machine ID D6B797B5-C7D3-480F-99C7-F419F48DE404)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine
ID D6B797B5-C7D3-480F-99C7-F419F48DE404)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation.
(0x8007000E). (Virtual machine ID D6B797B5-C7D3-480F-99C7-F419F48DE404)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: creating: exit status 1

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: exit status 1
*

### Operating System

Windows

### Driver

Hyper-V

**Comment by spowelljr** [comment]
Hi @Chethiya2001, it looks like the computer you're using doesn't have 2200MB of memory available? How much memory does the machine have?

**Comment by walterj028** [comment]
Hi @spowelljr, I'm having the same issue. My computer has installed RAM 8.00 GB (7.82 GB usable).

PS C:\Users\17328\.kube> minikube start
* minikube v1.28.0 on Microsoft Windows 10 Home 10.0.19044 Build 19044
* Automatically selected the hyperv driver
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...\ E1118 12:21:48.812495   14084 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'minikube' failed to start. (Virtual machine ID 262DD47A-A35E-4317-90FC-A5A745A65C60)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine
ID 262DD47A-A35E-4317-90FC-A5A745A65C60)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation.
(0x8007000E). (Virtual machine ID 262DD47A-A35E-4317-90FC-A5A745A65C60)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM



* Stopping node "minikube"  ...
* Deleting "minikube" in hyperv ...
! StartHost failed, but will try again: creating host: create: creating: exit status 1
* Failed to start hyperv VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\17328\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\17328\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'

**Comment by spowelljr** [comment]
Hi @walterj028, if you open task manager how much memory do you have unused?

**Comment by walterj028** [comment]
Hi Steve, It shows just under a 1Gb.

**Comment by spowelljr** [comment]
If you have less than 1GB of memory available then VirtualBox is unable to start the as it's requesting 2GB.

**Comment by walterj028** [comment]
That did the trick… I had all but given up. I was running virtualbox as an alternative VM but it has it’s own limitations with simulating a kubernetes cluster. Once I freed up 2Gb of memory Hyper-V start right up. Thanks for the help!

 

Kind Regards,

Walter

**Comment by spowelljr** [comment]
Glad to hear that solved your issue @walterj028
