### ISSUE TITLE
`minikube start` not working

### ISSUE THREAD

**Issue by kaizen-cmd** [kubernetes/minikube#14750]
### What Happened?

`minikube start` not working

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9277378/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @kaizen-cmd, minikube doesn't yet support Docker Desktop on Linux. You can find more about the issue here (https://github.com/kubernetes/minikube/issues/14202). This is a duplicate of https://github.com/kubernetes/minikube/issues/14202 so I'm going to close this, but please follow along there, thanks!
