### ISSUE TITLE
Docs: stop vs pause

### ISSUE THREAD

**Issue by guettli** [kubernetes/minikube#14773]
### What Happened?

I see that minikube containers in minikube consume ressources, so that my laptop fan makes noise.

At the moment I don't need minikube.

I look at 

* https://minikube.sigs.k8s.io/docs/commands/stop/
* https://minikube.sigs.k8s.io/docs/commands/pause/

I have no clue what the difference between both commands.

It would be great, if the docs would explain the difference between both commands.

### Attach the log file

.

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Stop kills the process, so that it has to be started up again.

Pause freezes the process, so that it can be resumed later.

**Comment by Aryan-Deshpande** [comment]
hey, I would like to work on this issue :)

**Comment by Aryan-Deshpande** [comment]
Please let me know if any feedback, would love to learn or implement such suggestions.

**Comment by afbjorklund** [comment]
Note that if/when doing the "stop" command, it might also halt a virtual machine (if used)

The comments above applied to the "docker" driver, and doesn't affect the VM (if any)

e.g. the Docker Desktop VM is started and stopped, independent from minikube

Currently there is no way to suspend and resume VM, but that feature might arrive later.

**Comment by Aryan-Deshpande** [comment]
So essentially when you mention "minikube stop", the underlying docker container that minikube runs on is halted.

**Comment by Aryan-Deshpande** [comment]
I have also noticed that when you use "minikube pause", its container on docker appears to be running. 
![image](https://user-images.githubusercontent.com/72693780/184468036-7d65cbce-ef15-482f-bd94-e2a38ac35a93.png)

**Comment by afbjorklund** [comment]
> So essentially when you mention "minikube stop", the underlying docker container that minikube runs on is halted.

That is correct, or stopped (as in `docker stop`). This means that the actual process (systemd) inside, is killed.

> I have also noticed that when you use "minikube pause", its container on docker appears to be running.

Right, in this scenario the kubernetes cluster containers' processes are all frozen. But the main process runs.

----

Things are a little different, when running a virtual machine instead of a container. Then it is halted with "stop", for real.

When the machine is started up again later, the whole VM needs to be booted again. And _then_ processes are started.

For the platforms running Docker Desktop, that VM is handled with separate controls - minikube does **not** start/stop it.

This is similar to starting the machine with --no-kubernetes, when only the Linux system processes runs - no control plane

**Comment by afbjorklund** [comment]
Same comment applies to Podman Desktop, there the VM is controlled using the GUI or `podman machine` CLI.

**Comment by guettli** [comment]
@Aryan-Deshpande you said you want to work on the issue. I think it would be great if you could extend a docs a bit, so that the difference is easier to understand.
