### ISSUE TITLE
/bin/bash: /tmp/ Permission denied

### ISSUE THREAD

**Issue by elamribadrayour** [kubernetes/minikube#14833]
### What Happened?

Unable to start minikube.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9393633/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by klaases** [comment]
Hi @elamribadrayour, have you tried debugging this issue?

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @elamribadrayour, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
