### ISSUE TITLE
minikube addons enable ingress

### ISSUE THREAD

**Issue by Zeinab-Mamdouh** [kubernetes/minikube#14896]
### What Happened?

Hello everyone when I'm trying to install Ingress, i received this message "Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]"

### Attach the log file

-

### Operating System

Ubuntu

**Comment by klaases** [comment]
Hi @Zeinab-Mamdouh, what is the start command that you are using to enable the ingress addon?

Also, if you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @Zeinab-Mamdouh, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
