### ISSUE TITLE
Minikube not working 

### ISSUE THREAD

**Issue by smandalika** [kubernetes/minikube#14899]
### What Happened?

Cant seem to finish minikube installation my MAC

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9474355/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by klaases** [comment]
Hi @smandalika, are you installing / re-installing minikube via Brew?

**Comment by smandalika** [comment]
Installing minikube via Brew?

**Comment by afbjorklund** [comment]
The error is somewhat odd:

```

W0712 12:56:59.172076   30540 out.go:239] âŒ  Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /etc/kubernetes: mkdir /etc/kubernetes: permission denied
```

**Comment by spowelljr** [comment]
As @afbjorklund pointed out, you explicitly set `KUBECONFIG` to `/etc/kubernetes/admin.conf`, but your user doesn't have permission to access `/etc/kubernetes`. You'll either have to manually create the directory and make sure you current user has permission to access it or change the directory of `KUBECONFIG` to a directory you do already have access to.

**Comment by spowelljr** [comment]
Hi @smandalika, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
