### ISSUE TITLE
error while installing minikube

### ISSUE THREAD

**Issue by Sachin290287** [kubernetes/minikube#14921]
### What Happened?

* Failed to start hyperv VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": Error getting migrated host: unexpected end of JSON input

X Exiting due to GUEST_PROVISION: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": Error getting migrated host: unexpected end of JSON input
*

### Attach the log file

[lastStart.txt](https://github.com/kubernetes/minikube/files/9524902/lastStart.txt)

### Operating System

Windows

### Driver

Hyper-V

**Comment by klaases** [comment]
Hi @Sachin290287, what happens when trying to run `minikube delete`? Does that help alleviate the issue?

**Comment by spowelljr** [comment]
Hi @Sachin290287, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
