### ISSUE TITLE
Minikube start --driver=docker hangs on addons

### ISSUE THREAD

**Issue by Excel619** [kubernetes/minikube#14920]
### What Happened?

Upon running `minikube start --driver=docker`, the command hangs with an eventual timeout, declaring `❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition`

I am running on windows 10 with WSL2 ubuntu 20.04. 

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9523420/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by klaases** [comment]
Hi @Excel619  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @Excel619, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
