### ISSUE TITLE
 Pulling base image ..

### ISSUE THREAD

**Issue by RajrupDasid** [kubernetes/minikube#14968]
### What Happened?

As a new user i am trying to download minikube 
but after installing 400 mb its goes to next base download
and stuck and it's almost 1.40 hours it's stuck 
tried cancel and start download again 
but nope not a single chance . 
not downloading stuck at same area at same position 0%.

I am on latest arch linux

### Attach the log file

not found because I've not still installed it 

### Operating System

Other

### Driver

Docker

**Comment by afbjorklund** [comment]
You can download the image "manually", which gives better progress bars and what not.

`docker pull gcr.io/k8s-minikube/kicbase:v0.0.34`

**Comment by afbjorklund** [comment]
It should be possible to make the download smaller, by optimizing for size instead of speed.

1) install the container runtime and friends from archive, instead of including it in the base image 

2) unpack and prepare the container images from storage, instead of having it preloaded in /var

But it would probably only save 100M off each tarball, so it wouldn't make a **big** difference...

**Comment by RajrupDasid** [comment]
Yeah @afbjorklund  you're right . Yestarday after 7-8 tries I was able to successfully download it .
Thanks for your help and advise . I am closing this issue . Because for now it's solved
