### ISSUE TITLE
Unable to connect to the server

### ISSUE THREAD

**Issue by umeshpolavarapu** [kubernetes/minikube#15024]
### What Happened?

C>kubectl get po -A
Unable to connect to the server: dial tcp 127.0.0.1:49848: connectex: No connection could be made because the target machine actively refused it.

### Attach the log file

kubectl get po -A
Unable to connect to the server: dial tcp 127.0.0.1:49848: connectex: No connection could be made because the target machine actively refused it.

### Operating System

Windows

**Comment by coy18** [comment]
# I get the same issue too. So all looks good when creating 2 nodes:
$ minikube start --nodes 2 -p multinode-demo
😄  [multinode-demo] minikube v1.27.1 on Microsoft Windows 11 Pro 10.0.22621 Build 22621
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node multinode-demo in cluster multinode-demo
🤷  virtualbox "multinode-demo" VM is missing, will recreate.
🔥  Creating virtualbox VM (CPUs=2, Memory=4050MB, Disk=20000MB) ...
❗  This VM is having trouble accessing https://registry.k8s.io
🔎  Verifying Kubernetes components...
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "multinode-demo" cluster and "default" namespace by default

# When I check for the nodes:
$ k get nodes
Unable to connect to the server: dial tcp 192.168.59.100:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

# minikube status. Tho I can see VMs in are in a running state. 
$ minikube status
E1014 10:09:47.902157   11980 status.go:260] status error: host: state: machine does not exist
E1014 10:09:47.902248   11980 status.go:263] The "minikube" host does not exist!
minikube
type: Control Plane
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent

I am using virtualbox and Win11 OS.

**Comment by umeshpolavarapu** [comment]
Thanks alot

**Comment by coy18** [comment]
what you can do tho is to manually start a cluster by 
: minikube start

then add node to the cluster
: minkube node add

check
: minikube kubectl -- get no
