### ISSUE TITLE
hello-minikube incorrect image

### ISSUE THREAD

**Issue by michaldorsett** [kubernetes/minikube#15086]
The image specified at https://minikube.sigs.k8s.io/docs/start/ is ocker.io/nginx:1.23.
However, the landing page on this image is the "Welcome to Nginx" page, instead of the one show "CLIENT VALUES", "SERVER VALUES", etc.
[The basic controls page ](https://minikube.sigs.k8s.io/docs/handbook/controls/)does specify the correct image: k8s.gcr.io/echoserver:1.4.

**Comment by afbjorklund** [comment]
The "correct image" needs replacing:

* https://github.com/kubernetes/minikube/issues/11107

**Comment by spowelljr** [comment]
We changed the image to `docker.io/nginx:1.23` because @afbjorklund pointed out the existing image didn't run on arm64. So to stop the flow of issue of people on arm64 having troubles we replaced it with `docker.io/nginx:1.23`. However I seem to have missed the line below talking about the response values from the previous image.
