### ISSUE TITLE
Krishna

### ISSUE THREAD

**Issue by kkghattamaneni** [kubernetes/minikube#15082]
### What Happened?

unable to set local host: 8080

### Attach the log file

X Exiting due to DRV_AS_ROOT: The "docker" driver should not be used with root privileges.

**Comment by RA489** [comment]
@kkghattamaneni could you try using docker driver without root user?

**Comment by spowelljr** [comment]
Hi @kkghattamaneni, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
