### ISSUE TITLE
Unable to run "minikube start"

### ISSUE THREAD

**Issue by santoshchilkunda** [kubernetes/minikube#15140]
### What Happened?

W1015 15:32:50.114356    2194 certs.go:489] WARNING: could not validate bounds for certificate apiserver: the certificate has expired: NotBefore: 2021-09-12 13:21:49 +0000 UTC, NotAfter: 2022-09-13 13:21:49 +0000 UTC
error execution phase certs/apiserver: [certs] certificate apiserver not signed by CA certificate ca: x509: certificate has expired or is not yet valid: current time 2022-10-15T15:32:50Z is after 2022-09-13T13:21:49Z
To see the stack trace of this error execute with --v=5 or higher

### Attach the log file

**minikube logs** command fails as well with the following message:
_unable to fetch logs for: describe nodes_

### Operating System

macOS (Default)

**Comment by spowelljr** [comment]
Hi @santoshchilkunda, could you try running `minikube delete --all --purge` and then try starting minikube again and see if that resolves your issue.

**Comment by spowelljr** [comment]
Hi @santoshchilkunda, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
