### ISSUE TITLE
--files=log.txt cammand is not working

### ISSUE THREAD

**Issue by gitarbaz** [kubernetes/minikube#15168]
### What Happened?

 --file=logs.txt`
> --file=logs.txt`
--file=logs.txt: command not found
--file=logs.txt: command not found

### Attach the log file

--file=logs.txt`
> --file=logs.txt`
--file=logs.txt: command not found

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @gitarbaz, you make to include `minikube logs` such as `minikube logs --file=logs.txt`.

**Comment by spowelljr** [comment]
Hi @gitarbaz, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
