### ISSUE TITLE
unable to start minikube

### ISSUE THREAD

**Issue by dpx2016** [kubernetes/minikube#15167]
### What Happened?

i have an error message when i try minikube start on ubuntu

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9814019/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @dpx2016, could you try running `minikube delete --all --purge` to clear out your existing certificates and then try starting minikube again.

**Comment by spowelljr** [comment]
Hi @dpx2016, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
