### ISSUE TITLE
Using minikube as Docker Desktop Replacement

### ISSUE THREAD

**Issue by carlospalmaroldan** [kubernetes/minikube#15190]
eval $(minikube -p <profile> docker-env)

after running this I get 

 eval $(minikube -p <profile> docker-env)
zsh: no such file or directory: profile

The shell for minikube recommends this:

# To point your shell to minikube's docker-daemon, run:
# eval $(minikube -p minikube docker-env)

In my case this doesn't work either, since after running it I get  command not found docker

**Comment by spowelljr** [comment]
Hi @carlospalmaroldan, the problem is you're not passing the profile into the command and it's passing the command `docker-env` as the profile flag.

ex.
```
# You're running:
eval $(minikube -p docker-env)

# You want to run:
eval $(minikube -p minikube docker-env)
```

**Comment by spowelljr** [comment]
Hi @carlospalmaroldan, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
