### ISSUE TITLE
Report an issue

### ISSUE THREAD

**Issue by shtlamrut** [kubernetes/minikube#15227]
### What Happened?

stderr:
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/minikube/json": dial unix /var/run/docker.sock: connect: permission denied

### Attach the log file

- /tmp/minikube_logs_4bc0d8589f1126f97fe10ac6ed84228b09be5273_0.log 

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @shtlamrut, it seems your user can't use docker without sudo, follow the Docker Engine post-installation steps for Linux and that should solve your issue

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by spowelljr** [comment]
Hi @shtlamrut, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
