### ISSUE TITLE
unable to start minikube

### ISSUE THREAD

**Issue by ghost** [kubernetes/minikube#15231]
### What Happened?

root@ubuntu-s-2vcpu-4gb-ams3-01:~/cri-dockerd# sudo minikube start --vm-driver=none
* minikube v1.27.1 on Ubuntu 22.10 (kvm/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 22.10

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

* 
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

root@ubuntu-s-2vcpu-4gb-ams3-01:~/cri-dockerd# sudo minikube start --vm-driver=none
* minikube v1.27.1 on Ubuntu 22.10 (kvm/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 22.10

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

* 
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Ubuntu

https://github.com/kubernetes/minikube/issues/15231#tasklist-block-bc8258a1-65cc-4cc6-b753-5e7a4c455be0

**Comment by ThomWilhelm** [comment]
Following as I just ran into the same issue, almost identical setup except I'm on Ubuntu 22.04.1.

However for some reason running **minikube stop** then **minikube start** it worked again.

**Comment by muraliprasadece** [comment]
Hi Thom,

i have done minikube stop and start, but still same error
***@***.***:~# minikube stop
* Stopping node "minikube"  ...
* 1 node stopped.
***@***.***:~# minikube start
* minikube v1.27.1 on Ubuntu 22.10 (kvm/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 22.10

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit
status 1
stdout:

stderr:
sudo: crictl: command not found

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│
                  │
│    * If the above advice does not help, please let us know:
                  │
│      https://github.com/kubernetes/minikube/issues/new/choose
                  │
│
                  │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to
the GitHub issue.    │
│
                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
Regards,
Muraliprasad.M
