### ISSUE TITLE
Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

### ISSUE THREAD

**Issue by AhmedMohamedEid** [kubernetes/minikube#15298]
### What Happened?

After install Kubernetes and when get run this to start minikube

`minikube start`
# Output
```
😄  minikube v1.27.1 on Ubuntu 20.04
✨  Automatically selected the docker driver. Other choices: none, ssh, qemu2 (experimental)
🎉  minikube 1.28.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.28.0
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.25.2 preload ...
    > preloaded-images-k8s-v18-v1...:  385.41 MiB / 385.41 MiB  100.00% 1010.56
    > gcr.io/k8s-minikube/kicbase:  387.10 MiB / 387.11 MiB  100.00% 954.69 KiB
    > gcr.io/k8s-minikube/kicbase:  0 B [______________________] ?% ? p/s 3m32s
🔥  Creating docker container (CPUs=2, Memory=7732MB) ...
🐳  Preparing Kubernetes v1.25.2 on Docker 20.10.18 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...\ E1105 10:22:59.319786   30667 start.go:268] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.49.2:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 192.168.49.2:8443: i/o timeout]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9943380/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @AhmedMohamedEid, minikube just added support for Docker Desktop Linux with v1.28.0, could you update, run `minikube delete` and then try starting again.

**Comment by spowelljr** [comment]
Hi @AhmedMohamedEid, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by nguyentthai96** [comment]
I after setup coredns by recommend in terminal then I cannot start minikube

![image](https://github.com/kubernetes/minikube/assets/14333403/9d5904fe-1150-4a62-ab1f-64493cb6b449)
nguyenthanhthai@ThanhThaisMBP Desktop % minikube start               
😄  minikube v1.31.2 on Darwin 13.4.1 (arm64)
✨  Using the qemu2 driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running qemu2 "minikube" VM ...
🐳  Preparing Kubernetes v1.27.4 on Docker 24.0.4 ...
🤦  Unable to restart cluster, will reset it: apiserver health: apiserver healthz never reported healthy: context deadline exceeded
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
💡  Some dashboard features require the metrics-server addon. To enable all features please run:

	minikube addons enable metrics-server	


🔎  Verifying ingress addon...
    ▪ Using image gcr.io/k8s-minikube/minikube-ingress-dns:0.0.2
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
E0114 01:18:06.737735    3080 start.go:219] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: non-retryable failure while getting "coredns" deployment scale: Get "https://10.0.2.15:8443/apis/apps/v1/namespaces/kube-system/deployments/coredns/scale": dial tcp 10.0.2.15:8443: i/o timeout
🔎  Verifying Kubernetes components...

❌  Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded

Attach the log file
[logs.txt](https://github.com/kubernetes/minikube/files/13929114/logs.txt)

Operating System
MacOS 13.4.1 (22F82) M1 Pro

Driver
Podman, qemu2

**Comment by 5tigerjelly** [comment]
I have the same issue.

Similar setup as well,

M1 Pro,

Driver
QEMU2

**Comment by juan-domenech** [comment]
I've fixed this issue after updating MacOS to Sonoma by installing `socket_vmnet`

https://minikube.sigs.k8s.io/docs/drivers/qemu/#networking

**Comment by hahnandrew** [comment]
#####`Fedora 40`, `Docker` driver

The solution for me was setting `docker` permissions correctly. On (but not limited to) `Fedora`, docker daemon default binds to a root-owned socket. My start command kept hanging and then timing out into the posted error, but my system processes were mostly inactive. Containers by virtue tend to be low observable / non logging, so you definitely have to do a bit of digging around to get it to work.
