### ISSUE TITLE
Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1

### ISSUE THREAD

**Issue by gbenga2686** [kubernetes/minikube#15301]
### What Happened?

Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1

### Attach the log file

Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1

stderr:
sudo: crictl: command not found

### Operating System

Ubuntu

### Driver

None (Baremetal)

**Comment by spowelljr** [comment]
Hi @gbenga2686, `crictl` is a requirement listed in our documentation for the none driver, please install it and then try starting minikube again.

https://minikube.sigs.k8s.io/docs/drivers/none/#requirements

**Comment by A-Zhai123** [comment]
> Hi @gbenga2686, `crictl` is a requirement listed in our documentation for the none driver, please install it and then try starting minikube again.
> 
> https://minikube.sigs.k8s.io/docs/drivers/none/#requirements

 Hi @spowelljr I installed crictl,and can execute 'sudo crictl version'

But when start the minikube, it still promt that :

"X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl：command not found "

![image](https://user-images.githubusercontent.com/73648688/202138747-6ddcb274-bea2-4c1f-b1df-0ba0d9f81f9b.png)

**Comment by A-Zhai123** [comment]
I re-installed minikube,the issue disappeared.

**Comment by spowelljr** [comment]
Glad your issue was resolved @A-Zhai123
