### ISSUE TITLE
make sure minikube auto-selects Qemu Driver when Docker is not running and qemu is installed

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15316]
### What Happened?

on MacOs M1 right now if I close docker minikube will not Choose Qemu as a 
driver ( most probably because we have marked it as experimental)

```
10:44:21 medya
$ minikube start
😄  minikube v1.28.0 on Darwin 12.6.1 (arm64)
👎  Unable to pick a default driver. Here is what was considered, in preference order:
    ▪ docker: Not healthy: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
    ▪ docker: Suggestion: Start the Docker service <https://minikube.sigs.k8s.io/docs/drivers/docker/>
    ▪ virtualbox: Not healthy: "/usr/local/bin/VBoxManage --version" returned: <nil>
    ▪ virtualbox: Suggestion: Restart VirtualBox, or upgrade to the latest version of VirtualBox <https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/>
💡  Alternatively you could install one of these drivers:
    ▪ hyperkit: Not installed: exec: "hyperkit": executable file not found in $PATH
    ▪ parallels: Not installed: exec: "prlctl": executable file not found in $PATH
    ▪ vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in $PATH
    ▪ podman: Not installed: exec: "podman": executable file not found in $PATH

❌  Exiting due to DRV_DOCKER_NOT_RUNNING: Found docker, but the docker service isn't running. Try restarting the docker service.

```

### Attach the log file

n/a

**Comment by kloseliebej** [comment]
Qemu is not being picked because its priority is labeled as "experimental" and is lower than the pick priority https://github.com/kubernetes/minikube/blob/8bd593b4338f473e2138c68668847b21e7e283b7/pkg/minikube/driver/driver.go#L308

Two options here to improve user experience:
1. Add experimental drivers to the logs as well, like the unhealthy and uninstalled drivers here https://github.com/kubernetes/minikube/blob/f77209d23cadfd6d919b8481cf15eab0d716ae07/pkg/minikube/driver/driver.go#L317
So if user wants to use experimental drivers we can ask them to add the flag
3. Remove the experimental flag for Qemu, if Qemu is out of experimental already

**Comment by medyagh** [comment]
I think we can move the Qemu out of experimental but the priority still should be less than docker, so it should be picked only if Docker Driver is not available or healthy

**Comment by afbjorklund** [comment]
It should probably also stay below libvirt/hyper-v/hyperkit (for now), so changing from "experimental" to "default" is enough
