### ISSUE TITLE
virtualbox

### ISSUE THREAD

**Issue by Surjendu78** [kubernetes/minikube#15348]

**Comment by Surjendu78** [comment]
virtual box not found

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by spowelljr** [comment]
Hi @Surjendu78, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
