### ISSUE TITLE
Failed to enable ingress addon

### ISSUE THREAD

**Issue by sdicke** [kubernetes/minikube#15373]
### What Happened?

The command  `minikube addons enable ingress` failed with the following output: „_Terminiere aufgrund von MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]_“

Distribution: openSUSE Tumbleweed

### Attach the log file

[minikube_addons_de34a38a67b9bbc28b3b77cfae49428ef7535477_0.log](https://github.com/kubernetes/minikube/files/10032662/minikube_addons_de34a38a67b9bbc28b3b77cfae49428ef7535477_0.log)

### Operating System

Other

### Driver

KVM2

**Comment by spowelljr** [comment]
Hi @sdicke, what version of minikube are you using?

**Comment by sdicke** [comment]
I'm using die version 1.27.1-1.1.

**Comment by spowelljr** [comment]
Hi @sdicke, Kubernetes previously removed the image `k8s.gcr.io/ingress-nginx/controller:v1.2.1` from their registry, but it seems to be back now. Could you run `minikube addons disable ingress` and then `minikube addons enable ingress` and if it's still failing could you include the output of `kubectl get pods -A`.

**Comment by jorgegonzalez** [comment]
same issue here

**Comment by spowelljr** [comment]
Hi @sdicke, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
