### ISSUE TITLE
Create a prototype of direct image build on containerd and cri-o

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15389]
### What Happened?

we need to create a similar feature to docker-env that is only for docker-runtime.

**Comment by medyagh** [comment]
@afbjorklund knows a POC in his mind that could work, please share so someone could pick it up

**Comment by afbjorklund** [comment]
For accessing the `podman.sock` (for cri-o) and `nerdctl.sock` (for containerd), we _need_ to use SSH.

So the first step, would be to make sure that using SSH for `docker.sock` works OK and is documented:

`minikube ssh-host --append-known`

`minikube docker-env --ssh-host --ssh-add`

**Comment by afbjorklund** [comment]
Typical output of `docker-env` (tcp, 3 variables):

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.49.2:2376"
export DOCKER_CERT_PATH="/home/anders/.minikube/certs"
export MINIKUBE_ACTIVE_DOCKERD="minikube"

# To point your shell to minikube's docker-daemon, run:
# eval $(minikube -p minikube docker-env)
```

Typical output of `docker-env` (ssh, 1 variable):

```
export DOCKER_HOST="ssh://docker@127.0.0.1:49157"
export MINIKUBE_ACTIVE_DOCKERD="minikube"

# To point your shell to minikube's docker-daemon, run:
# eval $(minikube -p minikube docker-env --ssh-host)
```

**Comment by afbjorklund** [comment]
The `nerdctl.sock` is available from here: https://github.com/afbjorklund/nerdctld

Note that the unit CONTAINERD_NAMESPACE need to be changed to use "k8s.io"

**Comment by afbjorklund** [comment]
The default option in minikube should be to use the `minikube image` command instead of the legacy `docker` client...

https://minikube.sigs.k8s.io/docs/commands/image/

The "docker-env" command is mostly for backwards compatibility, and the "podman-env" should be fully deprecated.

It is also possible to do everything yourself with the `minikube ssh` command and `minikube mount`, but less usable.

----

The main use for "docker-env", is when using minikube as a replacement for Docker Toolbox and Docker Machine...

That is, as an OS alternative to Docker Desktop. Not when running a Kubernetes cluster, which doesn't _need_ Docker.

So the `docker` commands in this issue, are **only** for minikube. Mostly filling in the gaps in the CRI specification ?

If you need to run Docker in a VM, there are other projects.

**Comment by afbjorklund** [comment]
As per the docker instructions, one should make sure to configure $DOCKER_HOST **on the remote side**

* https://docs.docker.com/engine/security/protect-access/

* https://docs.docker.com/engine/security/rootless/#expose-docker-api-socket-through-ssh

So that when one connects via ssh, the environment variable points to the correct unix socket location.

Using the path parameter in the URL is **not** supported:

```
ssh host connection is not valid: extra path after the host: "/var/run/docker.sock"
```

A workaround is to create a symlink from the default location (`/var/run/docker.sock`), but more of a hack...

So the best is to use a global configuration in /etc, to properly set the socket location for the selected runtime ?

k8s runtime | cri | crictl socket | client | docker socket
--- | --- | ---- | --- | ---
docker | cri-dockerd | `/var/run/cri-dockerd.sock` | docker | `/var/run/docker.sock`
cri-o | crio | `/run/crio/crio.sock` | podman | `/run/podman/podman.sock`
containerd | containerd*| `/run/containerd/containerd.sock` | nerdctl | `/var/run/nerdctl.sock`

Normally the variable contains the URL (with a `unix://` scheme). In systemd (only), /var/run is a symlink to /run.

\* requires the "cri" containerd plugin to be enabled

**Comment by afbjorklund** [comment]
See this issue, for the `nerdctl` installation:

* https://github.com/kubernetes/minikube/issues/13252

It only needs the client, not the "nerdctl-full".

**Comment by afbjorklund** [comment]
This is the full "cri-o" runtime installation:

bin/crun

bin/conmon

bin/crio
bin/crio-status
bin/pinns
lib/systemd/system/crio.service
lib/systemd/system/crio-wipe.service

bin/podman
lib/systemd/system/podman.service
lib/systemd/system/podman.socket
