### ISSUE TITLE
Cannot start minikube start --driver=virtualbox

### ISSUE THREAD

**Issue by kerian1** [kubernetes/minikube#15447]
### What Happened?

![error minikube](https://user-images.githubusercontent.com/98924311/205170921-b07c48fe-4c8d-40b7-86d5-405d04d44dd0.png)

pls am new with this and am stock in run minikube getting this error  so i cant proceed

### Attach the log file

![error minikube](https://user-images.githubusercontent.com/98924311/205171265-1cc7a4f3-7c57-4441-a86a-511dfdd6d51d.png)

### Operating System

Windows

### Driver

VirtualBox

**Comment by kerian1** [comment]
> pls i am a newbie in this 
I am just beginning so pls explain for me

**Comment by spowelljr** [comment]
Hi @kundan2707, did you follow the getting started guide?

https://minikube.sigs.k8s.io/docs/start/

I'd recommend installing and using Docker Desktop if you're new to minikube.

**Comment by kundan2707** [comment]
> Hi @kundan2707, did you follow the getting started guide?
> 
> https://minikube.sigs.k8s.io/docs/start/
> 
> I'd recommend installing and using Docker Desktop if you're new to minikube.

@kerian1  you can follow link as suggested by @spowelljr

**Comment by spowelljr** [comment]
Hi @ , we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
