### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fuattirtar** [kubernetes/minikube#15637]
### What Happened?

Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_addons_03336b98cd11d8f893b1e8c978458f1d10da8137_0.log  

### Attach the log file

Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_addons_03336b98cd11d8f893b1e8c978458f1d10da8137_0.log  

### Operating System

Ubuntu

### Driver

None

**Comment by fuattirtar** [comment]
$ minikube logs
$ minikube start --alsologtostderr -v=2
$ kubectl config view

**Comment by medyagh** [comment]
hi @fuattirtar the log has not been attached, can you please Drag the file into github text box?

**Comment by spowelljr** [comment]
Hi @fuattirtar, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
