### ISSUE TITLE
create automation to bump the ubuntu base image

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15772]
### What Happened?

we need to create add an automation to do PRs like this https://github.com/kubernetes/minikube/pull/15768/files

we already have a script that does a lot of updating PRs that would need to be updated to include this type of update
here is the path to the script

https://github.com/kubernetes/minikube/tree/master/hack/update

**Comment by salasberryfin** [comment]
Hi @medyagh,

I'd like to work on this but I may need some extra help.

What I understand is that this automation should get the latest version from the registry and modify the Dockerfile.

This is my first contribution to minikube and I'd appreciate some help navigating the code base. Should this be integrated into one of the existing automations? Is it specific for the kicbase Dockerfile or does it need to be extensible to other similar cases?

Thanks!

/assign

**Comment by spowelljr** [comment]
@salasberryfin It should get the latest `focal` tag (https://hub.docker.com/_/ubuntu/tags?page=1&name=focal) and update the kicbase Dockerfile.

Here's an example of what the change should look like:

https://github.com/kubernetes/minikube/pull/15768/files#diff-7b41e58d929bdb16083790c3500e6f9aa19efb0976e6b65609b60396cd9ceeebL40

It can be specific to the kicbase Dockerfile.

If you look at `hack/update` you'll see a bunch of scripts that do updating related logic, and if you look in `.github/workflows` you can see some crons to run the update scripts.

The hardest part is going to find somewhere we can curl to get the latest Ubuntu focal version, after that everything else has already been done and can copy existing logic.

**Comment by salasberryfin** [comment]
Thanks for the info @spowelljr. I will take a look at this!

**Comment by salasberryfin** [comment]
Hi @spowelljr,

I was taking a look at the Docker Hub API, which is probably the easiest solution to get the latest `focal` tag and I was wondering, if this is supposed to automatically retrieve and update to the latest version, couldn't it point directly to `ubuntu:focal` instead of the specific tag name? Would this cause any unexpected issue?

**Comment by spowelljr** [comment]
@salasberryfin There are two reasons we don't use `ubuntu:focal`. The first reason is a convenience/security issue, for example, if `ubuntu:focal-20230126` ended up having a critical security vulnerability we could easily check the Dockerfile and see if we're on that version or not. If instead we used `ubuntu:focal` we'd have to do some work to check what version of Ubuntu the image was last build with. While we can get that information the convenience of just checking the Dockerfile is preferred. The second reason is an incompatibility could arise in an Ubuntu update which could cause the image to build with minikube. For example, if we're using `ubuntu:focal` and someone wanted to update the version of the tool, but the latest version of `Ubuntu` has an incompatibility we're stuck not being able to update the tool, but if we pin the version of Ubuntu then we could just hold back the update until the issue is resolved and other things can be updated without issue.

**Comment by salasberryfin** [comment]
Makes sense. Thanks for the detailed explanation!

I'll try to find a way to parse the response from the Docker Hub API and extract the latest focal version.

**Comment by salasberryfin** [comment]
This is now solved with PR #16409. Should it had been closed after merging?
