### ISSUE TITLE
KubeVirt Addon broken due to missing curl in Pod

### ISSUE THREAD

**Issue by cwilkers** [kubernetes/minikube#15918]
### What Happened?

Tried `minikube start --addons=kubevirt`

No kubevirt resources are created.

I will attempt a fix at https://github.com/kubernetes/minikube/blob/master/deploy/addons/kubevirt/pod.yaml.tmpl

### Attach the log file

Not using the standard logging, found problem in:

kubectl -n kube-system logs kubevirt-install-manager

/kubevirt-scripts/install.sh: line 3: curl: command not found
Installing KubeVirt version: 
/kubevirt-scripts/install.sh: line 6: curl: command not found
error: the path "/manifests/kubevirt-operator.yaml" does not exist
error: resource mapping not found for name: "kubevirt" namespace: "kubevirt" from "STDIN": no matches for kind "KubeVirt" in version "kubevirt.io/v1"
ensure CRDs are installed first

### Operating System

Redhat/Fedora

### Driver

KVM2

**Comment by timway** [comment]
The `curl` command was in the prior container image as seen:

```bash
$ podman run --rm -it --entrypoint sh docker.io/bitnami/kubectl:1.17@sha256:de642e973d3d0ef60e4d0a1f92286a9fdae245535c5990d4762bbe86fcf95887
$ curl --version
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
```

The `curl` command **is not** in the prior container image as seen:

```bash
$ podman run --rm -it --entrypoint sh docker.io/bitnami/kubectl:1.24.7@sha256:195f5a7a40cfb06e308701ae850abfa436d23baf9d39c0282298e540c9d07863
$ curl --version
sh: 1: curl: not found
```

This is caused by #15310 but it may be resolved elsewhere to keep the newer image. The default user is UID 1001 and the image does not contain `sudo` so it does not seem adjusting the `install.sh` blurb initially linked would allow us to get `curl`. I'd appreciate some advice on the best place to get `curl` in this image in a sustainable way.

I was impacted by this and did some of this sleuthing trying to use KubeVirt on Minikube on KVM. In the meantime I'm running:

```bash
$ minikube version
minikube version: v1.28.0
commit: 986b1ebd987211ed16f8cc10aed7d2c42fc8392f
```

This enables me to get some bits moving with KubeVirt but I'd like to be tracking the latest release.

**Comment by adilwiser** [comment]
This is closed by the bot and not a maintainer. But I believe in its usefulness due to several discussion and [kubevirt's official quickstart](https://github.com/kubevirt/kubevirt.github.io/blob/0532d8fa1ef7ee31ba38ce7c91bdf335ddec4ae0/pages/quickstart_minikube.md?plain=1#L78) mentions the issue, hence [I fixed it in this PR](https://github.com/kubernetes/minikube/pull/22557). I have tested it end to end on Fedora 43 and it works :) 
I hope it helps, happy to address any changes or give it a direction that sounds feasible by the maintainers. Thanks!
