### ISSUE TITLE
 Docker sunsets Free Team Organizations affecting Kicbase

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#16054]
Following the same issue as kind https://github.com/kubernetes-sigs/kind/issues/3124
Just got the notice, we have Until April 14th to resolve this. 

here is a list of organizations we use in build and release of minikube, even though minikube uses docker hub as a fail over, it is essential for users not having access to gcr.io

- kicbase/stable (production images)
- kicbase/echo-server (production image used on tutorial on website)
- kicbase/build (images used in CI)

it seems like we could apply for open source exception here I will apply today
https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf

**Comment by medyagh** [comment]
I just applied for the open source exceptions in docker hub, hopefully we will get it before its shut down
<img width="454" alt="Screenshot 2023-03-15 at 11 22 42 AM" src="https://user-images.githubusercontent.com/4564227/225406400-21ed4324-2707-4cc3-84c2-e80601925d9c.png">

**Comment by afbjorklund** [comment]
If registry.k8s.io suddently started to allow sigs (like kind or minikube), that would the preferred option

**Comment by BenTheElder** [comment]
An update was posted today https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/

> If registry.k8s.io suddently started to allow sigs (like kind or minikube), that would the preferred option

always_has.jpg 🙃 

Since even before registry.k8s.io, k8s.gcr.io was accepting subproject images.
To publish images there's a process here: https://github.com/kubernetes/k8s.io/tree/main/registry.k8s.io

Things are slightly in flux as k8s.gcr.io gets wound down a bit more, but it should generally still work.

Worth noting: 
- You're required to push to a staging location first and then file a PR to promote images, so it's not fully automated in that the PR to k8s.io has to be filed to specify digests to promote to tags. NO ONE has direct push access to any of the production infrastructure, a robot will copy in images by digest from staging following path scoped PRs merging. so you can have images like `registry.k8s.io/minikube/foo:bar`
- Mutable tags are not permitted. The robots will not allow it.
- Paying for this is "fun" $$$$ and the project may have to evolve its stance. Currently we hope to get huge cost effectiveness gains for the images we already host by ensuring AWS traffic => AWS (more on this at https://registry.k8s.io) and also to alleviate pressure on the project's oversubscribed GCP funding by not-AWS not-GCP => AWS largely.

**Comment by afbjorklund** [comment]
The primary location is still `gcr.io/k8s-minikube/kicbase`, so it was mostly for the secret `docker.io` fallback.

The "echo-server" should probably be moved to a different location, but it is still fighting with the "agnhost"...
* https://github.com/kubernetes/minikube/issues/15650

The other affected images for minikube are `docker.io/kubernetesui/dashboard` and `.../metrics-scraper`
* https://github.com/kubernetes/dashboard/issues/7598

I _think_ most minikube installations are using preload from GCS, but we changed it for the "none" driver users.

**Comment by afbjorklund** [comment]
https://hub.docker.com/u/kicbase

kicbase
Community Organization
kicbase
https://minikube.sigs.k8s.io/
Joined April 10, 2020
