### ISSUE TITLE
0Warning: Failed to create the file minikube-linux-amd64: Permission denied

### ISSUE THREAD

**Issue by ganeshdandagala1** [kubernetes/minikube#16154]

**Comment by spowelljr** [comment]
Hi @ganeshdandagala1, it sounds like you're trying to download the binary to a location your don't have access to, make sure you're downloading it to a folder you own.

**Comment by spowelljr** [comment]
Hi @ganeshdandagala1, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
