### ISSUE TITLE
not able to start minikube

### ISSUE THREAD

**Issue by ankits8840** [kubernetes/minikube#16160]
### What Happened?

/tmp/minikube_logs_560582b931ac7137f924abcbfc9044de33fb8594_0.log

### Attach the log file

/tmp/minikube_logs_560582b931ac7137f924abcbfc9044de33fb8594_0.log

### Operating System

Ubuntu

### Driver

Docker

**Comment by kundan2707** [comment]
@ankits8840  no log file is present in issue

**Comment by spowelljr** [comment]
Hi @ankits8840, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
