### ISSUE TITLE
changes between 1.28 and 1.29+ lead to decrease in docker/daemon.json options (aka daemon.json is being always overwritten)

### ISSUE THREAD

**Issue by dmpe** [kubernetes/minikube#16323]
### What Happened?

Hi, 

We are using Centos 7 VM where we install minikube using something like this:

```
minikube start --cni="calico" \
                      --container-runtime="docker" \
                      --driver=none \
                      --delete-on-failure=true
```

This works perfectly fine, both using 1.28 as well as 1.29+ minikube releases. However, while in 1.28 `/etc/docker/daemon.json` was not replaced during the installation, in 1.29+ it is being replaced via this function 
https://github.com/kubernetes/minikube/blob/v1.29.0/pkg/minikube/cruntime/docker.go#L524. 
See for 1.28 here: https://github.com/kubernetes/minikube/blob/v1.28.0/pkg/minikube/cruntime/docker.go#L511

Well, of course, when we install minikube & docker and use `none` driver, we already setup docker in a way which allows us to use such configuration. :) :) 

In fact, we already set CGroupDriver to `systemd`, and not just that. We also customize many other settings in to make it work in a strictly regulated environment in our company, resulting into file be more like this:

```
{
  "data-root": "/srv/docker",
  "storage-driver": "overlay2",
  "bip": "10.xx.xx.xx/24",
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  }
}
```

Now, we are stuck on using minikube 1.28 because with 1.29 the minikube will replace daemon.json file which -- even though makes minikube start properly ! -- it is not usable for our purposes in the company. Reason being "docker data" (images, etc.) are stored in `/var/lib/docker` and `bip` with logging options cannot adjusted either, making it hard work in our environment.

What would be your suggestion here? Should we maybe add a new option which will disable such overwrite of a file (e.g. `minikube start --disable-daemon-overwrite=true`, with a default being `false` (current behavior). Or maybe fix it in a different way - e.g. check if driver is `systemd`, and if it is then do nothing, while it is not, attempt to change it. 

cc @prezha @afbjorklund

Thank you for any suggestions, or help. 

### Attach the log file

Minikube runs perfectly fine, it is just that daemon.json options for docker are no longer configurable.

### Operating System

Other

### Driver

None

**Comment by afbjorklund** [comment]
It got broken here: e59d6217a82ceccec53fc064e831ab4894b4ac26 (when the forceSystemd was changed)

**Comment by dmpe** [comment]
Great, thanks for a quick look and confirmation.

**Comment by willsu** [comment]
Is there any known workaround to this issue? My minikube is failing to start due to the docker service failing startup. To fix my docker service startup issue, I need to change the 'storage-driver' to 'vfs', which I can test in the Minikube container itself and it works (by modifying the /etc/docker/daemon.json). Due to this issue, the 'daemon.json' is regenerated everytime I run 'minikube start --docker-opt storage-driver=vfs' and the resulting storage driver is 'overlay2', which causes. Since the '--docker-opt' values seem to be discarded, is there any way to set the 'storage-driver' docker daemon in the minikube container?

**Comment by willsu** [comment]
Thanks for the follow-up @dmpe. I see that the fix has been lingering for quite a long time, but has not been merged. I hope that the minikube team will fix ''--docker-opt" and other options that affect the 'daemon.json' file, because it's very misleading to document it as an option. Maybe the team can change the documentation to more clearly document that current state, because these issues can be very hard to diagnose for folks who don't (want to) know the internals of Minikube.

**Comment by lunarfs** [comment]
Hi, I was also facing this issue, my workaround  was to
1) create /etc/docker/alternate-daemon.json" that had the config i like
2) create /etc/systemd/system/docker.service.d/docker.conf with the following content
` 
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --config-file=/etc/docker/alternate-daemon.json 
TimeoutStartSec=5min
`
3) reload the systemctl
`systemctl daemon-reload`
4) `sudo systemctl restart docker`
and my docker is running with my prefered config

**Comment by dmpe** [comment]
Thanks, that's creative. We have on the other hand taken the opportunity to migrate to k3s. 
Granted minikube and k3s are different projects with different objectives. However, we have already used minikube cluster much more like a "stable" cluster. And k3s fit the purpose even better.
