### ISSUE TITLE
Ingress enable issue

### ISSUE THREAD

**Issue by prerakmathur05** [kubernetes/minikube#16431]
### What Happened?

Command 
-minikube addons enable ingress 
is failing
[logs.txt](https://github.com/kubernetes/minikube/files/11391238/logs.txt)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/11391240/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Your error is:
```
Failed to pull image" err="rpc error: code = Unknown desc = Error response from daemon: Get \"https://registry.k8s.io/v2/\": x509: certificate signed by unknown authority" image="registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794@sha256:01d181618f270f2a96c04006f33b2699ad3ccb02da48d0f89b22abce084b292f
```

It looks like your cert is expired, have you created this minikube cluster a long time ago? If so you could try `minikube stop` and then `minikube start` and the certs should renew.

**Comment by spowelljr** [comment]
Hi @prerakmathur05, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
