### ISSUE TITLE
 Minikube connection error while installing on wsl2 ubuntu on windows10

### ISSUE THREAD

**Issue by venkatjk86** [kubernetes/minikube#16874]
### What Happened?

I'm trying to install minikube locally in  WSL2 system(Ubuntu) that runs on Windows 10. I had followed the project document that listed several steps and I had followed them in a sequential manner. I encountered an connection issue which is E0713 06:00:46.618940    5887 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused. Any ideas and solution(s) would be highly appreciated.

### Attach the log file

[minikubconctnerr.txt](https://github.com/kubernetes/minikube/files/12035969/minikubconctnerr.txt)

### Operating System

None

### Driver

None

**Comment by spowelljr** [comment]
Looks like you're getting a cert issue `[certs] certificate apiserver-kubelet-client not signed by CA certificate ca: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "minikubeCA"`.

If you delete your minikube home folder with `minikube delete --all --purge` and then try starting it again do you get any difference?
