### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by obonudoh44** [kubernetes/minikube#17111]
### What Happened?

I am getting this error when i run minikube start "- /var/folders/44/4x1_qvbx68vd63bnqr55bjf40000gn/T/minikube_logs_316a9d0e8553f39aafe351ec2c78118489d5709a_0.log"

### Attach the log file

❌  Exiting due to MK_USAGE: Failed to create file: open logs.txt: read-only file system

- /var/folders/44/4x1_qvbx68vd63bnqr55bjf40000gn/T/minikube_logs_316a9d0e8553f39aafe351ec2c78118489d5709a_0.log

### Operating System

macOS (Default)

### Driver

None

**Comment by rmsilva1973** [comment]
What exactly did you type to start minikube? It's not clear.
Also: if a log file with the path provided was generated, can you attach it to the issue?

**Comment by spowelljr** [comment]
Hi @obonudoh44, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
