### ISSUE TITLE
While getting a service, below message appears

### ISSUE THREAD

**Issue by sandeepbelavalekar** [kubernetes/minikube#17141]
### What Happened?

|-----------|-----------------------|-------------|---------------------------|
| NAMESPACE |         NAME          | TARGET PORT |            URL            |
|-----------|-----------------------|-------------|---------------------------|
| default   | mongo-express-service |             | http://172.31.89.44:30000 |
|-----------|-----------------------|-------------|---------------------------|
* Opening service default/mongo-express-service in default browser...
* 
X open url failed: http://172.31.89.44:30000: exec: "xdg-open": executable file not found in $PATH
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

### Attach the log file

X open url failed: http://172.31.89.44:30000: exec: "xdg-open": executable file not found in $PATH

Getting this error message.

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
The `xdg-open` command should come with your desktop installation

**Comment by spowelljr** [comment]
Hi @sandeepbelavalekar, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
