### ISSUE TITLE
Error starting Minikube, looks like issued podman command has problem (wrong quotes)

### ISSUE THREAD

**Issue by xyzzy31415926** [kubernetes/minikube#17154]
### What Happened?

in the log:

I0829 22:00:49.753796 3190103 cli_runner.go:164] Run: podman network inspect minikube --format "{{range .}}{{if eq .Driver "bridge"}}{{(index .Subnets 0).Subnet}},{{(index .Subnets 0).Gateway}}{{end}}{{end}}"
W0829 22:00:49.948031 3190103 cli_runner.go:211] podman network inspect minikube --format "{{range .}}{{if eq .Driver "bridge"}}{{(index .Subnets 0).Subnet}},{{(index .Subnets 0).Gateway}}{{end}}{{end}}" returned with exit code 125

invoked from command prompt shows command interpreted wrongly:

> podman network inspect minikube --format "{{range .}}{{if eq .Driver "bridge"}}{{(index .Subnets 0).Subnet}},{{(index .Subnets 0).Gateway}}{{end}}{{end}}"
Error: template: inspect:1: function "bridge" not defined

Same command, double quotes replaced to single quotes - command works fine:
> podman network inspect minikube --format '{{range .}}{{if eq .Driver "bridge"}}{{(index .Subnets 0).Subnet}},{{(index .Subnets 0).Gateway}}{{end}}{{end}}'
192.168.58.0/24,192.168.58.1

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/12470013/log.txt)

### Operating System

Redhat/Fedora

### Driver

Podman

**Comment by rmsilva1973** [comment]
Having the same issue with Ubuntu 22.04 and Podman. Even tough the log shows that double quote surrounding the format, the command is running correctly. It gets error 125 because the network doesn't existe yet. If you look down the log you'll see it gets created. The real issue seems to be related to the fact that podman creates a CNI with version 1.0.0 by default:

![image](https://github.com/kubernetes/minikube/assets/28487379/22956373-c282-43ae-892c-29c597f4f23f)

And it has been broken according to [Ubuntu 22.04.1 LTS libpod (package podman 3.4.4+ds1-1ubuntu1.22.04.1): broken network functionality for CNI plugins](https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394)

This link suggests - at some point - this to fix it:

curl -O http://archive.ubuntu.com/ubuntu/pool/universe/g/golang-github-containernetworking-plugins/containernetworking-plugins_1.1.1+ds1-1_amd64.deb
dpkg -i containernetworking-plugins_1.1.1+ds1-1_amd64.deb

Doing so allowed me to go a little further. However it fails later with:

🤦  StartHost failed, but will try again: creating host: create: creating: create kic node: container name "minikube": log: 2023-09-03T00:59:02.339043000-03:00 + grep -qw cpu /sys/fs/cgroup/cgroup.controllers
2023-09-03T00:59:02.339923000-03:00 + echo 'ERROR: UserNS: cpu controller needs to be delegated'
2023-09-03T00:59:02.340076000-03:00 ERROR: UserNS: cpu controller needs to be delegated
2023-09-03T00:59:02.340217000-03:00 + exit 1: container exited unexpectedly

Will look further into that some other day.

**Comment by afbjorklund** [comment]
The log does not always reflect the quoting used, it depends on what command was used to log.

**Comment by rmsilva1973** [comment]
This link [cgroups v2: cgroup controllers not delegated to non-privileged users on CentOS Stream (8)](https://unix.stackexchange.com/questions/624428/cgroups-v2-cgroup-controllers-not-delegated-to-non-privileged-users-on-centos-s) seems to provide a solution for Centos (8). But the last comment states it didn't work with Ubuntu 22.04 (which is what I have). I haven't tried myself. Don't know about RH/Fedora.

**Comment by afbjorklund** [comment]
Ubuntu uses an older version of podman (3.4), compared with Fedora and CentOS (4.6)

**Comment by rmsilva1973** [comment]
> Ubuntu uses an older version of podman (3.4), compared with Fedora and CentOS (4.6)

Ok. But I don't see how this is related to the problem. In fact - like I mentioned - eventually the podman network inspect succeeds (after the CNI is created - I assume). Here's an excerpt from the issue author log that shows that:

**I0829 21:58:41.450024 3190103 cli_runner.go:164] Run: podman network inspect podman --format "{{range .}}{{if eq .Driver "bridge"}}{{(index .Subnets 0).Subnet}},{{(index .Subnets 0).Gateway}}{{end}}{{end}}"
I0829 21:58:41.642994 3190103 network.go:209] using free private subnet 192.168.49.0/24: &{IP:192.168.49.0 Netmask:255.255.255.0 Prefix:24 CIDR:192.168.49.0/24 Gateway:192.168.49.1 ClientMin:192.168.49.2 ClientMax:192.168.49.254 Broadcast:192.168.49.255 IsPrivate:true Interface:{IfaceName: IfaceIPv4: IfaceMTU:0 IfaceMAC:} reservation:0xc0021fa570}**

If you see my message, it seems related to an issue with cgroups CPU delegation to user namespace. I'm not fluent in cgroups stuff but that SEEMS to be problem. When I tried running rootless docker, I got the same message. Switch to rootfull docker and it worked.

**Comment by rmsilva1973** [comment]
It doesn't seem to be an issue with minikube. So, I don't know if there's an appropriate label. I suppose I can slap the support label for now. It can be changed later..

**Comment by rmsilva1973** [comment]
So, I found out how to make it work (under WSL/Ubuntu22.04 at least). I had to:

- Disable cgroup v1 following this instruction: https://stackoverflow.com/questions/73021599/how-to-enable-cgroup-v2-in-wsl2  (if not running under WSL, you have to pass the same pareter to the kernel tweaking grub passing the followin parameter to the kernel: unified_cgroup_hierarchy=1

- After doing that (observer the fix for docker.socket on the stackoverflow post if you also use docker) I noticed that /sys/fs/cgroup/user.slice/user-$(id -u)/cgroup.subtree_control still didn't have the CPU controller enabled. That's the reason podman isn't able to delegate to the cgroup where it would start a container. In order to enable it, since I'm using systemd, I had to tweak systemd files. Luckily, since I'm not too systemd savvy - I found this link which despite a comment on the good answer did work for me: https://unix.stackexchange.com/questions/624428/cgroups-v2-cgroup-controllers-not-delegated-to-non-privileged-users-on-centos-s

And... Voilá...

./out/minikube start --driver=podman --container-runtime=cri-o
😄  minikube v1.31.2 on Ubuntu 22.04 (amd64)
    ▪ MINIKUBE_ROOTLESS=true
✨  Using the podman driver based on user configuration
📌  Using rootless Podman driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E0904 22:38:09.235355   40732 cache.go:190] Error downloading kic artifacts:  not yet implemented, see issue #8426
🔥  Creating podman container (CPUs=2, Memory=2200MB) ...
🌐  Found network options:
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.49.0/24,192.168.39.0/24
❗  This container is having trouble accessing https://registry.k8s.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🎁  Preparing Kubernetes v1.28.1 on CRI-O 1.24.6 ...
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.49.0/24,192.168.39.0/24
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

Minikube running with podman and cri-o on WSL/Ubuntu-22.04 after bumping on the same initial issue the author had.

Phew... That wasn't easy... 🫠 But at least I got it. ❤️

Now... Unless the issue author comes back that's as far as I am able to go (it was fun and I learned a lot, however...)

**Comment by rmsilva1973** [comment]
@xyzzy31415926 this is as far as I'm able to go without a reply from you.

**Comment by spowelljr** [comment]
@rmsilva1973 This information could be useful, would you be willing to add a FAQ block to the website and/or minikube help text if the failure output is something you can detect?

**Comment by spowelljr** [comment]
Hi @rmsilva1973, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by a1exus** [comment]
```
toor@suey:~$ cat /etc/systemd/system/user@.service.d/delegate.conf 
[Service]
Delegate=cpu cpuset io memory pids
toor@suey:~$ sudo systemctl daemon-reload
[sudo] password for toor: 
toor@suey:~$ echo $?
0
toor@suey:~$ 
```

and yet still

> ERROR: UserNS: memory controller needs to be delegated
