### ISSUE TITLE
На M1 процессоре не запускается minikube

### ISSUE THREAD

**Issue by Mamontosik** [kubernetes/minikube#17237]
### Что произошло?

После запуска команды minikube start --driver=docker выводится ошибка

You are trying to run the amd64 binary on an M1 system.                                               │
│    Please consider running the darwin/arm64 binary instead.                                              │
│    Download at https://github.com/kubernetes/minikube/releases/download/v1.31.2/minikube-darwin-arm64

💢  Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "parallels" driver, which is incompatible with requested "docker" driver.
💡  Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=parallels'

### Приложите логи

[log.txt](https://github.com/kubernetes/minikube/files/12586771/log.txt)

### Операционная система

macOS (Default)

### Драйвер

Docker

**Comment by caerulescens** [comment]
@Mamontosik 

There's a few things going on with the messages you're receiving, and I will explain in order; see below:
1. The first command, `minikube start --driver=docker`, attempts to start a `minikube` cluster; this command runs into an issue, which I explain below in (4).

2. The first error you're receiving indicates that you have installed the incorrect `minikube` binary for your computer processor's architecture type; your laptop has an Apple M1 processor which uses `arm64` for its processor's instruction set, which is also known as `aarch64`. You installed the `minikube` binary for `64-bit` `x86` architecture processors. When Apple switched from purchasing Intel processors to designing their own chips, like your [M-Series](https://ru.wikipedia.org/wiki/Apple_Silicon#Apple_M), their processor's architecture type changed from 64-bit `x86` (`amd64`) to 64-bit `arm` (`arm64`). Apple computers with M series processors need to run the `darwin/arm64` `minikube` binary to be able to run on M-series processors, which is what the message is saying. This architecture type change has been a significant challenge for the FOSS community, but most compatibility issues have been fixed such that you shouldn't notice a difference between `arm64` and `amd64` in daily software development. 
```
You are trying to run the amd64 binary on an M1 system. │
│ Please consider running the darwin/arm64 binary instead. │
│ Download at https://github.com/kubernetes/minikube/releases/download/v1.31.2/minikube-darwin-arm64
```

3. It looks like you installed the `amd64` binary manually instead of using a package manager; if that is the case, then you should manage your `minikube` installation using a package manager, which will handles selecting the correct architecture type for your processor during installation or will inform you about missing architecture support for a specific `minikube` binary. Using a package manager will prevent this compatibility issue for you going forward on M-series Apple computers, and there are two commonly used package managers for `macOS`: [HomeBrew](https://ru.wikipedia.org/wiki/Homebrew_(%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80_%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2)) and [MacPorts](https://ru.wikipedia.org/wiki/MacPorts). I have a `m2` processor, and I use `brew` to manage my `minikube` installations, and I have not had any installation issues.

4. You are receiving this error because you are trying to run a minikube cluster that's named "minikube" when a cluster named "minikube" already exists; "minikube" is the default cluster profile when `--profile`/`-p` flags are not selected. It looks like you started a minikube cluster using the `parallels` driver, stopped the cluster using the `parallels` driver, and then you started another minikube cluster with the same name that's using the `docker` driver. This causes the error because there's a driver configuration mismatch for the cluster (of the same name) that you're trying to start. You can name the cluster at start like this `minikube start --profile=<name>`, and you then refer to the cluster by name in each command like `minikube tunnel -p <name>` or `minikube delete -p <name>`. I recommend fixing this problem by listing your cluster profiles using `minikube profile list`, and then deleting any cluster(s) that had a bugged initialization; this is what the message is saying as well. You delete each cluster using `minikube delete -p <name>`; `minikube delete` will have the same effect as `minikube delete -p minikube` because the default profile name is "minikube".
```
💢 Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "parallels" driver, which is incompatible with requested "docker" driver.
💡 Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=parallels'
```

5. Lastly, I recommend using the `qemu2` driver right now for M-Series chips using `--network=socket_vmnet` because `minikube tunnel` has an open issue with the `parallels` driver that needs to be investigated: see https://github.com/kubernetes/minikube/issues/11229. You will need to install [qemu](https://formulae.brew.sh/formula/qemu) and [socket_vmnet](https://formulae.brew.sh/formula/socket_vmnet). I have verified that `minikube start --driver=qemu2 --network=socket_vmnet` and `minikube tunnel` work as expected on my `m2` processor with the latest `macOS`. You will probably not want to use `parallels` as your driver because support for it right now is "best effort". 

---

@snidarian Would you be able to translate this into Russian to @Mamontosik for me? I think he may have figured it out, as this is from September 2023, but I think it could be useful anyhow as search engines will index this thread, and it relates to a common issues that all M-series `macOS` `minikube` users are having right now.

**Comment by caerulescens** [comment]
@afbjorklund Is the information above in (5) up to date as far as you know?

**Comment by caerulescens** [comment]
This is not an issue with `minikube`; this issue can be closed. 

/close
