### ISSUE TITLE
Exiting due to HOST_HOME_MKDIR: Error creating minikube directory: mkdir /home/Newuser: permission denied

### ISSUE THREAD

**Issue by Pankaj8821** [kubernetes/minikube#17289]
### What Happened?

Exiting due to HOST_HOME_MKDIR: Error creating minikube directory: mkdir /home/Newuser: permission denied

### Attach the log file

![image](https://github.com/kubernetes/minikube/assets/131384457/a1e25cb0-1eb9-4b18-9ee6-e744e97f95cf)

### Operating System

Ubuntu

### Driver

Docker

**Comment by termdew** [comment]
minikube tries do create a folder named **.minikube** in your home folder.
It seems that the user that runs minikube in your environment has no write access to /home/Newuser.

Which user is running minikube in your environment?

**Comment by spowelljr** [comment]
If you run `whoami` what do you get? If you get `Newuser` it sound like your home directory is not setup correctly.

**Comment by ps-spark** [comment]
Hi Guys,

This problem still exists and very annoying. Please reopen it!

- OS: Ubuntu 22.04
- minikube: 1.33.1 (downloaded from the website and installed with dpkg following the instructions)
- minikube will be installed automatically to: /usr/bin/minikube 

Trying to start as a normal user:
`
minikube start -v=8`

❌  Exiting due to HOST_HOME_MKDIR: Error creating minikube directory: mkdir /opt/minikube: permission denied

[minikube.INFO.log](https://github.com/user-attachments/files/16102341/minikube.INFO.log)

[minikube.WARNING.log](https://github.com/user-attachments/files/16102342/minikube.WARNING.log)

Why is it trying to use the /opt/minikube dir and how could I change this configuration?
