### ISSUE TITLE
add support for adding multiple control plane for multi node

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#17685]
### What Happened?

https://github.com/kubernetes/minikube/pull/17681#pullrequestreview-1756035264

### Attach the log file

n/a

### Operating System

None

### Driver

None

**Comment by prezha** [comment]
turns out that it'd be _easy_ to "just add" yet another control-plane node to an existing cluster, whereas it's a bit _trickier_ to fully utilise a multi-control-plane (ie, ha) cluster, requiring, amongst other things, a load-balancer for multiple apiservers and quorum for multiple etcd nodes, etc.

also, "upgrading" a non-ha cluster to one that'd become a ha cluster would currently require resetting the cluster, as  the kubeadm config would have to change as well, therefore i've created a more general issue #17908 & pr #17909 (containing more details) to address adding native support for creating and managing ha clusters in minikube
