### ISSUE TITLE
The connection to the server 10.0.2.15:6443 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by siddique670** [kubernetes/minikube#17859]
### What Happened?

As per attached below screnshot getting the "connection refused" error.

![connection_refuse](https://github.com/kubernetes/minikube/assets/97210868/6d7ec8da-702f-4d36-8773-575c11926828)

## I configured the master node on ubuntu it has installed on VirtualBox -07. As per below ubuntu version.

root@master:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

## Docker service is also running fine as per the below screenshot. ##

![image](https://github.com/kubernetes/minikube/assets/97210868/c0f2f97d-acd7-462c-8022-528346256112)

## Container also running fine.

![image](https://github.com/kubernetes/minikube/assets/97210868/232ee0f2-e11d-441f-9e82-9843b267f8d5)

## Swap is also i did off.
![image](https://github.com/kubernetes/minikube/assets/97210868/a79a3321-db07-4f76-918b-a149e1f58ea1)

## IP netsed.
![image](https://github.com/kubernetes/minikube/assets/97210868/cb4cd9e7-edef-4323-a298-1379e6f10807)

## systemctl status kubelet.service
![image](https://github.com/kubernetes/minikube/assets/97210868/001287ed-6fce-43e7-871d-e85b76bebdc4)

## kubectl config view
![image](https://github.com/kubernetes/minikube/assets/97210868/90d703c6-1917-44c1-8368-266614a5ee89)

##  sudo systemctl restart kubelet.service
![image](https://github.com/kubernetes/minikube/assets/97210868/ec42fa1b-ce4f-4806-a791-1893a40deb79)

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by devopsncloud** [comment]
Me too facing the same issue. When we restart it's fine but after a while it's repeating the same.

**Comment by OleksandrTimoshenko** [comment]
I faced the same issue, with the same symptoms, as described in this topic.
I used this [Vagrantfile](https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/kubeadm-clusters/virtualbox/Vagrantfile)
In my case, the problem was with containerd settings.
I regenerate the `/etc/containerd/config.toml` file, and it fixes the problem.
`containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1`
also if you use _Systemd cgroup driver_ you need to do 
`sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml` 
after that, you can restart the containerd service, and it should help

**Comment by pythonkid2** [comment]
@siddique670 Have u found the solution ?

**Comment by siddique670** [comment]
@pythonkid2 Issue is still there, it's need to add some rules in ubuntu firewall with port or else?

**Comment by gu1gzz** [comment]
Same issue, I add the right rules on UFW, but I think it's not the root cause because after reboot the cluster is ok and after sometimes the error appears, and I need to restart the controlplane to "resolve" the problem.
