### ISSUE TITLE
Starting more than one cluster fails on linux/aarch64

### ISSUE THREAD

**Issue by nirs** [kubernetes/minikube#18240]
### What Happened?

With #18239 we can start one cluster on linux/aarch64, but starting the second cluster fails:

> virError(Code=55, Domain=24, Message='Requested operation is not
> valid: Setting different SELinux label on /usr/share/AAVMF/AAVMF_VARS.fd
> which is already in use

Example commands:

    minikube start --driver kvm2 -p c1 # works
    minikube start --driver kvm2 -p c2 # fails

The issue is using:
    
    <nvram>/usr/share/AAVMF/AAVMF_VARS.fd</nvram>

This is a template used by libvirt to create a per-vm image. Selinux saved us
preventing sharing the nvram image in 2 vms.

To reproduce install [Ashai Linux Fedora remix](https://asahilinux.org/) on a MacBook,
get and build #18239 and try to start 2 clusters.

### Attach the log file

Not relevant at this point.

### Operating System

Redhat/Fedora

### Driver

KVM2

**Comment by afbjorklund** [comment]
Added for reasons unknown.

* 58754c910c2e2c9786928beafef073057beb95aa

Adding firmware for UEFI was needed, but this change looks unrelated.

**Comment by afbjorklund** [comment]
The "libvirt" group is what I meant (similar to the "docker" group)

The alternative would be to run in session mode rather than system mode, but the problem is networking...

The workaround for the old drivers (like docker and qemu), is to use port-forwarding over the ssh (admin) port.
Newer drivers use some solution like gvproxy, to allow user networking to allocate IP, but not in minikube yet.

It's not really a problem to be solved, but more of a design decision. Also, libvirt wasn't very portable (mac/win)
