### ISSUE TITLE
minikube start --driver=none   Not working

### ISSUE THREAD

**Issue by dharminfadia** [kubernetes/minikube#18891]
### What Happened?

I have install minikube on centOS 8 and Docker version is 26 I am starting my minikube with command is minikube start --driver=none giving error kindly help me on this

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/15319779/logs.txt)

### Operating System

Other

### Driver

None

**Comment by spowelljr** [comment]
Hi @dharminfadia, I'm seeing the following error in your logs
```
time="2024-05-15T15:36:51+05:30" level=fatal msg="connect: connect endpoint 'unix:///var/run/cri-dockerd.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded"
```

Do you have a cri-dockerd.socket and cri-dockerd.service systemd unit files setup? Seems like the socket may not exist?

**Comment by spowelljr** [comment]
Hi @dharminfadia, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
