### ISSUE TITLE
minikube service hello-minikube --url

### ISSUE THREAD

**Issue by bertiniawara** [kubernetes/minikube#18892]
### What Happened?

❌  Exiting due to SVC_UNREACHABLE: service not available: no running pod for service hello-minikube found

### Attach the log file

   - /tmp/minikube_service_009b8dead7f0d23fb7d9a1aecf14844e0d16d32a_0.log 

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @bertiniawara, could you expand on the previous steps you took before getting to this step.

**Comment by spowelljr** [comment]
Hi @bertiniawara, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
