### ISSUE TITLE
RBAC missing "minikube" user permissions

### ISSUE THREAD

**Issue by gugahoi** [kubernetes/minikube#1907]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Minikube version**: `minikube version: v0.21.0`
- **OS**: `macOS`
- **VM Driver**:`virtualbox`
- **ISO version**: `minikube-v0.23.0.iso`

**What happened**:
Minikube starts with RBAC enabled and assigns the `minikube` user in `~/.kube/config` however never creates any permission for it

**What you expected to happen**:
Expected `minikube` user to have any permissions into the cluster, likely admin 

**How to reproduce it**:

```bash
❯ minikube start --extra-config=apiserver.Authorization.Mode=RBAC
❯ kubectl get clusterrolebinding,clusterrole | grep minikube

❯ kubectl get role,rolebinding --all-namespaces | grep minikube

❯ cat ~/.kube/config | grep minikube
    certificate-authority: /Users/XXXXXXX/.minikube/ca.crt
  name: minikube
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
- name: minikube
    client-certificate: /Users/XXXXXXX/.minikube/apiserver.crt
    client-key: /Users/XXXXXXX/.minikube/apiserver.key
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
As you can see no cluster roles, cluster role bindings, roles, role bindings or service accounts exists for user `minikube` however the config file is authenticated as this user with no permissions.

**Comment by Ahmed-Khalifa-Architech** [comment]
I am facing the same problem and can not install with helm charts, even though I bind Tiller to System-Admin, there is not roles at all !

**Comment by gugahoi** [comment]
the solution for me was to assign admin permission to minikube user however I would expect this to be done for me

**Comment by keithjohnhowe** [comment]
That for getting back - I'll look into that


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Gustavo Hoirisch <notifications@github.com> Date: 10/01/2018  03:38  (GMT+00:00) To: kubernetes/minikube <minikube@noreply.github.com> Cc: Keith Howe <keith.j.howe@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [kubernetes/minikube] RBAC missing "minikube" user permissions (#1907) 
the solution for me was to assign admin permission to minikube user however I would expect this to be done for me

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kubernetes/minikube","title":"kubernetes/minikube","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kubernetes/minikube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gugahoi in #1907: the solution for me was to assign admin permission to minikube user however I would expect this to be done for me"}],"action":{"name":"View Issue","url":"https://github.com/kubernetes/minikube/issues/1907#issuecomment-356490777"}}}

**Comment by r2d4** [comment]
If you use the kubeadm bootstrapper with `--bootstrapper=kubeadm`, RBAC is enabled automatically and this is done for you.

That flag will be the default soon, and we don't plan on supporting this for localkube.

**Comment by gugahoi** [comment]
@r2d4 I'm not sure I understand how this helps, I already stated that RBAC was enabled. The problem I had was unrelated to RBAC being enabled or not but to fact the the `minikube` user does not have the correct set of permissions when RBAC is on.

**Comment by r2d4** [comment]
The permissions are created automatically when the `--bootstrapper kubeadm` flag is provided.  For reference, it is done here https://github.com/kubernetes/minikube/blob/master/pkg/minikube/bootstrapper/kubeadm/util.go#L93-L124 

If you enable RBAC in localkube, through the extra-config flag, you will have to continue to add the permissions yourself.
