### ISSUE TITLE
Minikube not starting in Mac M1

### ISSUE THREAD

**Issue by Muhammadali-Akbarov** [kubernetes/minikube#19075]
### What Happened?

![image](https://github.com/kubernetes/minikube/assets/79622590/0415ae19-a6b8-4bbb-a85f-53ab750741fc)

it's freezing 

### Attach the log file

[logs.txt](https://github.com/user-attachments/files/15856284/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @Muhammadali-Akbarov, it looks like Docker isn't running on your machine, could you double check that Docker Desktop is running and then try running the command again.

**Comment by spowelljr** [comment]
Hi @Muhammadali-Akbarov, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
