### ISSUE TITLE
Broken link in minikube/SECURITY.md

### ISSUE THREAD

**Issue by lexbryan** [kubernetes/minikube#19161]
### What Happened?

https://github.com/kubernetes/minikube/blob/master/SECURITY.md?plain=1#L7

[this link][kubernetes-security-announce-rss]

[kubernetes-security-announce-rss]: https://groups.google.com/forum/feed/kubernetes-security-announce/msgs/rss_v2_0.xml?num=50

### Attach the log file

n/a

### Operating System

None

### Driver

None

**Comment by spowelljr** [comment]
Hi @lexbryan, thanks for bringing this to our attention! After investigation I found that this used to be a feature Google supported in Google Groups but they since removed the feature so the instructions from leadership is to simply remove the link. If you are looking for core Kubernetes CVE RSS feed you can use https://kubernetes.io/docs/reference/issues-security/official-cve-feed/feed.xml.
