### ISSUE TITLE
"minikube start" fails with E0908 on MacOS Sierra running on MacBook 12" 2017

### ISSUE THREAD

**Issue by tharpa** [kubernetes/minikube#1931]
I've installed minikube v0.22.0 using brew on my MacBook 12" but `minikube start` fails with E0908:

```$ minikube start
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
E0908 17:17:33.767424    3593 start.go:143] Error starting host: Error creating host: Error executing step: Running precreate checks.
: exit status 126.

 Retrying.
E0908 17:17:33.768637    3593 start.go:149] Error starting host:  Error creating host: Error executing step: Running precreate checks.
: exit status 126
$ 
$ minikube version
minikube version: v0.22.0
```

Any idea what the error code means and how to fix it?

**Comment by r2d4** [comment]
Have you installed either virtualbox or the docker-machine-driver-xhyve? https://github.com/kubernetes/minikube/blob/master/docs/drivers.md

**Comment by tharpa** [comment]
Yes, I've installed the docker-machine-driver-xhyve using brew according to this instructions:

https://github.com/zchee/docker-machine-driver-xhyve#install

```$ brew install docker-machine-driver-xhyve

# docker-machine-driver-xhyve need root owner and uid
$ sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
$ sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve```

**Comment by tharpa** [comment]
It turns out you need to install Virtualbox as well: `brew cask install virtualbox`  After that, the Issue is solved for me.

**Comment by r2d4** [comment]
You don't actually need virtualbox if you're using the xhyve driver.  Most likely, you have an incomplete uninstall of virtualbox, leaving the VboxManage binary.  

See https://github.com/zchee/docker-machine-driver-xhyve/issues/134#issuecomment-243008505
https://github.com/kubernetes/minikube/issues/519

**Comment by tharpa** [comment]
Interesting, that might be the case as I've copied over the whole `/usr/local` from my iMac.  So, you're saying because the VboxManage binary is there, you're detection mechanism is confused?  I was also trying to start with the explicit specification of the xhyve driver with no success.

**Comment by r2d4** [comment]
Yeah, the original issue (which I'll try to track down) was that xhyve would panic if <= virtualbox 5 was installed.  So there was a check added to the xhyve driver to see the version of virtualbox before starting

https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L398-L425

However, if the binary is present, but it can't check the version for some reason - kernel modules are loaded, or the installation is incomplete - the command will exit with a non-zero exit code, so starting xhyve will fail prematurely, since it can't determine the version of virtualbox.

I think there have been some discussions about changing this or not making the check fatal.
