### ISSUE TITLE
Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded

### ISSUE THREAD

**Issue by shafficmuza** [kubernetes/minikube#19325]
### What Happened?

I get error when starting minikube on MacOS with M1. I am using the Qemu driver since the hyperkit is deprecated in can't install hyperkit on my M1 MacOS so i decided to use Qemu driver.

    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://localhost:49383/apis/storage.k8s.io/v1/storageclasses": dial tcp 127.0.0.1:49383: connect: connection refused]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded

### Attach the log file

[logs.txt](https://github.com/user-attachments/files/16373155/logs.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by federico-moya-form3** [comment]
Same error here

😄  minikube v1.33.1 on Darwin 14.5 (arm64)

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://localhost:65236/apis/storage.k8s.io/v1/storageclasses": dial tcp [::1]:65236: connect: connection refused]
E0730 14:14:59.488439   44124 start.go:159] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: non-retryable failure while getting "coredns" deployment scale: Get "https://localhost:65236/apis/apps/v1/namespaces/kube-system/deployments/coredns/scale": dial tcp [::1]:65236: connect: connection refused
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded
