### ISSUE TITLE
Kubectl cannot connect to minikube api-server on windows 10

### ISSUE THREAD

**Issue by fatcat6** [kubernetes/minikube#1943]
**Env**
OS: Windows 10, 64 bit
VM driver: hyperv
Minikube version: v0.22.0
kubectl version: v1.7.0

**Steps**
1. Running "minikube start --kubernetes-version="v1.7.0" --vm-driver="hyperv" --hyperv-virtual-switch="My Virtual Switch" --v=7" does not generate ".\kube\config" file, but VM "minikube" started and running in hyperv. can log in as "root" user. 

2. Manually running kubectl config cluster, context and 
kubectl config set-cluster minikube  --server='https://192.168.1.125' --certificate-authority='C:\Users\xxx\.minikube\certs\ca.pem'

kubectl config set-context minikube --cluster=minikube --user='minikube'
kubectl config use-context minikube

kubectl config set-credentials minikube --client-certificate='C:\Users\xxx\.minikube\certs\cert.pem' --client-key='C:\Users\xxx\.minikube\certs\key.pem'                 

I tried both secure and "--insecure-skip-tls-verify=true", but still not working. 

**Command and Error messages**
PS C:\Users\xxx> kubectl cluster-info          
Kubernetes master is running at https://192.168.1.125

PS C:\Users\xxx> kubectl cluster-info dump                                                                                                  Unable to connect to the server: dial tcp 192.168.1.125:443: connectex: No connection could be made because the target machine actively refused it.

Questions: 
1. What is the reason ".kube/config" file not being generated automatically? 
2. Are my " client-certificate" and "client-key" right? 
3. How do I get the right server ip address for "set-cluster" CLI command? 

Thanks!

**Comment by zlemisie** [comment]
I've got the same problem.
https://github.com/kubernetes/minikube/issues/1981 fixed the issue

**Comment by EricssonVNFCloud** [comment]
I am still facing this issue in Windows 7

**Comment by fatcat6** [comment]
Works on my windows 10 laptop by using "https://storage.googleapis.com/minikube-builds/1982/minikube-windows-amd64.exe".

**Comment by amansingh2604** [comment]
in windows 7 in cmd when i type kubectl version i got this error

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCom
mit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:
"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/a
md64"}
Unable to connect to the server: dial tcp 192.168.99.100:8443: connectex: A conn
ection attempt failed because the connected party did not properly respond after
 a period of time, or established connection failed because connected host has f
ailed to respond.

Please help me out!!

**Comment by abhishekweb** [comment]
@amansingh2604  have you found solution for your posted problem. I am facing same issue :(
