### ISSUE TITLE
create a virtual machine

### ISSUE THREAD

**Issue by ralphie44** [kubernetes/minikube#19465]
### What Happened?

downloading windows 10 on chromebook

### Attach the log file

Unable to complete install: 'Unable to set XATTR trusted.libvirt.security.dac on /var/lib/libvirt/qemu/domain-3-win/master-key.aes: Operation not permitted'

### Operating System

Other

### Driver

N/A

**Comment by kundan2707** [comment]
without complete detail of each steps its difficult to help you

**Comment by spowelljr** [comment]
Hi @ralphie44, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
