### ISSUE TITLE
minikube addons 

### ISSUE THREAD

**Issue by kaggavenki** [kubernetes/minikube#19691]
### What Happened?

minikube addons enable csi-hostpath-driver

### Attach the log file

/var/folders/08/jtb203vx3_50dj_5h4900bw00000gp/T/minikube_addons_94d48a3bbd29c1b70f5756f0aa15047605098ead_0.log

### Operating System

macOS (Default)

### Driver

None

**Comment by mahmut-Abi** [comment]
upload your log file.

**Comment by spowelljr** [comment]
Hi @kaggavenki, as @mahmut-Abi stated, could you please upload the log file, right now we have nothing to debug off of.

**Comment by spowelljr** [comment]
Hi @kaggavenki, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
