### ISSUE TITLE
Proxy port

### ISSUE THREAD

**Issue by rahul-tkmr** [kubernetes/minikube#19702]
### What Happened?

The proxy port is not specified 8080 in this case, until `kubectl proxy --port=8080` is not specified

### Attach the log file

As a result `curl http://localhost:8080/version` returns nothing

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @rahul-tkmr, could you please more details of what you did and what you're trying to do so we can reproduce what you're trying to accomplish.

**Comment by spowelljr** [comment]
Hi @rahul-tkmr, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
