### ISSUE TITLE
Add command for caching non-minikube images

### ISSUE THREAD

**Issue by ptrain** [kubernetes/minikube#2065]
Feature Request:

A command for caching non-minikube-specific images could speed up time to rebuild a minikube VM. The command would look something like this:

```
minikube cache <IMAGE_URL>
```

This would cache the image locally, potentially by leveraging the work that was done to cache minikube-specific images from one of the last releases.

This would prevent the need for running a separate docker registry on dev machines, and be less ram-intensive as a result.

For deletion, there could be a `--delete` flag, or we could use subcommands `add`/`delete`. There would also need to be an easy way to delete all non-minikube cached images.

**Comment by r2d4** [comment]
I absolutely agree, and I designed the caching/loading mechanism to be able to accommodate something like this.  

One thing to decide is how we're actually going to expose this to the user.  Having a subcommand definitely works, but users are most likely going to want to keep a list of images that they will cache everytime they start up a new minikube VM.

We could kind of do this through the `minikube config` set of commands, but I'm not sure the best way to do this.

I see a few possibilities

- `minikube cache` + subcommands
- `minikube config` option
- `minikube start --cache-images=` or `minikube start --docker-load-from=`

Ideally, a user would probably want to specify a list of images instead of a single image, but it might even make sense to allow an option to load all the docker images from the daemon (in reverse chronological order).  The loading happens in the background and in parallel, so I think that, despite seeming like overkill, this could probably be done.

An idea that I've thought about before is to let a user specify a config file of the form found at `~/.minikube/config.json` but the whole configuration method needs a little more thought put into it.

Any thoughts @dlorenc @aaron-prindle?

**Comment by ijl** [comment]
It would be useful to have the `minikube cache` command for scripting. E.g., cache all images in use: `kubectl get deployments -o jsonpath='{.items..spec.template.spec.containers..image}' | minikube cache`. That will always be up to date, but a separate JSON manifest would not necessarily be remembered by devs.

**Comment by mahdix** [comment]
I'll pick up this one.

**Comment by mahdix** [comment]
I would suggest using the first option you mentioned.
`minikube cache eu.gcr.io/my_collection/ubuntu:latest`
This can be scripted to cache a file with a list of images or fetch that list from an external source like a Kubernetes cluster.
And to empty the cache: `minikube cache --delete`.
And I assume this cache will be preserved across multiple start/stop cycles, but will be deleted by `minikube delete`.

I think caching with `minikube start` makes it difficult to cache additional images after the VM is started and using `minikube config` will make it more complicated that it needs to be.

**Comment by r2d4** [comment]
@mahdix that plan SGTM.  I anticipated this feature and work the caching functions to be reusable, so you should be able to use them pretty easily in a new command.

CacheImages
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/machine/cache_images.go#L61

LoadImages
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/machine/cache_images.go#L81

LoadImage should probably take a CommandRunner of type SSHRunner, which would exclude the none driver.  It doesn't really make sense to cache any images with the none driver, since the docker daemon has its own cache.
