### ISSUE TITLE
Support Docker for Windows with --vm-driver=none

### ISSUE THREAD

**Issue by hach-que** [kubernetes/minikube#2189]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I have Docker for Windows installed and now I want to use minikube. There should be really no reason that I have to run a second Hyper-V VM, as Docker for Windows already handles all the port forwarding and networking to make Docker on the command line on Windows act like Docker on the command line on Linux.

minikube should support `minikube start --vm-driver=none` with Docker for Windows.

**Environment**:

**Minikube version** (use `minikube version`): v0.23.0
- **OS** (e.g. from /etc/os-release): Windows 10 Pro Insider Preview, Build 17025.rs_prerelease.171020-1626
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): In this case, "none" would be preferred.
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): N/A
- **Install tools**: N/A
- **Others**: N/A

**Comment by tapuzzo-fsi** [comment]
(My wild guess is that) this would require additional coordination between Docker and Kubernetes teams since setting this up would require modifications to the "MobyLinuxVM" and could have repercussions when Docker is upgraded or other changes are made by Docker.  Would be nice but seems like a rather difficult thing to do.

With luck, the recent alignment between Kubernetes and Docker will eventually result in a minikube-like environment being available as a check-box config in the Docker-for-Windows installation.
