### ISSUE TITLE
ISO download fails with proxy: A connection attempt failed because the connected party did not properly respond

### ISSUE THREAD

**Issue by SriharshaAngadi** [kubernetes/minikube#2425]
/kind bug

**What happened**:

Trying to start minikube with command as :
**C:\>minikube start --docker-env="HTTP_PROXY=http://XXXX/YYY" \ --docker-env="HTTPS_PROXY=http://XXX/YYY" --alsologtostderr**
 over windows with corporate proxy, with Virtual box VM. It fails to start with the following error (Attached):
[ErrorWithoutStdErrorLog.txt](https://github.com/kubernetes/minikube/files/1628014/ErrorWithoutStdErrorLog.txt)
[ErrorWithStdErrorLog.txt](https://github.com/kubernetes/minikube/files/1628015/ErrorWithStdErrorLog.txt)

**I have also set the environment variables** 
**Proxy is present in the form of .PAC file**
**Used the IP from PAC file , still it does not work**
**What you expected to happen**:
MiniKube should have started. 
**How to reproduce it (as minimally and precisely as possible)**:
Start Mini kube with the below command:
**C:\>minikube start --docker-env="HTTP_PROXY=http://XXXX/YYY.pac" \ --docker-env="HTTPS_PROXY=http://XXX/YYY.pac" --alsologtostderr**

**Anything else we need to know?**:
Minikube starts fine without corporate proxy
**Windows 8 enterprise**:
- Kubernetes version command gave the following error
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommi
t:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2
017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd6
4"}
Unable to connect to the server: dial tcp 127.0.0.1:8080: connectex: No connecti
on could be made because the target machine actively refused it.
- hardware configuration: 
8Gb RAM 
64 Bit OS

- OS (e.g. from /etc/os-release):**Windows 8 enterprise**:
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ErikWegner** [comment]
Does it work this way?

`minikube start  --docker-env http_proxy=http://192.168.99.1:3128 --docker-env https_proxy=http://192.168.99.1:3128 --docker-env no_proxy=192.168.99.0/24`

**Comment by amandadebler** [comment]
@ErikWegner No, and I think that's because there are some initial things that minikube needs to download in order to make the machine itself - the docker-env variables are for the machine that minikube makes.

The following command does not work behind an NTLM-authenticating proxy, either:

minikube get-k8s-versions

minikube does not appear to use the HTTP_PROXY and HTTPS_PROXY Windows environment variables.

Docker for Windows works with Fiddler if you set Fiddler to listen to remote traffic (check your Windows firewall first!) and give Docker for Windows your PC's IP address as the proxy.

**Comment by ErikWegner** [comment]
Maybe [privoxy](https://www.privoxy.org/) can be your solution. It can be setup to add the [authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization) [headers](https://www.privoxy.org/user-manual/actions-file.html#ADD-HEADER) for an upstream proxy.

    { +add-header{Proxy-Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l} }
    .*

Then you can point your HTTP_PROXY and HTTPS_PROXY to your locally running instance: `HTTP_PROXY=http://localhost:3128`.

Privoxy can also listen to the virtual box interface on 192.168.99.1 to allow your virtual machine to access remote resources.

**Comment by jzinedine** [comment]
Download cmder(http://cmder.net/), type bash to switch to bash
export http_proxy and https_proxy and run minikube start, it worked for me.

**Comment by ManiSubramaniyan** [comment]
I am trying out minikube on Windows 10 Professional behind a corporate proxy, so far without luck. I have tried using CNTLM for windows, but turns out unless minikube itself uses proxy, that's not going to help. 
Tried a few things:
1. Tested the proxy itself by manually setting the internet options for iexplorer and it works.
2. Docker CE settings proxy: works fine and can download from docker.io after setting proxy.
3. Just the basic get-k8s-versions doesn't work with minikube in this environment.
Also tried wireshark while running "minikube get-k8s-versions" and I can see t is directly going to storage.googleapis.com and not routing it through proxy server at all.

I am lost.. Any help appreciated...

**Comment by geertschuring** [comment]
Thanks @jzinedine, that worked for me too!

**Comment by ragebflame** [comment]
Thanks @jzinedine. This method worked perfect for me.

**Comment by tstromberg** [comment]
The important snippet from the logs:

```shell
Starting VM...
Downloading Minikube ISO
E0112 16:35:47.717429    5924 start.go:150] Error starting host: Error attemptin
g to cache minikube ISO from URL: Error downloading Minikube ISO: failed to down
load: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/mini
kube-v0.23.6.iso: dial tcp 74.125.133.128:443: connectex: A connection attempt f
ailed because the connected party did not properly respond after a period of tim
e, or established connection failed because connected host has failed to respond
```
