### ISSUE TITLE
Minikube with Windows10 and VirtualBox( Fails to set IP for the minikube VM )

### ISSUE THREAD

**Issue by arjunm183** [kubernetes/minikube#2596]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: Windows 10 , Virtual Box 

**Minikube version** (use `minikube version`): minikube version: v0.25.0
- **OS** (e.g. from /etc/os-release):  Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "virtualbox",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): "Boot2DockerURL": "file://C:/Users/ARMURUG/.minikube/cache/iso/minikube-v0.25.1.iso",
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**: 
                                  When launching minikube on windows 10 with virtualbox. Minikube doesn't get the ip ( 192.168.99.100 ). 
                                  I have  to set the minikube ip manually by entering the VM. 
                                  ( ip addr add 192.168.99.100/24 dev eth1 )

**What you expected to happen**:
                                   As soon as minikube starts it should assign ip to the interface of the vm.

**How to reproduce it** (as minimally and precisely as possible):
                                   Start minikube with windows 10 and VirtualBox installed.
It doesn't start by default.

**Output of `minikube logs` (if applicable)**:
                      **eth1 doesnt get ip address.**

Host-only MAC: 080027fec4ab
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x83ffb0] 0x83ff60  [] 0s} 127.0.0.1 56358 <nil> <nil>}
About to run SSH command:
ip addr show
SSH cmd err, output: <nil>: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:e5:ca:64 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86388sec preferred_lft 86388sec
    inet6 fe80::a00:27ff:fee5:ca64/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:fe:c4:ab brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fefe:c4ab/64 scope link
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0

SSH returned: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:e5:ca:64 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86388sec preferred_lft 86388sec
    inet6 fe80::a00:27ff:fee5:ca64/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:fe:c4:ab brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fefe:c4ab/64 scope link
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0

END SSH

ERROR getting IP: Could not find matching IP for MAC address 080027fec4ab

**Anything else do we need to know**:

After the above stage... Have to do the manual execution of ip address addition in vm to reach the minikube vm.

**Comment by arjunm183** [comment]
Any update on this bug

**Comment by whren** [comment]
I faced the same issue since 2 days.
Everything was working fine and suddenly, after a stop/start (caused by a reboot for a windows update), minikube can't reach the started vm anymore (eht1 did not get ipv4 assigned, only ipv6).
I confirm the workaround mentioned by @arjunm183 ` ip addr add 192.168.99.100/24 dev eth1`

My setup : 

- **minikube version**: v0.25.2

- **OS**: Windows 10

- **VM driver**: "DriverName": "virtualbox"

- **ISO version**: "Boot2DockerURL": "file://C:/Users/xxxx/.minikube/cache/iso/minikube-v0.25.1.iso"


minikube start -v 7 : 

...
Host-only MAC: 0800275410c1

Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x83ffb0] 0x83ff60  [] 0s} 127.0.0.1 56836 <nil> <nil>}
About to run SSH command:
ip addr show
SSH cmd err, output: <nil>: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:9f:a9:ab brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86378sec preferred_lft 86378sec
    inet6 fe80::a00:27ff:fe9f:a9ab/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:54:10:c1 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe54:10c1/64 scope link
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0

SSH returned: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:9f:a9:ab brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86378sec preferred_lft 86378sec
    inet6 fe80::a00:27ff:fe9f:a9ab/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:54:10:c1 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe54:10c1/64 scope link
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0

END SSH


ERROR getting IP: Could not find matching IP for MAC address 0800275410c1
E0423 09:44:51.072653   50380 start.go:159] Error starting host: Error starting stopped host: Maximum number of retries (5) exceeded.

 Retrying.
E0423 09:44:51.072653   50380 start.go:165] Error starting host:  Error starting stopped host: Maximum number of retries (5) exceeded
