### ISSUE TITLE
Support for NFS-based mount of host $HOME folder inside minikube VM (replace vbox shared folder)

### ISSUE THREAD

**Issue by pcm32** [kubernetes/minikube#266]
It would be great to have an option for minikube that would avoid using VBox shared folders and instead makes available the user's home to the minikube VM through NFS. Something like  `minikube start --use-nfs-instead-of-shared-folder` would be great. You could leave to the user the responsability of setting an nfs export that is compatible with this. There is a script that does something like this [here](https://gist.github.com/olalonde/3f7512c0bd2bc8abb46d). Thanks!

**Comment by aaron-prindle** [comment]
We have host mounting working for xhyve and virtualbox.  We still need to add this to hyper-v and kvm.

**Comment by aaron-prindle** [comment]
Closing.  Since this issue we have added the `minikube mount /path/to/dir/to/mount' command which mounts folders into minikube across platforms.  I have created issue #1336 to track removing native folder sharing in favor of minikube mount.  Also we have added additional kernel modules to the iso to better support nfs mounting.
