### ISSUE TITLE
Postgres and hostPath permission issue

### ISSUE THREAD

**Issue by gintautassulskus** [kubernetes/minikube#2688]
Not sure if it's a bug or just a configuration issue and if I should have created it in github.com/kubernetes.

**Minikube version**: v0.25.2
- **OS**: macOS 10.13.4
- **VM Driver**: virtualbox
- **ISO version** : v0.25.1

**What happened**:
Attempted to create a postgres statefulset with a mounted data directory.

Case 1:
If `mountPath` matches postgres data dir, then I receive a permission denied error - postgres can't write to the dir.

Case 2:
If I configure postgres data directory under the `mountPath`, then postgres initialises the db and starts just fine. However, on the localhost I can only see an empty folder with no db files.

I did not see any relevant logs running `minikube logs` with `--loglevel 0`.

**What you expected to happen**:
To have an operational postgres and see db files on localhost.

**How to reproduce it** (as minimally and precisely as possible):
Case 1: kubectl apply -f https://pastebin.com/raw/tsC7V3LK
Case 2: kubectl apply -f https://pastebin.com/raw/uy33DjCn

The manifests are identical with the exception of the `mountPath:` line.

**Comment by saule1508** [comment]
I believe that you must change the directory ownership on the host, because postgres requires that the PGDATA directory is owned by the user postgres. So the host directory must be owned by the uid:gid of the user postgres in your docker image 

So, do minikube ssh to get into the host, then as root set the ownership of the directory to the same uid:gid as the postgres user in your image.  

`chown <uid>:<gid> /usr/local/var/k8s-pg-data`

this is what I do, but I created the user postgres on the host (the minikube vm) with the same uid as the postgres user of the image.

Also, on the minikube VM, you can use the hostpath under /data so that it will persist accross stop/start of minikube

Alternatively I suppose you could change the entrypoint of the image to do the chown, you would then have to modify your entrypoint to do
`chown postgres:postgres /var/lib/postgres/data`
before you init the DB.

**Comment by gintautassulskus** [comment]
Thanks, @saule1508 

For the Case 1, I tried setting `/usr/local/var/k8s-pg-data` postgres ownership (using container postgres IDs) on my host machine. This did not help.


How do find out what location this folder is mapped to within the minikube?
If I understood you correctly, my localhost path `/usr/local/var/k8s-pg-data` is mapped to a directory in minikube and that directory in turn is then mapped to postgres container.

**Comment by saule1508** [comment]
Ah OK, you want to use a folder from you host. It is one more indirection and it might be difficult to change the permissions of the folder inside the VM (I never tried that). Also I don't know how you mount the host folder in the minikube VM. 
It is documented here: https://github.com/kubernetes/minikube/blob/master/docs/host_folder_mount.md
but I know that virtual box has also a sharing functionality.

In any case you should be able to see what is the location in the minikube VM (you specify it in the mount command), but I am not sure if you will be able to change the ownership of this directory in the VM (since the permissions are set on the host and depending how it is mounted in the VM they can be different in the VM..)

Another possibility is to create the directory in the VM (in /data directory) but then of course you will not have the database on your host server.

**Comment by Megalepozy** [comment]
@gintautassulskus Hey, did u happen to solve this problem? if so I would love to hear what u did :)

**Comment by gintautassulskus** [comment]
@Megalepozy, as far as I can remember, nfs did the trick using this utility: https://github.com/mstrzele/minikube-nfs

In the end, this approach sounded to overengineered. Instead, we've decided to go with default storage options and rely on data initialisation scripts for each (micro)service. Works for all environments the same then.

**Comment by gintautassulskus** [comment]
@Megalepozy, yes, ephemeral storage.

**Comment by bahtou** [comment]
I am currently trouble shooting the exact same issue.
https://github.com/docker-library/postgres/issues/747#event-3479674362
Any thoughts on how to configure the manifest file to get this working with minikube?
