### ISSUE TITLE
minikube 0.5 ignores xhyve driver

### ISSUE THREAD

**Issue by amoAHCP** [kubernetes/minikube#283]
hi, when I try to start minikube with xhyve I get following error:

minikube --vm-driver="xhyve" start
Starting local Kubernetes cluster...
E0707 09:36:24.213382    3014 start.go:70] Error starting host:  Error creating. Error with pre-create check: "Error detecting VBox version: exit status 126"

with fmwarefusion driver it works

**Comment by dlorenc** [comment]
Hey,

This is confusing, but the flag isn't getting ignored. The xhyve driver is checking to see what version of virtualbox is installed: https://github.com/zchee/docker-machine-driver-xhyve/blob/0ca005ce9fc204478675ac6692585fd4873f668d/xhyve/xhyve.go#L322

It looks like that code is finding a VBoxManage executable on your path, but having trouble executing it.

What happens if you run "VBoxManage -v"

**Comment by jimmidyson** [comment]
AFAIK there is no reason that it should check for vbox - assume that is just copy/paste from the core vbox libmachine driver.

**Comment by dlorenc** [comment]
It looks like it was done on purpose, there were some kernel panic issues when xhyve runs at the same time as older vbox versions.

The code looks smart enough to not mind when vbox isn't installed at all, this is an error checking the version after it found vbox installed.

**Comment by jimmidyson** [comment]
I guess I should have looked better at the code ;) Of course you're correct.

**Comment by dlorenc** [comment]
Going to close this out, as it's a bug in the xhyve driver. Making sure VboxManage is executable should be a workaround for now.
