### ISSUE TITLE
Document how to build and use minikube for offline development

### ISSUE THREAD

**Issue by mjschmidt** [kubernetes/minikube#2965]
I want to add a feature to minikube, but I am having trouble finding documentation on how to build minikube from source. Are there docs? I am seeing the following error when I try to build without making any code changes but I have a question of what goals do I need to actually make minikube?

Help! (:

**Comment by vdups** [comment]
Hi all

I've got the same issues as you have for offline mode.
1/ I want to be able to run minikube offline after installing it with Internet connection : seems OK except for metrics-server addon, because of "imagePullPolicy: Always" in  minikube/deploy/addons/metrics-server/metrics-server-deployment.yaml ==> should be easy to patch

2/ I want to be able to install to install it offline (airgap). Then an archive containing every images ready for "docker load" commands or to populate .minikube cache directory would be great. 

Cheers,

**Comment by mjschmidt** [comment]
We succeed in taking minikube offline. We did have an internal docker registry, so the workaround for us was to pull the containers and then retag them to the images minikube was expecting.

More details next week @vdups

**Comment by mjschmidt** [comment]
Didn't mean to close, keeping open until we can see if we can push changes back or at least provide you some details

**Comment by tstromberg** [comment]
Related issue: #3144

**Comment by tstromberg** [comment]
Thanks for raising this issue! I've done some documentation fixing to help out:

New Offline documentation: https://github.com/kubernetes/minikube/blob/master/docs/offline.md
Build documentation: https://github.com/kubernetes/minikube/blob/master/docs/contributors/build_guide.md

Please let me know if there is anything I missed.
