### ISSUE TITLE
Move kvm2 driver upstream (was: machine-drivers/docker-machine-driver-libvirt)

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3169]
Evidently it has some fixes we might be interested in.

We'll need to ensure that our local improvements to dhiltgen/docker-machine-kvm are also represented in machine-drivers/docker-machine-driver-libvirt

**Comment by mheese** [comment]
ok, let me reference the issue on "the other side" here: https://github.com/machine-drivers/docker-machine-driver-libvirt/issues/3

**Comment by afbjorklund** [comment]
Currently that URL contains the *KVM* driver, not the *KVM2* driver:

https://github.com/dhiltgen/docker-machine-kvm/releases/tag/v0.10.0 ==
https://github.com/machine-drivers/docker-machine-driver-libvirt/releases/tag/v0.10.0

And the prebuilt binaries are **only** available at the previous location...

----

Once the two drivers have been merged, it's probably a good idea.

But at the moment, the driver location is still [kubernetes/minikube](https://github.com/kubernetes/minikube/tree/master/pkg/drivers/kvm)

**Comment by afbjorklund** [comment]
The renaming was also slightly premature, just didn't want it to be named "kvm2" and thought the name of "docker-machine-kvm" was confusing and it didn't really talk to kvm (like our qemu did) but used libvirt...

See https://github.com/dhiltgen/docker-machine-kvm/issues/67

**Comment by tstromberg** [comment]
@mheese - any interest in continuing on this issue?

**Comment by mheese** [comment]
@tstromberg yes, you can assign me

**Comment by gbraad** [comment]
Good to hear. You also need something on the end of machine-drivers?

**Comment by afbjorklund** [comment]
Probably least confusing would be to rename the current KVM repo back to "kvm" again (since that _is_ the name of the driver binary), and then use the "libvirt" name for a new designation for the KVM2 driver ?
Not that it matters much, compared to providing it... But considering that nothing in the driver has changed in the machine-drivers repo and that the upstream repo still remains (although unmaintained), I mean.

* https://github.com/dhiltgen/docker-machine-kvm
* https://github.com/machine-drivers/docker-machine-driver-libvirt

**Comment by mheese** [comment]
Yeah, I like that idea ... However, I would maybe even like to go a step further and remove the kvm driver completely. They are both doing the same thing and they are both using libvirt, it's just that kvm2 covers a bit more - and at the end of the day, it's based on the kvm driver anyway. The current state is confusing people (even me) too much.

With regards to naming in general: I'd like to use the name _libvirt_ instead of kvm because it is a more accurate description of what it uses. At KubeCon in December in Seattle, I learned from a minikube user that this driver did not work for him because he needed to install libvirt - which apparently was not obvious to him. He was though however using kvm, but not together with libvirt. I've personally never see anybody do this, but obviously it seems to happen. If we keep the `kvm` folder and/or driver around, we should at least make a note that the libvirt driver is recommended and should be used. After all people are more familiar with `kvm` than with `libvirt`.

@gbraad there might be something that is needed from machine-drivers that has to do with passing on configuration (or something like that) while initializing the driver. There is currently a reference to other minikube code, however, if I remember correctly from the top of my head that part can be removed (it's been a couple of months since I looked at this the last time). I'll let you know when I run into an impasse, and will just go through the official github issue way and will reference your github user account.

**Comment by gbraad** [comment]
One of the things Minishift and Minikube discussed was to enhance the
drivers to handle the prerequisites of the actual driver. At the moment we
handled this in project, but you can imagine that you can do the same: to
add the user to the needed group, prepare and start network, the daemon,
etc. and then most of the 'burden' or 'PITA' can be taken away.

**Comment by josedonizetti** [comment]
Is this something we still want to do? If so, I can definitely start looking into it. Checking what are the differences, and work on migrating it to machine-drivers/docker-machine-driver-libvirt

**Comment by afbjorklund** [comment]
The "machine-drivers/docker-machine-driver-libvirt" development never went anywhere, so you can (for the discussion above) just consider it a fork of "dhiltgen/docker-machine-kvm" (which hosts the binaries):

https://github.com/dhiltgen/docker-machine-kvm _Latest commit f328c4b  on 17 Apr 2017_
https://github.com/machine-drivers/docker-machine-driver-libvirt _Latest commit f328c4b  on 17 Apr 2017_

So I guess an alternative phrasing of this issue would be "Move KVM driver upstream", similar to #3939 for hyperkit. As in: removing minikube-specific issues from the driver, and have it replace kvm(1) driver ?

This probably also means that the driver binary should work for _both_ minikube (libmachine) and `docker-machine`, we are currently using API version `v0.16.1`: https://github.com/docker/machine/releases

**Comment by afbjorklund** [comment]
I renamed https://github.com/machine-drivers/docker-machine-driver-libvirt, since it was misleading.
The repository **never** became more than a fork of https://github.com/dhiltgen/docker-machine-kvm ...

We could still move the "kvm2" driver to machine-drivers organization, if it works with docker-machine ?
But I'm not sure anyone has tried it with boot2docker.iso/anything other than minikube.iso, for a long time.
