### ISSUE TITLE
Implement --wait or --timeout option for `minikube dashbord`

### ISSUE THREAD

**Issue by vemv** [kubernetes/minikube#3298]
## The problem

On a freshly created cluster, `minikube dashboard` may fail in one of the two following ways if invoked too early:

* Successfully opens an IP address on Chrome, but I'll get a `Connection Refused` error. The page will work after some 5 minutes, but meanwhile as a user I was confused.
* It is repeatedly logged that the service is unavailable, for a few minutes, until it finally gives up. But if it had waited enough time, this retry strategy would have been successful.

## Suggestion

Either (or both) of the following:

* Implement a `--wait` flag, which causes the `minikube dashboard` invocation to block as long as the dashboard is fully ready (which may imply an indefinite block)
* Implement a `--timeout flag`.

Thanks - Victor

**Comment by tstromberg** [comment]
We've recently re-architected how the dashboard works, so that it:

- Doesn't start the frontend until "minikube dashboard" is executed
- Waits until the pod is brought up
- Waits until the dashboard service appears to be healthy (up to 3 minutes)

I hope you'll find that in minikube v0.33, that the dashboard is pretty darned reliable. Please let me know if it isn't!

I'm not against further tuning of these mechanisms to increase reliability, but I would rather not add any new flags for things that should just work properly to begin with.

**Comment by vemv** [comment]
Great to know, thanks!
