### ISSUE TITLE
containerd built for minikube reports it's version as a commit hash from buildroot

### ISSUE THREAD

**Issue by ianlewis** [kubernetes/minikube#3454]
**Minikube version** (use `minikube version`): 0.31.0
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS (Xenial Xerus)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm2
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): 0.31.0

```
$ minikube ssh 'containerd -v'
containerd github.com/containerd/containerd f3d114a1ef f3d114a1effd8a6ef773bee14fe49ea6d8d7c350
```

https://github.com/buildroot/buildroot/commit/f3d114a1ef

**Comment by afbjorklund** [comment]
Seems like it doesn't "support"* building from a tarball, it is supposed to say `v1.2.0-beta.0`
https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk#L6

* https://github.com/containerd/containerd/blob/master/Makefile#L23

**Comment by ianlewis** [comment]
I'm sure there are reasons minikube builds from source, but is it out of the question to just use the containerd binary releases?

**Comment by afbjorklund** [comment]
Minikube uses binary releases for other software (like docker), it is a bit random at the moment.

It might even be so that the "-bin" in the package name originally referred to binary installations ?

Also the version seems a bit old, but I guess nobody uses containerd (preferring docker or cri-o)

https://github.com/containerd/containerd/releases
