### ISSUE TITLE
kubelet: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory (harmless race)

### ISSUE THREAD

**Issue by lluck42** [kubernetes/minikube#3557]
minikube v0.31 logs

Jan 19 13:36:23 minikube kubelet[3037]: F0119 13:36:23.441215 3037 server.go:262] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory

**Comment by tstromberg** [comment]
I believe this log message appears during a normal successful run of minikube, and is a historical artifact of how kubelet is configured. If minikube failed, do you mind posting the failure information from minikube?

Also, minikube v0.33.1 does a bit of a better job showing error messages.

**Comment by davidovich** [comment]
I was not able to update to 0.33.0 apparently for the same reason (failing to stat bootstrap-kubelet.conf). #2927 seems also to be the same problem. Skimming on the code shows that this error is fatal, and cannot recover. 0.30.0 does not exhibit this problem for us.

I maintain two local Kubernetes cluster offerings; Docker for desktop and Minikube, so I have both installed on Windows 10 1809.

**Comment by tstromberg** [comment]
Just to clarify, this message is annoying, but completely harmless and expected in a normal working minikube environment. We never use this file.

As best as I can tell, there is a race condition in kubeadm between when the kubelet service is first started, and when /etc/kubernetes/kubelet.conf is first generated. In my environment, there was a 23 second delta between the two events, and it caused kubelet to restart 3 times.

If this is still happening in a recent (v0.33.x) release of minikube, it should be accompanied by other failure messages that should provide useful in debugging this issue.

I'm going to keep this open, because honestly, crash-looping services should never be considered normal.

**Comment by tstromberg** [comment]
Recent version of minikube improve this slightly: the message is still displayed, but we restart the kubelet more rapidly so this is less likely to be noticed. It doesn't seem feasible to address the root Kubernetes issues responsible to making this error message go away.
