### ISSUE TITLE
hyperv: Error getting ssh host name for driver: IP not found (external switch)

### ISSUE THREAD

**Issue by scrossan-crown** [kubernetes/minikube#3648]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.33.1
- **OS** (e.g. from /etc/os-release): Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "hyperv",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.33.1.iso
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):

**What happened**: When trying to start minikube the hyper-v vm doesn't get an ip address

**What you expected to happen**: minikube to start successfully

**How to reproduce it** (as minimally and precisely as possible): run `minikube start --vm-driver -v999`

**Output of `minikube logs` (if applicable)**: 
```
F0211 08:38:23.413516   18304 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
```

**Anything else do we need to know**: the output of minikube with `-v999` gets stuck in the below loop. I've also connected to the vm via the hyper-v manager and run the `ip address` command and the `eth0` adaptor has now ip address (see below screenshot)

![image](https://user-images.githubusercontent.com/30405149/52552491-5728fa80-2dd8-11e9-8cad-109792c3ffc4.png)

```
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] :
[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] :
[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] :
[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] :
[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] :
[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] :
[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] : Running
```

**Comment by scrossan-crown** [comment]
I've also tried creating an vswitch that has an external connection type but it still ended up without an ip address. I've tried deleting the vm and the .minikube folder and re-installing the vm all with the same issue

**Comment by tstromberg** [comment]
Do you mind attaching the entire log file? Just drag it to the github comment box.

I personally don't understand what's going on here, but I'm not experienced with Hyper-V.

**Comment by scrossan-crown** [comment]
@tstromberg `F0211 08:38:23.413516   18304 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found` is all that was in the `minikube logs`. I agree I couldn't work out what was happening, so I switch to Virtual Box and eventually got it running

**Comment by ksprashu** [comment]
+1 to @scrossan-crown . I am facing the same issues with the external switch not showing any ip address. It gets into this infinite loop trying to find the ip address. 

I am going to go test this external switch with docker-machine and see if that works. 
This is probably an issue with hyper-v and its network switches rather than with minikube, but I can't be sure.

**Comment by ksprashu** [comment]
This was so obvious, and I went through this option multiple times, but looks like I was blind to the issue. In HyperV Virtual Switch settings, the place where you have create the external vm switch, ensure you are selection the right "external network" in the drop down. 

I had selected the wireless network, whereas my PC was plugged into the wired network. Once I selected the ethernet card then everything started working seamlessly and I got my IP address as well.****

**Comment by ki11roy** [comment]
In contrast, in my case that was ethernet to wireless adapter change that helped.

**Comment by tstromberg** [comment]
@scrossan-crown : I believe this issue is now addressed by minikube v1.4, as it no longer requires an external switch to be configured. If you still see this issue with minikube v1.4 or higher, please reopen this issue by commenting with `/reopen`

Thank you for reporting this issue!

**Comment by petefurtado** [comment]
The solution on the post by ksprashu on May 1 worked for me! I had the exact same setup! Thanks!

**Comment by azeemzaidi** [comment]
azeem@azeem-Aspire-E1-571:~$ minikube start
😄  minikube v1.12.1 on Ubuntu 18.04
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running virtualbox "minikube" VM ...
🤦  StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 0800273eaa14
🏃  Updating the running virtualbox "minikube" VM ...
😿  Failed to start virtualbox VM. "minikube start" may fix it: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 0800273eaa14

💣  error provisioning host: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 0800273eaa14

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
azeem@azeem-Aspire-E1-571:~$ minikube status
E0809 00:11:32.556875    6726 status.go:210] failed to get driver ip: getting IP: Could not find matching IP for MAC address 0800273eaa14
E0809 00:11:32.849323    6726 status.go:129] status error: getting IP: Could not find matching IP for MAC address 0800273eaa14
minikube
type: Control Plane
host: Error
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent

azeem@azeem-Aspire-E1-571:~$

**Comment by azeemzaidi** [comment]
kindly let me know how to remove/solve existing error mentioned above.
Thanks

**Comment by codestorycooked** [comment]
In my case, the issue occurred when I am on a VPN network. Once I come out of VPN minikube starts working.
