### ISSUE TITLE
Support multiple separate minikubes

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#370]
Thinking that `minikube start` could take an argument for a name (defaulting to `default`) so you could run separate minikubes on the same box. This would be especially useful for demo purposes where you may have set up independent environments to demo different things & to reduce resource usage when you're working on a particular task.

**Comment by dlorenc** [comment]
Yeah I'd prefer if we could keep "minikube start" with no arguments working, unlike the current docker-machine CLI where name is required on all commands.

We'd need to add name to most of our commands though:

```shell
minikube start --name=DEFAULT
minikube stop --name=DEFAULT
minikube delete --name=DEFAULT
minikube status --name=DEFAULT
minikube ssh --name=DEFAULT
minikube service --name=DEFAULT
minikube dashboard --name=DEFAULT
minikube ip --name=DEFAULT
minikube logs --name=DEFAULT
```

This would also make our config work tricker, because most settings would need to be namespaced to a named instance.

Toggling the kubectl configs might also be tricky to get right.

**Comment by ramitsurana** [comment]
Nice Idea.How about introducing a new command for this feature ? We could setup a name such as (multiple/spread) to indicate that this command will actually setup multiple separate minikubes on different nodes.Let's just say 3 for starting ? We could use different namespaces for each of them.By default minikube CLI can be used to control on the DEFAULT namespace but in case the user wants to use over different namespace he can use the flags.

**Comment by curtis628** [comment]
I'm interested in this feature too. I'm working on scripts to automate the upgrade process of our k8s cluster itself (which would also include creating our k8s deployments, services, etc. on the new k8s cluster).

If minikube supported multiple VMs... I would be able to write/test these scripts all locally rather than relying on a full k8s cluster deployed somewhere. I could have two minikube `kubectl config` contexts that I could switch between, each pointing to a separate minikube VM.

I tried cloning the `minikubeVM` VirtualBox VM that minikube created, but since the IP will be different, all the generated certs will be invalid.

**Comment by marun** [comment]
It would be possible to run multiple kube instances on a single minikube vm with docker-in-docker.  Heck, we could use the initial minikube instance as the host and deploy subsequent clusters on kubernetes itself.  I have prototyped this for openshift, and the hardest part was getting the initial cluster up which minikube and 'oc cluster up' have effectively solved.

**Comment by dlorenc** [comment]
Closing as a dup of #886. Normally I'd go the other way, but that one has a nice writeup by @jorgemoralespou about how to possibly implement this.
