### ISSUE TITLE
kvm2: Error creating VM: Failed to find user record for uid

### ISSUE THREAD

**Issue by ashnair1** [kubernetes/minikube#3771]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [ ] The operating system name and version used

Command used: **minikube start**
Output of failed command:

😄  minikube v0.34.1 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: Error creating VM: virError(Code=38, Domain=0, Message='Failed to find user record for uid '64055'')

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

OS: **Ubuntu 16.04**
Minikube version: **v0.34.1**

**Comment by afbjorklund** [comment]
Are you using LDAP ? Found this: https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1382046

**Comment by ash1995** [comment]
I'm not sure how to verify that. I tried uninstalling and reinstalling the libvirt-bin libvirt-daemon-system qemu-kvm files and now I'm getting this error : 

😄  minikube v0.34.1 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: ensuring active networks: setting autostart for network default: virError(Code=55, Domain=19, Message='Requested operation is not valid: cannot set autostart for transient network')

I've now moved on to using virtual box as the vm driver for minikube as I couldn't get kvm to work.

**Comment by josedonizetti** [comment]
> I'm not sure how to verify that. I tried uninstalling and reinstalling the libvirt-bin libvirt-daemon-system qemu-kvm files and now I'm getting this error :
> 
>  minikube v0.34.1 on linux (amd64)
>  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
>  Unable to start VM: create: Error creating machine: Error in driver during machine creation: ensuring active networks: setting autostart for network default: virError(Code=55, Domain=19, Message='Requested operation is not valid: cannot set autostart for transient network')

Note for others having the same problem above. minikube (kvm2 driver) doesn't work with transient networks, only persistent networks. From libvirt documentation: ` transient network, once created (using net-create) lasts until destroyed or the libvirt daemon restarts.` To create a persistent network, you can use the same XML used for the transient network but instead of `net-create` use `net-define`, then `net-start`.

If you are using the default network,  you can delete it `net-destroy` and then use the kvm documentation to create a new one https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#troubleshoot

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by olof-nord** [comment]
This issue unfortunately still exists.

minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392

minikube start 
😄  minikube v1.6.2 on Arch rolling
✨  Automatically selected the 'kvm2' driver (alternates: [virtualbox none])
🔥  Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: create: Error creating machine: Error in driver during machine creation: ensuring active networks: starting network default: virError(Code=1, Domain=59, Message='internal error: Failed to initialize a valid firewall backend')

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
@olof-nord - Your issue appears to be an unrelated system configuration issue. Please check:

- https://computingforgeeks.com/solve-libvirt-failed-to-initialize-a-valid-firewall-backend-on-arch-linux/
- https://superuser.com/questions/1063240/libvirt-failed-to-initialize-a-valid-firewall-backend

If those don't help, please open a new issue.
