### ISSUE TITLE
apiserver pod is not able to resolve internal DNS: Name or service not known

### ISSUE THREAD

**Issue by viovanov** [kubernetes/minikube#3772]
Run minikube, then create a pod (using apiserver's image), then run:

```
kubectl exec -it test-pod -- sh -c "ping kubernetes"
```

The output correctly says:

```
PING kubernetes.default.svc.cluster.local (10.96.0.1) 56(84) bytes of data.
```

When trying to do the same thing on the api server:

```
kubectl exec -it kube-apiserver-minikube --namespace kube-system -- /bin/sh -c "ping kubernetes"
```

We get:

```
ping: kubernetes: Name or service not known
```

This happens because the `resolv.conf` in the apiserver pod is not pointing to the DNS service.
Why is this the case? Admission controllers (webhook servers) don't work if the apiserver can't resolve services.

**Comment by afbjorklund** [comment]
This is a known issue where the `resolv.conf` only contains the external DNS, not the internal DNS.

In my cause the default one is `10.0.2.3` (for eth0 host `10.0.2.15`), while internal one is `10.96.0.10`

It also does not have a search domain:

```
$ nslookup kubernetes
Server:    10.0.2.3
Address 1: 10.0.2.3

nslookup: can't resolve 'kubernetes'
$ nslookup kubernetes 10.96.0.10
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'kubernetes'
$ nslookup kubernetes.default.svc.cluster.local 10.96.0.10
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default.svc.cluster.local
Address 1: 10.96.0.1 kubernetes.default.svc.cluster.local
```
And doesn't know its own IP address.

```
$ nslookup minikube
Server:    10.0.2.3
Address 1: 10.0.2.3

Name:      minikube
Address 1: 127.0.1.1 minikube
```

It _could_ have chosen eth0 (`10.0.2.15`) or eth1 (`192.168.99.100`,
but decided to go for lo (`127.0.0.1`) when it came to `/etc/hosts`.

The API server just inherits these files, so the same root cause.

**Comment by josh-ferrell** [comment]
I wanted to add on to this. Creating an AuditSink with a webhook url set to a service FQDN(i.e. twistlock.kube-system.svc.cluster.local) will fail and present in the kubernetes apiserver logs. 

E0520 13:30:02.470263       1 metrics.go:96] Error in audit plugin 'dynamic_webhook' affecting 1 audit events: Post [_urladdress_] dial tcp: lookup twistlock-console on 10.19.1.23:53: no such host

**Comment by tstromberg** [comment]
Still an issue in v1.4.

**Comment by medyagh** [comment]
@viovanov we fixed a bug in latest release that might also fix this one,
do you mind try with latest version 1.6.1 ?

**Comment by medyagh** [comment]
@afbjorklund  @viovanov is this still an issue ?

**Comment by viovanov** [comment]
@medyagh I'm not currently using minikube, maybe @jandubois knows?

**Comment by tstromberg** [comment]
I looked into this, and it seems to be intentional behavior in Kubernetes to avoid circular dependencies: as DNS is directly reflected by apiserver state. 

webhooks have to be handled in a special way, to tell the apiserver which hostnames they refer to:

https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers

**Comment by qingwusunny** [comment]
> I looked into this, and it seems to be intentional behavior in Kubernetes to avoid circular dependencies: as DNS is directly reflected by apiserver state.
> 
> webhooks have to be handled in a special way, to tell the apiserver which hostnames they refer to:
> 
> https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers
When use serviceReference to registry webhook，how kube-apiserver curl service in that case kube-apiserver can't resolve service dns?

**Comment by Jeansen** [comment]
I had the same issue and asked this in the sig-architecture Slack channel. For everyone stumbling over this issue, here's their answer with respect to the OPs questions and my addition, if this is by design:

"Control plane components run with host networking; because of what these components to, they need to be able to boot before there is a healthy control plane for your cluster."
