### ISSUE TITLE
Proxy settings by --docker-env http_proxy fails with percent encoded chars

### ISSUE THREAD

**Issue by MichtToen** [kubernetes/minikube#3812]
If this is a bug report, please include:

- [x] How to replicate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [x] The operating system name and version used

**Comment by MichtToen** [comment]
If you are behind a proxy and your auth name is for example an email, like "user@example.com", you will have an proxy settings like this:

http_proxy=http://user%40example.com:password@proxy.com:8080

The "%40" is the needed and a legal url encoded part-

If you call now

minikube start --docker-env HTTP_PROXY=http://user%40example.com:password@proxy.com:8080

the HTTP_PROXY will not be set in the created VM. Which is easily to test on another terminal with 
minikube ssh
and
systemctl show --property=Environment docker

In fact every percent encode sign will fail.

To see the effect, change the request to a double @
minikube start --docker-env HTTP_PROXY=http://user@example.com:password@proxy.com:8080

and the HTTP_PROXY env will be set.

**Comment by MichtToen** [comment]
As a note: The env var will be silent skipped, there is no error message or warning.

**Comment by tstromberg** [comment]
This sounds terrible, and I would be happy to review any PR's which address this. Help wanted!

**Comment by michtoen** [comment]
OP on company account.

This bug seems to have it root in the  --docker-env parser part and when i should guess its related to a broken string processing/pipe by not respecting the double quotes.

A single space in the NO_PROXY rules will break the VM too.
Tests are done with Hyper-V.
I tried 3 different startup lines (without the driver settings)

a.) minikube start --docker-env "NO_PROXY=1.2.3.4,5.6.7.8"
b:) minikube start --docker-env "NO_PROXY=1.2.3.4, 5.6.7.8" # notice the ", " part
c.) minikube start --docker-env NO_PROXY="1.2.3.4, 5.6.7.8" # same

Output of minikube in the terminal:
a:) - env NO_PROXY=1.2.3.4,5.6.7.8
b.) - env NO_PROXY=1.2.3.4, 5.6.7.8
c.) - env NO_PROXY=1.2.3.4, 5.6.7.8

Output with minikube ssh & systemctl show --property=Environment docker

a.) Environment=DOCKER_RAMDISK=yes NO_PROXY=1.2.3.4,5.6.7.8
b.) Environment=DOCKER_RAMDISK=yes NO_PROXY=1.2.3.4,
c.) Environment=DOCKER_RAMDISK=yes NO_PROXY=1.2.3.4,

A buggy string processing of the arguments would also explain the behaviour with the procent encoded string part of the proxy settings - minukube and/or the bash should read the % part then as variable, if i understand this right.

**Comment by 11janci** [comment]
I will take a look at this

**Comment by michtoen** [comment]
We start to get the idea this is perhaps not a problem of minikube but of the docker daemon, which can't set the env vars from minikube when they are not in the perfect format.

**Comment by 11janci** [comment]
@MichtToen you are on the right track, except it is not a problem of docker but systemd (the input env vars must be escaped). I will come up with a PR that will do it next week.

**Comment by michtoen** [comment]
Great! Thank you!
