### ISSUE TITLE
how to skip download kubeadm & kubelet . because I download these in $PATH.

### ISSUE THREAD

**Issue by clearcodecn** [kubernetes/minikube#3846]
minikube start
😄  minikube v0.34.1 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.13.3
💾  Downloading kubelet v1.13.3
💣  Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.13.3: failed to download: failed to download to temp file: failed to copy contents: read tcp 192.168.2.229:59753->172.217.160.80:443: read: operation timed out

**Comment by afbjorklund** [comment]
Did you put the linux binaries into your darwin PATH ? If you want to download the binaries ahead of time, they need to go in the minikube cache folder rather than in some generic host folder.

But it is probably easier to sort out the network issues ("operation timed out") and let minikube handle the downloading, rather than doing it yourself. Otherwise use `~/.minikube/cache/v1.13.3/`

**Comment by tstromberg** [comment]
Additionally, if you configure a HTTP proxy, fetches should work:

https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

**Comment by clearcodecn** [comment]
😭 I am in china . can`t download that by it . I will try . tks.

**Comment by garlic0708** [comment]
I'm facing a similar issue, and thanks to @afbjorklund 's suggestion it was resolved. But it is rather strange that I can easily `wget` to the cache directory, but the cli tool cannot, as its output shows:

```
😄  minikube v0.35.0 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.13.4
💾  Downloading kubelet v1.13.4
💣  Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.13.4: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubelet: dial tcp: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubelet: dial tcp: lookup storage.googleapis.com on 180.168.255.118:53: read udp 10.200.146.182:56730->180.168.255.118:53: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubelet: dial tcp: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubelet: dial tcp: lookup storage.googleapis.com on 180.168.255.118:53: read udp 10.200.146.182:56190->180.168.255.118:53: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.13.4/bin/linux/amd64/kubelet: dial tcp: i/o timeout

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

**Comment by Kingonion** [comment]
If you want to skip the downloading, you should put the needed binaries in `$MINIKUBE_HOME/.minikube/cache/$KUBE_VERSION/.` I wrote a shell script that can help you install minikube on Linux OS easily. And you can also  make a offline installation package by using the script. The project home is [https://github.com/Kingonion/minikube-on-linux]()

**Comment by tstromberg** [comment]
Added documentation at https://github.com/kubernetes/minikube/blob/master/docs/offline.md

**Comment by alchemist123** [comment]
X Exiting due to INET_DOWNLOAD_TIMEOUT: Failed to cache ISO: unable to cache ISO:
  https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso.sha256 Dst:C:\Users\asus\.minikube\cache\iso\minikube-v1.22.0.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3358488 0x3358488 0x3358488 0x3358488 0x3358488 0x3358488 0x3358488] Decompressors:map[bz2:0x3358488 gz:0x3358488 tar:0x3358488 tar.bz2:0x3358488 tar.gz:0x3358488 tar.xz:0x3358488 tar.zst:0x3358488 tbz2:0x3358488 tgz:0x3358488 txz:0x3358488 tzst:0x3358488 xz:0x3358488 zip:0x3358488 zst:0x3358488] Getters:map[file:0xc0002d4760 http:0xc000356880 https:0xc000356940] Dir:false ProgressListener:0x3304080 Insecure:false Options:[0x178c5c0]}: invalid checksum: Error downloading checksum file: Get "https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso.sha256": net/http: TLS handshake timeout
  https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube-v1.22.0.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube-v1.22.0.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube-v1.22.0.iso.sha256 Dst:C:\Users\asus\.minikube\cache\iso\minikube-v1.22.0.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3358488 0x3358488 0x3358488 0x3358488 0x3358488 0x3358488 0x3358488] Decompressors:map[bz2:0x3358488 gz:0x3358488 tar:0x3358488 tar.bz2:0x3358488 tar.gz:0x3358488 tar.xz:0x3358488 tar.zst:0x3358488 tbz2:0x3358488 tgz:0x3358488 txz:0x3358488 tzst:0x3358488 xz:0x3358488 zip:0x3358488 zst:0x3358488] Getters:map[file:0xc0002d49f0 http:0xc000356f40 https:0xc000356fc0] Dir:false ProgressListener:0x3304080 Insecure:false Options:[0x178c5c0]}: invalid checksum: Error downloading checksum file: Get "https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube-v1.22.0.iso.sha256": net/http: TLS handshake timeout
  https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.22.0.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.22.0.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.22.0.iso.sha256 Dst:C:\Users\asus\.minikube\cache\iso\minikube-v1.22.0.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3358488 0x3358488 0x3358488 0x3358488 0x3358488 0x3358488 0x3358488] Decompressors:map[bz2:0x3358488 gz:0x3358488 tar:0x3358488 tar.bz2:0x3358488 tar.gz:0x3358488 tar.xz:0x3358488 tar.zst:0x3358488 tbz2:0x3358488 tgz:0x3358488 txz:0x3358488 tzst:0x3358488 xz:0x3358488 zip:0x3358488 zst:0x3358488] Getters:map[file:0xc0002d4b00 http:0xc000357220 https:0xc0003572a0] Dir:false ProgressListener:0x3304080 Insecure:false Options:[0x178c5c0]}: invalid checksum: Error downloading checksum file: Get "https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.22.0.iso.sha256": net/http: TLS handshake timeout

**Comment by renzhengeek** [comment]
> Did you put the linux binaries into your darwin PATH ? If you want to download the binaries ahead of time, they need to go in the minikube cache folder rather than in some generic host folder.
> 
> But it is probably easier to sort out the network issues ("operation timed out") and let minikube handle the downloading, rather than doing it yourself. Otherwise use `~/.minikube/cache/v1.13.3/`

greate job！Nowadays, however, for k8s v1.27.3, minikube v1.31.1, it seems finding those binaries from `/var/lib/minikube/binaries/v1.27.3`:
```
I0728 15:25:15.473838   84786 binaries.go:47] Didn't find k8s binaries: didn't find preexisting kubelet
Initiating transfer...
I0728 15:25:15.473888   84786 exec_runner.go:51] Run: sudo mkdir -p /var/lib/minikube/binaries/v1.27.3
```

So, one may should `cp /opt/minikube/.minikube/cache/v1.27.3/kube* /var/lib/minikube/binaries/v1.27.3/` to workaround network issue.
