### ISSUE TITLE
Unable to start VM: create: precreate: vswitch "minikubeSwitch" not found

### ISSUE THREAD

**Issue by z-ab** [kubernetes/minikube#3858]

**Comment by tstromberg** [comment]
Thank you for your bug report! Please include:

 *  The exact command-lines used so that we can replicate the issue - as well as anything you've configured in HyperV
*  The full output of the command that failed
*  Which operating system version was used

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

- The exact command line used
- The full output of the command
- The full output of "minikube logs"

Please feel free to do so at any point. Thank you for sharing your experience!
