### ISSUE TITLE
Unable to start VM: This computer doesn't have VT-X/AMD-v enabled.

### ISSUE THREAD

**Issue by sundarabt** [kubernetes/minikube#3862]

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you are reporting a bug, please include:

*  The exact command-lines used so that we can replicate the issue
*  The full output of the command that failed
* Which operating system version was used

Assuming this is minikube v0.35 - the message is probably correct, though we did see an issue with AMD CPU's on VirtualBox in a previous release. Thanks!

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube and run `minikube delete` to remove the previous cluster state.

If the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!
