### ISSUE TITLE
lvm volumes are not activated after reboot

### ISSUE THREAD

**Issue by noahdesu** [kubernetes/minikube#3908]
I'm running minikube with kvm2 driver. I've attached a virtual sata device and used this to create lvm volumes. However, after a reboot these volumes are not activated automatically.

Prior to a reboot after creating the lv we can see the active/open flags `ao` under the attributes column:

```
$ sudo lvs
  LV                                            VG                                        Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  osd-data-91656739-d2a4-4406-8d6b-362daff0faf4 ceph-c1042f4b-8ba0-4d32-b9e5-ac47d6eea3c0 -wi-ao---- <10.00g                                                    
```

After reboot the same logical volume is not active or open.

Running `lvchange -ay` will reactivate the volumes.

I suppose this is likely an issue with the udev rules in the minikube host.

```
$ minikube version
minikube version: v0.35.0
```

**Comment by balopat** [comment]
My guess would be that this might be a bug due to how our [automount script](https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/automount/minikube-automount) works. 

The `/usr/sbin/minikube-automount` script is ran by the minikube-automount service at startup.  

Can you please have a go at `/usr/sbin/minikube-automount` inside your minikube vm and see if something causes this? That would be immensely helpful. 

Thank you!
