### ISSUE TITLE
Improve error handling for "VirtualBox won't boot a 64bits VM when Hyper-V is activated"

### ISSUE THREAD

**Issue by Dhiraj0007** [kubernetes/minikube#4051]
Shows the error bellow:
!   Unable to start VM: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)

**Comment by RA489** [comment]
@Dhiraj0007 are you using virtualbox to create the VM when Hyper-V is activated?

**Comment by Dhiraj0007** [comment]
Yes

**Comment by RA489** [comment]
@Dhiraj0007 Only one hypervisor can run at a time, and since Hyper-V runs all the time as it is enabled virtualbox won't boot a 64bits VM.

**Comment by RA489** [comment]
@Dhiraj0007 try this workaround and lets see this works for you or not

**Comment by snip300r** [comment]
Did we find any solution for this problem?

**Comment by aningoo** [comment]
When you want to use Hyper-V instead of the default vBox.

1) run CMD as admin
2) "minikube start --vm-driver hyperv"

**Comment by KnutRyagerInmeta** [comment]
I was able to deactivate hyper-V. However, now I get an error message from Docker that it requires Hyper-V to work properly, and `minikube start` just stops at `Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...` indefinitely. My understanding is that running Docker containers is the main purpose of Kubernetes? Confused.

**Comment by codepractisedemo** [comment]
I am also facing the similar problem , when you disable the deactivate hyper-V and it wont able to connect the virtual box itself. since i have download the latest version

**Comment by lukasmrtvy** [comment]
@tstromberg Latest VirtualBox 6.1.16 can run 64bits VM with Hyper-V backend

**Comment by panktrip** [comment]
I am running virtualbox 6.1.32 on windows-10. but I still see the above reported issue.

PS C:> minikube start --driver=virtualbox

* minikube v1.25.1 on Microsoft Windows 10 Enterprise 10.0.19044 Build 19044
* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)

X Exiting due to PR_VBOX_HYPERV_64_BOOT: Failed to start host: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
* Suggestion: VirtualBox and Hyper-V are having a conflict. Use '--driver=hyperv' or disable Hyper-V using: 'bcdedit /set hypervisorlaunchtype off'
* Related issues:
  - https://github.com/kubernetes/minikube/issues/4051
  - https://github.com/kubernetes/minikube/issues/4783

**Comment by panktrip** [comment]
when I disable the check, as suggested in the error message above,  I do get other error as shown below.  

PS C:\WINDOWS\system32> minikube start --driver=virtualbox **--no-vtx-check=true**
* minikube v1.25.1 on Microsoft Windows 10 Enterprise 10.0.19044 Build 19044
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.438665 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))
* Failed to start virtualbox VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\tripathip\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\tripathip\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

**Comment by Jonaz1982** [comment]
$ minikube start --vm-driver kvm2
* minikube v1.25.2 en Microsoft Windows 10 Pro 10.0.19044 Build 19044
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Creando virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: This c
omputer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is ac
tivated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To
skip this check, use --virtualbox-no-vtx-check)
* Creando virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating
host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot
 a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disab
le the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)

X Saliendo por un error PR_VBOX_HYPERV_64_BOOT: Failed to start host: creating h
ost: create: precreate: This computer is running Hyper-V. VirtualBox won't boot
a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disabl
e the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
* Suggestion: VirtualBox and Hyper-V are having a conflict. Use '--driver=hyperv
' or disable Hyper-V using: 'bcdedit /set hypervisorlaunchtype off'
* Related issues:
  - https://github.com/kubernetes/minikube/issues/4051
  - https://github.com/kubernetes/minikube/issues/4783

**Comment by akaikkhan** [comment]
Error-!

Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "virtualbox" driver, which is incompatible with requested "hyperv" driver.
* Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=virtualbox'

Solutions- 

C:\Windows\system32>minikube delete                    **(delete the existing minikube cluster)**
* Removed all traces of the "minikube" cluster.

C:\Windows\system32>minikube start --vm-driver hyperv (Use this command and you must have windows10 Pro OS)
* minikube v1.30.1 on Microsoft Windows 10 Pro 10.0.19045.3086 Build 19045.3086
* Using the hyperv driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Preparing Kubernetes v1.26.3 on Docker 20.10.23 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Configuring bridge CNI (Container Networking Interface) ...
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

And please must check the virtual machine plateform checked off and hypervisor is turn on by going to turn on windows feature on or off.

**Comment by MecHCoDeR2023** [comment]
Hi, for me the issue has been solved by the following steps:

1. Runs PowerShell as administrator.
2. Specifies Hyper-V as the user driver
3. Before creating any new minikube clusters delete any of the existing logs using the command "minikube delete"

**#Result**

C:\WINDOWS\system32> minikube start --driver=hyperv     
                                                             
* minikube v1.32.0 on Microsoft Windows 10 Pro 10.0.19045.3803 Build 19045.3803                                         
* Using the hyperv driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Preparing Kubernetes v1.28.3 on Docker 24.0.7 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Configuring bridge CNI (Container Networking Interface) ...
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**OR**

1. Run bcdedit /set hypervisorlaunchtype off to disable Hyper-V temporarily.
2. Started Minikube with the --driver=hyperv flag to use the Hyper-V driver.
3. Resolved conflicts between VirtualBox and Hyper-V.

**Comment by nidhi102** [comment]
**I am gtting below error,while trying to start the minikube,please help:**
C:\Windows\system>minikube start --vm-driver hyperv
* minikube v1.34.0 on Microsoft Windows 11 Pro 10.0.22000.2538 Build 22000.2538
E1028 22:13:12.590832    1220 start.go:812] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

! Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "virtualbox" driver, which is incompatible with requested "hyperv" driver.
* Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=virtualbox'


C:\Windows\system32>minikube status
E1028 22:13:27.139283    9852 status.go:263] The "minikube" host does not exist!
minikube
type: Control Plane
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent
