### ISSUE TITLE
dashboard: Could not decode config /home/user/.minikube/config/config.json: EOF

### ISSUE THREAD

**Issue by ramanavakka** [kubernetes/minikube#4071]
```
user@ubu18041:~$ minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.39.226
user@ubu18041:~$
```

```
user@ubu18041:~$ minikube dashboard
-   Enabling dashboard ...
!   Unable to enable dashboard: Could not decode config /home/user/.minikube/config/config.json: EOF
```

I am running Ubuntu 18.04.1

**Comment by tstromberg** [comment]
Interesting! Do you mind attaching /home/user/.minikube/config/config.json so that we could see what's going on? I'm stumped as to what it might  be.

As a workaround, you should be able to use: `minikube delete` and `rm  /home/user/.minikube/config/config.json` -- but I would like to see what this file has so that we could hopefully prevent this from happening to other users.

Thank you for the bug report!

**Comment by ramanavakka** [comment]
Thanks for asking. The file has nothing. 
user@ubu18041:~/.minikube$ cd config
user@ubu18041:~/.minikube/config$ ls
config.json
user@ubu18041:~/.minikube/config$ cat config.json
user@ubu18041:~/.minikube/config$

**Comment by tstromberg** [comment]
Weird. It looks like "status" doesn't try to read this file at all, which is why it succeeded. My theory is that minikube previously exited while having the file open for write access, or perhaps it failed to detect that it couldn't write to that file..

Regardless, I think the only way to recover here is:

```shell
minikube delete
rm /home/user/.minikube/config/config.json
```

If it happens again, I'll raise the priority on this issue.

**Comment by ramanavakka** [comment]
deleting and removing the config.json file seems to have fixed the problem.  However, 
a couple of observations while looking at the logs,

1. The first time the following command was run..
minikube start --vm-driver kvm2 

Got the following error but completed the minikube start. 

$   Downloading Kubernetes v1.14.0 images in the background ...
2019/04/09 13:48:26 Unable to read "/home/user/.docker/config.json": open /home/user/.docker/config.json: no such file or directory

Now after doing the delete and removing the config.json file, I do not have the same
error.  Now it's good.  I can run the dashboard also. 
Thanks for the help.
