### ISSUE TITLE
Error getting host: Machine does not exist for api.Exists(minikube)

### ISSUE THREAD

**Issue by carol011** [kubernetes/minikube#4093]

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you are reporting a bug, please include: 

*  The exact command-lines used so that we can replicate the issue
*  The full output of the command that failed
*  Which operating system version was used

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

*  The exact command-lines used, so that we may replicate the issue 
*  The full output of the command that failed
*  The full output of the "minikube logs" command
*  Which operating system version was used

This will help us isolate the problem further. Thank you!
