### ISSUE TITLE
mount: Error finding IPV4 address for VirtualBox

### ISSUE THREAD

**Issue by perrywang** [kubernetes/minikube#4098]
**problem**
after minkube start successfully, run minikube mount xxxx:/mnt
**logs**
!   Error getting the host IP address to use from within the VM: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox
Host-Only Ethernet Adapter #2
**environment:**
windows 10 + virtualbox
minikube 1.0.0

**Comment by tstromberg** [comment]
- Definitely a dupe of #2072 (now closed because it was stale)
- Possibly a dupe of #2442

There seems to be an expectation mismatch for interface names. The code that raises the error itself looks simple:

https://github.com/kubernetes/minikube/blob/3746fb999404867616fc54fdd2d2e82ad7c0c2c7/pkg/minikube/cluster/cluster.go#L405
 
So I suspect the problem is actually in GetVMHostIP.  Do you mind attaching the output of:

`minikube mount <your flags> --alsologtostderr -v=8`

As well as:

`VBoxManage showvminfo minikube --machinereadable`
`minikube ssh ip addr`

Thanks!

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

- The exact command line used
- The full output of the command
- The full output of "minikube logs"

Please feel free to do so at any point. Thank you for sharing your experience!
