### ISSUE TITLE
Respect the XDG Base Directory Specification

### ISSUE THREAD

**Issue by MazeChaZer** [kubernetes/minikube#4109]
Under Linux/Unix systems, there is the [XDG Base Directory Specifiation](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) that states where applications should store user-related data. For example, the `config.json` currently resides in `.minikube/config/config.json`, but it should be in `$XDG_CONFIG_HOME/minikube/config.json` (which would be `.config/minikube/config.json` most of the time).

**Comment by afbjorklund** [comment]
We could add a symbolic link from config (or something), but splitting up the current $MINIKUBE_HOME into the various XDG directories (config/data/cache/etc) is not currently doable without a **lot** of restructuring...

Similar to issue https://github.com/docker/machine/issues/3116 (for libmachine)

i.e. we are using the _same_ directory for state/configuration

**Comment by MazeChaZer** [comment]
Thanks for the response! I think adding a symbolic link doesn't help much because all the stuff would still be sitting in the `.minikube` folder outside the XDG base directory folders.

**Comment by tstromberg** [comment]
I would really like to see this happen - and is something I briefly call out in #3718.

To make this happen, we'll need some migration path to move files from older paths, but it should be doable.

**Comment by afbjorklund** [comment]
I don't this see this moving anytime soon (unless we stop using libmachine)

Upstream hasn't looked at moving their `~/.docker` anywhere, since 2016 ?

**Comment by gibfahn** [comment]
>Upstream hasn't looked at moving their ~/.docker anywhere, since 2016 ?

Docker is listed [here](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Supported) as having partial support, as you can simply add `export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker` to your shell rc files.

**Comment by afbjorklund** [comment]
You can move the home folder (see MINIKUBE_HOME), problem is that you cannot split the contents into the XDG sub folders as per standard

**Comment by afbjorklund** [comment]
But if it is enough with `MINIKUBE_HOME=$XDG_CONFIG_HOME/minikube`, maybe we can close this (and "partially" support the standard, the same way as `docker-machine` is already listed - but in "data" ?) 

Application | Legacy Path | Supported Since | Discussion | Notes
-- | -- | -- | -- | --
Docker | ~/.docker |   |   | $ export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
docker-machine | ~/.docker/machine |   |   | $ export MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine

Someone else was having an issue with dumping a few hundred MB of images into the `~/.config` dir. And having configuration files in the data (or cache) directories wasn't deemed as "perfect" either.

**Comment by priyawadhwa** [comment]
This issue is still open as far as I know, if anyone is interested in working on this, please assign yourself to the issue by commenting `/assign`.

**Comment by medyagh** [comment]
I dont think this a big effort, and we could invest in this, if other kubernetes cli's go this route, we will do the same thing (kubectl,...)
