### ISSUE TITLE
creating kubeConfig: auth info "minikube" does not exist

### ISSUE THREAD

**Issue by lhlyu** [kubernetes/minikube#4126]

**Comment by tstromberg** [comment]
Thank you for sharing your experience!  Could you please include:

 *  The exact command-lines used so that we can replicate the issue
*  The full output of the command that failed
*  Which operating system version was used

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

*  The exact command-lines used, so that we may replicate the issue 
*  The full output of the command that failed
*  The full output of the "minikube logs" command
*  Which operating system version was used

This will help us isolate the problem further. Thank you!
