### ISSUE TITLE
hyperv: Unable to start VM: Get-VM : You do not have the required permission to complete this task

### ISSUE THREAD

**Issue by thesteve0** [kubernetes/minikube#4146]
I successfully create a minikube instance with hyperv on windows 10 professional using the following command line 

.\minikube.exe --vm-driver hyperv start

But then when I stopped it, it returned a message that it crashed. 
Today when I try to restart I get:

```
PS C:\Program Files\Kubernetes\Minikube> .\minikube.exe start
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...

!   Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the hyperv driver.
!   To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
!   Alternatively, you may delete the existing VM using `minikube delete -p minikube`

:   Restarting existing hyperv VM for "minikube" ...

!   Unable to start VM: start: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
```

Then I try to delete it:
```
PS C:\Program Files\Kubernetes\Minikube> .\minikube.exe delete
x   Deleting "minikube" from hyperv ...

!   Failed to delete cluster: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
```
But it turns out it is already running and it is fine!?!?! 

```
PS C:\Program Files\Kubernetes\Minikube> kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   19h
```

![image](https://user-images.githubusercontent.com/1404099/56672148-c473ca00-666a-11e9-903d-1563b6a9f85c.png)

**Comment by tstromberg** [comment]
Thank you for the bug report! Do you mind running:

`minikube delete --alsologtostderr -v=8`

That should give us enough information to hunt this down.

**Comment by thesteve0** [comment]
PS C:\Program Files\Kubernetes\Minikube> .\minikube delete --alsologtostderr -v=8
I0426 09:25:32.658677    3540 notify.go:126] Checking for updates...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : You do not have the required permission to complete this task. Contact the administrator of the authorization policy for the computer 'DESKTOP-LECFF3J'.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.GetVM


I0426 09:25:33.511520    3540 cluster.go:142] host is in state
x   Deleting "minikube" from hyperv ...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : You do not have the required permission to complete this task. Contact the administrator of the authorization policy for the computer 'DESKTOP-LECFF3J'.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.GetVM


[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Remove-VM minikube -Force
[stdout =====>] :
[stderr =====>] : Hyper-V\Remove-VM : You do not have the required permission to complete this task. Contact the administrator of the authorization policy for the computer 'DESKTOP-LECFF3J'.
At line:1 char:1
+ Hyper-V\Remove-VM minikube -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.RemoveVM

**And it is running**

PS C:\Program Files\Kubernetes\Minikube> kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   2d

**Comment by daniel-habib** [comment]
@thesteve0 :
for what's it worth...
I had the same issue.
solved it by running this in an elevated powershell.
did you try this?

**Comment by thesteve0** [comment]
No I didn't - let me try now.

Yup that did the trick. Seems like that should be added to the doc?

**Comment by thesteve0** [comment]
Spoke too soon

-   Pulling images required by Kubernetes v1.14.0 ...
:   Relaunching Kubernetes v1.14.0 using kubeadm ...

!   Error restarting cluster: running cmd: sudo kubeadm init phase certs
all --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm init phase
certs all --config /var/lib/kubeadm.yaml
stdout: [certs] Using certificateDir folder "/var/lib/minikube/certs/"
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing ca certificate authority

stderr: error execution phase certs/apiserver: failed to write or validate
certificate "apiserver": failure loading apiserver certificate: failed to
load certificate: the certificate is not valid yet
: Process exited with status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to
hear from you:
-   https://github.com/kubernetes/minikube/issues/new
X   Problems detected in "kube-addon-manager":
    - error: no objects passed to apply

**Comment by daniel-habib** [comment]
sorry for the slow response. i don't work on istio on a daily basis...
are you using minikube v1.0.0 ?
the documentation seems to suggest that this is the version to go with.

while we are at it, I noticed you are trying to run kubernetes 1.14.0.
I could not get istio 1.1.4 to work with Kubernetes v1.14.0
(failed to apply  install/kubernetes/helm/istio-init/files/crd*yaml with reason `error: SchemaError(io.k8s.api.core.v1.Node): invalid object doesn't have additional properties`)
 
what worked for me:
`minikube start --vm-driver hyperv --hyperv-virtual-switch "My Virtual Switch" --memory=4096 --kubernetes-version=v1.13.0`
adding more ram/ cpu caused the vm to fail on my machine (4 cores, 16GB RAM).

hope this helps.

**Comment by technomage** [comment]
I ran into a similar issue.  It may be the same or slightly different.  I am on windows 10.

1) I started minikube and added some helm charts and it hung (probably because dynamic memory was still enabled).
2) I tried to stop and restart, delete, etc to no avail.
3) I deleted the VM from the hyperv management window.
4) Minikube will not "delete" the vm because hyperv does not have one any longer, but does not clearn up after hyperv reports no vm.  Minikube will not start a new vm because it thinks there is one in hyperv still.  Using -p <name> allowed me to create a new vm, but minikube should clean up when the hyperv vm has been deleted manually.

This is the log output from attempting to delete the vm that was manually deleted from hyperv:

C:\Users\mlatt>minikube delete --alsologtostderr -v=8
I0520 15:19:45.357326   13488 notify.go:126] Checking for updates...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM


I0520 15:19:46.027248   13488 cluster.go:163] host is in state
x   Deleting "minikube" from hyperv ...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM


[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Remove-VM minikube -Force
[stdout =====>] :
[stderr =====>] : Hyper-V\Remove-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:1
+ Hyper-V\Remove-VM minikube -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Remove-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.RemoveVM


W0520 15:19:47.201490   13488 exit.go:99] Failed to delete cluster: exit status 1

!   Failed to delete cluster: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
Could you please check to see if minikube v1.4 addresses this issue? We've made some changes with how this is handled, and improved the log output to help us debug tricky cases like this.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
