### ISSUE TITLE
kvm2: this function is not supported by the connection driver: virNetworkDefineXML

### ISSUE THREAD

**Issue by frunzales** [kubernetes/minikube#4195]
I'm unable to do a 'minikube start' on gentoo ~amd64. Could this be libvirt related?
```
xxx@x230 ~ $ minikube start --vm-driver kvm2 --logtostderr -v 8
😄  minikube v1.0.1 on linux (amd64)
...
💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: creating network: defining network from xml:
<network>
  <name>minikube-net</name>
  <dns enable='no'/>
  <ip address='192.168.39.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.39.2' end='192.168.39.254'/>
    </dhcp>
  </ip>
</network>
: virError(Code=3, Domain=19, Message='this function is not supported by the connection driver: virNetworkDefineXML')
```

**Comment by tstromberg** [comment]
I found this Gentoo forum post which seems relevant: https://forums.gentoo.org/viewtopic-t-981692-start-0.html

`You need libvirt built with USE=virt-network too.`

Do you mind checking if that fixes the problem, and if it does, provide the exact steps for rebuilding libvirt appropriately?  I'd like to improve the error message so that it is more helpful to others who run into this problem.

**Comment by frunzales** [comment]
@tstromberg you're right, I rebuild libvirt with USE=virt-network and things seem to be better. I think it's safe to close for now.
