### ISSUE TITLE
Unable to start VM: Error getting state for host: exit status 126

### ISSUE THREAD

**Issue by grbusiness18** [kubernetes/minikube#4226]
**The exact command to reproduce the issue**:

As per the documentation provided by KYMA (https://kyma-project.io/docs/root/kyma/#installation-install-kyma-locally).., I am trying to install kyma.

When I run the COMMAND to install scripts "./scripts/minikube.sh --domain "kyma.local" --vm-driver "hyperkit" then i get the following output..minikube crashed.

**The full output of the command that failed**:

################################################################################
# Minikube setup with driver hyperkit
################################################################################

Your minikube is in 0.35.0. Your version is newer than the supported version of minikube (v0.33.0)
Your kubectl version is v1.10.11. Supported versions of kubectl are from 1.11.* to 1.13.*
💣  Error getting host status: state: exit status 126

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
😄  minikube v0.35.0 on darwin (amd64)
💥  Kubernetes downgrade is not supported, will continue to use v1.13.4

⚠️  Ignoring --vm-driver=hyperkit, as the existing "minikube" VM was created using the virtualbox driver.
⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=hyperkit`
⚠️  Alternatively, you may delete the existing VM using `minikube delete -p minikube`

💣  Unable to start VM: Error getting state for host: exit status 126

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**The output of the `minikube logs` command**:

**The operating system version**:

MAC OS Mojave 10.14.3

**Comment by tstromberg** [comment]
Do you mind sharing the result of:

`minikube start --v=3`

This command will return more information than "exit status 126", which is admittedly not a very useful message. Based on other messages, I suspect it's because VirtualBox isn't installed properly.

Here's my advice:

* Run `minikube delete` to delete your old VirtualBox VM
* Install the latest hyperkit driver: https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver
* Upgrade to the latest minikube release

I suspect things will work just fine for you then.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
