### ISSUE TITLE
minikube is crashed on my mac 

### ISSUE THREAD

**Issue by sriraj7** [kubernetes/minikube#4233]
**The exact command to reproduce the issue**:
 Minukube start

**The full output of the command that failed**:
Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
**The output of the `minikube logs` command**:
E0426 21:19:38.223888       1 reflector.go:205] k8s.io/minikube/vendor/github.com/r2d4/external-storage/lib/controller/controller.go:412: Failed to list *v1.PersistentVolume: Get https://10.96.0.1:443/api/v1/persistentvolumes?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
**The operating system version**:
macos Mojave version 10.14.2

**Comment by tech-gal** [comment]
was this resolved? i am seeing a similar issue

```bash-3.2$ minikube start
😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.1 ...
🔄  Relaunching Kubernetes v1.14.1 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy
💣  Error restarting cluster: wait: waiting for k8s-app=kube-proxy: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
    error: no objeINFO: == Kubernetcts passed to apply```

clear;minikube logs
```F0515 21:42:26.663689       1 main.go:37] Error getting server version: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout```

**Comment by tech-gal** [comment]
i found a solution in one of the threads that worked for me. use
`minikube delete`
`minikube start`

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

*  The exact command-lines used, so that we may replicate the issue 
*  The full output of the command that failed
*  The full output of the "minikube logs" command
*  Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

- The exact command line used
- The full output of the command
- The full output of "minikube logs"

Please feel free to do so at any point. Thank you for sharing your experience!
