### ISSUE TITLE
kvm2 with dns issues: waiting for component=kube-apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by raman36127** [kubernetes/minikube#4267]
**CentOS Linux release 7.6.1810 (Core)**

Removed - As wll [root@webser11 ~]# **rm .minikube**/

[root@webser11 bin]# **minikube start --vm-driver kvm2**
o   minikube v1.0.1 on linux (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 192.168.39.97
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.06.3-ce
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
@   Downloading kubelet v1.14.1
@   Downloading kubeadm v1.14.1
-   Pulling images required by Kubernetes v1.14.1 ...
X   Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.1": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 192.168.122.1:53: no such host
, error: exit status 1
: Process exited with status 1
-   Launching Kubernetes v1.14.1 using kubeadm ...
:   Waiting for pods: apiserver
!   Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you

**Comment by tstromberg** [comment]
Could you please include the output of: `minikube status` and `minikube logs`?

**Comment by tstromberg** [comment]
The ` Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 192.168.122.1:53: no such host
, error: exit status 1` is worrisome to me. Any idea what's going on here?

**Comment by raman36127** [comment]
kindly find both output.

**[root@webser11 ~]# minikube status**

!   Error getting bootstrapper
X   Error:         [SSH_AUTH_FAILURE] getting kubeadm bootstrapper: command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
i   Advice:        Your host is failing to route packets to the minikube VM. If you have VPN software, try turning it off or configuring it so that it does not re-route traffic to the VM IP. If not, check your VM environment routing options.
-   Related issues:
    - https://github.com/kubernetes/minikube/issues/3930

*   If the above advice does not help, please let us know:
-   https://github.com/kubernetes/minikube/issues/new

**[root@webser11 ~]# minikube logs**

!   command runner
X   Error:         [SSH_AUTH_FAILURE] getting ssh client for bootstrapper: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
i   Advice:        Your host is failing to route packets to the minikube VM. If you have VPN software, try turning it off or configuring it so that it does not re-route traffic to the VM IP. If not, check your VM environment routing options.
-   Related issues:
    - https://github.com/kubernetes/minikube/issues/3930

*   If the above advice does not help, please let us know:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by raman36127** [comment]
i tried following steps again.

**[root@webser11 ~]# minikube delete**
x   Deleting "minikube" from kvm2 ...
-   The "minikube" cluster has been deleted.

**[root@webser11 ~]# systemctl restart libvirtd.service**

**[root@webser11 ~]# minikube start --vm-driver kvm2 --docker-env http_proxy=http://proxy.rk.com:8080 --docker-env https_proxy=http://proxy.rk.com:8080 --docker-env no_proxy="127.0.0.1,localhost,10*"**
o   minikube v1.0.1 on linux (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 192.168.39.140
-   Configuring Docker as the container runtime ...
    - env http_proxy=http://proxy.rk.com:8080
    - env https_proxy=http://proxy.rk.com:8080
    - env no_proxy=127.0.0.1,localhost,10*
-   Version of container runtime is 18.06.3-ce
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.14.1 ...
-   Launching Kubernetes v1.14.1 using kubeadm ...
**:   Waiting for pods: apiserver
!   Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition**

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by MuhammadBilalYar** [comment]
Same Issue 
Window 10 Ent 

**ERROR LOGS:**
PS C:\WINDOWS\system32> minikube start --vm-driver=hyperv --hyperv-virtual-switch=Minikube
o   minikube v1.0.1 on windows (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is fe80::215:5dff:fe90:e505
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.06.3-ce
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.14.1 ...
X   Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.1": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on [2001:4860:4860::8888]:53: dial udp [2001:4860:4860::8888]:53: connect: network is unreachable
, error: exit status 1
: Process exited with status 1
-   Launching Kubernetes v1.14.1 using kubeadm ...

!   Error starting cluster: kubeadm init:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI

cannot use "fe80::215:5dff:fe90:e505" as the bind address for the API Server

: Process exited with status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

 **minikube status:**
host: Running
kubelet:
apiserver: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at fe80::215:5dff:fe90:e505

 **minikube logs**
==> dmesg <==
[May20 11:03] smpboot: 128 Processors exceeds NR_CPUS limit of 64
[  +0.000000] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[  +0.012896] * Found PM-Timer Bug on the chipset. Due to workarounds for a bug,
              * this clock source is slow. Consider trying other clock sources
[May20 11:04] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +0.582081] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
[  +0.337543] systemd-fstab-generator[1227]: Ignoring "noauto" for root device
[  +0.007853] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:35 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000003] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +5.533107] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +5.072362] vboxguest: loading out-of-tree module taints kernel.
[  +0.003445] vboxguest: PCI device not found, probably running on physical hardware.
[ +19.881393] systemd-fstab-generator[2414]: Ignoring "noauto" for root device
[May20 11:06] systemd-fstab-generator[3124]: Ignoring "noauto" for root device
[ +14.335450] NFSD: Unable to end grace period: -110
[May20 11:07] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.081980] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[May20 11:12] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[May20 11:17] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.

==> kernel <==
 11:19:28 up 15 min,  0 users,  load average: 0.00, 0.06, 0.10
Linux minikube 4.15.0 #1 SMP Thu Apr 25 20:51:48 UTC 2019 x86_64 GNU/Linux

==> kubelet <==
-- Logs begin at Mon 2019-05-20 11:04:09 UTC, end at Mon 2019-05-20 16:04:08 UTC. --
May 20 11:19:01 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 76.
May 20 11:19:01 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
May 20 11:19:01 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
May 20 11:19:01 minikube kubelet[4172]: Flag --allow-privileged has been deprecated, will be removed in a future version
May 20 11:19:01 minikube kubelet[4172]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:01 minikube kubelet[4172]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:01 minikube kubelet[4172]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:01 minikube kubelet[4172]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:01 minikube kubelet[4172]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:01 minikube kubelet[4172]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:01 minikube kubelet[4172]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:01 minikube kubelet[4172]: I0520 11:19:01.245008    4172 server.go:417] Version: v1.14.1
May 20 11:19:01 minikube kubelet[4172]: I0520 11:19:01.245197    4172 plugins.go:103] No cloud provider specified.
May 20 11:19:01 minikube kubelet[4172]: F0520 11:19:01.245262    4172 server.go:265] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
May 20 11:19:01 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
May 20 11:19:01 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
May 20 11:19:11 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
May 20 11:19:11 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 77.
May 20 11:19:11 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
May 20 11:19:11 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
May 20 11:19:11 minikube kubelet[4185]: Flag --allow-privileged has been deprecated, will be removed in a future version
May 20 11:19:11 minikube kubelet[4185]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:11 minikube kubelet[4185]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:11 minikube kubelet[4185]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:11 minikube kubelet[4185]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:11 minikube kubelet[4185]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:11 minikube kubelet[4185]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:11 minikube kubelet[4185]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:11 minikube kubelet[4185]: I0520 11:19:11.512965    4185 server.go:417] Version: v1.14.1
May 20 11:19:11 minikube kubelet[4185]: I0520 11:19:11.513265    4185 plugins.go:103] No cloud provider specified.
May 20 11:19:11 minikube kubelet[4185]: F0520 11:19:11.513359    4185 server.go:265] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
May 20 11:19:11 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
May 20 11:19:11 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
May 20 11:19:21 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
May 20 11:19:21 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 78.
May 20 11:19:21 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
May 20 11:19:21 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
May 20 11:19:21 minikube kubelet[4197]: Flag --allow-privileged has been deprecated, will be removed in a future version
May 20 11:19:21 minikube kubelet[4197]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:21 minikube kubelet[4197]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:21 minikube kubelet[4197]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:21 minikube kubelet[4197]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:21 minikube kubelet[4197]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:21 minikube kubelet[4197]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:21 minikube kubelet[4197]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 20 11:19:21 minikube kubelet[4197]: I0520 11:19:21.777304    4197 server.go:417] Version: v1.14.1
May 20 11:19:21 minikube kubelet[4197]: I0520 11:19:21.777467    4197 plugins.go:103] No cloud provider specified.
May 20 11:19:21 minikube kubelet[4197]: F0520 11:19:21.777503    4197 server.go:265] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
May 20 11:19:21 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
May 20 11:19:21 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by tstromberg** [comment]
@raman36127 - do you mind checking in minikube v1.1.0 fixes this? We recently refactored this health check to be more robust.

**Comment by raman36127** [comment]
@tstromberg v1.1.0 - Worked for me. Here all steps for ref. 

Steps which i tried.
#minikube delete
#rm -rf .minikube/
#rm /usr/local/bin/minikube
#rm /usr/local/bin/docker-machine-driver-kvm2

#yum -y install qemu-kvm libvirt libvirt-daemon-kvm

#wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 -O minikube
#wget https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2

#chmod 755 minikube docker-machine-driver-kvm2
#cp minikube docker-machine-driver-kvm2 /usr/local/bin/

[root@webser11 tmp]# minikube version
minikube version: v1.1.0

Now hit/Start minikube

[root@webser11 tmp]#minikube start --vm-driver kvm2 --docker-env http_proxy=http://proxy.rk.com:8080 --docker-env https_proxy=http://proxy.rk.com:8080 --docker-env no_proxy="127.0.0.1,localhost,10*"

* minikube v1.1.0 on linux (amd64)
* Downloading Minikube ISO ...
 131.28 MB / 131.28 MB [============================================] 100.00% 0s
* Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
* Configuring environment for Kubernetes v1.14.2 on Docker 18.09.6
  - env http_proxy=http://proxy.rk.com:8080
  - env https_proxy=http://proxy.rk.com:8080
  - env no_proxy=127.0.0.1,localhost,10*
* Downloading kubelet v1.14.2
* Downloading kubeadm v1.14.2
* Pulling images ...
* Launching Kubernetes ...
* Verifying: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "minikube"

[root@webser11 tmp]# minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.39.76

[root@webser11 tmp]# minikube service list
|-------------|------------|--------------|
|  NAMESPACE  |    NAME    |     URL      |
|-------------|------------|--------------|
| default     | kubernetes | No node port |
| kube-system | kube-dns   | No node port |
|-------------|------------|--------------|

[root@webser11 tmp]# minikube docker-env
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.76:2376"
export DOCKER_CERT_PATH="/root/.minikube/certs"
export DOCKER_API_VERSION="1.39"

[root@webser11 tmp]# kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

[root@webser11 tmp]# kubectl cluster-info dump
Unable to connect to the server: Tunnel Connection Failed

FIX for this.

[root@webser11 tmp]# env | grep -i proxy
http_proxy=http://proxy.rk.com:8080
https_proxy=http://proxy.rk.com:8080
no_proxy=127.0.0.1,localhost,10*

[root@webser11 tmp]# minikube delete
* Deleting "minikube" from kvm2 ...
* The "minikube" cluster has been deleted.

[root@webser11 tmp]#  systemctl restart libvirtd.service

[root@webser11 tmp]#minikube start --vm-driver kvm2 --docker-env http_proxy=http://proxy.rk.com:8080 --docker-env https_proxy=http://proxy.rk.com:8080 --docker-env no_proxy="127.0.0.1,localhost,10*"

[root@webser11 tmp]# minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.39.67

[root@webser11 tmp]# export NO_PROXY=$no_proxy,$(minikube ip)
[root@webser11 tmp]# export no_proxy=$no_proxy,$(minikube ip)

[root@webser11 tmp]# minikube service list
|-------------|------------|--------------|
|  NAMESPACE  |    NAME    |     URL      |
|-------------|------------|--------------|
| default     | kubernetes | No node port |
| kube-system | kube-dns   | No node port |
|-------------|------------|--------------|
[root@webser11 tmp]# kubectl cluster-info
Kubernetes master is running at https://192.168.39.67:8443
KubeDNS is running at https://192.168.39.67:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

#minikube VM running & do the ssh to machine.

# kubectl get nodes
NAME       STATUS   ROLES    AGE     VERSION
minikube   Ready    master   6m53s   v1.14.2

# virsh list
 Id    Name                           State
----------------------------------------------------
 1     minikube                       running

[root@webser11 tmp]# minikube ssh
                         _             _
            _         _ ( )           ( )
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ hostname
minikube

$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS               NAMES
a58fcb33dc7d        eb516548c180           "/coredns -conf /etcâ¦"   7 minutes ago       Up 7 minutes                            k8s_coredns_coredns-        fb8b8dccf-fq59n_kube-system_55675111-7c78-11e9-9888-100d230d7cce_1

![minikube](https://user-images.githubusercontent.com/30895452/58167450-9acdb300-7ca9-11e9-8948-d7301208183e.PNG)

$ exit
logout

[root@webser11 tmp]#

**Comment by raman36127** [comment]
@tstromberg  Thanks :)

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube and run `minikube delete` to remove the previous cluster state.

If the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!
