### ISSUE TITLE
Unable to stop VM: exit status 1

### ISSUE THREAD

**Issue by abhishekse87** [kubernetes/minikube#4268]
!   Unable to stop VM: Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

*  The exact command-lines used, so that we may replicate the issue 
*  The full output of the command that failed
*  The full output of the "minikube logs" command
*  Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment]
Also, the output of `minikube stop --alsologtostderr -v=8` would be *very* helpful in this case.

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

- The exact command line used
- The full output of the command
- The full output of "minikube logs"

Please feel free to do so at any point. Thank you for sharing your experience!
