### ISSUE TITLE
Minikube docker user UID and GID changed again

### ISSUE THREAD

**Issue by soderluk** [kubernetes/minikube#4269]
This is more of a question than an issue.

In version `v0.35.0` the `docker` user is `1001` and `rkt` user is `1000`.
Now in `v1.0.0` there is no `rkt` user at all, and the `docker` user is back to UID `1000`. 

It seems that support for `rkt` has been removed in version 1.0.0, but the question, is the docker user UID and GID going to remain at `1000` from now on, or is it going to keep changing from release to release?

**Comment by tstromberg** [comment]
In the short-term, we have no plans to add or remove any users, so the id's should stay stable at least for the next couple releases. 

In the long-term, the docker uid/gid is not guaranteed to be stable. I'm curious - what are you using the uid/gid for?

To deal with the changes, we did have to add the ability to set uid and gid to usernames rather than ID's, so that we can lookup the id's dynamically.

https://github.com/kubernetes/minikube/commit/7233a2d50defae0a55fe47ce58bd7d507da0d108#diff-f72dd12efe35f3d72431d67508344f84

If you need to do something similarly, I suggest calling 'id -u docker' and 'id -g docker'.

**Comment by soderluk** [comment]
We add a new user to our docker images, and set the same UID and GID to be able to access the project folders, e.g. write to test folders etc.

**Comment by tstromberg** [comment]
OK. We will do our best to keep the uid/gid stable then in the future. Thanks for the heads up!
