### ISSUE TITLE
hyperv: Unable to start VM: create: creating: exit status 1 (reason unknown)

### ISSUE THREAD

**Issue by samgentile42** [kubernetes/minikube#4303]
Ask Question 

0

I installed Minikube on Windows 10 but can't get it to run. I tried to start it with:
 minikube start --vm-driver=hyperv
The first error was:
[HYPERV_NO_VSWITCH] create: precreate: no External vswitch found. A valid vswitch must be available for this command to run.
I then searched on Google and found the solution to this error with this page: 
https://www.codingepiphany.com/2019/01/04/kubernetes-minikube-no-external-vswitch-found/
I then fixed the problem by defining a vswitch but I got this error:
minikube start --vm-driver hyperv --hyperv-virtual-switch "Minikube"
o   minikube v1.0.1 on windows (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM: create: creating: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new 
This is a pretty generic error. What do I do to get this working? Thanks!

**Comment by tstromberg** [comment]
Hello Sam!

The HyperV driver doesn't yet show error messages by default. Do you mind running:

`minikube start --vm-driver=hyperv --alsologtostderr -v=8`

That should reveal more information about what's going on here. Thank you!

**Comment by atekka85epam** [comment]
Hello!

I have the same problem, I fired the command and got: 
minikube start --vm-driver hyperv --hyperv-virtual-switch "Default Switch" --alsologtostderr -v=8

Starting VM...
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM minikube
I0522 10:47:54.780133    8952 cache_images.go:306]
[stdout =====>] :
[stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to change state.
The operation failed with error code '32788'.
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.StartVM


I0522 10:47:56.178638    8952 cache_images.go:306]
I0522 10:47:57.266970    8952 start.go:428] StartHost: create: creating: exit status 1
I0522 10:47:57.266970    8952 utils.go:122] non-retriable error: create: creating: exit status 1
W0522 10:47:57.268531    8952 exit.go:99] Unable to start VM: create: creating: exit status 1

!   Unable to start VM: create: creating: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by srv-twry** [comment]
Hi @tstromberg , I am facing the same issue as well.

### Logs
output of `minikube start --vm-driver hyperv --cpus 4 --memory=4096 --hyperv-virtual-switch "HV Virtual Switch"`

```

* minikube v1.1.0 on windows (amd64)
* Creating hyperv VM (CPUs=4, Memory=4096MB, Disk=20000MB) ...
E0528 16:32:54.006018    5416 start.go:529] StartHost: create: creating: exit status 1

X Unable to start VM: create: creating: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
```

Output of `minikube start --vm-driver=hyperv --alsologtostderr -v=8`

```
W0528 16:41:28.942655   13348 root.go:151] Error reading config file at C:\Users\t-satiwa\.minikube\config\config.json: open C:\Users\t-satiwa\.minikube\config\config.json: The system cannot find the file specified.
I0528 16:41:28.945657   13348 notify.go:128] Checking for updates...
* minikube v1.1.0 on windows (amd64)
I0528 16:41:30.122687   13348 downloader.go:60] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.1.0.iso
I0528 16:41:30.123711   13348 start.go:721] Saving config:
{
    "MachineConfig": {
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.1.0.iso",
        "Memory": 2048,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "hyperv",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false,
        "Hidden": false,
        "NoVTXCheck": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.14.2",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": true,
        "EnableDefaultCNI": false
    }
}
I0528 16:41:30.129685   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0
I0528 16:41:30.124689   13348 cache_images.go:307] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at C:\Users\t-satiwa\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1
I0528 16:41:30.124689   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/pause:3.1 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\pause_3.1
I0528 16:41:30.124689   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.14.2 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.14.2
I0528 16:41:30.124689   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13
I0528 16:41:30.124689   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.14.2 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.14.2
I0528 16:41:30.125686   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.14.2 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\kube-proxy_v1.14.2
I0528 16:41:30.125686   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0528 16:41:30.125686   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\kubernetes-dashboard-amd64_v1.10.1
I0528 16:41:30.125686   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\coredns_1.3.1
I0528 16:41:30.125686   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.14.2 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.14.2
I0528 16:41:30.125686   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13
I0528 16:41:30.130690   13348 cache_images.go:307] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at C:\Users\t-satiwa\.minikube\cache\images\k8s.gcr.io\etcd_3.3.10
I0528 16:41:30.148688   13348 cluster.go:81] Skipping create...Using existing machine configuration
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
[executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM


I0528 16:41:30.791629   13348 cluster.go:100] Machine state:
* Restarting existing hyperv VM for "minikube" ...
[executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM minikube
[stdout =====>] :
[stderr =====>] : Hyper-V\Start-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.StartVM


E0528 16:41:31.405057   13348 start.go:529] StartHost: start: exit status 1
I0528 16:41:31.408056   13348 utils.go:122] non-retriable error: start: exit status 1
W0528 16:41:31.408056   13348 exit.go:100] Unable to start VM: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
```

**Comment by atekka85epam** [comment]
Do your minikube machine visible in HyperV?Since the error msg suggest it is not there anymore.
Hyper-V\Start-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:1
+ Hyper-V\Start-VM minikube

**Comment by srv-twry** [comment]
There are two issues that I am facing. I delete the `.minikube` directory in order to do a fresh start.

When I run `minikube start --vm-driver hyperv --cpus 4 --memory=4096 --hyperv-virtual-switch "HV Virtual Switch"`, the VM is created and is visible in the Hyper-V Manager but the program just stalls and won't finish at all.

```
* minikube v1.1.0 on windows (amd64)                                  
* Creating hyperv VM (CPUs=4, Memory=4096MB, Disk=20000MB) ...
* Configuring environment for Kubernetes v1.14.2 on Docker 18.09.6
```
I have tried waiting for over an hour.

After that I used `ctrl + c` to exit. Then I used `minikube delete` to delete the VM.
After that when I run `minikube start --vm-driver hyperv --cpus 4 --memory=4096 --hyperv-virtual-switch "HV Virtual Switch"`, I get the error as shown in the above logs.

**Comment by atekka85epam** [comment]
When you create the machine and it stalls you can login to in Hyperv via docker user and tcuser password to check what it does and why not moves on.Maybe you find something. For me the problem was the docker for windows, after I stopped that minikube started to work, so it had problem with an another container related service. Right now I created an Ubuntu vm for docker  and using minikube on Windows until I get bored with the problems on it and create a linux vm for that too.

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information from the original author in this issue to make it actionable. Since some time has passed, I'm going to close this issue. You may reopen this issue any point by commenting with `/reopen`, but if possible, please add some additional information, such as:

- The exact `minikube start` command line used: preferably with `--alsologtostderr -v=8` added for extra debugging.
- The full output of the command
- The full output of "minikube logs"

Thank you for sharing your experience!

**Comment by putdns** [comment]
https://e.xieyonghui.com/k8s-minikube-retriable-failure-create_119.html

**Comment by m287867** [comment]
Hi 
I'am still facing almost the same error when starting minikube ! 
i tried 
and got the following Output : 
minikube start --vm-driver=hyperv --alsologtostderr -v=8



PS C:\Users\M287867> minikube start --vm-driver=hyperv --alsologtostderr -v=8
W0821 10:51:42.377252   14668 root.go:241] Error reading config file at C:\Users\SADM-M287867\.minikube\config\config.json: open C:\Users\SADM-M287867\.minikube\config\config.json: The system cannot find the file specified.
I0821 10:51:42.410254   14668 start.go:255] hostinfo: {"hostname":"LTDE114207","uptime":4583,"bootTime":1597995319,"procs":284,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.16299 Build 16299","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"96064378-f794-4296-99ba-6a84702f0034"}
W0821 10:51:42.411258   14668 start.go:263] gopshost.Virtualization returned error: not implemented yet
* minikube v1.6.2 on Microsoft Windows 10 Enterprise 10.0.16299 Build 16299
I0821 10:51:42.420257   14668 start.go:555] selectDriver: flag="hyperv", old=&{minikube false false https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso 2000 2 20000 hyperv docker  [] [] [] [] 192.168.99.1/24  default qemu:///system false false <nil> [] false [] /nfsshares  false false true {v1.17.0  8443 minikube minikubeCA [] [] cluster.local docker    10.96.0.0/12  [] true false} virtio virtio}
I0821 10:51:42.420257   14668 global.go:60] Querying for installed drivers using PATH=C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_251\bin;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin\;C:\WINDOWS\system32;C:\Program Files\Amazon\AWSCLIV2\;C:\Users\SADM-M287867\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs;C:\Python27;C:\Python27\;C:\Program Files\nodejs\;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\sbt\\bin;;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\SADM-M287867\AppData\Local\Yarn\bin;C:\Users\SADM-M287867\AppData\Roaming\npm;C:\Program Files\Oracle\VirtualBox
I0821 10:51:48.615576   14668 global.go:68] hyperv priority: 6, state: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0821 10:51:49.939901   14668 global.go:68] virtualbox priority: 4, state: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0821 10:51:49.984942   14668 global.go:68] vmware priority: 5, state: {Installed:false Healthy:false Error:exec: "docker-machine-driver-vmware": executable file not found in %PATH% Fix:Install docker-machine-driver-vmware Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/}
I0821 10:51:49.984942   14668 driver.go:109] requested: "hyperv"
I0821 10:51:49.986949   14668 driver.go:113] choosing "hyperv" because it was requested
I0821 10:51:49.989945   14668 driver.go:146] Picked: hyperv
I0821 10:51:49.989945   14668 driver.go:147] Alternatives: [virtualbox]
* Selecting 'hyperv' driver from user configuration (alternates: [virtualbox])
I0821 10:51:49.990943   14668 start.go:297] selected driver: hyperv
I0821 10:51:49.991942   14668 start.go:585] validating driver "hyperv" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso Memory:2000 CPUs:2 DiskSize:20000 VMDriver:hyperv ContainerRuntime:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false Downloader:<nil> DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true KubernetesConfig:{KubernetesVersion:v1.17.0 NodeIP: NodePort:8443 NodeName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false} HostOnlyNicType:virtio NatNicType:virtio}
I0821 10:51:54.259574   14668 start.go:591] status for hyperv: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
W0821 10:51:54.262077   14668 start.go:624] selectDriver api.Load: filestore "minikube": open C:\Users\SADM-M287867\.minikube\machines\minikube\config.json: The system cannot find the file specified.
I0821 10:51:54.265600   14668 downloader.go:60] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\kubernetesui\metrics-scraper:v1.0.2 -> C:\Users\SADM-M287867\.minikube\cache\images\kubernetesui\metrics-scraper_v1.0.2
I0821 10:51:54.266607   14668 cache_images.go:347] CacheImage: kubernetesui/metrics-scraper:v1.0.2 -> C:\Users\SADM-M287867\.minikube\cache\images\kubernetesui\metrics-scraper_v1.0.2
I0821 10:51:54.266607   14668 profile.go:89] Saving config to C:\Users\SADM-M287867\.minikube\profiles\minikube\config.json ...
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\coredns:1.6.5 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\coredns_1.6.5
I0821 10:51:54.293601   14668 cache_images.go:347] CacheImage: k8s.gcr.io/coredns:1.6.5 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\coredns_1.6.5
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-proxy:v1.17.0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-proxy_v1.17.0
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-scheduler:v1.17.0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.17.0
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-controller-manager:v1.17.0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.17.0
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-apiserver:v1.17.0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.17.0
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-addon-manager:v9.0.2 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0.2
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\etcd:3.4.3-0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\etcd_3.4.3-0
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\pause:3.1 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\pause_3.1
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner:v1.8.1 -> C:\Users\SADM-M287867\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1
I0821 10:51:54.266607   14668 cache_images.go:200] windows sanitize: C:\Users\SADM-M287867\.minikube\cache\images\kubernetesui\dashboard:v2.0.0-beta8 -> C:\Users\SADM-M287867\.minikube\cache\images\kubernetesui\dashboard_v2.0.0-beta8
I0821 10:51:54.295607   14668 cache_images.go:347] CacheImage: k8s.gcr.io/kube-proxy:v1.17.0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-proxy_v1.17.0
I0821 10:51:54.298612   14668 cache_images.go:347] CacheImage: k8s.gcr.io/kube-scheduler:v1.17.0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.17.0
I0821 10:51:54.300604   14668 cache_images.go:347] CacheImage: k8s.gcr.io/kube-controller-manager:v1.17.0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.17.0
I0821 10:51:54.301604   14668 cluster.go:102] Skipping create...Using existing machine configuration
I0821 10:51:54.301604   14668 cache_images.go:347] CacheImage: k8s.gcr.io/kube-apiserver:v1.17.0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.17.0
I0821 10:51:54.302600   14668 cache_images.go:347] CacheImage: k8s.gcr.io/kube-addon-manager:v9.0.2 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0.2
I0821 10:51:54.302600   14668 cache_images.go:347] CacheImage: k8s.gcr.io/etcd:3.4.3-0 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\etcd_3.4.3-0
I0821 10:51:54.303600   14668 cache_images.go:347] CacheImage: k8s.gcr.io/pause:3.1 -> C:\Users\SADM-M287867\.minikube\cache\images\k8s.gcr.io\pause_3.1
I0821 10:51:54.304598   14668 cache_images.go:347] CacheImage: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 -> C:\Users\SADM-M287867\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1
I0821 10:51:54.304598   14668 cache_images.go:347] CacheImage: kubernetesui/dashboard:v2.0.0-beta8 -> C:\Users\SADM-M287867\.minikube\cache\images\kubernetesui\dashboard_v2.0.0-beta8
W0821 10:51:54.312599   14668 exit.go:101] Unable to start VM. Please investigate and run 'minikube delete' if possible: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\SADM-M287867\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\SADM-M287867\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by SureshPaspula** [comment]
This Command helped me to solve the issue 
minikube start --vm-driver hyperv --hyperv-virtual-switch "Default Switch" --alsologtostderr -v=8
