### ISSUE TITLE
not able to start minikube on windows after installing minikube.exe filr

### ISSUE THREAD

**Issue by nipun214** [kubernetes/minikube#4317]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

*  The exact command-lines used, so that we may replicate the issue 
*  The full output of the command that failed
*  The full output of the "minikube logs" command
*  Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

- The exact command line used
- The full output of the command
- The full output of "minikube logs"

Please feel free to do so at any point. Thank you for sharing your experience!
