### ISSUE TITLE
sudo minikube start command not working on mac

### ISSUE THREAD

**Issue by ashrivastavagit** [kubernetes/minikube#4365]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by tstromberg** [comment]
Please don't run minikube as root or with "sudo" privileges. It isn't necessary.

Regrettably, there isn't enough additional information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

- The exact command line used
- The full output of the command
- The full output of "minikube logs"

Please feel free to do so at any point. Thank you for sharing your experience!
