### ISSUE TITLE
Add support for VM-free deployments using Docker

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4389]
This will give a much better user experience for folks in nested VM's than the "none" driver currently provides.

If possible, this should be done in collaboration with the fine folks at https://github.com/kubernetes-sigs/kind

**Comment by afbjorklund** [comment]
Do we really have to write multiple implementations, or can we use something like CRI from the start ?

Like https://kind.sigs.k8s.io/docs/design/principles#target-cri-functionality (and to avoid that extra work)

**Comment by afbjorklund** [comment]
See this kind Dockerfile for some of the crazy stuff needed, when running systemd in a container:
https://github.com/kubernetes-sigs/kind/blob/master/images/base/Dockerfile (based on Ubuntu)

* https://kind.sigs.k8s.io/docs/design/base-image
* https://kind.sigs.k8s.io/docs/design/node-image

This issue (VM-free deployments) is likely to have to work with changes to libmachine and buildroot...
As in: it is **not** certain that we will keep the docker-machine API and the minikube ISO, while doing it.

----

The "none" driver isn't really a VM-free environment, it's just intended to run on a pre-allocated VM.

This issue is different, since it doesn't require the user to do anything but provide a container runtime.
Then it will start containers "faking" nodes, and use those to start pods. (see e.g. the [kind design doc](https://kind.sigs.k8s.io/docs/design/initial/))

That is something else than installing the kubelet on the local host. It also allows for _multiple_ nodes.

**Comment by afbjorklund** [comment]
See also https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cluster-lifecycle/local-cluster-ux.md for the original minikube proposal and some of the reasoning behind it...

**Comment by afbjorklund** [comment]
@medyagh : will you run a sshd in the "node" container, or should we use exec and nsenter instead ?

I was wondering about the `minikube ssh` use-case, as you know it is not supported by the `none` driver

* https://blog.docker.com/2014/06/why-you-dont-need-to-run-sshd-in-docker/

* https://blog.phusion.nl/2015/01/20/baseimage-docker-fat-containers-treating-containers-vms/

**Comment by medyagh** [comment]
I would user exec, which will invoke "docker exec"

I am implementing a specialized commander for the vm-free which is basically a helper for docker exec

**Comment by priyawadhwa** [comment]
This feature is expected to be done by next quarter.

**Comment by medyagh** [comment]
the undocumented support for docker vm driver has been merged by https://github.com/kubernetes/minikube/pull/6151

I will close this issue and make smaller issues to be tracked for next steps of kic
