### ISSUE TITLE
 hyperv: Minikube crashed on restart

### ISSUE THREAD

**Issue by felipefb** [kubernetes/minikube#4428]
**The exact command to reproduce the issue**:
minikube start --vm-driver hyperv --hyperv-virtual-switch "Novo Comutador Virtual"
**The full output of the command that failed**:
* minikube v1.1.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing hyperv VM for "minikube" ...
E0605 10:17:59.103239    9096 start.go:529] StartHost: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
**The output of the `minikube logs` command**:

**The operating system version**:
Windows 10
![minikube](https://user-images.githubusercontent.com/34892732/58959588-cb1e5280-877b-11e9-82a6-752ffc1bb5c1.jpg)

**Comment by shwetanshu21** [comment]
Can you run the minkube start command with "--v=10 --logtostderr" added so that it can provide better logs? 

Like this :  minikube start --kubernetes-version="v1.14.0" --vm-driver="hyperv" --hyperv-virtual-switch="OSwitch" --v=10 --logtostderr

Also the output of `minikube logs`

**Comment by medyagh** [comment]
just a guess could you try the switch name with 
` --hyperv-virtual-switch="Novo Comutador Virtual"`

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
