### ISSUE TITLE
minikube crashed

### ISSUE THREAD

**Issue by saichandreddy6666** [kubernetes/minikube#4472]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by dineshtobe** [comment]
C:\Users\edinrxx>minikube status
host: Running
kubelet: Running
apiserver: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.106

C:\Users\edinrxx>minikube delete
* Deleting "minikube" from virtualbox ...
* The "minikube" cluster has been deleted.

C:\Users\edinrxx>minikube start
* minikube v1.1.1 on windows (amd64)
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
* Configuring environment for Kubernetes v1.14.3 on Docker 18.09.6
* Pulling images ...
* Launching Kubernetes ...

X Error starting cluster: timed out waiting to elevate kube-system RBAC privileges: creating clusterrolebinding: Post https://192.168.99.107:8443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings?timeout=1m0s: dial tcp 192.168.99.107:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by dineshtobe** [comment]
I deleted the minikube and started again but minikube is crashing

**Comment by medyagh** [comment]
What is your virtualbox version?

**Comment by dineshtobe** [comment]
Hi Medyagh,

virtualbox version :
VirtualBox Graphical User Interface
Version 6.0.4 r128413 (Qt5.6.2)

After rebooting the PC it is working fine.

Thanks.

**Comment by saichandreddy6666** [comment]
delete minikube from virtual machine
un install minikube
remove .minikube files from c drive
do same thing with kubernates
resstart machine
now try to install minikube and kubernates
start minikube on hyper v if your using

* Thanks*

*Saichand kunduru*

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

- The exact `minikube start` command line used: preferably with `--alsologtostderr -v=8` added.
- The full output of the command
- The full output of "minikube logs"

Please feel free to do so at any point. Thank you for sharing your experience!

**Comment by dineshtobe** [comment]
C:\WINDOWS\system32>minikube start
* minikube v1.2.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube
delete' to delete this one.
* Re-using the currently running virtualbox VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
* Relaunching Kubernetes v1.15.0 using kubeadm ...
X Error restarting cluster: waiting for apiserver: timed out waiting for
the condition
* Sorry that minikube crashed. If this was unexpected, we would love to
hear from you:
  - https://github.com/kubernetes/minikube/issues/new
* Problems detected in "kube-addon-manager":
  - error: unable to recognize "STDIN": Get
https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect:
connection refused
