### ISSUE TITLE
kvm: 'Unable to create bridge virbr1: Package not installed'

### ISSUE THREAD

**Issue by chazzrobbz** [kubernetes/minikube#4505]
**The exact command to reproduce the issue**: minikube start --vm-driver kvm2

**The full output of the command that failed**: Unable to start VM: create: Error creating machine: Error in driver during machine creation: creating network: creating network minikube-net: virError(Code=38, Domain=0, Message='Unable to create bridge virbr1: Package not installed'

**The output of the `minikube logs` command**: E0617 02:03:15.125013   77729 start.go:529] StartHost: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')

**The operating system version**: Manjaro

**Comment by medyagh** [comment]
do you mind sharing the output of ? `libvirtd --version` 

if libvirt is not installed, does installing it according to this docs help ?
https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver

**Comment by medyagh** [comment]
if this issue is solved by installing libvirt we could probably do a better job in giving solution message.

I would be happy to review any PR that adds a nice solution message for this error

**Comment by josedonizetti** [comment]
@medyagh I don't think libivirt installation is the reason here. If libvirt wasn't installed it would have failed before, when getting the connection: https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kvm/network.go#L115, instead it is failing after getting a connection, when creating the `minikube-net` network: https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kvm/network.go#L145

**Comment by afbjorklund** [comment]
This does indeed look like a libvirt issue: https://bugzilla.redhat.com/show_bug.cgi?id=524880

`error : internal error cannot create bridge 'virbr0' : Package not installed`

The new version says:

`error: Unable to create bridge virbr0: Function not implemented`

----

So it seems like there is something wrong with this Manjaro setup, like missing bridge support ?

As in: the actual problem is with libvirt and the distribution, rather than something in minikube...

**Comment by tstromberg** [comment]
Try opening an issue with your Linux distro provider. This sounds like many possible issues:

- https://www.reddit.com/r/archlinux/comments/88lq7k/trying_virtmanager_but_cant_get_nat_to_work/
- https://bugzilla.redhat.com/show_bug.cgi?id=711154
- https://bbs.archlinux.org/viewtopic.php?id=237771
