### ISSUE TITLE
minikube status should show status for all profiles

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4598]
minikube status shows "Stopped" when starting a minikube in a different profile.

```
$ minikube start -p p1
$ minikube status
host: Stopped
kubelet: 
apiserver: 
kubectl: 
$ minikube status -p p1
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.132
```

To recreate  : 
- Start minikube default profile  `minikube start`
- Stop minikube `minikube stop`
- Start minikube in a different profile `minikube start -p p1`
- Get miniube status `minikube status`

Expected : 

I would like minikube status, show status of all profiles, if I don't provide a profile name.

**Comment by josedonizetti** [comment]
I'm working on this.

**Comment by josedonizetti** [comment]
@medyagh A problem we have by implementing `minikube status` to list everything is that `minikube status -p minikube` would also list everything because the `-p` flag is a global flag set at the root level.

https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/root.go#L129

The `-p` value is always `minikube` if you pass it or not. We can't do a simple comparison to check if the `-p` flag was passed or not. I tried overriding the `-p` flag on the status command but it corba does not like it. 

I think to change this behavior isn't simple, cos all commands rely on the initialization done with the `-p` flag to get the machine profile.

Does this make sense? Or I'm losing something?

I was wondering, what about having a flag `--all`, `-a` on the status command, that if passed would have more preference than the `-p` flag.

**Comment by medyagh** [comment]
You pointed out it correctly, yes similar to this 

https://github.com/kubernetes/minikube/issues/4668

It's better than to have a --all flag.
And I would say when showing status we could change the message to make it clear it's showing status for the default profile and they might be looking for another profile. 


I believe the pre-work for both these issues is to have a method that lists all valid profiles .

- by listing the subfolders under profile
- also verifying the config files under those profile folders are valid. ( Json parses to a config object, without error)

**Comment by marekschwarz** [comment]
> You pointed out it correctly, yes similar to this
> 
> #4668
> 
> It's better than to have a --all flag.
> And I would say when showing status we could change the message to make it clear it's showing status for the default profile and they might be looking for another profile. specially if the status is N/A we might wanna suggest them to use the flag to see status of all profiles ( if there are more than one profile)
> 
> I believe the pre-work for both these issues is to have a method that lists all valid profiles .
> 
> * by listing the subfolders under profile
> * also verifying the config files under those profile folders are valid. ( Json parses to a config object, without error)

I'm currently writing a method to get all profiles that only to lists valid profiles (has config.json, parses without errors). What I noticed is, that if you parse a corrupt config.json, it still parses without errors. Is there any kind of validator for the config.json implemented yet? If not, I can implement one.

**Comment by josedonizetti** [comment]
@marekschwarz Great! Thanks. If you need some early review on it, create the PR as `WIP: XXX`.

**Comment by marekschwarz** [comment]
> @marekschwarz Great! Thanks. If you need some early review on it, create the PR as `WIP: XXX`.

I opened a pull-request. There is still a lot to refactor, but I would like to hear what you think :-)

**Comment by tstromberg** [comment]
This is now supported in minikube v1.6 using: `minikube profile list`
