### ISSUE TITLE
minikube error

### ISSUE THREAD

**Issue by counterliu666** [kubernetes/minikube#4626]
X Error restarting cluster: running cmd: sudo kubeadm init phase kubeconfig all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase kubeconfig all --config /var/lib/kubeadm.yaml: exit status 1

**Comment by sharifelgamal** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

The exact command-lines used, so that we may replicate the issue
The full output of the command that failed
The full output of the "minikube logs" command
Which operating system version was used
This will help us isolate the problem further. Thank you!

**Comment by baikunthasahoo** [comment]
getting error while installing minikube 

[root@server1 ~]# minikube start
* minikube v1.3.0 on Centos 7.6.1810
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
*

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the kvm2 driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`
*

* Using the running kvm2 "minikube" VM ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
* Relaunching Kubernetes using kubeadm ...
*
X Error restarting cluster: waiting for apiserver: timed out waiting for the condition
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
* Problems detected in kube-addon-manager:
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
