### ISSUE TITLE
Improve Error message when Kubernetes version asked is too old

### ISSUE THREAD

**Issue by apupier** [kubernetes/minikube#4673]
While investigating n issue I encountered, i discovered that i (mistakenly) mistyped a Kubernetes version and it was causing trouble which was not so easy to understand. It would be nice to improve the error message.

The issue encountered was https://github.com/kubernetes/minikube/issues/4670

@tstromberg is suggesting to add a line here to print a warning if the user requests a version (`nv`) less than `constants.OldestKubernetesVersion`:

https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start.go#L682

to go further:

@tstromberg also suggested:
It doesn’t have to be in the same PR, but we should also check against `constants.NewestKubernetesVersion`. This check is slightly trickier, as we should allow users to specify newer build numbers than we know about (like 1.15.1 rather than 1.15.0), and only check the major.minor version.

**Comment by medyagh** [comment]
Thank you for creating this issue, you pointed out correctly, we should not allow invalid kubernetes versions to too old and fail fast without crashing ! 

I will make sure there will be a PR to handle this, either myself or if you are interested to make a PR, I would be more than happy to review it.

thank you again for helping the user experience on minikube :)

**Comment by medyagh** [comment]
here is a link for supported by kubeadm versions https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Comment by serhatcetinkaya** [comment]
Hi @medyagh, I'd like to work on this issue if that's ok for everyone.

**Comment by medyagh** [comment]
sounds good @serhatcetinkaya I will assign you.

**Comment by medyagh** [comment]
what I would like to see is it shoud exit with error with SUPER old kubernetes versions, and it should warn you with anything which is less than our supported versions.

for example currently kubernetes 1.9 still works with minkube even though it is not supported, but 1.2 does NOT work since it is super old.

**Comment by tstromberg** [comment]
I spoke with @medyagh on this offline, and wanted to add my thoughts here:

- `constants.OldestKubernetesVersion` should reflect the oldest version that is known to pass integration tests. If 1.9 works (I've never tried), the constant should reflect it. Let's keep the code path simple rather than tracking two oldest values.

- All sanity checks should either be a warning, or skippable using a `--force` flag

**Comment by tstromberg** [comment]
This shipped with minikube v1.4.
