### ISSUE TITLE
Minikube logging

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#468]
Right now minikube logs to the `/tmp` folder.  It might be useful for users or support to keep them in the `.minikube` directory or somewhere else (`/var/log`?)  Of course, we might have to think about log rotation then. I don't feel too strongly on this either way, but it might be useful to some. 

Any thoughts on this?

**Comment by jimmidyson** [comment]
~~Kubernetes (localkube) logs go to the persistent disk under /var/lib/localkube/ (see https://github.com/kubernetes/minikube/blob/master/pkg/minikube/constants/constants.go#L65-L68). This was fixed in #301 & available from 0.6.0 onwards. Or are you talking about some other logs?~~

Do you mean client side logs? I wouldn't expect those to be redirected to file at all unless user chooses to do so.

**Comment by r2d4** [comment]
Yup sorry, I meant client side logs for the binary itself.  Upon running `minikube start` without flags, I get a minikube.$USER.log.INFO.$date.

**Comment by jimmidyson** [comment]
Ooo yeah I get the same. I wonder if that is a glog thing?

**Comment by dlorenc** [comment]
It's not documented well, but it looks like glog always logs to a temp dir: https://github.com/golang/glog/blob/master/glog_file.go#L47

**Comment by dlorenc** [comment]
I think we should log to the .minikube/logs directory. This would help debugging issues.
