### ISSUE TITLE
Allow configuration of Kube components

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/minikube#47]
Currently there isn't a way to change localkube's configuration without recompiling. It would be useful if localkube could be configured using a set of YAML files.

**Kube**
* [APIServer](https://godoc.org/github.com/kubernetes/kubernetes/cmd/kube-apiserver/app/options#APIServer) - api.yml
* [KubeControllerManagerConfiguration](https://godoc.org/k8s.io/kubernetes/pkg/apis/componentconfig#KubeControllerManagerConfiguration) - controller-manager.yml
* [KubeletConfiguration](https://godoc.org/k8s.io/kubernetes/pkg/apis/componentconfig#KubeletConfiguration) - kubelet.yml
* [KubeProxyConfiguration](https://godoc.org/k8s.io/kubernetes/pkg/apis/componentconfig#KubeProxyConfiguration) - proxy.yml
* [KubeSchedulerConfiguration](https://godoc.org/k8s.io/kubernetes/pkg/apis/componentconfig#KubeSchedulerConfiguration) - scheduler.yml

**Non-kube**
* [Config](https://godoc.org/github.com/skynetservices/skydns/server#Config) - skydns.yml
* [ServerConfig](https://godoc.org/github.com/coreos/etcd/etcdserver#ServerConfig) - etcd.yml + etcd-skydns.yml

A potential issue is that the structs for API Server, SkyDNS, and Etcd don't have JSON tags.

It would be nice if these could be editable on the host computer (perhaps in `~/.minikube`) and could be synced over to the VM or mounted.

**Comment by luxas** [comment]
I'm working on a large refactor of localkube.
It isn't what you're proposing here, but anyway.
What do you think about mounting the flags from all servers?

**Comment by ethernetdan** [comment]
What do you mean by "mounting flags"?

**Comment by luxas** [comment]
I mean mounting commonly used flags like `--service-cluster-ip-range`, which will in turn be passed to the apiserver. If there would be a way to automatically mount _all_ flags with a server prefix, it would be great. I. e. `--service-cluster-ip-range` for apiserver automatically becomes `--apiserver-service-cluster-ip-range` for localkube.

BTW, are you okay with removing the `start`, `stop`, `status` commands to make `localkube` like the other kubernetes components (flags only)? We would get rid of so much unnecessary complexity, and it would be easier to understand. I'm not understanding either how one is supposed to run status on a binary that's running as a daemon w/ start, but that's just me.

So I would propose to have a flag `--servers` where the user may specify which servers localkube should start, instead of `start`ing multiple localkube servers by hand.

**Comment by ethernetdan** [comment]
I like the idea of allowing parameters for every server by using prefixes. Seems like a very logical way to provide configuration. How do you feel about also providing configuration in files?

The original plan was to have localkube run a server which would allow commands to be sent while it's running (ie. getting status while the binary is running).

The reasoning behind this was to avoid a problem I commonly have with docker-machine where the VM will be running but the daemon is not functioning correctly and typically requires a restart. I wanted to provide a command like tool that could introspect (and act) on it's state. I figured with having so many more components this problem is even worse but I definitely see your point about complexity.

**Comment by Jan-M** [comment]
:+1: for configurability. Having a hard time to figure out how to change --service-node-port-range.

Without this I cannot easily mirror our existing vagrant box - otherwise minikube is great so far.

**Comment by r2d4** [comment]
ref #529

**Comment by aaron-prindle** [comment]
Fixed with #529.  Closing.
