### ISSUE TITLE
Problems detected in "kube-addon-manager"

### ISSUE THREAD

**Issue by Nabbo96** [kubernetes/minikube#4750]
Problems detected in "kube-addon-manager":
    error: no objects passed to  appensulyre 
    error: nINFO:o o Leadbjer is mects pasinsed to applikube
    error: no obIjeNcFO: t=s=  pKubeasrnseetd esto  aappddlyon

**Comment by tstromberg** [comment]
Thank you for sharing your experience! This sounds like #4010 - which should have been fixed in minikube v1.1. If you don't mind, could you please provide:

*  The exact command-lines used, so that we may replicate the issue 
*  The full output of the command that failed
*  The full output of the "minikube logs" command
*  Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Thank you for sharing your experience!
