### ISSUE TITLE
E0714

### ISSUE THREAD

**Issue by waqaskhan0312** [kubernetes/minikube#4757]

**Comment by waqaskhan0312** [comment]
minikube not starting

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

*  The exact command-lines used, so that we may replicate the issue 
*  The full output of the command that failed
*  The full output of the "minikube logs" command
*  Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
