### ISSUE TITLE
Problems detected in "kube-addon-manager"

### ISSUE THREAD

**Issue by IshwarChandra** [kubernetes/minikube#4784]
Getting below error while trying to start minikube. 

Problems detected in "kube-addon-manager":
    error: no objects passed toe a accpply
    error: no objects passed to WRN: apply=
    error: WnRoN: ==  Error getting default service account, retry in 0.5 second ==

**minikube version: v1.1.0**

**Comment by afbjorklund** [comment]
Possibly similar to #4750

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
