### ISSUE TITLE
 StartHost: create: creating: exit status 1

### ISSUE THREAD

**Issue by denisusmpWS** [kubernetes/minikube#4801]

**Comment by denisusmpWS** [comment]
I have problem on initializer service minikube.

This is message:

E0717 20:38:03.963546   16260 start.go:559] StartHost: create: creating: exit status 1

X Unable to start VM: create: creating: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
Hey @denisusmpWS. I'm sorry to hear that you are running into a problem. I don't see the full output, but I suspect this is Hyper-V related. Do you mind sharing:

* The command-line you used to start minikube
* The output of this command-line, but adding these two flags: `--alsologtostderr -v=8`

Thanks!

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=7` for extra logging.

Thank you for sharing your experience!
