### ISSUE TITLE
hyperv: StartHost: start: exit status 1

### ISSUE THREAD

**Issue by narernder** [kubernetes/minikube#4803]
Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing hyperv VM for "minikube" ...
StartHost: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by tstromberg** [comment]
Hey @narernder . I'm sorry to hear that you are running into a problem Do you mind sharing:

* The command-line you used to start minikube
* The output of this command-line, but adding these two flags: `--alsologtostderr -v=8`

Thanks!

**Comment by hemantasingh** [comment]
Hi Thomas Strömberg, 

Unable to setup local minikube environment. Could you please let me know the issue.
Thank you in advance 
[issueLog.txt](https://github.com/kubernetes/minikube/files/3525129/issueLog.txt)

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding `/reopen` to your comment.

Here is additional information that may be helpful to us:

*  Whether this issue exists with the latest minikube release (v1.4)
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
