### ISSUE TITLE
restarting hyperv: StartHost: start: exit status 1

### ISSUE THREAD

**Issue by SRamY** [kubernetes/minikube#4845]
PS C:\WINDOWS\system32> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp 127.0.0.1:8080: connectex: No connection could be made because the target machine actively refused it.

PS C:\WINDOWS\system32> minikube start
* minikube v1.2.0 on windows (amd64)

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the hyperv driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`

* Restarting existing hyperv VM for "minikube" ...
E0723 10:49:40.963913   18336 start.go:559] StartHost: start: exit status 1

X Unable to start VM: start: exit status 1

Windows 10 Enterprise
Activated HyperV also in windows services .

still i'm facing the error.

**Comment by blueelvis** [comment]
Thanks for reporting this!

Could you please paste back the output of the following command? 

`minikube start --alsologtostderr -v=8`

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding `/reopen` to your comment.

Here is additional information that may be helpful to us:

*  Whether this issue exists with the latest minikube release (v1.4)
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
