### ISSUE TITLE
Can't contact gcr - waiting for apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by wangxiaodong628** [kubernetes/minikube#4860]
minikube start --docker-env=HTTP_PROXY=$HTTP_PROXY --docker-env HTTPS_PROXY=$HTTPS_PRO
XY --docker-env NO_PROXY=$NO_PROXY
Error caching images:  Caching images for kubeadm: caching images: caching image C:\Users\user-xyz\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1: fetching remote image: Get https://gcr.io/v2/: dial tcp 74.125.203.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
* Unable to load cached images: loading cached images: loading image C:\Users\user-xyz\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1: CreateFile C:\Users\user-xyz\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1: The system cannot find the file specified.
* Relaunching Kubernetes v1.15.0 using kubeadm ...

X Error restarting cluster: waiting for apiserver: timed out waiting for the condition

**Comment by tstromberg** [comment]
It seems like your host is unable to pull images from gcr.io, possibly due to running from China. Do you mind sharing the output of `kubectl get po -A`?

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
