### ISSUE TITLE
Rework the documentation so that people use the "Default Switch" on Hyper-V

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#4864]
**The exact command to reproduce the issue**: minikube start --vm-driver=hyperv --virtual-switch-name=""

This is something which I have observed on my own machine as well. Instead of asking the users (Atleast on Windows & Hyper-V), to create a new External Switch, use the Default Switch which is provisioned by Hyper-V.

The issue is described over here - https://superuser.com/questions/1266248/hyper-v-external-network-switch-kills-my-hosts-network-performance

If you pass the default switch name, the performance is not affected. 

We need to -
1. Document the issue somewhere in our repo as well.
2. Check if this issue happens on < Windows 10 and if a Default switch is available or not.

-Pranav

**Comment by longwuyuan** [comment]
I don't have logs and screenshots but I was unable to use the default switch and ended up assuming that a manually created external vswitch in HyperV is a required essential. And coupled with the fact that it was a bridge as per my assumptions, I avoided it and moved to virtualbox so that I can have the reliability of NAT and not have to deal with  bridging my wifi interface and impacting my laptop reliability. I hope to add more info when i test hyperv again.
thnx

**Comment by tstromberg** [comment]
Does this mean that minikube already uses the default switch if --virtual-switch-name is not provided?

If so #4079 isn't necessary.

**Comment by blueelvis** [comment]
@tstromberg - No, that is not the case. That PR is necessary but I wonder when it will be merged...

**Comment by longwuyuan** [comment]
if hyperv is to be used, maybe it can be made default on windows

**Comment by tstromberg** [comment]
IMHO, the default switch should be the default for minikube. How do we do so?
