### ISSUE TITLE
4175 start.go:723] StartHost: create: Error creating machine: Error in driver during machine creation: machine didn't return an IP after 120 seconds

### ISSUE THREAD

**Issue by at-huynguyen4-admin** [kubernetes/minikube#5006]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by at-huynguyen4-admin** [comment]
ta can't creat kvm2...please help me
4175 start.go:723] StartHost: create: Error creating machine: Error in driver during machine creation: machine didn't return an IP after 120 seconds

**Comment by tstromberg** [comment]
This issue appears to be a duplicate of #3566, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!
