### ISSUE TITLE
Minikube start issue

### ISSUE THREAD

**Issue by vinothbuj85** [kubernetes/minikube#5009]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
