### ISSUE TITLE
hyperv mount: /mount-dir: mount(2) system call failed: Connection timed out.

### ISSUE THREAD

**Issue by Valgard** [kubernetes/minikube#5029]
**The exact command to reproduce the issue**:
minikube mount "C:\Path\to\mount\dir:/mount-dir" --uid 999 --9p-version=9p2000.L  --alsologtostderr -v=8

**The full output of the command that failed**:<details>
I0809 15:05:04.537573   13984 notify.go:124] Checking for updates...
* Mounting host path C:\Path\to\mount\dir into VM as /mount-dir ...
  - Mount type:   <no value>
  - User ID:      999
  - Group ID:     docker
  - Version:      9p2000.L
  - Message Size: 262144
  - Permissions:  755 (-rwxr-xr-x)
  - Options:      map[]
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
* Userspace file server: ufs starting
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.189.173

[stderr =====>] :
I0809 15:05:06.241585   13984 mount.go:149] Will run: [ "x$(findmnt -T /mount-dir | grep /mount-dir)" != "x" ] && { sudo fuser -km /mount-dir; sudo umount /mount-dir; } || echo
I0809 15:05:06.242231   13984 ssh_runner.go:137] Run with output: [ "x$(findmnt -T /mount-dir | grep /mount-dir)" != "x" ] && { sudo fuser -km /mount-dir; sudo umount /mount-dir; } || echo
I0809 15:05:06.289091   13984 mount.go:62] Will run: sudo mkdir -m 755 -p /mount-dir && sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=999,msize=262144,port=59653,version=9p2000.L 192.168.189.161 /c
heckout-fragment
I0809 15:05:06.290087   13984 ssh_runner.go:137] Run with output: sudo mkdir -m 755 -p /mount-dir && sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=999,msize=262144,port=59653,version=9p2000.L 192.1
68.189.161 /mount-dir
I0809 15:07:14.610443   13984 utils.go:227] ! mount: /mount-dir: mount(2) system call failed: Connection timed out.
I0809 15:07:14.612443   13984 mount.go:64] mount err=Process exited with status 32, out=mount: /mount-dir: mount(2) system call failed: Connection timed out.
W0809 15:07:14.616451   13984 exit.go:99] mount failed: mount: /mount-dir: mount(2) system call failed: Connection timed out.
: Process exited with status 32
*
X mount failed: mount: /mount-dir: mount(2) system call failed: Connection timed out.
: Process exited with status 32
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
[logs.txt](https://github.com/kubernetes/minikube/files/3486475/logs.txt)
</details>

**The operating system version**:
Microsoft Windows 10 Pro 10.0.18362 Build 18362

**Comment by blueelvis** [comment]
Thanks for reporting this issue! Just want to confirm, was this working with the previous version or this hasn't worked ever?

**Comment by Valgard** [comment]
I had not used 'minikube mount' before. so i can not say if it works in a previous version.

**Comment by blueelvis** [comment]
Thanks for reporting this. Let me work on this issue and get back.

/assign

**Comment by tstromberg** [comment]
Do you think this might be resolved by v1.4.0 (Sep 16)? I'd be happy to provide any help.

**Comment by blueelvis** [comment]
@tstromberg - I have my exam on 14th September. Not sure if I can make it till then. Happy to work on this if no one has taken it till then though. WDYT?

**Comment by tstromberg** [comment]
Thanks for the update!

@sharifelgamal has been hacking away at Hyper-V integration testing stability. He may have cycles to take this on, especially if it's broken in our CI environment. Good luck with the exam!

**Comment by avinashmeda** [comment]
@blueelvis  :Does this also hold good for a Virtual Box Hypervisor ?  A known issue ?

**Comment by tstromberg** [comment]
@avinashmeda - Due to the nature of the issue, my gut instinct says this is a Windows issue rather than a Hyper-V specific issue. Have you seen it in VirtualBox?

**Comment by avinashmeda** [comment]
@tstromberg : Yes its Virtualbox and windows issue. Little more light. I also verified the firewall rules that minikube adds, and it seemed fined ( cross verified with the firewall logs and there were no packet drop)

**Comment by blueelvis** [comment]
Wait. I am not clear. You are confirming what Thomas said right? That even
using Windows & Virtualbox did not fix the mounting issue, right?

**Comment by blueelvis** [comment]
@avinashmeda @Valgard - I was able to replicate the issue on my machine. Thanks for reporting this! Could you please follow the below guide and see if your issues are resolved or not?

----
If you are on Windows, you might see an error where the mounting command errors like below -
```
I0809 15:07:14.612443 13984 mount.go:64] mount err=Process exited with status 32, out=mount: /mount-dir: mount(2) system call failed: Connection timed out.
W0809 15:07:14.616451 13984 exit.go:99] mount failed: mount: /mount-dir: mount(2) system call failed: Connection timed out.
: Process exited with status 32
*
X mount failed: mount: /mount-dir: mount(2) system call failed: Connection timed out.
: Process exited with status 32
```

What this technically means is that 9P client inside minikube was not able to connect to the Host. This generally happens when your Firewall is blocking the incoming connection to the host for file sharing. I was able to replicate this on my Hyper-V machine and pretty sure that this would be the case with Virtualbox as well.

In order to resolve this issue, please follow the below steps (These need to be followed only once and require Administrator privileges.)-
1. Open up an Administrator PowerShell Prompt.
2. Type in the following query -
```
Get-NetFirewallRule | Where-Object { $_.Name -match "minikube" } | Remove-NetFirewallRule
```
3. Once the command has completed, run your mounting command again.
4. This time, Windows Defender Firewall will ask your for permissions.
5. Allow the minikube executable access to the Private & Public networks and click on "Allow".

If you install a new version, you *might* have to redo these steps.

If you are using some 3rd party Firewall, please follow the below steps -
1. Fire up your cluster.
2. Once your cluster has started, run `minikube ip`. Note down the IP address which is outputted.
3. For example, if the IP address you get is `192.168.215.103`, then you need to allow INBOUND communication to your system from the range - `192.168.215.0-192.168.215.255`
----


/cc: @tstromberg - This most likely is being caused because the executable is not signed and Windows Firewall (at least) is having a hard time recognizing it... So, it is blocking all the inbound communication to the executable.

**Comment by avinashmeda** [comment]
@blueelvis : We did follow your steps and it still doesnt seem to work.Verified with the rules as well. They seem to be alright as i mentioned earlier

**Comment by blueelvis** [comment]
@avinashmeda @Valgard - Did you get a chance to try the above instructions?

**Comment by prasy-loyola** [comment]
The NetFirewallRule for minikube was like this. Clearly inbound was blocked.
>Name                  : {22FC9B74-EB8A-4BED-A314-4208E3446349}
>DisplayName           : minikube
>Description           : minikube
>Direction             : Inbound
>Action                : Block

As the Name is a GUID in the NetFirewallRule, you have to use the below command.
> Get-NetFirewallRule | Where-Object { $_.**DisplayName**-match "minikube" } |  Remove-NetFirewallRule
This fixed the problem for me.

**Comment by tstromberg** [comment]
I believe this also affects not-hyperv uses on Windows, FWIW.

**Comment by sharifelgamal** [comment]
This is still an outstanding issue affecting all Windows users.
