### ISSUE TITLE
(meta) Make Windows/Hyper-V a first-class solution

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5072]
Here are the issues to be resolved:

* <del>Hyper-V: Use the "Default Switch" (NAT based) by default - #4079 </del>
* <del>Hyper-V: Stable integration testing #3591</del>
* <del>Hyper-V: minikube mount fails with windows 10 default switch - #3591</del>
* [NON_C_DRIVE] when run from C:\ but user config is on different drive - #4079 

Please feel free to comment with any others that cause a large user experience gap for users of Windows + Hyper-V.

**Comment by orthoxerox** [comment]
Being able to run minikube as a non-admin user on Windows is pretty important if you value enterprise adoption of minikube. 

Docker Desktop, for example, achieves this by running a privileged service that creates and destroys VMs when commanded by a non-privileged application launched by the user.

**Comment by tstromberg** [comment]
@orthoxerox - Understood. I personally am not a fan of that model, as it subverts the more typical Hyper-V Administrators ACL: https://blogs.msdn.microsoft.com/virtual_pc_guy/2014/06/11/allowing-non-administrators-to-control-hyper-vupdated/

**Comment by orthoxerox** [comment]
@tstromberg I think the idea was to allow the user to create and run just one VM, the only with MobyLinux on it. Making a user a Hyper-V admin allows them to create and run all possible VMs.

**Comment by brainfull** [comment]
I spent the last few days on installing minikube on Windows 10 Pro with Hyper-V and went through a lot of problems. So here are the problems I faced and how I solved. I hope it will be useful.

1. External VM Switch : While it is easy to setup an external VM switch, it goes through your network DHCP server to get an address and you cannot put your laptop to sleep and open it under another Wi-Fi network and oping that everything runs fine. You would have to restart Minikube everytime. So it's better to go with internal VM Switch.

2. Internal VM Switch : There are many advantages to use internal VM Switch but there's a lack of understanding overall on the web about it. 
 2.1 First, it is necessary to setup an old Windows technology called ICS (Internet Connection Sharing) which deploys its own internal ICS DHCP server. This allows to connect to another Wi-Fi network without having trouble to restart minikube. 
 2.2 Second, it comes with a neat feature of assigning an hostname to your VM. For example, if your VM is called 'minikube' you will be able to connect to it through minikube.mshome.net which is defined under C:\Windows\System32\drivers\etc\hosts.ics automatically. Everytime you restart minikube the hostname will be updated with the latest IP address assigned by the internal ICS DHCP server. So there's no need to try to setup a static IP address or setup a hostname in the hosts file by yourself.
 2.3 However, everytime you reboot your computer, even if the ICS settings survived, somehow minikube is not able to start correctly. So it is necessary to disable ICS and re-enable it again between your Wi-FI and the internal VM switch. That is why I came with my powershell script that does it for me. I copied it in the comment for your pleasure. I call the powershell script automatically just before 'minikube start'. Essentially, it creates the internal VM switch if it doesn't exist, it disable whatever ICS settings that pre-existed, it setups ICS between the internet connection and the internal VM switch.
[Set-ICS - Copy.ps1.txt](https://github.com/kubernetes/minikube/files/3811870/Set-ICS.-.Copy.ps1.txt)

3. Kubectl : Unfortunately the kubernetes client that get installed on your machine keeps a cache that may become a problem when your minikube VM IP address changes. So it is better to delete C:/Users/<username>/.kube (same as %userprofile%/.kube) before every 'minikube start'. This way you ensure that the old kubernetes cache will not interfere with your new minikube state.

4. Docker Build : For some reason when you restart minikube many times you end up with a very slow docker build. Somehow, pulling images like ubuntu or simply calling apt-get within ubuntu will get very slow. And I finally found out why by looking at the network usage on my internal VM Switch. On my side I wanted to install only docker-cli on my machine and use docker installed within minikube by invoking 'minikube docker-env', which is pretty simple setup without the need to spend time configuring Docker on Windows and minikube altogether. While it works very well, sometimes the network bridge that is created between docker-cli and minikube container during the build process is very slow and the pull image will literally get stuck for many minutes. To avoid this problem always build images with 'docker build .... --network host'. This way you make sure the docker image that is currently building is using the network within minikube VM, not using a bridge between your machine and the container within minikube VM, which can become very slow. 

So that's it for today. I'll post other findings if I still get problems. I definitely find there is a lack of documentation on minikube on Windows.

But for now I am pretty happy with my dev environment on my laptop and it allows to automate the deployment, the debug and the test. I even built an ubuntu image with open-ssh and python so I can setup a Remote Interpreter in Pycharm that allows me to debug directly within the running container, the code need to access other containers for MongoDB and Redis... I find minikube amazing because it allows me to create from scratch a test environment with 5 different docker images under 30 minutes. And I know I have a similar environment to what I'll get in production in my cloud provider even if my laptop is Windows 10 :(

**Comment by brainfull** [comment]
#5812

**Comment by kfox1111** [comment]
Defaulting to internal switch like the other platforms would be very good. Some sites, like my org's capture unknown mac address dhcp requests and assign them temporary ip's and isolate traffic until they agree to some terms of service / register some additional information. Making it unsuitable for minikube. Internal switch with nat works fine though as the host is already registered.

**Comment by brainfull** [comment]
> Defaulting to internal switch like the other platforms would be very good. Some sites, like my org's capture unknown mac address dhcp requests and assign them temporary ip's and isolate traffic until they agree to some terms of service / register some additional information. Making it unsuitable for minikube. Internal switch with nat works fine though as the host is already registered.

FYI If you would need to set a pre-defined mac address on the minikube VM this is the script to do it. It could be nice to have a feature in minikube to set that mac address automatically on 'minikube start ... --mac-address ....'.

The following in Powershell works fine but is cumbersome because you need to start and stop and start again. And you need to redo it everytime the VM is deleted.
`
minikube start
minikube stop
Set-VMNetworkAdapter -VMName minikube -StaticMacAddress 00-15-5D-2B-D9-26
minikube start
`

**Comment by kfox1111** [comment]
yes, but you still need a mechanism to get that mac address either preregistered with the network, or get a web browser in the vm long enough to do the registration, before minikube starts trying to fetch artefacts. Either way, not a great user experience. Defaulting to internal and making nat work out of the box like the other platforms would be seamless/much preferred.

**Comment by medyagh** [comment]
this is still on our roadmap !

**Comment by dsebastien** [comment]
Really interested in seeing progress for this.

I've spent the whole day trying to make things work for my use case.

I had trouble getting the Minikube VM to access internet (I suppose because I didn't do anything for ICS with the default switch?). I hoped everything would workd OOB but it didn't :)

I ended up using an external vSwitch in Hyper-V which fixed that issue, but now my problem is that I can only access the VM ports when using minikube tunnel, through the unstable IP.

The problem is that our setup within K8S uses an Nginx ingress which maps the "localhost" host to some web service, which of course does not work when the host header is set to... something else.. :)

On Linux this setup works fine because I can setup port forwarding to the host using commands such as:
`vboxmanage controlvm "minikube" natpf1 "blabla,tcp,127.0.0.1,4200,,30000"`

I could work around this by forwarding the ports exposed by the Hyper-V VM using commands such as: `netsh interface portproxy add v4tov4 listenaddress=127.0.0.1 listenport=4200 connectaddress="$(minikube ip)" connectport=30000`.

This seems to work but of course remains fragile as the Minikube VM IP on my network is not stable and will be different for each developer (assuming an heterogeneous environment). For the moment I'm just re-executing those commands in my start script (right after `minikube start`), but this ain't great as it requires admin rights if I'm not mistaken (same for `minikube start` though).

I suppose I could indeed define a static Mac after the VM's creation and register that on my network but this feels flaky and tiresome, plus it puts too many expectations on things outside of my scripts control.

I'm really hoping for something better/simpler :)

**Comment by tstromberg** [comment]
Related: #6264

**Comment by tstromberg** [comment]
I think we should be able to close this once v1.9 is released, given the improvements to hyper-v deletion. The rest of the major issues seem sorted out.

That is not to say that Windows support is completely bug-free or as well tested as other platforms, but that we should track those issues with a finer granularity.

**Comment by tstromberg** [comment]
Closing because we've reached enough parity that we can now track this via individual issues. Thank you for your patience!
