### ISSUE TITLE
Consider using TUF for update checks and downloading the ISO/localkube binaries

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#508]
If this is a FEATURE REQUEST, please:
- Describe _in detail_ the feature/behavior/change you'd like to see.

See details here: https://theupdateframework.github.io/

There's a Go library here: https://github.com/flynn/go-tuf

**Comment by r2d4** [comment]
SGTM.  This would be a lot better and more secure than trying to roll our own.  

What are the key differences between [flynn/go-tuf](https://github.com/flynn/go-tuf) and [docker/notary](https://github.com/docker/notary)?  Seems like they are both go implementations of TUF.

**Comment by philips** [comment]
cc @ecordell

**Comment by ecordell** [comment]
Notary is actually a fork of go-tuf that implements more of the TUF spec and adds a few things on top of it (db storage support and a server/signer/client split) to support a production deployment. The `tuf` folder in the notary repo is almost exactly the same as `go-tuf` (IMO this should be upstreamed, but if you look through the GH issues/commits there was some point where they felt it had diverged too much; IIRC mainly by deprecating the command-line tuf client and replacing it with the server-aware notary client).

In my opinion: If the plan is for maintainers to be very hands-on with the TUF metadata, go-tuf is a fine choice because it gives you a simple tool to modify a set of TUF metadata files, which you can then host statically and clients can pull and verify. TUF is designed with this simple case in mind, a cron job or something can update the timestamp metadata (which would be the only online key in the simple case). If you instead need to support multiple users modifying metadata, coordinating signing, etc, I think notary is a better choice.
