### ISSUE TITLE
Upgrade nginx ingress to 0.25.1

### ISSUE THREAD

**Issue by declum** [kubernetes/minikube#5178]
Current minikube uses nginx-ingress 0.25.0. 

Can you please update it to latest 0.25.1? It has support for php-fpm.

**Comment by tstromberg** [comment]
Hey @declum 

I believe this can be fixed by editing the version here:

https://github.com/kubernetes/minikube/blob/master/deploy/addons/ingress/ingress-dp.yaml.tmpl#L45

and then running `make` to build a new release using it. Do you or someone else mind trying to see if v0.25.1 works properly in minikube?

**Comment by RA489** [comment]
nginx ingress has been upgraded to 0.25.1 and it works properly in minikube.

**Comment by n0npax** [comment]
Hey guys. The task seems to be done. Could you please close it?

**Comment by tstromberg** [comment]
Fixed by https://github.com/kubernetes/minikube/pull/5197
