### ISSUE TITLE
sudo none: Please run with sudo. the vm-driver "none" requires sudo.

### ISSUE THREAD

**Issue by ArsenyZorin** [kubernetes/minikube#5259]
**The exact command to reproduce the issue**:
```
sudo minikube --vm-driver=none start
```

**The full output of the command that failed**:<details>
```
😄  minikube v1.3.1 on Arch rolling
💡  Please run with sudo. the vm-driver "none" requires sudo.
```

</details>

**The output of the `minikube logs` command**:<details>

```
💣  Error getting config: stat /home/azorin/.minikube/profiles/minikube/config.json: no such file or directory

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

</details>

**The operating system version**:

* OS: Arch Linux
* kernel: 5.2.11-arch1-1-ARCH

**Comment by tstromberg** [comment]
Hey @ArsenyZorin 

I suspect we've fixed this at head, but do you mind sharing the output of:

`sudo id`

Thanks!

**Comment by ArsenyZorin** [comment]
@tstromberg, yes. Here it is:
```
➜ sudo id
uid=0(root) gid=0(root) groups=0(root)
```

**Comment by tstromberg** [comment]
@ArsenyZorin - Bizarre. I'm not sure what's going on there. Do you mind trying minikube v1.4.0 beta and report back on whether or not it fixes the problem?

For consistency, I would tell it to use Kubernetes v1.15.2 so that you aren't accidentally upgraded to Kubernetes v1.6.0-beta (particularly because downgrades aren't supported!)

`sudo minikube --vm-driver=none start --kubernetes-version=v1.15.2`

**Comment by ArsenyZorin** [comment]
@tstromberg, hello again.
Yes, minikube v1.4.0 beta fixed the problem. Thank you!

**Comment by tstromberg** [comment]
excellent. Thank you for the update! Will mark as closed then.
