### ISSUE TITLE
Error getting host status: permission denied (sudo mismatch)

### ISSUE THREAD

**Issue by fahad03361126193** [kubernetes/minikube#5266]
![Screenshot from 2019-09-05 06-50-01](https://user-images.githubusercontent.com/46647834/64318401-7e7c2a80-cfa9-11e9-9758-f3ba66c0d3ad.png)

**Comment by tstromberg** [comment]
The issue here is that once you run minikube with sudo, all subsequent commands will need to be run with sudo. Please heed the warning and do not run minikube with sudo. 

My suggestion, is to run `sudo minikube delete`, and then run minikube without sudo from then on.

If you really really must run "minikube start" as root, you can workaround this by running:

`sudo chown -R $SUDO_USER ~/.minikube ~/.kubeconfig` 

Please let me know if this helps.

**Comment by tstromberg** [comment]
minikube v1.4 helps the situation a bit in that it no longer allows VirtualBox to be run as root.

That said, this is solvable by using `sudo chown -R $USER ~/.minikube ~/.kubeconfig
