### ISSUE TITLE
hyperv: NOT ENOUGH MEMORY TO START A MINIKUBE

### ISSUE THREAD

**Issue by Saim1** [kubernetes/minikube#5286]
minikube start --vm-driver="hyperv" --hyperv-virtual-switch="Minikube"

When i run this command docs tell me i am able to see the minikube cluster but i am getting this error "NOT ENOUGH MEMORY TO START A MINIKUBE" can anybody tell me what went wrong? How can i am able to run minikube.

**Comment by tstromberg** [comment]
Do you mind sharing the full output of:

`minikube start --vm-driver="hyperv" --hyperv-virtual-switch="Minikube" --alsologtostderr -v=1`

and:

`systeminfo`

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
