### ISSUE TITLE
X Unable to start VM: create: creating: exit status 1 -- On windows10

### ISSUE THREAD

**Issue by bodachaitanya** [kubernetes/minikube#5288]
**The exact command to reproduce the issue**:
minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"

**The full output of the command that failed**:<details>

PS C:\WINDOWS\system32> minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"
* minikube v1.3.1 on Microsoft Windows 10 Enterprise 10.0.16299 Build 16299
* Downloading VM boot image ...
minikube-v1.3.0.iso.sha256: 65 B / 65 B [--------------------] 100.00% ? p/s 0s
minikube-v1.3.0.iso: 131.07 MiB / 131.07 MiB [-------] 100.00% 3.58 MiB p/s 37s
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0907 14:37:34.441895   15272 start.go:723] StartHost: create: creating: exit status 1
*
X Unable to start VM: create: creating: exit status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
Windows10

**Comment by tstromberg** [comment]
Hey @bodachaitanya -

Sorry to hear that minikube isn't working for you yet. It seems like minikube isn't able to correctly work with Hyper-V,  likely due to a small configuration issue: Do you mind sharing the output of these 3 commands so that I can make the appropriate suggestion?

* `minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch" --alsologtostderr -v=1`
* `systeminfo`
* `Get-VMSwitch -SwitchType External`

Thank you!

**Comment by tstromberg** [comment]
@bodachaitanya  - I believe this issue is now addressed by minikube v1.4, as it no longer requires a virtual switch to be defined. If you still see this issue with minikube v1.4 or higher, please reopen this issue by commenting with `/reopen`

Thank you for reporting this issue!
