### ISSUE TITLE
Minikube should (build and) use the latest localkube binary

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#53]

**Comment by dlorenc** [comment]
Here's what I'm thinking here:

Building minikube from scratch should do the following:

- build localkube for linux/amd64 with cgo enabled
- run go-bindata to add the localkube binary to the minikube source
- build minikube for the target platform

Then when you start the cluster, minikube can transfer the file to the VM from memory.

This has a few problems though:

- building localkube is slow
- cross compiling with cgo is hard

So we could have a second, "quick" compile mode for minikube that uses a separate build of localkube instead of building one from head.

Then whenever someone changes localkube, we'll update the separate build of localkube as well.

Thoughts?

**Comment by dlorenc** [comment]
Closed with #66
