### ISSUE TITLE
minikube start: Allow Hyper-V virtual switch to be configured

### ISSUE THREAD

**Issue by jcjf** [kubernetes/minikube#561]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

Equivalent functionality to ``--hyperv-virtual-switch`` in Docker Machine

**Minikube version** (use `minikube version`):
0.9.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikubeVM/config.json | grep DriverName`): hyperv
- **Docker version** (e.g. `docker -v`): 1.12.0
- **Install tools**:
- **Others**:

**What happened**:
Error creating machine: Error detecting OS: OS type not recognized

**What you expected to happen**:
Success!

**How to reproduce it** (as minimally and precisely as possible):
``minikube start --vm-driver=hyperv``

**Anything else do we need to know**:

**Comment by aaron-prindle** [comment]
This is a good idea, we will try to get this in.

**Comment by swinterberger** [comment]
It appears as though you can set the hyper-v switch via the ENV variable HYPERV_VIRTUAL_SWITCH

**Comment by indcoder** [comment]
@swinterberger Well I tried your suggestion of setting the switch via the Env variable HYPERV_VIRTUAL_SWITCH  but it does not work. It still picks up the Virtual Swtch created first (even though its internal)

**Comment by swinterberger** [comment]
I'm not sure I follow.  It being internal/external has nothing to do with the selection.  It must either be the only vswitch in the list, queried first (somehow) or specified via ENV VAR.  The specified switch must also be set to external or it won't work at all.  Granted a new ver of minikube has released since I posted that but I still use it this way because I have multiple vswitches and without the ENV var it will not choose my external.

I am on a windows machine (booo) so maybe that is the difference.
