### ISSUE TITLE
Cannot start minikube on macOS Catalina 

### ISSUE THREAD

**Issue by venkateshreddypala** [kubernetes/minikube#5625]
**minikube start**:

**cannot verify the developer **: followed by a prompt to terminate 

**macOS Catalina**:

**Comment by afbjorklund** [comment]
Duplicate, #5568

**Comment by tstromberg** [comment]
This issue appears to be a duplicate of #5568, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!
