### ISSUE TITLE
virtualbox: Minikube often goes to paused state

### ISSUE THREAD

**Issue by anthonma** [kubernetes/minikube#5634]
Minikube gets often in paused state.
Could you please tell me what could be the cause of it and how to fix it.

I'm starting minikube with:
````
minikube start --memory=5120 --kubernetes-version=v1.15.4
````

**The exact command to reproduce the issue**:
-/-

**The full output of the command that failed**:
-/-

**The output of the `minikube logs` command**:
I've tried to get the logs via minikube logs, but I nether I got output nor the command terminated, so I stopped th command after about 10 minutes.

**The operating system version**:
minikube version: v1.4.0
OS: Windows 7

**Comment by tstromberg** [comment]
Could you provide the exact output of the `minikube start` command that you used? I am curious what VM driver you are using. I suspect VirtualBox.

minikube itself does not support pausing a VM, so the pausing is coming from your hypervisor or something monitoring your hypervisors status.  Also, what version of VirtualBox are you running?

**Comment by anthonma** [comment]
This is the output of the minikube start command:
````
* minikube v1.4.0 on Microsoft Windows 7 Professional Service Pack 1 6.1.7601 Build 7601
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing virtualbox VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Found network options:
  - NO_PROXY=192.168.99.100,192.168.99.101
  - no_proxy=192.168.99.100,192.168.99.101
* Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...
  - env NO_PROXY=192.168.99.100,192.168.99.101
  - env NO_PROXY=192.168.99.100,192.168.99.101
* Relaunching Kubernetes using kubeadm ...
* Waiting for: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "minikube"
````
The version of VirtualBox is 5.2.20

**Comment by anthonma** [comment]
Since I'm still facing this issue, I would appreciate any kind of help.

**Comment by tstromberg** [comment]
@anthonma - This appears to be a VirtualBox issue rather than a minikube issue, so I spent some time hunting out some reasons why. Some possibilities I found were:

- If your machine is running low on memory. How much memory does your machine have? minikube requires 2.1GB of RAM to be available
- There are evidently some power management settings so that idle VM's get automatically paused: https://forums.virtualbox.org/viewtopic.php?f=1&t=37426

Do you mind checking your VirtualBox preferences to see if anything looks obvious?

One thing that would help is a VirtualBox log. https://support.oracle.com/knowledge/Sun%20Microsystems/1342727_1.html has some info as to how to find the log - it may say why the VM was suspended.

**Comment by anthonma** [comment]
Because of an change of the environment I use, this issue is obsolete, at least for now, so I'll close it.
