### ISSUE TITLE
error: no oIbjectsN passFed toO appl: == y

### ISSUE THREAD

**Issue by jxhsjxhs** [kubernetes/minikube#5744]
Problems detected in kube-addon-manager [d40cbccfdfb8]:
    error: no oIbjectsN passFed toO appl: == y

mac os 10.14.6

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by medyagh** [comment]
@jxhsjxhs do you still need help on this issue ?

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
