### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by quany** [kubernetes/minikube#5788]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by medyagh** [comment]
@quany are you still having this issue ?
