### ISSUE TITLE
none: "start" may declare success prematurely immediately after "stop"

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5795]
With the none driver, if you run:

"minikube start"
"minikube stop"
"minikube start"

You may run into a situation where the apiserver health check passes, but found the old apiserver process instead, that is subsequently restarted, so a call to the apiserver fails. This mostly manifests with unreliable integration testing.

**Comment by tstromberg** [comment]
One could argue that "stop" should also block until the apiserver pod is down, but to be fully robust, "start" needs to also learn to deal with it.

**Comment by vamossagar12** [comment]
@tstromberg This issue is open and has some work to be done? I would like to take a shot at it.

**Comment by medyagh** [comment]
@vamossagar12 yes it is open, it is yours, please feel free to ask questions

**Comment by medyagh** [comment]
@vamossagar12 thats correct and it only work on linux and currently needs sudo.

**Comment by vamossagar12** [comment]
thanks @medyagh . i am currently running kubernetes using docker for mac on my mac os. I would need linux to be able to test/work upon this?

**Comment by medyagh** [comment]
@vamossagar12 mac and linux should be acting the same in this case. plus we have integration tests in linux, so you will the results once make the PR. you dont need to get a linux box :)

**Comment by medyagh** [comment]
for running the integration tests locally you would need a linux box,

you could alternatively also run none driver inside a linux vm on your mac !

**Comment by vamossagar12** [comment]
Hi @tstromberg , @medyagh I wanted to do a few test runs on 1 of the ubuntu vms that I have(18.04.3) but I bumped into the issue mentioned here:

https://github.com/kubernetes/minikube/issues/4835

I have added the things requested for, in case somebody notices this issue again in that issue. Please let me know in case of any other details needed.

**Comment by vamossagar12** [comment]
Also, @tstromberg while going through the code, I noticed that there have been changes made yesterday on the waitForPods method. You have split the process finding and api server finding into 2 methods and added a new method called waitForCluster to block until the api-server isn't healthy:

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/bootstrapper/kubeadm/kubeadm.go#L442

I was thinking along the same lines to fix this issue. What I had in mind though was before checking the api server status, can we check if the pid of the api-server has changed- assuming that it changes across minikube restarts. It didn't change when I started and restarted minikube but that could also be because I could never start it properly because of the above error.

**Comment by vamossagar12** [comment]
hi @tstromberg did you get a chance to look at my last 2 comments?

**Comment by vamossagar12** [comment]
hi @tstromberg , so I was able to replicate the issue on a linux box. Honestly, it took me some time because of some of the other issues with minikube start(highlighted above) and then not always was I getting this issue. After running minikube start->stop->start, I sometimes get this exception which leads to the failure of minikube start:

```
💣  Error restarting cluster: addon phase cmd:"/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml\"": command failed: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml"
stdout: [addons]: Migrating CoreDNS Corefile
[addons] Applied essential addon: CoreDNS


stderr: error execution phase addon/kube-proxy: error when creating kube-proxy RBAC rules: unable to create RBAC clusterrolebinding: etcdserver: request timed out
To see the stack trace of this error execute with --v=5 or higher
: exit status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

This is during the restartCluster phase in kubeadm, where there are multiple phases that are being run 1 after the another. It happens for the addon phase when trying to create kube-proxy via kube-apiserver. The apiserver health check and psgrep command ran successfully (as per the logs and since this addon phase is run after the apiserver health checks. 

The manifest file local etcd file is also generated but it times out while reaching out to etcdserver when trying to create RBAC rules for kube-proxy. 1 question that I have is, at what point would the kubelet create the pods once this manifest files are created? 

One more thing to note is that, before running the kube-proxy phase, there's also a step for waiting for system pods. So, if any errors were there while reaching out to etcd, it should have been caught there itself, so I am not sure why would it time out.

Would it make sense to wait for etcd server explicitly just like we do for api-server before running the kube-proxy phase?

Lastly, is this the error that you had encountered when you had filed this issue? Or was it some other issue?

**Comment by tstromberg** [comment]
My gut instinct here is that `stop` was not stopping all of the Kubernetes pods, so that when Kubernetes came back up, it had a false sense of things running.

If the kube-proxy step requires etcd to be running, we should definitely probably be waiting for etcd before executing that step.

I don't recall the error I was running into before, just the observation that the apiserver appeared to  restart after a stop & start cycle, hinting to me that perhaps the apiserver running at first was an old one.
