### ISSUE TITLE
proxyconnect tcp: tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by asynclox** [kubernetes/minikube#5797]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command

Thank you for sharing your experience!

**Comment by DAAC** [comment]
when I running this command minikube start --cpus 2 --memory 4096,
 I am getting this issue:
! minikube v1.5.2 on Microsoft Windows 10 Enterprise 10.0.15063 Build 15063
E1119 12:39:07.353979   70432 driver_windows.go:74] Can't find VirtualBox registry entries, is VirtualBox really installed properly? The system cannot find the file specified.
* Automatically selected the 'hyperv' driver
* Downloading VM boot image ...
*
X Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.5.1.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.5.1.iso.sha256: proxyconnect tcp: tls: first record does not look like a TLS handshake
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose


I used this link https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
in order to set the proxy on window

**Comment by rezabojnordi** [comment]
> my error lts

> for run minikube singe cluster and run dashboard kubernetes
> kubectl proxy 

`Error trying to reach service: 'tls: first record does not look like a TLS handshake'`

please healp me

**Comment by rezabojnordi** [comment]
using command 

`minikube logs`

> Error syncing pod a6018c70-bcfe-4d00-9ea8-5b0beb66f1b8 ("kubernetes-dashboard-5996555fd8-dwzjs_kubernetes-dashboard(a6018c70-bcfe-4d00-9ea8-5b0beb66f1b8)"), skipping: unmounted volumes=[tmp-volume kubernetes-dashboard-token-c6gf9 kubernetes-dashboard-certs], unattached volumes=[tmp-volume kubernetes-dashboard-token-c6gf9 kubernetes-dashboard-certs]: timed out waiting for the condition

**Comment by medyagh** [comment]
@rezabojnordi  do you mind sharing what driver do you use ?
and do you happen to be using a vpn ?

**Comment by medyagh** [comment]
@rezabojnordi  I haven't heared from you, I will close this issue please feel free to reopen
