### ISSUE TITLE
sudo dashboard crash: Error getting machine status: state: machine does not exist

### ISSUE THREAD

**Issue by jeger** [kubernetes/minikube#5807]
Trying to run 
sudo minikube dashboard

ends up with output: 
💣  Error getting machine status: state: machine does not exist

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

but it works alright with just minikube dashboard

**Comment by tstromberg** [comment]
This is because minikube clusters are per-user: when you run "sudo", you are running minikube as a different user (root -- not recommended), which does not know about the cluster.

Anyways, minikube should not "crash", but simply mention that it can't see the cluster. Leaving open as a bug because of that.

**Comment by medyagh** [comment]
as tstromberg  mentioned, we should not crash on this ! we could replace the crash with a solution message that user doesn't need sudo for it !

**Comment by priyawadhwa** [comment]
This seems to have been fixed by https://github.com/kubernetes/minikube/pull/7176
