### ISSUE TITLE
Feature: new release link on front page of website

### ISSUE THREAD

**Issue by nanikjava** [kubernetes/minikube#5832]
Website is the first place that normally user goes to find something. What if we update the front page of the website when new releases happen ?. Maybe some sort of a link to the latest version.

Screenshot shows the idea.

Comment and suggestions welcome !.

![ReleaseNotification](https://user-images.githubusercontent.com/883406/68184416-1078d180-fff3-11e9-92bd-a64c237ed7a6.png)

**Comment by nanikjava** [comment]
Happy to take on the job of updating the website everytime there is a new release :+1:

**Comment by medyagh** [comment]
I would like an easy access to download on first page, however at the same time the minikube first page is getting a bit crowded.
I would like to see a more simple minikube website front page. 


@tstromberg

**Comment by medyagh** [comment]
@nanikjava currently we have Two links to github on the front page, I recommend removing one of them and replacing them with the Link to the Latest release download page.

**Comment by nanikjava** [comment]
![Screenshot from 2019-11-08 07-08-56](https://user-images.githubusercontent.com/883406/68424541-581c7a80-01f8-11ea-9a84-6ff35d5d74b8.png)

@medyagh is the diagram correctly highlight the part that need to be changed to point to download the latest release ?

**Comment by nanikjava** [comment]
PR submitted https://github.com/kubernetes/minikube/pull/5879

**Comment by afbjorklund** [comment]
I think the idea was that the "Getting Started" would have a link to the download...

Especially since there are **so** many steps involved, to choosing-the-right-binary.

1)
 Linux
 macOS
 Windows

2)
 Direct
 Debian/Ubuntu (deb)
 Fedora/Red Hat (rpm)

3)
 KVM
 VirtualBox
 None (bare-metal)

etc) etc) etc)

These are not very easy to figure out, given just a list of names of cryptic binaries ?

Normally the user only wants **one** of these, probably same as their browser OS...

- docker-machine-driver-hyperkit
- docker-machine-driver-hyperkit.sha256
- docker-machine-driver-kvm2
- docker-machine-driver-kvm2.sha256
- minikube-1.5.2.rpm
- minikube-darwin-amd64
- minikube-darwin-amd64.sha256
- minikube-installer.exe
- minikube-linux-amd64
- minikube-linux-amd64.sha256
- minikube-windows-amd64.exe
- minikube-windows-amd64.exe.sha256
- minikube_1.5.2.deb

**Comment by nanikjava** [comment]
To make things simpler for user the link on the front page will point to the /release page. This way the user will choose the correct binary for their needs
