### ISSUE TITLE
windows: timeout acquiring mutex (minikube v1.6)

### ISSUE THREAD

**Issue by chandu14017** [kubernetes/minikube#5857]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by moussa21** [comment]
PS C:\WINDOWS\system32> minikube start
* minikube v1.6.0 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
* Selecting 'hyperv' driver from existing profile (alternates: [])
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Using the running hyperv "minikube" VM ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
*
X Failed to setup kubeconfig: writing kubeconfig: Error writing file C:\Users\Baldemou/.kube/config: error acquiring lock for C:\Users\Baldemou/.kube/config: timeout acquiring mutex
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32>
