### ISSUE TITLE
I can't run k8s in WSL2

### ISSUE THREAD

**Issue by mituso89** [kubernetes/minikube#5963]
![image](https://user-images.githubusercontent.com/29556841/69476515-6cbe5c80-0e0d-11ea-8c74-7eca71e0c671.png)

Pls help me. k8s in my windows is available. However i can't run k8s in wsl2
![image](https://user-images.githubusercontent.com/29556841/69476549-d0488a00-0e0d-11ea-986b-a8756045ef4e.png)

**Comment by telefoontoestel** [comment]
Are you sure that the kubectl binary in wsl is pointing to the same kubectl binary in Windows? It might be that these are different binaries and therefore have different config files. Try to run the `kubectl version` and `kubectl config view` commands in both environments and check that they output the same information.

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
