### ISSUE TITLE
Add installation documentation for ARM64

### ISSUE THREAD

**Issue by chendave** [kubernetes/minikube#6159]
The guide here: https://minikube.sigs.k8s.io/docs/start/linux/ seems for X86 only, the deb package I get is not supported on ARM64,

```
# dpkg -i minikube_1.6.2.deb
dpkg: error processing archive minikube_1.6.2.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 minikube_1.6.2.deb
```

Is there any guide for installation for ARM64 and the deb is ready?

Thanks a lot!

**Comment by afbjorklund** [comment]
There is no guide just yet, since the support is still rather experimental (#5667) - still lacking a couple of images, for instance. So the support for building the deb was added, but we haven't started using it just yet. However, I think the binary is posted to GCS (even if not added to GitHub): [minikube-linux-arm64](https://storage.googleapis.com/minikube/releases/v1.6.2/minikube-linux-arm64)

Usage should be very similar to normal, but some container images _only_ have support for amd64. Originally Docker didn't have support for multiple architectures, but it has been added to newer images. You will need a powerful CPU like the Raspberry Pi 4 to run with `kvm2`, otherwise use `none`.

The main problem is the 2G memory requirement, which might mean having to add a swapfile...
There was also heat issues (overhearing) on the earlier modules, due to processing requirements.

But with the addition of more powerful ARM processors, it should work fine to run regular kubernetes.
So it will be regular deployment in a future version of minikube, with a `minikube_1.6.2-0_arm64.deb`

**Comment by afbjorklund** [comment]
Added a reminder to add the architecture to the package filenames in #6281

The main "problem" at the moment is that we **only** support the server use case... The main desktop OS solution (Raspbian) is using `arm` rather than `arm64`, and even though KVM is supported we don't have an ISO for that architecture. Same with the new `docker` driver (KIC), no ARM images for that. The kubeadm requirements (2 CPU, 4G RAM) also puts it at the high end of the available hardware.

So for the end user, the problems are similar to when running on a virtual desktop. And the total lack of isolation in the `none` driver still makes it non-recommended to use on a regular machine, and the use of `sudo` even makes it impractical  for the client (since all the files end up being owned by root). The biggest long-term benefit of this form factor ([RPi](https://www.raspberrypi.org/)) also comes when running _multiple_ such nodes locally.

But for trying it out, things "should work" now - on both the RPi3b and RPi4b.

* https://github.com/kubernetes/minikube/issues/5667#issuecomment-544196658
* https://github.com/kubernetes/minikube/issues/6280#issuecomment-573312349

**Comment by sharifelgamal** [comment]
We support ARM64 now, but still do not have documentation for it. I'll keep this open for now.

**Comment by tstromberg** [comment]
It isn't pretty, but it looks like this was fixed: https://minikube.sigs.k8s.io/docs/start/

**Comment by afbjorklund** [comment]
> It isn't pretty, but it looks like this was fixed: https://minikube.sigs.k8s.io/docs/start/

Added an issue to make it pretty: #10353
