### ISSUE TITLE
virtualbox: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

### ISSUE THREAD

**Issue by atanu2531** [kubernetes/minikube#6171]
minikube start --vm-driver=virtualbox
* minikube v1.6.2 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Selecting 'virtualbox' driver from user configuration (alternates: [])
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible
* Error: [VBOX_VTX_DISABLED] create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--vm-driver=none'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3900
  - https://github.com/kubernetes/minikube/issues/4730
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
Have you tried enabling virtualization (VT-x/AMD-v) in your BIOS?

**Comment by priyawadhwa** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by gillespiejim78** [comment]
I am having the same issue on a Windows 10 Home machine. Virtualization is enabled, and I am able to run other VMs using VirtualBox.

> C:\Users\gille>minikube start
> * minikube v1.8.1 on Microsoft Windows 10 Home 10.0.19577 Build 19577
> * Using the virtualbox driver based on existing profile
> * Downloading VM boot image ...
> * Creating virtualbox VM (CPUs=2, Memory=4057MB, Disk=20000MB) ...
> *
> X Unable to start VM. Please investigate and run 'minikube delete' if possible
> * Error: [VBOX_VTX_DISABLED] creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
> * Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=none'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
> * Related issues:
>   - https://github.com/kubernetes/minikube/issues/3900
>   - https://github.com/kubernetes/minikube/issues/4730


I have tried using the --no-vtx-check, and I end up getting a timeout. Looking at the VM in VirtualBox, it appears to be stuck at "Booting the kernel."


> C:\Users\gille>minikube start --no-vtx-check
> * minikube v1.8.1 on Microsoft Windows 10 Home 10.0.19577 Build 19577
> * Using the virtualbox driver based on existing profile
> * Downloading VM boot image ...
> * Creating virtualbox VM (CPUs=2, Memory=4057MB, Disk=20000MB) ...
> *
> X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create > host timed out in 120.000000 seconds
> *
> * minikube is exiting due to an error. If the above message is not useful, open an issue:
>   - https://github.com/kubernetes/minikube/issues/new/choose

/reopen

**Comment by Randikaviraj** [comment]
I am using the cloud flatform and cannt start minikube it's give as


😄  minikube v1.15.1 on Ubuntu 18.04
✨  Using the virtualbox driver based on existing profile

⛔  Requested memory allocation (978MB) is less than the recommended minimum 1907MB. Deployments may fail.


🧯  The requested memory allocation of 978MiB does not leave room for system overhead (total system memory: 978MiB). You may face stability issues.
💡  Suggestion: Start minikube with less memory allocated: 'minikube start --memory=978mb'

👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.225083 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
🔄  Restarting existing virtualbox VM for "minikube" ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: driver start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.226152 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

❌  Exiting due to HOST_VTX_UNAVAILABLE: Failed to start host: driver start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.226152 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
💡  Suggestion: Your host does not support virtualization. If you are running minikube within a VM, try '--driver=docker'. Otherwise, enable virtualization in your BIOS
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/1994
    ▪ https://github.com/kubernetes/minikube/issues/5326

**Comment by 3ch01c** [comment]
I had to remove Windows features Hyper-V, Virtual Machine Platform, and Windows Hypervisor Platform to be able to use VirtualBox. Unfortunately, removing Virtual Machine Platform means you won't be able to use WSL.
