### ISSUE TITLE
 Unable to load config

### ISSUE THREAD

**Issue by BArman1991** [kubernetes/minikube#6197]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by priyawadhwa** [comment]
Hey @BArman1991 thanks for opening this issue. I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`
* The full output of `kubectl get po -A`


Thank you for sharing your experience!

**Comment by priyawadhwa** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by newbieDatascientist** [comment]
/reopen. I am facing the exact same issue. Here is the info:

Whether the issue occurs with the latest minikube release: Yes

The exact minikube start command line used: minikube start --driver=docker

The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.:
W0908 16:40:35.403438   20872 root.go:252] Error reading config file at P:\.minikube\config\config.json: open P:\.minikube\config\config.json: This file is currently not available for use on this computer.
I0908 16:40:35.448437   20872 out.go:191] Setting JSON to false
I0908 16:40:35.459463   20872 start.go:102] hostinfo: {"hostname":"USHBKGLFQHVMH2","uptime":882,"bootTime":1599596753,"procs":285,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.16299 Build 16299","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"d2d3a943-dcb9-49a3-8fc1-3edee16b3e07"}
W0908 16:40:35.459953   20872 start.go:110] gopshost.Virtualization returned error: not implemented yet
I0908 16:40:35.463947   20872 out.go:109] * minikube v1.13.0 on Microsoft Windows 10 Enterprise 10.0.16299 Build 16299
* minikube v1.13.0 on Microsoft Windows 10 Enterprise 10.0.16299 Build 16299
I0908 16:40:35.483458   20872 out.go:109]

I0908 16:40:35.483458   20872 notify.go:126] Checking for updates...
W0908 16:40:35.485458   20872 out.go:145] X Exiting due to HOST_CONFIG_LOAD: Unable to load config: stat: CreateFile P:\.minikube\profiles\minikube\config.json: This file is currently not available for use on this computer.
X Exiting due to HOST_CONFIG_LOAD: Unable to load config: stat: CreateFile P:\.minikube\profiles\minikube\config.json: This file is currently not available for use on this computer.
I0908 16:40:35.494459   20872 out.go:109]

The full output of minikube logs:
X Exiting due to HOST_CONFIG_LOAD: stat: CreateFile P:\.minikube\profiles\minikube\config.json: This file is currently not available for use on this computer.
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose
