### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by sandeept1986** [kubernetes/minikube#6198]
![Screenshot_2](https://user-images.githubusercontent.com/33664662/71707973-d457c680-2e13-11ea-967a-f0afef1db8c3.png)

**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by afbjorklund** [comment]
Did you install docker ?

**Comment by medyagh** [comment]
@sandeept1986  I will close this issue due to no update, and sorry to hear you had this issue, please feel free to reopen.

meanwhile I recommend to give our newest driver a try in latest release

minikube start --vm-driver=docker
that might solve your issue !

and make sure docker is installed on your system.
you can verify by docker info

**Comment by medyagh** [comment]
@sandeept1986   I will close this issue due to no update, and sorry to hear you had this issue, please feel free to reopen.

meanwhile I recommend to give our newest driver a try in latest release

minikube start --vm-driver=docker
that might solve your issue !
