### ISSUE TITLE
minikube start --vm-driver=virtualbox

### ISSUE THREAD

**Issue by gangganghong** [kubernetes/minikube#6247]
**The exact command to reproduce the issue**:
minikube start --vm-driver=virtualbox

**The full output of the command that failed**:<details>

😄  minikube v1.3.1 on Darwin 10.15.1
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running virtualbox "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
E0109 09:45:39.006936   92021 start.go:558] Error caching images:  Caching images for kubeadm: caching images: caching image /Users/cg/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.15.2: fetching remote image: Get https://k8s.gcr.io/v2/: dial tcp 64.233.187.82:443: i/o timeout
❌  Unable to load cached images: loading cached images: loading image /Users/cg/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.15.2: stat /Users/cg/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.15.2: no such file or directory
🔄  Relaunching Kubernetes using kubeadm ...
^@^@
💣  Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
chugangdeMacBook-Pro:eureka-server cg$ minikube delete
🔥  Deleting "minikube" in virtualbox ...
💔  The "minikube" cluster has been deleted.
chugangdeMacBook-Pro:eureka-server cg$ minikube start --vm-driver=virtualbox
😄  minikube v1.3.1 on Darwin 10.15.1
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
E0109 10:16:37.340574   92454 start.go:558] Error caching images:  Caching images for kubeadm: caching images: caching image /Users/cg/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13: fetching remote image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: i/o timeout
❌  Unable to load cached images: loading cached images: loading image /Users/cg/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: stat /Users/cg/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: no such file or directory
🚜  拉取镜像 ...
🚀  正在启动 Kubernetes ...
^@^@
💣  Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
[init] Using Kubernetes version: v1.15.2
[preflight] Running pre-flight checks
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.15.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.15.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.15.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.15.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.3.10: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**Comment by medyagh** [comment]
@gangganghong  I am curious do you use a vpn or a proxy that restricts you from using gcr?

**Comment by priyawadhwa** [comment]
Hey @gangganghong are you still seeing this issue?

**Comment by s709t** [comment]
i'm getting this issue, it happen when you're using a windows machine to run minikube

**Comment by gangganghong** [comment]
@medyagh It happens when I'm not using vpn.

**Comment by gangganghong** [comment]
@priyawadhwa Not any more.

**Comment by s709t** [comment]
How this was solved?

**Comment by gangganghong** [comment]
@s709t using vpn

**Comment by skgandikota** [comment]
using command "minikube start --vm-driver=virtualbox" ; since @gangganghong  dont have internet it failed

**Comment by ayushpawar21** [comment]
I0721 00:52:07.867866   13464 start.go:98] hostinfo: {"hostname":"MSI","uptime":943,"bootTime":1595271984,"procs":207,"os":"windows","platform":"Microsoft Windows 10 Home Single Language","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"9f82c8c8-281d-43fe-8c5c-a12bde437794"}
W0721 00:52:07.868801   13464 start.go:106] gopshost.Virtualization returned error: not implemented yet
* minikube v1.11.0 on Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
W0721 00:52:07.876800   13464 start.go:562] selectDriver api.Load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I0721 00:52:07.877800   13464 driver.go:253] Setting default libvirt URI to qemu:///system
W0721 00:52:07.877800   13464 start.go:562] selectDriver api.Load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
* Using the virtualbox driver based on existing profile
I0721 00:52:07.914801   13464 start.go:214] selected driver: virtualbox
I0721 00:52:07.916800   13464 start.go:611] validating driver "virtualbox" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:--no-vtx-check HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0721 00:52:07.923799   13464 start.go:617] status for virtualbox: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0721 00:52:07.924804   13464 iso.go:118] acquiring lock: {Name:mk7cf256979929a1d8096bd87c5bd1c9e06b09cd Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Starting control plane node minikube in cluster minikube
I0721 00:52:07.934800   13464 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0721 00:52:07.935800   13464 preload.go:103] Found local preload: C:\Users\Vimo\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0721 00:52:07.935800   13464 cache.go:49] Caching tarball of preloaded images
I0721 00:52:07.936800   13464 preload.go:129] Found C:\Users\Vimo\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0721 00:52:07.936800   13464 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0721 00:52:07.937800   13464 profile.go:156] Saving config to C:\Users\Vimo\.minikube\profiles\minikube\config.json ...
I0721 00:52:07.942801   13464 cache.go:152] Successfully downloaded all kic artifacts
I0721 00:52:07.947803   13464 start.go:240] acquiring machines lock for minikube: {Name:mk8e996d96cd1a7a4448059f239dc4bfc648d0d4 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0721 00:52:07.948800   13464 start.go:244] acquired machines lock for "minikube" in 996.8µs
I0721 00:52:07.948800   13464 start.go:84] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:--no-vtx-check HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]} &{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}
I0721 00:52:07.949800   13464 start.go:121] createHost starting for "" (driver="virtualbox")
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
I0721 00:52:07.961800   13464 start.go:157] libmachine.API.Create for "minikube" (driver="virtualbox")
I0721 00:52:07.961800   13464 client.go:161] LocalClient.Create starting
I0721 00:52:07.962803   13464 main.go:110] libmachine: Reading certificate data from C:\Users\Vimo\.minikube\certs\ca.pem
I0721 00:52:07.963801   13464 main.go:110] libmachine: Decoding PEM data...
I0721 00:52:07.963801   13464 main.go:110] libmachine: Parsing certificate...
I0721 00:52:07.964802   13464 main.go:110] libmachine: Reading certificate data from C:\Users\Vimo\.minikube\certs\cert.pem
I0721 00:52:07.964802   13464 main.go:110] libmachine: Decoding PEM data...
I0721 00:52:07.965800   13464 main.go:110] libmachine: Parsing certificate...
I0721 00:52:07.965800   13464 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
I0721 00:52:07.991818   13464 main.go:110] libmachine: STDOUT:
{
6.1.10r138449
}
I0721 00:52:07.991818   13464 main.go:110] libmachine: STDERR:
{
}
I0721 00:52:08.003801   13464 main.go:110] libmachine: Hyper-V is not installed.
%!(EXTRA *exec.Error=exec: "vmms.exe": executable file not found in %PATH%)
I0721 00:52:08.003801   13464 client.go:164] LocalClient.Create took 40.9987ms
I0721 00:52:10.004496   13464 start.go:124] duration metric: createHost completed in 2.0446964s
I0721 00:52:10.004496   13464 start.go:75] releasing machines lock for "minikube", held for 2.0556961s
I0721 00:52:10.041470   13464 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0721 00:52:10.041470   13464 delete.go:45] couldn't inspect container "minikube" before deleting: unknown state "minikube": docker container inspect minikube --format={{.State.Status}}: exec: "docker": executable file not found in %PATH%
stdout:

stderr:
I0721 00:52:10.063439   13464 cli_runner.go:108] Run: podman container inspect minikube --format={{.State.Status}}
I0721 00:52:10.063439   13464 delete.go:45] couldn't inspect container "minikube" before deleting: unknown state "minikube": podman container inspect minikube --format={{.State.Status}}: exec: "podman": executable file not found in %PATH%
stdout:

stderr:
W0721 00:52:10.066441   13464 start.go:359] delete host: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
! StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
I0721 00:52:15.068603   13464 start.go:240] acquiring machines lock for minikube: {Name:mk8e996d96cd1a7a4448059f239dc4bfc648d0d4 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0721 00:52:15.068603   13464 start.go:244] acquired machines lock for "minikube" in 0s
I0721 00:52:15.069599   13464 start.go:84] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:--no-vtx-check HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]} &{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}
I0721 00:52:15.070594   13464 start.go:121] createHost starting for "" (driver="virtualbox")
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
I0721 00:52:15.073624   13464 start.go:157] libmachine.API.Create for "minikube" (driver="virtualbox")
I0721 00:52:15.073624   13464 client.go:161] LocalClient.Create starting
I0721 00:52:15.073624   13464 main.go:110] libmachine: Reading certificate data from C:\Users\Vimo\.minikube\certs\ca.pem
I0721 00:52:15.074593   13464 main.go:110] libmachine: Decoding PEM data...
I0721 00:52:15.074593   13464 main.go:110] libmachine: Parsing certificate...
I0721 00:52:15.074593   13464 main.go:110] libmachine: Reading certificate data from C:\Users\Vimo\.minikube\certs\cert.pem
I0721 00:52:15.075592   13464 main.go:110] libmachine: Decoding PEM data...
I0721 00:52:15.075592   13464 main.go:110] libmachine: Parsing certificate...
I0721 00:52:15.076598   13464 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
I0721 00:52:15.128628   13464 main.go:110] libmachine: STDOUT:
{
6.1.10r138449
}
I0721 00:52:15.128628   13464 main.go:110] libmachine: STDERR:
{
}
I0721 00:52:15.164651   13464 main.go:110] libmachine: Hyper-V is not installed.
%!(EXTRA *exec.Error=exec: "vmms.exe": executable file not found in %PATH%)
I0721 00:52:15.164651   13464 client.go:164] LocalClient.Create took 91.0271ms
I0721 00:52:17.167091   13464 start.go:124] duration metric: createHost completed in 2.0964973s
I0721 00:52:17.167091   13464 start.go:75] releasing machines lock for "minikube", held for 2.0974923s
* Failed to start virtualbox VM. "minikube start" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
I0721 00:52:17.179904   13464 exit.go:58] WithError(error provisioning host)=Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d85a0, 0x18bd240)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b44a0c, 0x17, 0x1e16f20, 0xc000826c60)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b6c200, 0xc000723aa0, 0x0, 0x2)
        /app/cmd/minikube/cmd/start.go:169 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b6c200, 0xc000723a80, 0x2, 0x2, 0x2b6c200, 0xc000723a80)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x0, 0xc000723601)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
*
* [VBOX_VTX_DISABLED] error provisioning host Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3900
  - https://github.com/kubernetes/minikube/issues/4730

**Comment by sharifelgamal** [comment]
@ayushpawar21 Can you please open a new issue with the details asked for in our issue template? Thanks.

**Comment by tarunk** [comment]
Follow this : https://www.youtube.com/watch?v=18fU8FHgG80
