### ISSUE TITLE
Create package with kubectl and minikube

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/minikube#628]
_Feature request_:

In the case of a new user who wants to take k8s for a spin. Minikube is great.
_but_ one needs to find `kubectl` somewhere.

It would be great if the installation instructions for minikube would also show how to get `kubectl`.

Even better, there should be a package for minikube (brew, yum, apt) which has kubectl has a dependency.

```
yum install minikube
```

and you don't have to go hunt for kubectl somewhere.

**Comment by yissachar** [comment]
The README already has a [requirements](https://github.com/kubernetes/minikube#requirements) section, which points to `kubectl` installation instructions.

If `kubectl` does get packaged with minikube, I hope it is optional or overridable, since users may have a different version of `kubectl` that they want to use with their production clusters.

**Comment by kevin-smets** [comment]
Brew cask has minikube:

    brew cask install minikube

**Comment by aaron-prindle** [comment]
Closing as this is fixed now:
As @yissachar stated there is an issue with bundling/automatically-downloading kubectl as it might override a users desired kubectl version or install path.  We added a check that kubectl is on a users path and if not, provide a link to download kubectl in this PR #783

**Comment by sebgoa** [comment]
thanks
