### ISSUE TITLE
hyperv: NotSpecified: (:) [Get-WindowsOptionalFeature], COMException

### ISSUE THREAD

**Issue by abhishek09091** [kubernetes/minikube#6335]
**The operating system version**:

Microsoft Windows 10 Pro 

**Output of the systeminfo command**:

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**The exact command to reproduce the issue**:  minikube-windows-amd64.exe start

**The full output of the command that failed**:

* minikube v1.6.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Selecting 'hyperv' driver from existing profile (alternates: [virtualbox])

! 'hyperv' driver reported an issue: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:
Get-WindowsOptionalFeature : The requested operation requires elevation.
At line:1 char:1
+ Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

X hyperv does not appear to be installed, but is specified by an existing profile. Please run 'minikube delete' or install hyperv

I have hypervisior installed please check the

**Comment by lmurali89** [comment]
Even I am facing an issue. What needs to be done here?

**Comment by dpiessens** [comment]
Looks like this is related to #6579 You can use --force to get past this but the timeout for this needs to be increased.

**Comment by lmurali89** [comment]
Someone please help. i am facing below issue.

PS C:\WINDOWS\system32> minikube start --vm-driver hyperv --hyperv-virtual-switch "MiniKube Switch" --force
* minikube v1.7.3 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the hyperv driver based on user configuration

! 'hyperv' driver reported an issue: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

* Downloading VM boot image ...
    > minikube-v1.7.3.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.7.3.iso: 167.39 MiB / 167.39 MiB [-] 100.00% 7.10 MiB p/s 24s
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32>

**Comment by tstromberg** [comment]
I found a reference to your Hyper-V error here:

https://github.com/Microsoft/WSL/issues/3413

The two workarounds appear to be:

* Run Powershell as Administrator if you are not already
* Use the UI to enable Hyper-V: `Start >> Windows Features >> Turn Windows Features on or off `

Please let me know if this helps.

**Comment by sharifelgamal** [comment]
Running Powershell as an Administrator should fix any "required elevation" errors that you're running into.

I'm going to go ahead and close this. If this doesn't help, please reopen this with more detail on the errors you're seeing.
