### ISSUE TITLE
expoter

### ISSUE THREAD

**Issue by ghost** [kubernetes/minikube#6342]
[root@minikube ~]# minikube start --vm-driver=none --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
* minikube v1.6.2 on Centos 7.6.1810
* Selecting 'none' driver from user configuration (alternates: [])
* Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing none VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
* Launching Kubernetes ... 
* 
X Error starting cluster: apiserver healthz: apiserver healthz never reported healthy
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by afbjorklund** [comment]
There are some common issues with centos listed in #6166, if any of that helps ?

**Comment by sharifelgamal** [comment]
@core-liu We'll need a little more information in order to help debug your issue. Could you tell us:

* Whether the issue occurs with the latest minikube release
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`
