### ISSUE TITLE
improve downoading binaries...

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6518]
on at least two occasions I saw minikube taking a LOOONG time to download kubectl (more than 20 seconds) 
both cases I was on a good wifi network. we should either consider finding a better / alternative source for downloading these binaries or ship them with minikube

```
💾  Downloading kubectl v1.17.2
💾  Downloading kubeadm v1.17.2
💾  Downloading kubelet v1.17.2
```

Least we could do is show a progressbar for download waiting ...

**Comment by tstromberg** [comment]
I don't think we'll find a faster source, but we'll definitely want to bundle these into the images alongside the rest of the Kubernetes components.

**Comment by afbjorklund** [comment]
Why are we downloading the kubernetes-client (kubectl), when setting up the server ?

**Comment by afbjorklund** [comment]
One old suggestion was to use the _compressed_ versions rather than the raw binaries...
But I'm not sure if it is a win for the server binaries, since it includes a lot of other "stuff":

69M	kubectl
13M	kubernetes-client-linux-amd64.tar.gz

107M	kubelet
38M	kubeadm
343M	kubernetes-server-linux-amd64.tar.gz

i.e. it duplicates a lot of content that we are pulling in the container images as well
As well as some extra bonus features like the source code, in case you needed it:

31M	kubernetes/kubernetes-src.tar.gz

**Comment by ninja-tester** [comment]
Hi! I got [this issue](https://stackoverflow.com/questions/60177588/minikube-start-taking-long-time-to-downloading-kubectl-v1-17-2) too.
And really, why minkube downloading kubectl if it was already installed (added to PATH)?

**Comment by sharifelgamal** [comment]
We install kubectl because we need it for the addon manager.

**Comment by medyagh** [comment]
@ninja-tester the reason is, minikube wants to make sure, u are using the kubectl compatible with your k8s version. (they could be incampatible)
