### ISSUE TITLE
version_upgrade_test: Add upgraded second-start test

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#6532]
version_upgrade_test only tests stop/start upgrades, not double-start upgrades.

**Comment by sayboras** [comment]
hi, just want to clarify a little bit on this issue.

Currently, the test is performing below actions:

- start cluster with OldestKubernetesVersion --> should pass
- start cluster with NewestKubernetesVersion --> should pass
- start cluster with OldestKubernetesVersion --> should fail due to downgrade.

Please let me know if you want to add `start cluster with NewestKubernetesVersion` step.
