### ISSUE TITLE
 Error entering my cluster after shutting down the PC

### ISSUE THREAD

**Issue by juniomik14** [kubernetes/minikube#6613]
OS: Windows 10
VM Driver: hyperv
ISO version: minikube-v1.7.2

Hi, I have created an infrastructure with jmeter-grafana-influxdb in a laptop with docker and every time I turn off the laptop when accessing my cluster I get this error:
Unable to connect to the server: dial tcp 172.17.131.210:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
