### ISSUE TITLE
"lint" (`golangci-lint`) sometimes misses !

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6714]
our lint has some issues, it acts differently on different computers and sometimes misses things like this : 
https://github.com/kubernetes/minikube/pull/6712

**Comment by afbjorklund** [comment]
I also have the problem with `code` (\<sigh\>, an editor that doesn't save...) but also with `make lint`.

My workaround is to use different targets, like `make gofmt` and `make golint`. And then Travis.

It would be nice if there was a reliable way to run the tests locally, though.

Maybe we can set up a custom image with the pre-requisites and run it ?

**Comment by afbjorklund** [comment]
Maybe

`docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.23.6 golangci-lint run --timeout 7m --build-tags "integration container_image_ostree_stub containers_image_openpgp go_getter_nos3 go_getter_nogcs" --enable goimports,gocritic,golint,gocyclo,misspell,nakedret,stylecheck,unconvert,unparam,dogsled --exclude 'variable on range scope.*in function literal|ifElseChain' --skip-files "pkg/minikube/translate/translations.go|pkg/minikube/assets/assets.go" ./...`

**Comment by afbjorklund** [comment]
Fails because of missing libvirt, probably have to make our own downstream image:

`level=warning msg="[runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/app/pkg/drivers/kvm/domain.go:28:10: could not import github.com/libvirt/libvirt-go (/go/pkg/mod/github.com/libvirt/libvirt-go@v3.4.0+incompatible/callbacks.go:63:8: could not import C (cgo preprocessing failed))]"
`

**Comment by afbjorklund** [comment]
We could also use these flags:

```
      --skip-dirs strings           Regexps of directories to skip
      --skip-files strings          Regexps of files to skip
```

And just run the minikube packages, not all bundled drivers and provisioners and stuff ?
