### ISSUE TITLE
Error starting cluster: apiserver healthz: apiserver healthz never reported healthy

### ISSUE THREAD

**Issue by hanjunchao1234** [kubernetes/minikube#6729]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

Error starting cluster: apiserver healthz: apiserver healthz never reported healthy
</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
