### ISSUE TITLE
Minikube (re)start on docker driver breaks docker-env

### ISSUE THREAD

**Issue by balopat** [kubernetes/minikube#6824]
```
 minikube start -p docker3 --container-runtime docker --vm-driver=docker 
```
Restarting caused some issue with the IP (minikube docker-env command) that was working before - this is a skaffold log output:  

```
'docker load' command failed with error: error during connect: Post https://127.0.0.1:32772/v1.40/images/load?quiet=1: EOF
```

```
minikube version                                                                                                                     6.7s  Thu Feb 27 10:59:00 2020
minikube version: v1.7.3
commit: 436667c819c324e35d7e839f8116b968a2d0a3ff
```

_Originally posted by @balopat in https://github.com/kubernetes/minikube/issues/6820#issuecomment-592036441_

**Comment by josedonizetti** [comment]
The bugs happens because kic is using random ports when exposing internal ports to localhost. When a container is restarted it might get the same port or not (likely to not).

https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kic/oci/oci.go#L407

To fix this we need to control which port is exposed, but passing it to the run command. But this can have side effects, imagine we start kic with passing the port 32011, and then the container is stopped, and some other service is started on the user computer that is not related to minikube and this service is using the port 32011, if the user now tries to restart the container we have a conflict, which to be avoid will required another port, creating the same bug again.

One can also run `docker-env` again every time the container is restarted.

@medyagh thoughts?

**Comment by medyagh** [comment]
Regarding that issue I was thinking. Minikube status should have a new line that tells you if you are using the docker env inside minikube or not . And if it needs updating it should also tell you.

**Comment by medyagh** [comment]
Another almost related is we could add something to the bash prompt (if user selects to)
That tells you your terminal is using docker inside minikube

**Comment by medyagh** [comment]
Additionally on restart, we should detect user is using docker env and re-new docker env for them or warn them to do so

**Comment by medyagh** [comment]
I will work on this.

**Comment by medyagh** [comment]
I also noticed on a terminal with docker-env
we warn this incorrectly

```
⚠️  'docker' driver reported an issue: exit status 1
💡  Suggestion: Docker is not running or is responding too slow. Try: restarting docker desktop.
```
