### ISSUE TITLE
FR: Ability to pass docker.sock from host

### ISSUE THREAD

**Issue by applike-ss** [kubernetes/minikube#6856]
I would like to be able to pass my docker.sock from the host to minikube when using the vm driver docker.

This would in the end make using devspace in combination with minikube easier and more comfortable.

Also my images would then not be deleted when i remove the minikube cluster.

**Comment by medyagh** [comment]
this is  an interesting discussion @applike-ss thanks for brining it up
you mean you want the docker run-time inside minikube to point somewhere outside ?
this might have some negative effects on the performance.
there are ways to use a registery for your images, and make minikube use that registery, is there any reason not to use that approach ?

**Comment by applike-ss** [comment]
I want to use it that way, because if i used the docker vm driver, then a docker within a docker is spun up (which doesn't make sense to me).
If i can pass my hosts docker inside the docker container there is no overhead (which you mentioned) afaik.
This also enabled me to use a setup like:
```
---------------              ----------------------------------- 
| Linux Host  |      <---->  | Macbook (or low powered laptop) |
| Runs:       |              | Runs:                           |
| Docker      |              | IDE (Goland + a given Project)  |
| Minikube    |              | devspace                        |
                             | kubectl                         |
--------------               ----------------------------------- 
```

**Comment by afbjorklund** [comment]
The above scenario is the _default_ minikube setup, you use `minikube docker-env` to access it...

With the environment set up, you can use `kubectl` (or other tool) to access the docker daemon.

https://minikube.sigs.k8s.io/docs/tasks/docker_daemon/

When you use the local docker daemon, there is no isolation between the host and the k8s master.

This is also doable (using the "none" driver), but **not** recommended due to security and safety.

https://minikube.sigs.k8s.io/docs/reference/drivers/none/

The Docker driver adds a layer (simulating a "node") between the Kubernetes cluster and the laptop.

This is something you want, as a real cluster will have lots of such nodes (both master and workers)

**Comment by applike-ss** [comment]
This is definitelly not the default setup, if you watch the docs.
I do have two machines involved, not one.
Using this kind of setup is very different from just using one machine, because there is external IPs involved.

Minikube itsself spawns a docker daemon in the "vm", right?
And this is exactly what i do not want to have. 
It is overhead that would not be required for me.
Also `minikube docker-env` does just give  me the local ip 127.0.0.1 instead of the external one, so i can't just eval the docker-env.

My issue with each local kubernetes solution (kind, minikube, microk8s) is currently that i can not use it with devspace together if i want to use my 2 machine setup, unless i push to a local registry (which should not be needed if i have just 1 machine which does build and run the images. Each kubernetes seems to spin up its own docker inside a vm.

**Comment by afbjorklund** [comment]
The “generic” driver (work in progress) would allow for your setup... It just needs the IP address (and user/key) of the machine to use

In minikube, the “none” driver assumes running on localhost... (so not remotely) And it only works on Linux, not Mac/Win.

I don’t think that KIC (docker/podman) works remotely?

But @medyagh is the expert on that, if it would work or not

**Comment by applike-ss** [comment]
ahh ok, so this is kinda soon to be supported. at least in my local 1.7.3 there is no generic driver.

**Comment by afbjorklund** [comment]
> ahh ok, so this is kinda soon to be supported. at least in my local 1.7.3 there is no generic driver.

Something like that, since it is not available in the 1.7 (or 1.8) releases.

Anyway, it is **not** possible to install Kubernetes using “just” docker (without something like KIC that will install a fake VM and then connect to that). But as long as you are OK with using SSH connectivity to your host, then minikube will use that (and `sudo`) to bootstrap. It will install Docker if missing, but if you already have a container runtime installed on the host it will use the existing one...

This setup works with both physical servers (incl. Raspberry Pi) and virtual servers (incl. Cloud hosts). However, there is no support for installing and setting up the basic OS as per the `kubeadm` requirements. But it is not fundamentally different from “none” driver, just runs remotely rather than locally ?

**Comment by applike-ss** [comment]
sounds like what i need. Should i close the ticket?

**Comment by afbjorklund** [comment]
> Should i close the ticket?

It is up to you, if the scenario is adequately described in the previous issue then we can close as dupe.

**Comment by applike-ss** [comment]
closing as duplicate of #4733

**Comment by afbjorklund** [comment]
@applike-ss : I rebased that other branch after months of not being used, so if you care to test it yourself it would be appreciated

**Comment by applike-ss** [comment]
@afbjorklund i didn't find your changeset. It isn't this one, right? https://github.com/afbjorklund/minikube/tree/generic

**Comment by afbjorklund** [comment]
Yeah, I meant #6873

**Comment by applike-ss** [comment]
the last commit i see on that branch is from 15.07.2019

**Comment by afbjorklund** [comment]
Well, that's how rebases work (they keep the author date)

**Comment by applike-ss** [comment]
i am used to the view of intelliJ ide's, they show both commit and update date. Will have a look when i can.
