### ISSUE TITLE
update minikube site :  not yet good for?

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7007]
on the site https://minikube.sigs.k8s.io/docs/overview/
```

Then minikube is for you.

What is it good for? Developing local Kubernetes applications
What is it not good for? Production Kubernetes deployments
What is it not yet good for? Environments which do not allow VM’s
```

the line,
''' What is it not yet good for? Environments which do not allow VM’s'''
is not accurate anymore and needs to deleted. since minikube know runs in both VMs, container and baremetal.

**Comment by afbjorklund** [comment]
@medyagh: funny story is that I got started with all this, in an environment that allowed VMs (KVM as yourself) but did not allow containers (Docker as root). So you **had** to use `docker-machine`...

But it's not worth keeping a line like "it is not good for environment that don't allow VMs or containers or bare metal", because that is just like saying "it will not fix your broken IT department for you" ☺️
