### ISSUE TITLE
Feature request: add a flag to disable Minikube's update messaging

### ISSUE THREAD

**Issue by etanshaul** [kubernetes/minikube#7181]
Something like `minikube start --wantUpdateNotification=false`

Example: 

```
* minikube 1.8.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.8.2
* To disable this notice, run: 'minikube config set WantUpdateNotification false'
```

For use-cases of driving Minikube from other tools - where the Minikube dependency is managed - it would be incredibly helpful to be able to pass in a flag to minikube to disable this update message, instead of setting a global config.

**Comment by etanshaul** [comment]
@tstromberg brought the `MINIKUBE_WANTUPDATENOTIFICATION` flag to my attention which would satisfy our use-case: https://minikube.sigs.k8s.io/docs/reference/environment_variables/

Will leave open for the team to decide if a this would be useful, still, as a flag.

**Comment by tstromberg** [comment]
I'm going to close it, since it's primarily used by tool builders who can encode this once rather than most users, so the extra cognitive overhead of seeing it in `--start` isn't worth it.

Historical note: this was made an environment variable because minikube used to show the update message on every command. I felt that was a bit obnoxious, so it only happens during start now.

Feel free to `/reopen` this issue if you disagree.
