### ISSUE TITLE
Define imaginary user character for minikube website

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7315]
How about we define a few characters with names that who are the ppl the we create minikube for ?

So when we redesign our document website we find a real user from that audience to try the website and tell us their frictions.

Here is a quick example.

User A
Wants to try kubernetes for first time and wants to install minikube

User B
A software developer who wants to use minikube for local development and wants learn how to deploy their app to minikube.
( Build image, push image and deploy to minikube and then hit the url of their app)

User C
A software engineer working at a corp with vpn and proxy and corp certs.
They wanna use minikube on corp machines.
Wants to figure out how to add corp certs to minikube.

User D:
Wants to explore and try different things that minikube is capable of .
And try different features with examples

User E:
Wants to troubleshoot their not working minikuke.

User F:
Wants to contribute to minikube and wants to learn how to build or add something to minikube.

User G: 
Wants to create an addon for minikube. So their cool service be easily installed on minikube for other users

**Comment by afbjorklund** [comment]
> How about we define a few characters with names that who are the ppl the we create minikube for ?

Sounds like a good idea. I'm no expert, but I think you normally find "real" users with "real" names ?

https://en.wikipedia.org/wiki/Persona_(user_experience)

Personally I think we lack some technical documentation, so I will try to do that instead of the website.

It would also be nice to collaborate more with [kubernetes.io](https://kubernetes.io/docs/tutorials/)
