### ISSUE TITLE
 Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".

### ISSUE THREAD

**Issue by Damarla499** [kubernetes/minikube#7365]
But, minikube machine is visible in HyperV. Can you please help me to solve this ?

**Comment by tstromberg** [comment]
Do you mind sharing the output of:

* `Get-VM`
* `minikube start --alsologtostderr -v=1`

Are you running minikube from within a admin PowerShell window?

**Comment by caoyukun0430** [comment]
> Do you mind sharing the output of:
> 
> * `Get-VM`
> * `minikube start --alsologtostderr -v=1`
> 
> Are you running minikube from within a admin PowerShell window?

Hi, I have also the same issue with hyperv, my minikube runs well with virtualbox, but not hyperv. 
The Get-VM output is as follows:
PS C:\WINDOWS\system32> Get-VM

Name            State   CPUUsage(%) MemoryAssigned(M) Uptime           Status             Version
----            -----   ----------- ----------------- ------           ------             -------
DockerDesktopVM Off     0           0                 00:00:00         Operating normally 9.0
minikube        Running 0           4000              00:03:45.5740000 Operating normally 9.0

And for the output of minikube start --alsologtostderr -v=1, since it's too long, I put in the attached text file. Thank you so much for helping!
[minikube start.txt](https://github.com/kubernetes/minikube/files/4452585/minikube.start.txt)

**Comment by caoyukun0430** [comment]
> > Do you mind sharing the output of:
> > 
> > * `Get-VM`
> > * `minikube start --alsologtostderr -v=1`
> > 
> > Are you running minikube from within a admin PowerShell window?
> 
> Hi, I have also the same issue with hyperv, my minikube runs well with virtualbox, but not hyperv.
> The Get-VM output is as follows:
> PS C:\WINDOWS\system32> Get-VM
> 
> Name State CPUUsage(%) MemoryAssigned(M) Uptime Status Version
> 
> DockerDesktopVM Off 0 0 00:00:00 Operating normally 9.0
> minikube Running 0 4000 00:03:45.5740000 Operating normally 9.0
> 
> And for the output of minikube start --alsologtostderr -v=1, since it's too long, I put in the attached text file. Thank you so much for helping!
> [minikube start.txt](https://github.com/kubernetes/minikube/files/4452585/minikube.start.txt)

Hi, I solved my issue by following comments here https://github.com/kubernetes/minikube/issues/1967.

**Comment by medyagh** [comment]
glad to see you solved your problem by setting the virtual switch, I will close this. please comment again if needed additional help
