### ISSUE TITLE
minikube status should show system status

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7421]
I was thinking today, how about we re-implement minikube status to show status on more things and categorize them ?

$ minikube status:
- Kubernetes Status
    -- apisever
    -- kubelet
- Machine Status
    -- Machine Status (VM running)
    -- Disk Usage
    -- Connectivity to Internet (nslookup Kubernets.io)
- Host System Status
   -- Free Memory
   -- Free Disk
   -- CPU Load
    -- Connectivity to internet (nslookup Kubernets.io)
   

it could also show as a table.

**Comment by afbjorklund** [comment]
We discussed this in #3574, where I also started on an implementation...

The idea was to make a go binary that outputs the information (rather than running the shell commands), so that it would be easier to run and more portable. Upload it to the node and run.

Kubernetes monitors _some_ of this information itself, but it would be nice to have an on-demand command that would output basic Linux information for _any_ type of node (VM or otherwise) ?

Today we have some info shown only at `start`, and not in the `status`.
