### ISSUE TITLE
不能启动

### ISSUE THREAD

**Issue by h353617145** [kubernetes/minikube#7467]
minikube start --vm-driver hyperkit

卡在这里了
😄  Darwin 10.14.6 上的 minikube v1.8.2
✨  根据用户配置使用 hyperkit 驱动程序
💾  Downloading preloaded images tarball for k8s v1.17.3 ...

**Comment by tstromberg** [comment]
minikube只是掛起-還是最終顯示錯誤消息？

我相信這可能與 #7612

**Comment by medyagh** [comment]
@h353617145 
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
