### ISSUE TITLE
Update documentation around supported kubernetes versions

### ISSUE THREAD

**Issue by mat-tia** [kubernetes/minikube#7492]
The text says: 

"As of September 2019, this means that minikube supports and actively tests against the latest builds of:

    v1.16 (default)
    v1.15
    v1.14
    v1.13
    v1.12
    v1.11 (best effort)
"
But it's April 2020, and Kubernetes is at version 1.18, which is pulled in by default by minikube too. Guess this needs an update.

**Comment by priyawadhwa** [comment]
Hey @mat-tia thanks for pointing this out! Looks like that documentation lives here:

https://minikube.sigs.k8s.io/docs/handbook/config/#selecting-a-kubernetes-version

We should probably make this more generic and just say that we support latest kubernetes version -> v1.11 so that this documentation doesn't need constant updating.

If anybody would be interested in submitting a PR for this fix, please comment here! This would be the file to change:

https://github.com/kubernetes/minikube/blob/f99a546c9c3a309768fa64fca949372e00a1ee50/site/content/en/docs/handbook/config.md
