### ISSUE TITLE
Add preload tar files to the "released files" automatically.

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7737]
we should include the preload images in the release notes automaticly.

at least for the past 10 versions maybe

**Comment by tstromberg** [comment]
I don't understand this. What exactly would you like to see in `CHANGELOG.md`?

**Comment by medyagh** [comment]
oops  I didnt mean release notes, I meant released  attached files

**Comment by afbjorklund** [comment]
> oops I didnt mean release notes, I meant released attached files

You mean the page on GitHub, or to the Google Cloud Storage ?

Currently we add some binaries **only** to the more "hidden" url.
Like for instance minikube for non-amd64 architectures and such.

We could also consider exposing the kicbase image ? https://github.com/kubernetes/minikube/issues/7012#issuecomment-614247192

**Comment by afbjorklund** [comment]
@medyagh is this issue related to issues like #7695 ?

Because normally minikube will handle the preload downloading
(and should work just fine, but slower, if no preload is available)

Maybe we should also have a tarball, with **only** the images.

Like a more portable version of the preload, and without the binaries.
Then you could use it as an alternative, like with containerd/podman

**Comment by afbjorklund** [comment]
Will open two **separate** issues, for the non-preloaded alternatives
Could even have variants using the OCI format (instead of docker)

* kicbase (`gcr.io/k8s-minikube/kicbase`)
  * gcr.io/k8s-minikube/kicbase:v0.0.9
* minikube ( the `essentials`, like `kubeadm config images list`)
  * k8s.gcr.io/kube-apiserver:v1.18.2
k8s.gcr.io/kube-controller-manager:v1.18.2
k8s.gcr.io/kube-scheduler:v1.18.2
k8s.gcr.io/kube-proxy:v1.18.2
k8s.gcr.io/pause:3.2
k8s.gcr.io/etcd:3.4.3-0
k8s.gcr.io/coredns:1.6.7
