### ISSUE TITLE
TestPause/serial/SecondStartNoReset: api server error

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7895]
as seen here: https://storage.googleapis.com/minikube-builds/logs/7862/87bb1c3/KVM_Linux.html#fail_TestPause%2fserial%2fSecondStartNoReset

TestPause/serial/SecondStartNoReset reveals a problem in minikube that right after a full healthy start (--wait=all)
the apiserver will go to an state of error (one suspection could be other tests doing too many kubedm init (which is expensive CPU and memory)

as seen in this test:
```
pause_test.go:78: expected the second start log outputs to include "The running cluster does not need a reset" but got: 
```
and the exact relevant error is:
```
I0424 15:10:25.506755   13119 kubeadm.go:452] needs reset: apiserver in state Error
```

**Comment by tstromberg** [comment]
I don't love that we are parsing log messages, but, a few notes:

* This was caused because the apiserver returned a 500 for the healthz check
* This test doesn't seem to be showing any sort of post-mortem logs
* `minikube logs` output would be very helpful here - but is currently not invoked by our tests.

**Comment by tstromberg** [comment]
Closing as possibly obsolete.
