### ISSUE TITLE
hyperv: This VM is having trouble accessing https://k8s.gcr.io

### ISSUE THREAD

**Issue by sachin67007** [kubernetes/minikube#7913]
Hello All,
I am getting the same issue and unable to PULL any image, looks like MINIKUB does not have access to internet
I have MINIKUBE directly installed on my LAPTOP WINDOWS no HyperV

PS C:\WINDOWS\system32> minikube start
* minikube v1.9.2 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Using the hyperv driver based on existing profile
* Starting control plane node m01 in cluster minikube
* Restarting existing hyperv VM for "minikube" ...
* Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
! This VM is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Enabling addons: dashboard, default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"
PS C:\WINDOWS\system32>

If I have only a wireless network that I connect to in my home network example 192.168.1.1 is my router IP, what should I configure as PROXY on minikube

**Comment by tstromberg** [comment]
It sounds like the default Hyper-V switch minikube using does not have network connectivity.  Possibly because it is trying to access the internet over an ethernet jack rather than wireless. Hard to tell.

Here's my suggestion:

1. First try `minikube delete` then `minikube start` -- this step is unlikely to work, but just in case it does, it would make life easier.
2. Create an external network switch in Hyper-V, name it `minikube` or something simple. There is a guide on https://www.isunshare.com/blog/fix-vm-no-internet-access-hyper-v-windows-10-2018/ for creating one - I'm sure you can find many such guides in other places as well.
3. Run `minikube start --hyperv-external-switch=minikube` 

If this does not help, and you happen to have Docker installed, consider trying `minikube start --driver=docker`, which will piggyback on Docker's Hyper-V configuration. It does mean you will need Docker running to use minikube, however.

Please let me know if this helps and we can write an appropriate FAQ entry for it! Thank you.

**Comment by tstromberg** [comment]
It sounds like the default Hyper-V switch does not have network connectivity for whatever reason, possibly because it's trying to use a hard-wired ethernet connection rather than wireless.

That's OK though, you can create your own hyper-v switch:

* Open Hyper-V Manager, Click on Virtual Switch Manager, Create New Virtual Network Switch, Select external type, and OK. I suggest naming the switch something simple like `minikube`

* Run `minikube start --hyperv-virtual-switch=minikube`

* See if the warning message comes up

**Comment by sachin67007** [comment]
Thanks You So much this worked,
Last solution I ready did not have the link to configure HYPER-V

After creating the Virtual Switch MINIKUBE I did not get the connectivity error.
[cid:image001.jpg@01D61C05.2B4BF220]

Regards,
Sachin Vaish
Head Professional Services
Email: sachinv@radware.com<mailto:sachinv@radware.com>
Mob. +91 9821555884
[Radware]
Radware TAC Support Toll Free # 0008003201489 / 0008009190282:

**Comment by tstromberg** [comment]
Thank you for the update!

**Comment by rnkaufman** [comment]
`minikube start --driver=docker` fixed up this issue for me, thank you greatly!

**Comment by irtaza909** [comment]
I have the exact same issue on my linux 20.04 i am using virtual box . Please guise

**Comment by abdullah-4Mohammed** [comment]
this issue not solved with vbox unfortunately.
