### ISSUE TITLE
ImagePullBackOff

### ISSUE THREAD

**Issue by safoueneraddaoui** [kubernetes/minikube#7941]
i'm using minikube in windows , i have pushed my image in docker hub , but when i wanna pull it i get this error : ImagePullBackOff

**Comment by tstromberg** [comment]
Can you please give instructions on how to reproduce this?

**Comment by medyagh** [comment]
@safoueneraddaoui have you set your pull policy correctly ? do you mind sharing your deployment yaml ? and is it a public docker hub or a private repo ?

**Comment by medyagh** [comment]
@safoueneraddaoui have you set your pull policy correctly ? do you mind sharing your deployment yaml ? and is it a public docker hub or a private repo ?

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
