### ISSUE TITLE
podman humor: restarting the sudo service may improve performance

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7966]
* The slow message isn't helpful for podman at all.
* We shouldn't include the sudo timing in this. 

```
❗  Executing "sudo podman ps -a --format {{.Names}}" took an unusually long time: 10.547099308s
💡  Restarting the sudo service may improve performance.
```

**Comment by afbjorklund** [comment]
Hmm, I suppose the help text is using the command arguments rather than the actual driver

**Comment by afbjorklund** [comment]
It's _possible_ that we may run podman remotely too in the future (like we do with docker today)

The "slow" warnings are a built-in feature of KIC, so leaving. Just skipping the hint for "sudo"...

**Comment by afbjorklund** [comment]
It works fine to run `podman` remotely... The problem is that there is no Podman Desktop yet.

This means the user will have to set up their own VM, if they want to use podman on Mac or Win.
Which should work too, but is a little inconvenient - and more like the none or generic drivers ?

Here is one example with Fedora: https://itnext.io/podman-and-skopeo-on-macos-1b3b9cf21e60
