### ISSUE TITLE
minikube start deleted my VM

### ISSUE THREAD

**Issue by xphoniex** [kubernetes/minikube#7994]
**Steps to reproduce the issue:** 

1. create a VM in VirtualBox, deploy **TONS** of stuff in it
2. stop VirtualBox and create another VM with KVM, run it
3. run `minikube start`

**Full output of `minikube start` command used, if not already included:**
```
$ minikube start
🙄  minikube v1.6.1 on Ubuntu 18.04
✨  Selecting 'virtualbox' driver from user configuration (alternates: [kvm2 none])
👍  Kubernetes 1.17.0 is now available. If you would like to upgrade, specify: --kubernetes-version=1.17.0
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing virtualbox VM for "minikube" ...
🔄  Retriable failure: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.239666 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
🔥  Deleting "minikube" in virtualbox ...
^C
```

# 

I have no idea who thought it was ok to delete someone's entire VM just because. It does not even make sense, you can't start VirtualBox so you go ahead and remove the VM?

Don't you people know you need to ask permission before removing stuff?

**Comment by tstromberg** [comment]
Hey @xphoniex 

First my apologies - I'm the one who introduced this behavioral change last year. The good news is that this was fixed in minikube v1.6.2 (released last December). Here's the issue: #5941

minikube was designed around the idea that the VM's are ephemeral, so I thought it would be safe to delete VM's if startup is failed. I understand now that some folks have more complicated configurations than others.

We did recently re-introduce this feature by request, but have it disabled by default: `--delete-on-failure`. I fully agree that deletion of data should always be done explicitly.

Again, my apologies.
