### ISSUE TITLE
minikube start --vm-dirver=none报错

### ISSUE THREAD

**Issue by dwyane3011** [kubernetes/minikube#8031]
**重现问题所需的命令**：minikube start --vm-dirver=none

**失败的命令的完整输出**：<details>
W0507 17:06:47.518734   43723 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
	[WARNING Swap]: running with swap on is not supported. Please disable swap
	[WARNING FileExisting-ebtables]: ebtables not found in system path
	[WARNING FileExisting-socat]: socat not found in system path
	[WARNING SystemVerification]: failed executing "docker info --format '{{json .}}'"\noutput: flag provided but not defined: --format
See 'docker info --help'.
\nerror: exit status 125
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR IsDockerSystemdCheck]: cannot execute 'docker info -f {{.CgroupDriver}}': exit status 125
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：Centos 7.2.1511

**Comment by dwyane3011** [comment]
help! help! help!

**Comment by sharifelgamal** [comment]
`minikube start --vm-dirver=none` is misspelled, so it's trying to use the docker driver, try `minikube start --driver=none`

**Comment by anencore94** [comment]
I guess the misspelling "--vm-dirver" is just typo in this issue. @sharifelgamal @dwyane3011 

If someone run "minikube start --vm-diver=none", the stdout says as followings: "Error: unknown flag: --vm-dirver" with minikube v1.9.2 and v1.10.0.

But, still need some more information to figure out what the problem is and to reproduce this issue..

**Comment by medyagh** [comment]
Hi @Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/triage support, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information....


Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
