### ISSUE TITLE
minikube addons enable metics-server

### ISSUE THREAD

**Issue by manojunnam1438** [kubernetes/minikube#8059]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by sharifelgamal** [comment]
Hey @manojunnam1438  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!
