### ISSUE TITLE
issue in launching minikube

### ISSUE THREAD

**Issue by amit17133129** [kubernetes/minikube#8165]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The version of minikube.
- The driver you are using.
- The Operation system you are using.
- The output of the "minikube logs" 

This will help us isolate the problem further. Thank you!

**Comment by medyagh** [comment]
@amit17133129 I noticed you created 3 issues, please use one issue for same issue, 
I am closing this in favor of
https://github.com/kubernetes/minikube/issues/8195
