### ISSUE TITLE
Unable to start minikube on OpenVZ server

### ISSUE THREAD

**Issue by yonz2** [kubernetes/minikube#8167]
**Steps to reproduce the issue:** 

I'm trying to get minikube to run on an OpenVZ / Ubuntu 18.04 Server (Hosted by https://strato.de). I followed the instructions here: https://minikube.sigs.k8s.io/docs/start/ .
Docker is running (using systemd as cgroup driver). See: 
[Docker-Version.txt](https://github.com/kubernetes/minikube/files/4637495/Docker-Version.txt).

`sudu minikube delete`
`sudo minikube start --driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost --extra-config=kubelet.cgroup-driver=systemd --alsologtostderr`

```
	[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

```

**Full output of `minikube start` command :**

[Minikube-stderr.log](https://github.com/kubernetes/minikube/files/4637494/Minikube-stderr.log)

No matter what I try Minikube never starts. I've tried with `--driver=docker` as well, but that's not working either. 

Any idea what my problem could be?

All help will be much appreciated,
Yonz

**Comment by afbjorklund** [comment]
Running minikube in a server container is **not** a fully supported environment, normally it is run on the laptop in either a virtual machine or a local container. So you might run into some problems, maybe your cloud provider has a better environment for Kubernetes available ?

Anyway, your problem seems to be with iptables. Since you are running it directly on the machine (none driver), you might want to look into the `kubeadm` documentation. https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by afbjorklund** [comment]
Probably need more documentation around LXC and OpenVZ environments #7957

And also the "none" driver page is missing some important information too. #7905

**Comment by medyagh** [comment]
is there a way we can detect we are running inside a OpenVZ so we can warn the user that this might not work ?
