### ISSUE TITLE
X Error getting cluster config: unmarshal: invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by Backbecher05** [kubernetes/minikube#8176]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The version of minikube.
- The driver you are using.
- The Operation system you are using.
- The output of the "minikube logs" 

This will help us isolate the problem further. Thank you!

**Comment by Backbecher05** [comment]
Please solve this issue as soon as possible
Am using windows 10

**Comment by medyagh** [comment]
@Backbecher05  in order to help you I need more information,
do you mind sharing the minikube version ?
and also could you please share the _FULL_ output of these commands:

```
minikube version
minikube delete
minikube start --alsologtostderr -v=8
```
and also
```
minikube logs
```
