### ISSUE TITLE
Failed to setup certs: profile certs: generate signed cert for "minikube": Unable to decode certificate

### ISSUE THREAD

**Issue by marwamemni** [kubernetes/minikube#8183]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The version of minikube.
- The driver you are using.
- The Operation system you are using.
- The output of the "minikube logs" 

This will help us isolate the problem further. Thank you!

**Comment by medyagh** [comment]
@marwamemni I  haven't heard from you, please reopen if you still have an issue
