### ISSUE TITLE
 Unable to load config: unmarshal: invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by Vedanshshri** [kubernetes/minikube#8186]
hey everyone i am facing this issue from some days in installation of minikube 
This is the command i am writing  in windows prompt :--
C:\Program Files\Kubernetes\Minikube> minikube start
this is error :--
* minikube v1.9.2 on Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
X Unable to load config: unmarshal: invalid character '\x00' looking for beginning of value
I am just installing kubernates not much

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The version of minikube.
- The driver you are using.
- The Operation system you are using.
- The output of the "minikube logs" 

This will help us isolate the problem further. Thank you!



@Vedanshshri I notied you are using an old minikube version, do you mind trying with latest verison and the docker driver and see if you still have the s

**Comment by Vedanshshri** [comment]
@medyagh  
driver :- oracle virtual box
minikube version :-  minikube v1.9.2 
operating system :-  windows 10

output of minikube logs :-
C:\Users\vedansh shrivastava>minikube logs
*
X Error getting cluster config: unmarshal: invalid character '\x00' looking for beginning of value
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by priyawadhwa** [comment]
Hey @Vedanshshri I wonder if your minikube cluster config has been corrupted, and so when minikube tries to read the file it errors out.

could you try running:

```
minikube config view --alsologtostderr
```

and provide the output if it fails?

**Comment by sachin53110** [comment]
Unable to load config: unmarshal: invalid character '\x00' looking for beginning of value 


how to solve this error in cmd

**Comment by priyawadhwa** [comment]
Hey @sachin53110 -- could you try running:

```
minikube delete --all --purge
```
and then see if `minikube start` works?

Note that running "minikube delete --all --purge" will delete all minikube clusters and the minikube home directory ($HOME/.minikube), which should delete the corrupt minikube config.

**Comment by priyawadhwa** [comment]
Hey @Vedanshshri are you still seeing this issue?

**Comment by sharifelgamal** [comment]
a `minikube delete --all --purge` should remove the corrupt config file and help you start a cluster properly.

**Comment by medyagh** [comment]
Hi @Vedanshshri, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by asutoshgec** [comment]
@medyagh I was getting below error while running `minikube start --driver=virtualbox`
`minikube start
* minikube v1.12.1 on Centos 7.8.2003
X Unable to load config: unmarshal: unexpected end of JSON input

[asutosh@docker1 root]$ minikube config view --alsologtostderr
W0723 20:48:17.713218    3479 root.go:246] Error reading config file at /home/asutosh/.minikube/config/config.json: open /home/asutosh/.minikube/config/config.json: no such file or directory`

The command `minikube delete --all --purge` works for me.

Thanx
