### ISSUE TITLE
minikube.exe start * minikube v1.9.2 on Microsoft Windows 10 Pro 10.0.17763 Build 17763 X Unable to load config: unmarshal: invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by Backbecher05** [kubernetes/minikube#8189]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

The exact command-lines used, so that we may replicate the issue
The version of minikube.
The driver you are using.
The Operation system you are using.
The output of the "minikube logs"
This will help us isolate the problem further. Thank you!

@Vedanshshri I notied you are using an old minikube version, do you mind trying with latest verison and the docker driver and see if you still have the s

**Comment by sharifelgamal** [comment]
Hey @Backbecher05 – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!
