### ISSUE TITLE
kubectl expose deployment hello-node --type=LoadBalancer --port=8080

### ISSUE THREAD

**Issue by zgswl** [kubernetes/minikube#8263]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>
|-----------|------------|-------------|-------------------------|
| NAMESPACE |    NAME    | TARGET PORT |           URL           |
|-----------|------------|-------------|-------------------------|
| default   | hello-node |             | http://172.17.0.7:30422 |
|-----------|------------|-------------|-------------------------|
* Opening service default/hello-node in default browser...
Minikube Dashboard is not supported via the interactive terminal experience.

Please click the 'Preview Port 30000' link above to access the dashboard.
This will now exit. Please continue with the rest of the tutorial.
*
X open url failed: http://172.17.0.7:30422: exit status 1
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by tstromberg** [comment]
I do not understand where this tutorial is coming from, but it seems like you may be trying to open a web browser in an environment where it is not possible. Where is this being run from?

Try these getting started docs: https://minikube.sigs.k8s.io/docs/start/

**Comment by medyagh** [comment]
Hi @zgswl , have you had a chance to try Thomas's suggestion?
 I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 


I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
