### ISSUE TITLE
error: error executing jsonpath "{.items[0].metadata.name}"

### ISSUE THREAD

**Issue by futaii** [kubernetes/minikube#8288]
hello,
I wanted to get the POD_NAME for running Grafana with 
 kubectl get pods --namespace default -l "app=grafana,release=grafana" -o jsonpath="{.items[0].metadata.name}"

but it tells me...
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
        template was:
                {.items[0].metadata.name}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}

grafana is running and it worked with Prometheus.

**Comment by n0npax** [comment]
Hey @futaii 

Can you please provide more details?

Does expected behavior works on Kubernetes deployed somewhere else?

I run almost the same command on my own instance of minikube and it works just fine (I had deployed grafana earlier)

```bash
kubectl get pods --namespace default  -l app.kubernetes.io/instance=grafana,app.kubernetes.io/name=grafana -o jsonpath="{.items[0].metadata.name}"
grafana-5745c4bd77-6wnfx%                                                                  
```

I'm guessing your issue is due to fact there is no pod matching your filter expression.

In my case, there is no pod with the label `foo=bar`, and I can see the same error as yours.

```bash
 kubectl get pods --namespace default  -l foo=bar -o jsonpath="{.items[0].metadata.name}"   
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

Please ensure `kubectl get pods --namespace default -l "app=grafana,release=grafana" ` is returning data, and provide more context if your issue is not solved.

**Comment by tstromberg** [comment]
Agreed. My guess is that there really is no pod that matches your expression.

**Comment by sharifelgamal** [comment]
@futaii Can you confirm that not having a pod match your expression was the issue?

**Comment by sharifelgamal** [comment]
@futaii I'm going to go ahead and close this issue, we haven't heard from you in a bit. Feel free to reopen this if it remains an issue.

**Comment by Chirag-786** [comment]
I am also facing the same issue ..

**Comment by busyboy77** [comment]
shouldn't be this like 
``` kubectl get pods --namespace kube-system   -l tier=control-plane -o jsonpath='{.items[0]..metadata.uid}{"\n"}'  ```
