### ISSUE TITLE
proxy environment variables are not used anymore in minikube v1.10.1

### ISSUE THREAD

**Issue by oocx** [kubernetes/minikube#8293]
I'm using minikube on Windows 10 with the hyperv driver. I'm behind a proxy server, connections to the internet without proxy server are not allowed.

After I upgraded to minikube v1.10.1, it seems like my proxy environment variables are no longer used by minikube. When I create pods, they are not able to pull images from the docker hub.

After downgrading back to v1.9.2 again, everything works as expected.

**Steps to reproduce the issue:** 

1. set HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables
2.minikube start --vm-driver hyperv --disk-size 24GB --cpus=6 --memory=3000 --extra-config=apiserver.runtime-config=api/all=true,extensions/v1beta1=true --force
3. create any pod, for example "kubectl run test --image busybox -i -t -- sh". The pod will not be able to pull images from the docker hub.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
* minikube v1.10.1 auf Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Using the hyperv driver based on existing profile

! 'hyperv' driver reported an issue: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent returned "WARNING: The names of some imported commands from the module 'Diamant.Apps' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For \r\na list of approved verbs, type Get-Verb.\nTrue\r\n"
* Suggestion: Enable Hyper-V: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

* Starting control plane node minikube in cluster minikube
* Restarting existing hyperv VM for "minikube" ...
* Gefundene Netzwerkoptionen:
  - HTTP_PROXY=http://192.168.100.101:8080
  - HTTPS_PROXY=http://192.168.100.101:8080
  - NO_PROXY=(long list of internal IPs + host names)
  - http_proxy=http://192.168.100.101:8080
  - https_proxy=http://192.168.100.101:8080
  - no_proxy=(long list of internal IPs + host names)
* Vorbereiten von Kubernetes v1.18.2 auf Docker 19.03.8...
  - env HTTP_PROXY=http://192.168.100.101:8080
  - env HTTPS_PROXY=http://192.168.100.101:8080
  - env NO_PROXY=(long list of internal IPs + host names)
  - env HTTP_PROXY=http://192.168.100.101:8080
  - env HTTPS_PROXY=http://192.168.100.101:8080
  - env NO_PROXY=(long list of internal IPs + host names)
  - apiserver.runtime-config=api/all=true,extensions/v1beta1=true
* Enabled addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"

**Comment by tstromberg** [comment]
I believe this was fixed by #8198 - do you mind trying one of the binaries to check?

https://storage.googleapis.com/minikube-builds/8198/docker-machine-driver-kvm2-amd64
https://storage.googleapis.com/minikube-builds/8198/e2e-darwin-amd64
https://storage.googleapis.com/minikube-builds/8198/e2e-linux-amd64
https://storage.googleapis.com/minikube-builds/8198/e2e-windows-amd64
https://storage.googleapis.com/minikube-builds/8198/e2e-windows-amd64.exe
https://storage.googleapis.com/minikube-builds/8198/minikube-darwin-amd64
https://storage.googleapis.com/minikube-builds/8198/minikube-darwin-amd64.tar.gz
https://storage.googleapis.com/minikube-builds/8198/minikube-linux-amd64
https://storage.googleapis.com/minikube-builds/8198/minikube-linux-amd64.tar.gz
https://storage.googleapis.com/minikube-builds/8198/minikube-windows-amd64
https://storage.googleapis.com/minikube-builds/8198/minikube-windows-amd64.exe
https://storage.googleapis.com/minikube-builds/8198/minikube-windows-amd64.tar.gz

**Comment by medyagh** [comment]
@oocx 
 I haven't heard back from you, I wonder if you still have this issue? I believe we had fixed this long time ago ,have you had a chance to try if this was fixed ? 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
