### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by munwar24** [kubernetes/minikube#8399]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by prasadkatti** [comment]
Hi @munwar24 . Can you please provide some details on what bug you encountered? Can you provide the full output for the following commands -

1. your `minikube start` command with `--logtostderr -v5` options
2. `minikube logs`

**Comment by medyagh** [comment]
@munwar24 

Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The version of minikube.
- The driver you are using.
- The Operation system you are using.
- The output of the "minikube logs" 

This will help us isolate the problem further. Thank you!


Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
