### ISSUE TITLE
docker: error getting ip during provisioning: IPs output should only be one line, got 2 lines

### ISSUE THREAD

**Issue by ghost** [kubernetes/minikube#8409]
**Steps to reproduce the issue:** 

1. After install minikube following this link https://kubernetes.io/docs/tasks/tools/install-minikube/ 
2. Then execute `minikube start --driver=docker`, then error above shown.
```
😄  minikube v1.11.0 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🤦  StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
🏃  Updating the running docker "minikube" container ...
😿  Failed to start docker container. "minikube start" may fix it: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

💣  error provisioning host: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by medyagh** [comment]
@phua-actech
that is interesting ! I have not seen this before, apparantly the docker inspect hat returned two lines for the network IP !

is there anything special about your docker setup ? do you have an enabled docker swarm ?


 do you mind sharing the full output of:
```
docker info
```
and also

```
docker inspect minikube
```

and also do you mind trying to paste the full output of 
minikube start --driver=docker --alsologtostderr

**Comment by jadiy** [comment]
I also had this problem , but on MacOs system.First I thought there was a problem about proxy, but after using `minikube delete` many times, I saw a message 'WARNING: Error loading config file: ~/.docker/config.json: EOF' . then I deleted this file by `rm ~/.docker/config.json` and then `minikube delete` and then start minikube again and it's going OK.

**Comment by priyawadhwa** [comment]
Hey @phua-gingsheng could you provide the output of:

```
cat ~/.docker/config.json
```

**Comment by AminuIsrael** [comment]
Am currently facing this issue too.

**Comment by vyom-soft** [comment]
Same here. I am also see this error
$ minikube start --driver=docker
😄  minikube v1.12.2 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for &quot;minikube&quot; ...
🤦  StartHost failed, but will try again: IPs output should only be one line, got 2 lines
🏃  Updating the running docker &quot;minikube&quot; container ...

**Comment by vyom-soft** [comment]
> I also had this problem , but on MacOs system.First I thought there was a problem about proxy, but after using `minikube delete` many times, I saw a message 'WARNING: Error loading config file: ~/.docker/config.json: EOF' . then I deleted this file by `rm ~/.docker/config.json` and then `minikube delete` and then start minikube again and it's going OK.

Yes that worked.

**Comment by priyawadhwa** [comment]
Looks like we could add a solution message for this; if we see this error:

```
IPs output should only be one line, got 2 lines
```

suggest to the user that they fix their `.docker/config` and restart minikube.

If anyone would be interested in fixing this, feel free to take this issue by commenting /assign!

**Comment by sachinkumarsingh092** [comment]
Will this suggestion work:
`IPs output should only be one line, got %d lines. Please fix your ~/.docker/config file and restart minikube.`

/assign

**Comment by PorasS** [comment]
😄  minikube v1.15.1 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.19.4 preload ...
    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 364.27 MiB
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by PorasS** [comment]
i am also getting the same issue on ubuntu.

**Comment by medyagh** [comment]
@vyom-soft I am curious if stil have this issue with latest version of minikube ? I believe we added a few checks arround old docker versions

**Comment by Filip-231** [comment]
I have the same issue nothing helps !
Terminal: 

(base) root>~ #cd ~/.docker
(base) root>.docker #rm -rf config.json
(base) root>.docker #minikube delete --profile=minikube
🔥  Deleting "minikube" in docker ...
💀  Removed all traces of the "minikube" cluster.
(base) root>.docker #minikube start --driver=docker
😄  minikube v1.18.1 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
🛑  The "docker" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❌  Exiting due to DRV_AS_ROOT: The "docker" driver should not be used with root privileges.

(base) root>.docker #sudo lorbi
sudo: lorbi: command not found
(base) root>.docker #su lorbi
(base) lorbi>.docker $minikube start --driver=docker
E0306 19:45:22.370311    7306 cloud_events.go:60] unable to write to /home/lorbi/.minikube/profiles/minikube/events.json: open /home/lorbi/.minikube/profiles/minikube/events.json: permission denied
😄  minikube v1.18.1 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube

❌  Exiting due to HOST_HOME_PERMISSION: Failed to save config: open /home/lorbi/.minikube/profiles/minikube/config.json: permission denied
💡  Suggestion: Your user lacks permissions to the minikube profile directory. Run: 'sudo chown -R $USER $HOME/.minikube; chmod -R u+wrx $HOME/.minikube' to fix
🍿  Related issue: https://github.com/kubernetes/minikube/issues/9165

(base) lorbi>.docker $sudo chown -R $USER $HOME/.minikube
(base) lorbi>.docker $chmod -R u+wrx $HOME/.minikube
(base) lorbi>.docker $minikube start --driver=docker
😄  minikube v1.18.1 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...- ^C
(base) lorbi>.docker $

**Comment by Filip-231** [comment]
> I have the same issue nothing helps !
> Terminal:
> 
> (base) root>~ #cd ~/.docker
> (base) root>.docker #rm -rf config.json
> (base) root>.docker #minikube delete --profile=minikube
> 🔥 Deleting "minikube" in docker ...
> 💀 Removed all traces of the "minikube" cluster.
> (base) root>.docker #minikube start --driver=docker
> 😄 minikube v1.18.1 on Ubuntu 18.04
> ✨ Using the docker driver based on user configuration
> 🛑 The "docker" driver should not be used with root privileges.
> 💡 If you are running minikube within a VM, consider using --driver=none:
> 📘 https://minikube.sigs.k8s.io/docs/reference/drivers/none/
> 
> ❌ Exiting due to DRV_AS_ROOT: The "docker" driver should not be used with root privileges.
> 
> (base) root>.docker #sudo lorbi
> sudo: lorbi: command not found
> (base) root>.docker #su lorbi
> (base) lorbi>.docker $minikube start --driver=docker
> E0306 19:45:22.370311 7306 cloud_events.go:60] unable to write to /home/lorbi/.minikube/profiles/minikube/events.json: open /home/lorbi/.minikube/profiles/minikube/events.json: permission denied
> 😄 minikube v1.18.1 on Ubuntu 18.04
> ✨ Using the docker driver based on user configuration
> 👍 Starting control plane node minikube in cluster minikube
> 
> ❌ Exiting due to HOST_HOME_PERMISSION: Failed to save config: open /home/lorbi/.minikube/profiles/minikube/config.json: permission denied
> 💡 Suggestion: Your user lacks permissions to the minikube profile directory. Run: 'sudo chown -R $USER $HOME/.minikube; chmod -R u+wrx $HOME/.minikube' to fix
> 🍿 Related issue: #9165
> 
> (base) lorbi>.docker $sudo chown -R $USER $HOME/.minikube
> (base) lorbi>.docker $chmod -R u+wrx $HOME/.minikube
> (base) lorbi>.docker $minikube start --driver=docker
> 😄 minikube v1.18.1 on Ubuntu 18.04
> ✨ Using the docker driver based on user configuration
> 👍 Starting control plane node minikube in cluster minikube
> 🔥 Creating docker container (CPUs=2, Memory=2200MB) ...
> ✋ Stopping node "minikube" ...
> 🛑 Powering off "minikube" via SSH ...
> 🔥 Deleting "minikube" in docker ...
> 🤦 StartHost failed, but will try again: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
> 🔥 Creating docker container (CPUs=2, Memory=2200MB) ...- ^C
> (base) lorbi>.docker $

I'm running docker on my Oracle VirtualBox, ubuntu 18.04

Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by matheusnicolas** [comment]
I had the same problem and I fixed using:

$ sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
$ sudo chmod g+rwx "$HOME/.docker" -R

Change user for your whoami, try whoami in your terminal and paste the result  on $USER and be happy!

**Comment by matheusnicolas** [comment]
I had the same problem and I fixed using:

$ sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
$ sudo chmod g+rwx "$HOME/.docker" -R

Change user for your whoami, try whoami in your terminal and paste the result  on $USER and be happy!

**Comment by matheusnicolas** [comment]
I had the same problem and first I tried to remove the .docker/config.json file, the same issue persists. So:

After deleted the config.json file I tried these steps:

$ sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
$ sudo chmod g+rwx "$HOME/.docker" -R

Change user for your whoami, try whoami in your terminal and paste the result  on $USER and be happy!

**Comment by ashokballolli** [comment]
> minikube delete

This resolved the issue, thank you

**Comment by ashokballolli** [comment]
> I also had this problem , but on MacOs system.First I thought there was a problem about proxy, but after using `minikube delete` many times, I saw a message 'WARNING: Error loading config file: ~/.docker/config.json: EOF' . then I deleted this file by `rm ~/.docker/config.json` and then `minikube delete` and then start minikube again and it's going OK.

This resolved the issue, thank you

**Comment by klaases** [comment]
This issue will be closed as some time has passed, and comments above address the issue. Furthermore, the OP is no longer active on Github at this time.

If needed, please feel free to re-open the issue by commenting with `/reopen`.

Thank you for sharing your experience!

**Comment by bejoinka** [comment]
I had an errant comma in my `/home/{user}/.docker/config.json`, which gave me this same issue... so, you'll see this issue when the `config.json` file is invalid.
