### ISSUE TITLE
istio issue for creeating ingress loadbalancer

### ISSUE THREAD

**Issue by mayukh1** [kubernetes/minikube#8443]
**Steps to reproduce the issue:** 

mayukh@mayukh-Inspiron-3521:~/istio-1.6.0$ export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}')
mayukh@mayukh-Inspiron-3521:~/istio-1.6.0$ export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}')
mayukh@mayukh-Inspiron-3521:~/istio-1.6.0$ export TCP_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="tcp")].nodePort}')
mayukh@mayukh-Inspiron-3521:~/istio-1.6.0$ export INGRESS_HOST=$(minikube ip)

💣  Error getting cluster config: read: open /home/mayukh/.minikube/profiles/minikube/config.json: permission denied

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Hi @mayukh1 , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
