### ISSUE TITLE
virtualbox: improve solution message -> ensure it is in the path

### ISSUE THREAD

**Issue by phpsxg** [kubernetes/minikube#8453]
**重现问题所需的命令**：
minikube start --driver=virtualbox

**失败的命令的完整输出**：<details>
😄  Debian 8.0 上的 minikube v1.11.0
✨  根据用户配置使用 virtualbox 驱动程序

❗  'virtualbox' 驱动程序报告了一个问题： /usr/bin/VBoxManage list hostinfo failed:

💡  建议：Install the latest version of VirtualBox
📘  文档：https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/

💣  Failed to validate 'virtualbox' driver

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
No LSB modules are available.
Distributor ID:	Deepin
Description:	Deepin 15.5 Professional
Release:	15.5
Codename:	camel

**Comment by medyagh** [comment]
@phpsxg what version of vbox are you using ? would upgrading vbox help ?

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by secnum** [comment]
Same issue here with vbox 6.1.10

**Comment by IllusionaryX** [comment]
For me I think this was a path issue. Running "VBoxManage.exe list hostinfo" from the VirtualBox directory ran fine, so I added VirtualBox path to the PATH environment variable, uninstalled and then reinstalled minikube (Via Chocolatey in my case) and it worked fine. 

NOTE: I made NO OTHER changes that what I just listed.

**Comment by medyagh** [comment]
seems like mininkube' suggestion could be improved 

minikube had said,
```
💡 ：Install the latest version of VirtualBox
📘 ：https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/
```

we could improve it and say 

💡：Install the latest version of VirtualBox and ensure it is in the path
📘：https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/

**Comment by Ajitesh13** [comment]
Hello, as this is marked as a good-first-issue, can you give me a good starting point for working on this issue?

**Comment by tstromberg** [comment]
@Ajitesh13 - Sure!

First modify this line with the wording you prefer:

https://github.com/kubernetes/minikube/blob/ad083ba7acafe4cd6018fb2fc92364e9eb148b33/pkg/minikube/problem/err_map.go#L334

Then build minikube:

`make`

Then test to see what happens if you try to use the VirtualBox driver where it isn't in PATH, for instance:

`env PATH=/bin:/sbin ./out/minikube start --driver=virtualbox`

Sound OK?

**Comment by Ajitesh13** [comment]
ok! Thanks for your support, will let you know if faced any difficulty.

**Comment by Ajitesh13** [comment]
@tstromberg while recreating this issue(executing the command: `env PATH=/bin:/sbin ./out/minikube start --driver=virtualbox`) I got the following:
```
❗  'virtualbox' driver reported an issue: unable to find VBoxManage in $PATH
💡  Suggestion: Install VirtualBox
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/
```
As specified in the above conversation, the suggestion is coming as "Install VirtualBox" instead of "Install the latest version of VirtualBox". Can you predict why?
