### ISSUE TITLE
`minikube dashboard` does not open

### ISSUE THREAD

**Issue by albertocsm** [kubernetes/minikube#846]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
minikube version: v0.12.2

**Environment**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
"DriverName": "virtualbox"

- **Docker version** (e.g. `docker -v`):
Docker version 1.12.3, build 6b644ec

- **Others**:

> kubectl --context=minikube --namespace=kube-system get svc kubernetes-dashboard -o json

```json
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "kubernetes-dashboard",
        "namespace": "kube-system",
        "selfLink": "/api/v1/namespaces/kube-system/services/kubernetes-dashboard",
        "uid": "a4f7ea4c-ac14-11e6-94fe-cae9f4c758ba",
        "resourceVersion": "103",
        "creationTimestamp": "2016-11-16T15:52:14Z",
        "labels": {
            "app": "kubernetes-dashboard",
            "kubernetes.io/cluster-service": "true"
        }
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 80,
                "targetPort": 9090,
                "nodePort": 30000
            }
        ],
        "selector": {
            "app": "kubernetes-dashboard"
        },
        "clusterIP": "10.0.0.204",
        "type": "NodePort",
        "sessionAffinity": "None"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

**What happened**:

can not obtain dashboard url
> minikube dashboard --url

`Service kube-system/kubernetes-dashboard does not have a node port. To have one assigned automatically, the service type must be NodePort or LoadBalancer, but this service is of type ClusterIP.
Check that minikube is running.`

also, can not open the dashboard with the address indicated when performing 
> kubectl --context=minikube cluster-info
> https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

I get a `401 Unauthorized`

or event using the service nodePort
> https://192.168.99.100:30000/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

This way I get a `404`

**Comment by dlorenc** [comment]
@aaron-prindle can you take a look here?

**Comment by aaron-prindle** [comment]
I am unable to reproduce with minikube v0.12.2., OS: Ubuntu 14.04, Driver: virtualbox.  
`minikube dashboard --url` is working for me:
```
$ minikube dashboard --url
http://192.168.99.100:30000
```

I have practically identical output for:
```
$ kubectl --context=minikube --namespace=kube-system get svc kubernetes-dashboard -o json
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "kubernetes-dashboard",
        "namespace": "kube-system",
        "selfLink": "/api/v1/namespaces/kube-system/services/kubernetes-dashboard",
        "uid": "c17d2b71-b1ad-11e6-9d35-eaaac50b9180",
        "resourceVersion": "82",
        "creationTimestamp": "2016-11-23T18:50:51Z",
        "labels": {
            "app": "kubernetes-dashboard",
            "kubernetes.io/cluster-service": "true"
        }
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 80,
                "targetPort": 9090,
                "nodePort": 30000
            }
        ],
        "selector": {
            "app": "kubernetes-dashboard"
        },
        "clusterIP": "10.0.0.54",
        "type": "NodePort",
        "sessionAffinity": "None"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

Regarding the dashboard urls posted, the first:
```
kubectl --context=minikube cluster-info
https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
```
 will not work due to the authentication on the kubernetes-api (as shown in the error message).  You have to use the exposed NodePort (I am not sure why this isn't coming up in your case).

The second url is incorrect, the dashboard url should not have https: or the /api/v1... suffix, it should simply be:
```
http://$(minikube ip):30000/
http://192.168.99.100:30000/ (in this case)
```

I am not sure why `minikube dashboard --url` is throwing the "service is not of type NodePort error" as the service definitely if of type NodePort (as shown in the json).  Can you verify that the `kubernetes-dashboard-<#####>` pod is running with `kubectl get po -n kube-system`? This error would suggest that there is another dashboard running with a different configuration as that error message gets the Spec.Type for the k8s service with name "kubernetes-dashboard".  Do you happen to have any .yaml files in the ~/.minikube/addons/ directory that could be overwriting the kubernetes-dashboard name?  A clean restart of minikube via `minikube delete`, `rm -rf ~.minikube`, and `minikube start` might solve this issue if there is an overriding .yaml in that directory.  In attempting to remove the dashboard-rc.yaml and the dashboard-svc.yaml independently I was not able to duplicate the error message you are receiving.

**Comment by albertocsm** [comment]
The pod is running and is ready. 

I have other k8s cluster configured in my contexts. One of those being default. 
Can that be interfering with whatever 'minikube dashboard' is doing?

I haven't put any yamls in the add-ons folder. Have to check if something is going on there tomorrow. 

I'll also try a clean restart and see if that helps. 

Either way, thks for the input.

**Comment by aaron-prindle** [comment]
I imagine that the issue is with regards to the contexts.  I am guessing
that minikube is talking to a different dashboard than the one it
initialized as the dashboard-addon that is packaged with minikube is
altered use NodePort where the default dashboard uses type ClusterIP.  I
will try to repro and get back to you.

**Comment by albertocsm** [comment]
`http://192.168.99.100:30000` works just fine
