### ISSUE TITLE
Failed to setup kubeconfig

### ISSUE THREAD

**Issue by 0x00-ketsu** [kubernetes/minikube#8460]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by prasadkatti** [comment]
Hi @0x00-ketsu. Can you provide some additional details for this issue? Can you provide your full minikube start command along with the output? Is this issue separate from the other one you filed?

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
