### ISSUE TITLE
hyperv:  provision: IP not found

### ISSUE THREAD

**Issue by prateek1203** [kubernetes/minikube#8474]
.\minikube.exe start --kubernetes-version="1.18.3" --vm-driver="hyperv"

* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

**Comment by sharifelgamal** [comment]
Hey @prateek1203  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!

**Comment by krylatij** [comment]
I've just faced the same issue on pretty the same environment with the latest minikube 1.12.0.

minikube version: v1.12.0
commit: c83e6c47124b71190e138dbc687d2556d31488d6

Command: `minikube start --driver hyperv --cpus=2 --memory='2000m' --disk-size='10000mb' --alsologtostderr -v=8`

Here are logs
https://drive.google.com/file/d/1RJW3MniT3RRGARabN_eK3QkcZsM64vy1/view?usp=sharing
https://drive.google.com/file/d/1UxO0FJs1lVjKmGQ5vS5j6aAlmChL6uzf/view?usp=sharing

Looks like error is related to hyper-v.
`! Enabling 'storage-provisioner' returned an error: running callbacks: [NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found]`

Wan't change to docker because it does not support Ingress on Windows. 

@sharifelgamal does it make sense to re-open this issue?
