### ISSUE TITLE
open config.json: The system cannot find the file specified

### ISSUE THREAD

**Issue by bunny07-tech** [kubernetes/minikube#8496]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.19025 Build 19025
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
! StartHost failed, but will try again: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\vinod\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Failed to start virtualbox VM. "minikube start" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\vinod\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X error provisioning host: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\vinod\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @bunny07-tech thanks for opening this issue. It looks like the same problem as https://github.com/kubernetes/minikube/issues/5509. Could you try deleting `C:\Users\vinod.minikube\machines\minikube\config.json` and then run:

```
minikube delete
minikube start
```

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
