### ISSUE TITLE
Suddenly  my minikube is not starting

### ISSUE THREAD

**Issue by Abhilash-sandupatla** [kubernetes/minikube#8566]
Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | MediumWrap
Interface: | IMedium {ad47ad09-787b-44ab-b343-a082a3f2dfb1}

**Comment by Abhilash-sandupatla** [comment]
Details: 00:00:00.158274 Power up failed (vrc=VINF_SUCCESS, rc=NS_ERROR_FAILURE (0X80004005))

**Comment by 9kranti** [comment]
Do you use VirtualBox as hypervisor?

**Comment by sharifelgamal** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by Abhilash-sandupatla** [comment]
HI The issue is solved..Thank you , please close
