### ISSUE TITLE
ensure docker restart happens only once 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8618]
on a KVM start log I saw docker restart happened twice during minikube start. which is slow

we should also add integration test ( by checking the logs ) to ensure that the docker restart happened only once (in functional test)

**Comment by afbjorklund** [comment]
I added a docker restart in #8518, when it had been started with the containerd service (about to be stopped)

Since we start every service at boot, before it is configured, we have to do a lot of cleanup like this. Would be nice to avoid that...

But we _needed_ this restart, since otherwise docker was hanging waiting for `/run/containerd/containerd.sock`

Ultimately I would like to fix the ISO (so that it can be restarted), and move the init/systemd scripts out of minikube altogether.

----

But an interim fix would be to rewrite the current units, and make them more like the vendor packages ?

docker.service
● ├─containerd.service
● ├─docker.socket
● ├─system.slice
● ├─network-online.target
● │ ├─networking.service
● │ └─NetworkManager-wait-online.service
● └─sysinit.target

It seems like something changed in the boot order, so now containerd is more likely to start before dockerd.
