### ISSUE TITLE
minio not error after minikube stop and start

### ISSUE THREAD

**Issue by Phelan164** [kubernetes/minikube#8622]
**Steps to reproduce the issue:** 
Env: 
minikube v1.11.0 on Ubuntu 18.04
Kubernetes v1.18.3 on Docker 19.03.2
driver=docker

1. Stop minikube: minikube stop
2. Then start minikube again: minikube start
3. check pods: kubectl get pods -n kubeflow

**Full output of failed command:** 

minio-5f4dc8cf46-k4v6r                                         0/1     CreateContainerConfigError   0          7m11s

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @Phelan164 could you please provide the output of:

- kubectl describe po minio-5f4dc8cf46-k4v6r 
- kubectl logs minio-5f4dc8cf46-k4v6r

**Comment by medyagh** [comment]
Hi @Phelan164 , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
