### ISSUE TITLE
Minikube error minikubestart

### ISSUE THREAD

**Issue by Gopilagadapati** [kubernetes/minikube#8641]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/triage support

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
