### ISSUE TITLE
ingress插件的部署模板文件硬编码了镜像下载路径，导致--image-repository失效

### ISSUE THREAD

**Issue by zhoujianhui** [kubernetes/minikube#8672]
**重现问题所需的命令**：
minikube start --driver=none --image-repository={{ NEXUS_DOCKER_GROUP_REPO }}  --addons ingress

在ingress-dp.yaml.tmpl中硬编码了镜像路径
image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0

这里应该修改为：
 image: {{default "quay.io" .ImageRepository}}/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/triage support

**Comment by medyagh** [comment]
同时，您是否尝试了使用最新版本的minikube的最新驱动程序Docker驱动程序？
你可以尝试
minikube删除
minikube start-驱动程序= docker

有关docker驱动程序签出的更多信息：
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by medyagh** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

The exact minikube start command line used: preferably with --alsologtostderr -v=8 added.
The full output of the command
The full output of "minikube logs"
Please feel free to do so at any point. Thank you for sharing your experience!

@zhoujianhui
