### ISSUE TITLE
bad --insecure-registry values cause: Job for docker.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by anencore94** [kubernetes/minikube#8790]
**Steps to reproduce the issue:** 
1. minikube start --insecure-registry " :5000" --driver=virtualbox
2. Just wait until failed with printing stdout, stderr.

**Full output of failed command:** 
- same as next log

**Full output of `minikube start` command used, if not already included:**

<details>
😄  Ubuntu 18.04 위의 minikube v1.12.1
✨  유저 환경 설정 정보에 기반하여 virtualbox 드라이버를 사용하는 중
👍  Starting control plane node minikube in cluster minikube
🔥  virtualbox VM (CPUs=2, Memory=3900MB, Disk=20000MB) 를 생성하는 중 ...
🔥  virtualbox 의 "minikube" 를 삭제하는 중 ...
🤦  StartHost failed, but will try again: creating host: create: provisioning: ssh command error:
command : sudo diff -u /lib/systemd/system/docker.service /lib/systemd/system/docker.service.new || { sudo mv /lib/systemd/system/docker.service.new /lib/systemd/system/docker.service; sudo systemctl -f daemon-reload && sudo systemctl -f enable docker && sudo systemctl -f restart docker; }
err     : Process exited with status 1
output  : diff: can't stat '/lib/systemd/system/docker.service': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

🔥  virtualbox VM (CPUs=2, Memory=3900MB, Disk=20000MB) 를 생성하는 중 ...
😿  Failed to start virtualbox VM. "minikube start" may fix it: creating host: create: provisioning: ssh command error:
command : sudo diff -u /lib/systemd/system/docker.service /lib/systemd/system/docker.service.new || { sudo mv /lib/systemd/system/docker.service.new /lib/systemd/system/docker.service; sudo systemctl -f daemon-reload && sudo systemctl -f enable docker && sudo systemctl -f restart docker; }
err     : Process exited with status 1
output  : diff: can't stat '/lib/systemd/system/docker.service': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

❌  [DOCKER_RESTART_FAILED] error provisioning host Failed to start host: creating host: create: provisioning: ssh command error:
command : sudo diff -u /lib/systemd/system/docker.service /lib/systemd/system/docker.service.new || { sudo mv /lib/systemd/system/docker.service.new /lib/systemd/system/docker.service; sudo systemctl -f daemon-reload && sudo systemctl -f enable docker && sudo systemctl -f restart docker; }
err     : Process exited with status 1
output  : diff: can't stat '/lib/systemd/system/docker.service': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

💡  Suggestion: Remove the incompatible --docker-opt flag if one was provided
⁉️   Related issue: https://github.com/kubernetes/minikube/issues/7070

</details>

**What I expect**
- I found this error(?) when I tried to start minikube with `minikube start --insecure-registry=$REGISTRY_IP:$REGISTRY_PORT`, but those env was not enrolled in bash.
- It would be nice to check insecure-registry flag value with regular expression checking.
- It does not failed when minikube start with non-existing registry but url is ipv4 type. I mean starting minikube with `--insecure-registry "localhost:5000"` before creating local registry does not failed in current version

**version info**
<details>
minikube version v1.12.1
docker version 19.03.6
ubuntu 18.04.3 LTS
</details>

**Comment by sharifelgamal** [comment]
Yeah, we should probably do a sanity check for URL parameters. Help wanted!

**Comment by kadern0** [comment]
@sharifelgamal I've been looking at a validation function. Are these all the supported formats for the registry or am I missing  something?

```
addresses := []string{"10.0.0.1/24", "example.com", "localhost:5000", "localhost", "127.0.0.1", "www.example.com"}
```

**Comment by tstromberg** [comment]
@kadern0 - I did some digging and discovered that we pass the value directly to dockerd's `--insecure-registry` flag. Here's the documentation: https://docs.docker.com/engine/reference/commandline/dockerd/#insecure-registries

```
 In order to communicate with an insecure registry, the Docker daemon requires --insecure-registry in one of the following two forms:

    --insecure-registry myregistry:5000 tells the Docker daemon that myregistry:5000 should be considered insecure.
    --insecure-registry 10.1.0.0/16 tells the Docker daemon that all registries whose domain resolve to an IP address is part of the subnet described by the CIDR syntax, should be considered insecure.
```

That suggests to me that the only valid forms should be:

* <ip>:<port>
* <hostname>:<port>
* <network>/<netmask> (CIDR)

**Comment by kadern0** [comment]
Thanks for your answer, @tstromberg. This should be easy to achieve with regular expressions although it might be interesting looking at using  some [validator](https://pkg.go.dev/gopkg.in/go-playground/validator.v9) within the ClusterConfig struct although this change will be bigger.

I mention this because it seems to me this function is not 100% correct since it won't reject some malformed URLs (like this "http://;;..,,----__???**"):

https://github.com/kubernetes/minikube/blob/129eefd6a264183850984bac28b48dbec83ee425/cmd/minikube/cmd/start.go#L1108

With the validator in place, many validation functions could be either removed or simplified.

**Comment by kadern0** [comment]
@tstromberg, this one is fixed by #9977

**Comment by cvila84** [comment]
Hello, would it be possible to also consider <ip> and <hostname> in the regexp without having to mention a port ?

In our situation, until 1.17, we were using --insecure-registry dockerhub.example.com in our CI/CD with all K8S manifests pointing to docker images built with tag of kind dockerhub.example.com/xxx/yyy

With 1.17+, to pass the validation, I have to set --insecure-registry dockerhub.example.com:80 (which means the same thing) but the result is that no K8S pod can start as images with tag of kind dockerhub.example.com/xxx/yyy are tried to be pulled in a secure way because it does not precisely match the insecure registry setting which contain the port...

Changing all the jobs that build our docker images in order to add port 80 to the tag is not really an option as we would like to keep consistency in our tags (as they are parsed by some other internal tools we have)

Thanks !

**Comment by kadern0** [comment]
@tstromberg it seems we might need to update the validation fuction according to docker's insecure registry validation (port is not mandatory):
https://github.com/docker/engine/blob/master/registry/config_test.go

Do you agree?
