### ISSUE TITLE
minikube IP not found

### ISSUE THREAD

**Issue by satyasure** [kubernetes/minikube#8898]
C:\WINDOWS\system32>minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"
* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.20180 Build 20180
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\WINDOWS\system32>minikube start
* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.20180 Build 20180
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\WINDOWS\system32>

**Comment by roberttco** [comment]
FYI - same issue for me - Hyper-V running on WS2016 STD and going through the Windows instructions here - https://kubernetes.io/docs/tasks/tools/install-minikube/.  The command line is '''minikube start --driver=hyperv --hyperv-virtual-switch vSwitch''' (e.g. nothing too exciting).  The vSwitch is an external switch.  I ensured guest services is installed and noted that the IP address is available in the Hyper-V manager GUI and via PowerShell.  I deleted minikube using minikube delete and changed the vSwitch to "internal" from "external".  Running the start command again I get '''! StartHost failed, but will try again: creating host: create host timed out in 240.000000 seconds'''

**Comment by roberttco** [comment]
Got wont let me edit my previous comment for come reason but what I meant to say was that guest services is enabled for the VM - although that seems to be irrelevant.

**Comment by priyawadhwa** [comment]
Could you try upgrading to the latest minikube release and running:

```
minikube delete
minikube start
```

Additionally, the docker driver is the recommended driver on windows. If you'd be interested in giving that a try, you can run:

```
minikube start --driver docker
```
assuming you have docker installed.

**Comment by medyagh** [comment]
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by LQss11** [comment]
I have had the same issue and have been trying to solve that for the last 2 days I have tried to install ingress addon:
```sh
minikube addons enable ingress
```
and also tried to run :
```sh
minikube tunnel
```
looked for a way to allow the host machine to access the container IP address but apparently couldn't find a way to do that.

If you run minikube on docker:
```sh
minikube start --driver=docker
```
you won't be able to access the **minikube IP** from your **host machine** since the minikube container's IP address would by accessible through `DockerDesktopVM` but not from your host machine.

You could run **minikube** on another driver such as `VirtualBox` or `Hyperv`, and that might help.


```sh
minikube start --driver=hyperv
minikube start --driver=virtualbox
```

Read more about the [minikube drivers][minikube-drivers]

>In fact, that's really annoying if you don't have enough resources on your computer to run both the Docker desktop VM and the minikube VM at the same time and will eventually slow down your computer. 

To solve that `docker-desktop UI` for `Mac and Windows` provides an easier alternative compared to minikube, which you could simply [activate the Kubernetes feature on your docker-desktop UI][deploy-on-kubernetes]:

![enable-kubernetes][enable-kubernetes]

once it is setup you can right click on the docker desktop icon > Kubernetes 
![docker-desktop][docker-desktop]

To verify now that your deployement/service works properly:
```sh
kubectl apply -f /file.yaml
```

[deploy-on-kubernetes]: https://docs.docker.com/desktop/kubernetes/
[minikube-drivers]: https://minikube.sigs.k8s.io/docs/drivers/
[docker-desktop]: https://docs.docker.com/desktop/images/kube-context.png
[enable-kubernetes]: https://user-images.githubusercontent.com/49565791/150873987-48b80313-a396-4906-8785-6f2149320c61.png
