### ISSUE TITLE
Port forwarding to clusters created with minikube start -p <profile_name>

### ISSUE THREAD

**Issue by igorpalant** [kubernetes/minikube#8944]
**Steps to reproduce the issue:** 
The reason I am going through steps below is that I want to be able to access services deployed into minikube with nondefault profile from machine other than where minikube is deployed.
1. Start Minikube using VirtualBox with **non default profile** - for example minikube start -p testProfile. 
2. Deploy application that has exposed endpoint with NodePort for example.
3. Use port forwarding command to forward port from local host into VirtualBox with following command: VBoxManage modifyvm "VM name" --natpf1 "nameofconnection,tcp,,host_port,,vbox_port"
4) Use IP of host and port you specified in port forwarding command to access your service. It will fail
5) If you use minkube with default profile, this port forwarding works. It might be by design, but I hope to have the way to port-forward traffic into services deployed 

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @igorpalant do you have multiple clusters running when you try to forward the non default cluster?

You can find out via 

```
minikube profile list
```

**Comment by medyagh** [comment]
Hi @igorpalant , I haven't heard back from you, I wonder if you still have this issue?

and do you mind providing those port forwarding commands ? and why did you have to use the port forwarding command ?

why you didnt use just the `minikube service name_of_svc`  command ?  

Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
