### ISSUE TITLE
kicbase build: E: Version '1.18.3~2' for 'cri-o' was not found

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#8982]
It seems that it is not currently possible to rebuild the kicbase image:

```
E: Version '1.18.3~2' for 'cri-o' was not found
The command '/bin/sh -c sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18:/1.18.3/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list" &&     curl -LO https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18:/1.18.3/xUbuntu_20.04/Release.key &&     apt-key add - < Release.key && apt-get update &&     apt-get install -y --no-install-recommends cri-o=1.18.3~2' returned a non-zero code: 100
make: *** [kic-base-image] Error 100
Makefile:533: recipe for target 'kic-base-image' failed
```

See https://github.com/kubernetes/minikube/pull/8974/checks?check_run_id=973059157

**Comment by afbjorklund** [comment]
There is a 1.18.3-3 now

**Comment by medyagh** [comment]
it might worth removing cri-o from supported and tested runtimes from minikube, since we don't have bandwith to troubleshoot cri-o packaing problems anymore. I created issues on cri-o package, I think once cri-o can provide stable packaging we can added it back to supported runtimes.

https://github.com/cri-o/cri-o/issues/4074
https://github.com/cri-o/cri-o/issues/4027
https://github.com/cri-o/cri-o/issues/4027

**Comment by afbjorklund** [comment]
The problem was that you tried to pin the package version (something that **doesn't work** - without a custom package repository)

`apt-get install -y --no-install-recommends cri-o=1.18.3~2`

Problem is "=1.18.3~2", it is the same issue as in ~#8766~

Upstream only said to pin the package repository, to the wanted subproject - they created one for each branch and major release:

`http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.18:/1.18.3/xUbuntu_20.04/`

https://build.opensuse.org/project/subprojects/devel:kubic:libcontainers:stable

----

But other than that, I tend to agree with the cost of supporting podman and cri-o (in addition to docker and docker)...

It's just that it is "the new rkt", so without it we don't have any diversity and no testing of CRI and maybe not even CNI ?
