### ISSUE TITLE
Windows: Suppress Docker Desktop file sharing alert

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9086]
![Screen Shot 2020-08-25 at 1 07 19 PM](https://user-images.githubusercontent.com/4564227/91222395-f6b89000-e6d3-11ea-8eab-397e57cf626d.png)

we need to investigate if Click on Yes causes slowness and issues.

users get prompted for this on windows, and I believe the right thing to do is Click on cancel.

we need to make sure this does not make the user in the dark and have them make this descsion. we should either help the user to decide correctly or suppress docker desskop

**Comment by andriyDev** [comment]
Still need to investigate on Windows.

/lifecycle frozen

**Comment by spowelljr** [comment]
Some background on how you get this message, you have to have Docker Desktop set to use the Hyper-V backend instead of the WSL 2 backend. If you do a non-mount start (`--mount` omitted) the file sharing message will come up, but there doesn't seem to be an issues with not sharing the files.

However, if you do a mount start (`--mount` included) the file sharing message will show up, and if you don't share the current users home directory, you'll get the following error:

`docker: Error response from daemon: Post "http://ipc/filesharing/share": context deadline exceeded (Client.Timeout exceeded while awaiting headers).`

And the start will fail.

There are three ways to resolve this, change Docker Desktop to use the WSL 2 backend, user can share specifically their users home directory, or user can share their whole drive that contains the users home directory (people may find that easier).

I'll add a regex help message that tells the user to do one of these things.
