### ISSUE TITLE
StartHost failed, but will try again: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube":

### ISSUE THREAD

**Issue by yogyad** [kubernetes/minikube#9130]
minikube start --driver=hyperv
* minikube v1.12.3 on Microsoft Windows 10 Enterprise 10.0.19041 Build 19041
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
! StartHost failed, but will try again: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Laxmi Computers\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Failed to start hyperv VM. "minikube start" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Laxmi Computers\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X error provisioning host: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Laxmi Computers\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
I'm curious if this is related to the username having spaces in it, or if the file is missing. 

Can you check if `C:\Users\Laxmi Computers\.minikube\machines` has any files in it?

**Comment by neel8989** [comment]
PS C:\Users\Neel> minikube start --driver=virtualbox
* minikube v1.13.0 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
* Failed to start virtualbox VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Neel\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Neel\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'

**Comment by derklauer-ocean** [comment]
I had this same error with `--vm-driver=hyperv`.  Resolved it by running `minikube delete` then reinstalling minkube as administrator.  Also depending on your windows license if you go the HyperV route you can only run one VM at a time.

**Comment by medyagh** [comment]
@yogyad @neel8989 do you still have this issue ?
do you mind trying deleteing all your VMs and minikube delete --all and try with latest version of minikube?

have you tried docker driver if you can install docker on your system ?

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by zamkhan29** [comment]
$ minikube start --driver=virtualbox
* minikube v1.16.0 on Microsoft Windows 10 Home Single Language 10.0.19042 Build 19042
* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:03.831308 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))
* Failed to start virtualbox VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\cygwin64
\home\91997\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\cygwin64\home\91997\.mi
nikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

**Comment by Kapildev0458** [comment]
> $ minikube start --driver=virtualbox
> 
> * minikube v1.16.0 on Microsoft Windows 10 Home Single Language 10.0.19042 Build 19042
> * Using the virtualbox driver based on user configuration
> * Starting control plane node minikube in cluster minikube
> * Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
> * Deleting "minikube" in virtualbox ...
>   ! StartHost failed, but will try again: creating host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
>   VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
>   VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
>   VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
> 
> Details: 00:00:03.831308 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))
> 
> * Failed to start virtualbox VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\cygwin64
>   \home\91997.minikube\machines\minikube\config.json: The system cannot find the file specified.
> 
> X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\cygwin64\home\91997.mi
> nikube\machines\minikube\config.json: The system cannot find the file specified.
> 
> * Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
> * Related issue: #9130

To solve #9130 issue simply update your VM

**Comment by yogyad** [comment]
Hi team,

Issue resolved.

Close this ticket.

**Comment by vagdevik** [comment]
I had the same issue. So I did the following and it was solved!!!

1. `minikube delete`
2. download minikube and install it again
3. download Virtualbox and instal it again
4. In new cmd, `minikube start --driver=virtualbox`

**Comment by prajaktapatil07** [comment]
C:\Users\Shivaji Patil>minikube start --driver=docker
* minikube v1.20.0 on Microsoft Windows 10 Home Single Language 10.0.19042 Build 19042
* Using the docker driver based on user configuration

X Exiting due to PROVIDER_DOCKER_NOT_RUNNING: deadline exceeded running "docker version --format -": exit status 1
* Suggestion: Restart the Docker service
* Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by sanjivsharmalv** [comment]
I also faced the issue with --vm-driver=hyperv:
Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube"
I resolved it by uninstalling Docker that I installed earlier and then executing the 'minikube start --vm-driver=hyperv '

**Comment by jtabasz** [comment]
Getting same issue. Using W10 Pro, Hyper-V, choco install minikube. All that works. Hyper-V enabled. Docker has been uninstalled. I run `minikube start --vm-driver=hyperv`, I can see the VM called minikube being created in the Hyper-V manager, but the minikube start fails after some time. looks like the VM created by minikube has no IP address. 
[Command_Line_Output.txt](https://github.com/kubernetes/minikube/files/7207721/Command_Line_Output.txt)
[lastStart.txt](https://github.com/kubernetes/minikube/files/7207723/lastStart.txt)

**Comment by souravsk** [comment]
PS C:\WINDOWS\system32> minikube config set driver hyperv
! These changes will take effect upon a minikube delete and then a minikube start
PS C:\WINDOWS\system32> minikube delete
* Stopping node "minikube"  ...
* Deleting "minikube" in hyperv ...
* Removed all traces of the "minikube" cluster.
PS C:\WINDOWS\system32> minikube start --vm-driver=Hyper-V
* minikube v1.25.1 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
! Both driver=hyperv and vm-driver=Hyper-V have been set.

    Since vm-driver is deprecated, minikube will default to driver=hyperv.

    If vm-driver is set in the global config, please run "minikube config unset vm-driver" to resolve this warning.

* Using the hyperv driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...| E0220 22:45:43.329201    5056 main.go:126] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'minikube' failed to start. (Virtual machine ID AD17EF61-EF3F-4B0F-9877-B8CC2B327141)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine
ID AD17EF61-EF3F-4B0F-9877-B8CC2B327141)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation.
(0x8007000E). (Virtual machine ID AD17EF61-EF3F-4B0F-9877-B8CC2B327141)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM



* Stopping node "minikube"  ...
* Deleting "minikube" in hyperv ...
! StartHost failed, but will try again: creating host: create: creating: exit status 1
* Failed to start hyperv VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Sourav\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Sourav\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

PS C:\WINDOWS\system32>

**Comment by chiragch** [comment]
Deleting minikube folder from the path mentioned in an error and then minikube restart solved my problem

**Comment by Axel15007256** [comment]
C:\WINDOWS\system32>minikube start -- vm-driver-virtualbox
* minikube v1.25.2 on Microsoft Windows 10 Home Single Language 10.0.19044 Build 19044
* Automatically selected the virtualbox driver
* Downloading VM boot image ...
    > minikube-v1.25.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.25.2.iso: 237.06 MiB / 237.06 MiB [] 100.00% 6.93 MiB p/s 34s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.23.3 preload ...
    > preloaded-images-k8s-v17-v1...: 505.68 MiB / 505.68 MiB  100.00% 6.83 MiB
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
* Failed to start virtualbox VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\hami_\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\hami_\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

I have tried so far:
minikube delete
minikube delete --all
deleting the folder outlined on the error message
reinstalled minikube

**Comment by codemonstur** [comment]
I had this issue. Reinstalling minikube with administrator rights solved it.

**Comment by msebi** [comment]
Issue similar to @Axel15007256 :

```
$ minikube start --no-vtx-check --vm-driver=virtualbox
* minikube v1.25.2 on Microsoft Windows 10 Home 10.0.19044 Build 19044
* Using the virtualbox driver based on user configuration
* Downloading VM boot image ...
    > minikube-v1.25.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.25.2.iso: 237.06 MiB / 237.06 MiB  100.00% 1.09 MiB p/s 3m38s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.23.3 preload ...
    > preloaded-images-k8s-v17-v1...: 505.68 MiB / 505.68 MiB  100.00% 1.04 MiB
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create host timed out in 360.000000 seconds
* Failed to start virtualbox VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\msebi\.minikube\machines\minikube\config.json: The system cannot
 find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\msebi\.minikube\machines\minikube\config.json: The system cannot find the file
specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130
```

```
$ minikube delete --all
* Removing C:\Users\msebi\.minikube\machines\minikube ...
* Removed all traces of the "minikube" cluster.
* Successfully deleted all profiles
```

```
$ minikube start --no-vtx-check --vm-driver=virtualbox
* minikube v1.25.2 on Microsoft Windows 10 Home 10.0.19044 Build 19044
* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create host timed out in 360.000000 seconds
* Failed to start virtualbox VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\msebi\.minikube\machines\minikube\config.json: The system cannot
 find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\msebi\.minikube\machines\minikube\config.json: The system cannot find the file
specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130
```

Please **don't** close obviously unsolved issues.

**Comment by AmosNyaundi** [comment]
If you are experincing this error "ind the file specified.
* Failed to start hyperv VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\AMOS\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\AMOS\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130"

Here's the reasons:
1. You had a previous installation of minikube or
2. You have not enabled Hyper V or

Take this steps in order to get yourself out:
1. For reason (1) above; run the following command on powershell: `minikube delete --all --purge` and then `minikube delete --all --purge`
2. For reason (2) above; run the following commands on powershell: `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All` and `minikube config set driver hyperv` to set hyper v as default driver then followed by `minikube start --driver=hyperv `

I hope this helps!

![image](https://github.com/kubernetes/minikube/assets/34121169/64feb6fa-15d0-4a64-96b3-3fc19cd353f6)

**Comment by amine-atyq** [comment]
> If you are experincing this error "ind the file specified.
> 
> * Failed to start hyperv VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\AMOS.minikube\machines\minikube\config.json: The system cannot find the file specified.
> 
> X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\AMOS.minikube\machines\minikube\config.json: The system cannot find the file specified.
> 
> * Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
> * Related issue: [StartHost failed, but will try again: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": #9130](https://github.com/kubernetes/minikube/issues/9130)"
> 
> Here's the reasons:
> 
> 1. You had a previous installation of minikube or
> 2. You have not enabled Hyper V or
> 
> Take this steps in order to get yourself out:
> 
> 1. For reason (1) above; run the following command on powershell: `minikube delete --all --purge` and then `minikube delete --all --purge`
> 2. For reason (2) above; run the following commands on powershell: `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All` and `minikube config set driver hyperv` to set hyper v as default driver then followed by `minikube start --driver=hyperv `
> 
> I hope this helps!
> 
> ![image](https://user-images.githubusercontent.com/34121169/252049946-64feb6fa-15d0-4a64-96b3-3fc19cd353f6.png)


Thanks, mate. It resolved the issue.

**Comment by HusmithaSilva** [comment]
Issue I was facing is not enough space in memory to create docker container on local machine.

![issue](https://github.com/kubernetes/minikube/assets/53034252/322c3f7f-5a52-45ce-b18c-bca6fd97ee1d)

These steps help me to solve the issue:

 1. **Close all tabs in Google Chrome, Close programs that are currently 
    running on memory in my local machine. Because of taking much space docker 
    container wouldn't be able to create container on machine.** 

 2. then minikube delete 

     $ minikube delete
     
![delete](https://github.com/kubernetes/minikube/assets/53034252/3ad87f20-bd65-47f9-bbda-8053d6a51495)  


 3. then minikube start.
     
     $ minikube start
    
![start](https://github.com/kubernetes/minikube/assets/53034252/3e1d1b6b-1626-4bcb-a13d-e2541cd79142)

It works for me.


  [1]: https://i.sstatic.net/AB5vH38J.png
  [2]: https://i.sstatic.net/ZLntUFzm.png
  [3]: https://i.sstatic.net/LPfbygdr.png

**Comment by NithyaNallasamy** [comment]
> > If you are experincing this error "ind the file specified.
> > 
> > * Failed to start hyperv VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\AMOS.minikube\machines\minikube\config.json: The system cannot find the file specified.
> > 
> > X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\AMOS.minikube\machines\minikube\config.json: The system cannot find the file specified.
> > 
> > * Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
> > * Related issue: [StartHost failed, but will try again: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": #9130](https://github.com/kubernetes/minikube/issues/9130)"
> > 
> > Here's the reasons:
> > 
> > 1. You had a previous installation of minikube or
> > 2. You have not enabled Hyper V or
> > 
> > Take this steps in order to get yourself out:
> > 
> > 1. For reason (1) above; run the following command on powershell: `minikube delete --all --purge` and then `minikube delete --all --purge`
> > 2. For reason (2) above; run the following commands on powershell: `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All` and `minikube config set driver hyperv` to set hyper v as default driver then followed by `minikube start --driver=hyperv `
> > 
> > I hope this helps!
> > ![image](https://user-images.githubusercontent.com/34121169/252049946-64feb6fa-15d0-4a64-96b3-3fc19cd353f6.png)
> 
> Thanks, mate. It resolved the issue.

thank you... this helped to resolve my issue
