### ISSUE TITLE
Publish additional ports and IPs when running minikube start

### ISSUE THREAD

**Issue by arielmoraes** [kubernetes/minikube#9198]
When `minikube start` command runs using the Docker driver it tells Docker to publish some ports, but it binds to the localhost ip only, thus not giving a chance to access the cluster from another machine using the `kubectl` for example. Another issue is if one wants to access a Service via an Ingress, in that case we need the same solution, which is to add some entries to the iptables as following:

```
iptables -I DOCKER-USER 1 ! -i docker0 -o docker0 -p tcp -j ACCEPT -d $(minikube ip) --dport 443
iptables -t nat -A DOCKER ! -i docker0 -p tcp -j DNAT --dport 443 --to-destination $(minikube ip):443
```

I could also execute those command to bind the 8443 port to 0.0.0.0 to use the kubectl outside the local minikube machine.

Does minikube provide a better way of doing that or is that an inexistent feature?

**Comment by afbjorklund** [comment]
This is by design. The minikube cluster is not _supposed_ to be available "outside" the local developer machine, currently the recommended approach is to `ssh` into the minikube host if wanting remote access. This goes for all the drivers, not only docker.

There actually two different issues here, the first is accessing the apiserver remotely (for some reason). Typically `kubectl proxy`. The other is making a deployed application available remotely, typically `kubectl port-forward` (or perhaps a proper ingress)

This probably need some better explaining in documentation.

Because it is a recurring question (and perhaps expectation)

**Comment by afbjorklund** [comment]
The currently exposed ports are:
* **22 for ssh**
* 2376 for old docker
* **8443 for apiserver**
* 5000 for registry hack

There is a pending request to make it possible for the user to add more (#7332), but that doesn't really answer the question...

We probably don't need to expose docker anymore, and the registry port is just to get around the TLS certificate requirement.

**Comment by arielmoraes** [comment]
I think the main reason that is asked a lot is because minikube is a very easy way of starting a new k8s cluster. So some people will want to use it as a "home cluster" which gives the possibility to host some small applications, like an DLNA server etc. Thus going beyond of just a developer cluster. 

Now for the design part, I think it would be nice to leave the decision of which ports to expose to the user, that would close all those issues, wouldn't it? 😄

**Comment by afbjorklund** [comment]
> I think the main reason that is asked a lot is because minikube is a very easy way of starting a new k8s cluster.

One could also view this as saying that `kubeadm` is too complicated, so people turn to `minikube` for some help ?

It would be nice to cooperate a bit more, so that there are available alternatives for **both** development and deployment.
There _should_ be an easy path to follow, how to start with containers and images and move on to orchestration and clusters.
But it also quickly becomes associated with particular vendors and cloud providers. And it is hard to please multiple audiences.
Both running kubeadm locally (with the none driver) and exposing it externally are popular options, whether we "like it" or not...

**Comment by tstromberg** [comment]
Discussed with team, it seems like we would be willing to accept a PR that introduces this functionality.

**Comment by bolipereira** [comment]
any updates on this? I'd also find it very useful
