### ISSUE TITLE
Include JSON Output as a standard option.

### ISSUE THREAD

**Issue by j-windsor** [kubernetes/minikube#9258]
the `--output` flag does not seem to be offered with most of the commands. `start` has it, but `pause`, `unpause`, and `stop` do not.

Is it possible to make this flag available to all commands as an inherited option? or at least more commands?

**Comment by sharifelgamal** [comment]
Yeah, I imagine this is the end goal for json output, but it's still a work in progress.

cc @priyawadhwa

**Comment by priyawadhwa** [comment]
Hey @j-windsor I think this would definitely be useful to include for the `stop` command. Both `pause` and `unpause` take <1 second to execute, and we initially added JSON output so that users could see progress during long-running commands. Do you think it would still make sense to add it in for `pause` and `unpause` as well?

**Comment by j-windsor** [comment]
I think it would help. In Cloud Code VSCode we are trying to report the ErrorID in metrics and we are currently parsing the ID out of the "Exiting due to..." string.

**Comment by priyawadhwa** [comment]
Currently working on this now.
