### ISSUE TITLE
update go version to be 1.15 in go mod

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9264]
to match 
https://github.com/kubernetes/kubernetes/blob/09b3f6dbb3224f32d28c81f330f303ac16ee2eae/go.mod#L9

**Comment by afbjorklund** [comment]
The master image is `k8s.gcr.io/build-image/kube-cross:v1.15.2-1`

https://github.com/kubernetes/kubernetes/commit/a4a98f440cea4fea7751f7eee377350a72669426

So that is the minor version that we should be using (but 1.15 for go.mod)

```Makefile
GO_VERSION ?= 1.15.2
```

----

Don't forget to update .travis.yml and .github/workflows/*.yml !

The new ISO has go 1.13, which is a problem for podman/cri-o.

**Comment by ravindrabhargava** [comment]
I would like to understand it more and also like to work on it Thanks

**Comment by afbjorklund** [comment]
> The new ISO has go1.13, which is a problem for podman/cri-o.
> 
> Other system programs are fine with that go compiler version...
> 
> Mostly since they don't import kubernetes, which is latest/greatest

This comment was regrading the go compiler version in Buildroot
