### ISSUE TITLE
Exiting due to GUEST_PROVISION: Failed to start host: boot lock: timeout acquiring mutex

### ISSUE THREAD

**Issue by joearul09** [kubernetes/minikube#9403]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`
* The full output of `kubectl get po -A`


Thank you for sharing your experience!

**Comment by ilya-zuyev** [comment]
Hey @barisAtmn, do you mind trying minikube v1.17.1 and if the issue still exists attach log output with the error? Thanks!

**Comment by spowelljr** [comment]
Hi @joearul09, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
