### ISSUE TITLE
mknikube start failed

### ISSUE THREAD

**Issue by scq355** [kubernetes/minikube#9438]
StartHost: Error getting state for host: exit status 126
Unable to start VM: Error getting state for host: exit status 126
Sorry that minikube crashed.

**Comment by sharifelgamal** [comment]
Hey @scq355, I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by medyagh** [comment]
Hi @scq355 , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
