### ISSUE TITLE
storage-provisioner' returned an error: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.2/kubectl apply -f /etc/kubernetes/addons/storage-provisioner.yaml: Process exited with status 1

### ISSUE THREAD

**Issue by spurum1008** [kubernetes/minikube#9509]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @spurum1008, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
