### ISSUE TITLE
`minikube docker` subcommand

### ISSUE THREAD

**Issue by owenthereal** [kubernetes/minikube#9524]
**Steps to reproduce the issue:** 

This is not an issue but a feature request.

It would be nice to have a `minikube docker` subcommand that shells out to  `docker` with the command's `DOCKER_*` env vars set to env vars output by `minikube docker-env`. This is similar to `minikube kubectl` which runs `kubectl` against the minikube cluster.

Currently, in order to not to pollute my current shell,  I'm running `sh -c 'eval $(minikube docker-env) && docker build ...'` to self-contain any docker commands against the minikube cluster. This is not as convenient.

**Full output of failed command:** 

N/A

**Full output of `minikube start` command used, if not already included:**

N/A

**Optional: Full output of `minikube logs` command:**

N/A

**Comment by afbjorklund** [comment]
Toyed with the idea, when implementing `minikube build` (which is pretty much the only thing we use docker for anyway). But it was disregarded both because "minikube is not a package manager" and that it is easy to install docker (not really true, see #6402)

Another practical problem was that docker is not available for all platforms (no binary for windows anymore), and that we would have to do the same for podman. In the worst case ending up having to build and support moby-engine and podman1 outselves.

When running docker-machine, it does have a "config" command matching the "env" command.

But we though that your current workaround wasn't _too_ much worse than having such a command...

**Comment by spowelljr** [comment]
Closing this for now, if there's more evidence that this should be implemented feel free to comment or reopen issue.
