### ISSUE TITLE
Enable minikube for other architectures

### ISSUE THREAD

**Issue by mellotron** [kubernetes/minikube#955]
FEATURE REQUEST

Hello,

I'm trying to run Kubernetes on some arm/arm64 hardware I have and I tried building minikube on a arm64 box (kubectl is available for the arch) - however it seems that minikube's Makefile is only amd64 aware.

Could this project please be enabled for ARM? Happy to do code testing as well.

**Comment by r2d4** [comment]
Minikube needs an environment with virtualization available.  It manages a VM that runs a binary called localkube [0] which runs the kubernetes components as goroutines.  I think that it would be fine to support arm/64 for localkube, however, you might want to check out kubernetes-on-arm [1]

[0] https://github.com/kubernetes/minikube/tree/master/pkg/localkube
https://github.com/kubernetes/minikube/blob/master/Makefile#L62
[1] https://github.com/luxas/kubernetes-on-arm

**Comment by dlorenc** [comment]
cc @luxas who was looking into this earlier.

@mellotron could you explain the use-case a little bit more? What are you hoping to run on the linux/arm64 box?

**Comment by dlorenc** [comment]
@mellotron ping :)

**Comment by luxas** [comment]
@mellotron You just might want to use kubeadm and create a one-node cluster with that: http://kubernetes.io/docs/getting-started-guides/kubeadm/

I moved on to hacking on kubeadm and making that working on ARM(64) since minikube is targeted at workstations with virtualization and cross-os, not arch, while kubeadm and other cluster lifecycle products are focusing on actually running a "real" cluster. But there the drawbacks are not as good UX/simplicity as minikube in the first hand, because you have literally tens or hundreds of options to configure.

Running kubernetes for real should indeed work on arm, and it does. So I don't see a need to use minikube here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multi-platform.md

**Comment by dlorenc** [comment]
I'm going to close this in favor of the kubeadm solution @luxas mentioned. Feel free to reopen if that doesn't work for you.
