### ISSUE TITLE
StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: check container "minikube" running: temporary error created container "minikube" is not running yet

### ISSUE THREAD

**Issue by prasanth595** [kubernetes/minikube#9617]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`
* The full output of `kubectl get po -A`


Thank you for sharing your experience!

**Comment by medyagh** [comment]
@prasanth595 
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

The exact minikube start command line used: preferably with --alsologtostderr -v=8 added.
The full output of the command
The full output of "minikube logs"
Please feel free to do so at any point. Thank you for sharing your experience!
