### ISSUE TITLE
Disable minikube-scheduled-stop.service until a user schedules a stop

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#9865]
The environment file is missing:

```
● minikube-scheduled-stop.service - m/var/lib/minikube/scheduled-stop/environmentinikube scheduled stop
     Loaded: loaded (/lib/systemd/system/minikube-scheduled-stop.service; enabled; vendor preset: enabled)
     Active: failed (Result: resources)

Dec 05 16:01:44 docker systemd[1]: minikube-scheduled-stop.service: Failed to load environment files: No such file or directory

Dec 05 16:01:44 docker systemd[1]: minikube-scheduled-stop.service: Failed to run 'start' task: No such file or direc
tory
Dec 05 16:01:44 docker systemd[1]: minikube-scheduled-stop.service: Failed with result 'resources'.
Dec 05 16:01:44 docker systemd[1]: Failed to start minikube scheduled stop.
```

It needs to have a `-` in front:

`EnvironmentFile=-/var/lib/minikube/scheduled-stop/environment`

**Comment by afbjorklund** [comment]
Something for you, @priyawadhwa ?

**Comment by priyawadhwa** [comment]
Yup that's for me! Did this happen before or after you tried to schedule a stop?

If before, it's not technically a bug since we copy in the env file when a user runs

```
minikube stop --schedule <duration>
```

**Comment by afbjorklund** [comment]
It happened on boot of a brand new cluster

**Comment by priyawadhwa** [comment]
That makes sense, since the file hasn't been copied over yet.

Best way to fix this is probably to disable the systemd service so it doesn't start on boot, and then enable it the first time user runs `minikube stop --schedule `

**Comment by tharun208** [comment]
@priyawadhwa I like to work on this

**Comment by priyawadhwa** [comment]
Thanks @tharun208 ! Some steps you will need to take:

1. We want to make sure minikube-scheduled-stop.service doesn't start on boot, so that will likely require a change in both of our systemd service files:

1. https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/scheduled-stop/minikube-scheduled-stop.service
1. https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/scheduled-stop/minikube-scheduled-stop

1. When we do run `minikube stop --schedule 3m`, we will probably need to enable the service before we start it, which would happen before we restart the service here:

https://github.com/kubernetes/minikube/blob/83f9bd1df385ae8d1d47a5951c2bc9231bd8358c/pkg/minikube/schedule/daemonize_windows.go#L104

**Comment by afbjorklund** [comment]
systemd has a weird way from stopping services to get enabled by default:
https://www.freedesktop.org/software/systemd/man/systemd.preset.html

**Comment by medyagh** [comment]
@tharun208 I haven't heard from you, meanwhile I assign this to @jiefenghe please feel free to start working on this

**Comment by jiefenghe** [comment]
> systemd has a weird way from stopping services to get enabled by default:
> https://www.freedesktop.org/software/systemd/man/systemd.preset.html

Then my understanding is to add a 50-minikube.preset file with `disable minikube-scheduled-stop.service` to disable it by default.

But since the suggested enable fix in `minikube/pkg/minikube/schedule/daemonize_windows.go` is only for windows. Do we need to enable the service in linux? Where is the code for that? Why the issue only exist for windows?
