### ISSUE TITLE
Provide more descriptive error codes for PROVIDER_DOCKER_ERROR

### ISSUE THREAD

**Issue by go-nelango** [kubernetes/minikube#9908]
PROVIDER_DOCKER_ERROR serves as a catch-all error for docker. Can minikube provide more descriptive error codes for docker related failures (besides docker not installed and docker not running which already have corresponding error codes)?

**Comment by tstromberg** [comment]
It can - but as this happens for any unexpected Docker exit, making this more specific so will need analysis of the error text that goes alongside it.

**Comment by tstromberg** [comment]
As a catchall error code, In order to break this code down further, we'll need to collect example error messages for known issues. We can then add support for them here:

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/reason/known_issues.go

Unfortunately, we do not have any example error messages to go by. For instance, no one has opened an issue that mentions this error code:

https://github.com/kubernetes/minikube/issues?q=is%3Aissue+PROVIDER_DOCKER_ERROR

Until we have example error messages, we can't do much with this request, unfortunately.
