### ISSUE TITLE
Provide more descriptive error codes for GUEST_START

### ISSUE THREAD

**Issue by nelango** [kubernetes/minikube#9909]
GUEST_START serves as a catch-all error for cluster node failing to start. Can minikube provide more descriptive error codes (is the failure owing to memory/cpu/disk constraints)?

**Comment by tstromberg** [comment]
Yes, but only if we can analyze the associated error text for patterns. This is a catch-all error that there are easily hundreds of possibilities with drivers that could lead to it.

**Comment by tstromberg** [comment]
As a catchall error code, In order to break this code down further, we'll need to collect example error messages for known issues. We can then add support for them here:

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/reason/known_issues.go

I see we have 19 examples currently that can get broken down into known issues:

https://github.com/kubernetes/minikube/issues?q=is%3Aissue+GUEST_START

**Comment by daehyeok** [comment]
Can i get more detail about this issue?

`reason.GuestStart` only used in `/cm/start.go` file for return error from `startWithDriver` func. 
https://github.com/kubernetes/minikube/blob/5ae4f60642f8d009bd5ecb8fd40b2c47d95d928c/cmd/minikube/cmd/start.go#L258-L262

and  all of error in `startWithDriver` func  come from `node.Start` or `node.Add` func. so If i wrap each error with `GUEST_NODE_START`  and `GUEST_NODE_ADD` code, is it enough for this issue?

**Comment by spowelljr** [comment]
In-progress
