### ISSUE TITLE
Verify Apiserver in docker-env

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9938]
currently we only wait 5 seconds after restarting,,,we should verify

here is an example of failure
https://storage.googleapis.com/minikube-builds/logs/9933/f3be305/Docker_Linux.html#fail_TestFunctional%2fparallel%2fDockerEnv

some places in the code

https://github.com/medyagh/minikube/blob/12893a6121d39ae4c3d2f2f7b4d9cfb3fa9f605f/cmd/minikube/cmd/docker-env.go#L245

https://github.com/medyagh/minikube/blob/12893a6121d39ae4c3d2f2f7b4d9cfb3fa9f605f/pkg/provision/ubuntu.go

**Comment by prezha** [comment]
@azhao155 i was looking at #9936 where the `TestFunctional/parallel/ComponentHealth` fails because of `expected component "kube-apiserver" was not found` error (https://github.com/kubernetes/minikube/runs/1540063530#step:7:140), and, as @medyagh rightly pointed out, that should not happen as `TestFunctional/serial/StartWithProxy` was run before it with `--wait=true` flag set (that should ensure, amongst others, `apiserver` was started:
https://github.com/kubernetes/minikube/blob/a60e2645f2b6b12b93437f2b6077a13757d2d3f7/cmd/minikube/cmd/start_flags.go#L665-L667
https://github.com/kubernetes/minikube/blob/a60e2645f2b6b12b93437f2b6077a13757d2d3f7/pkg/minikube/bootstrapper/bsutil/kverify/kverify.go#L49
so, these two issues might be related

**Comment by afbjorklund** [comment]
I don't understand the title, docker-env doesn't have anything to do wtih apiserver ?

**Comment by azhao155** [comment]
While run docker-env, we need to make sure dockerd is up. If it's not up, we need to wait for api server container to be up and then restart dockerd

**Comment by azhao155** [comment]
https://github.com/kubernetes/minikube/pull/9973 for the improvement.
